package com.tl.resource.dao;

import com.tl.resource.business.dto.AccessoriesDto;
import com.tl.resource.dao.pojo.TAccessories;
import com.tl.resource.dao.pojo.TAccessoriesExample;
import java.util.List;
import java.util.Map;

import org.springframework.orm.ibatis.support.SqlMapClientDaoSupport;

public class TAccessoriesDAOImpl extends SqlMapClientDaoSupport implements TAccessoriesDAO {

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table t_accessories
     *
     * @ibatorgenerated Sat Dec 26 17:27:05 CST 2009
     */
    public TAccessoriesDAOImpl() {
        super();
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table t_accessories
     *
     * @ibatorgenerated Sat Dec 26 17:27:05 CST 2009
     */
    public int countByExample(TAccessoriesExample example) {
        Integer count = (Integer)  getSqlMapClientTemplate().queryForObject("t_accessories.ibatorgenerated_countByExample", example);
        return count.intValue();
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table t_accessories
     *
     * @ibatorgenerated Sat Dec 26 17:27:05 CST 2009
     */
    public int deleteByExample(TAccessoriesExample example) {
        int rows = getSqlMapClientTemplate().delete("t_accessories.ibatorgenerated_deleteByExample", example);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table t_accessories
     *
     * @ibatorgenerated Sat Dec 26 17:27:05 CST 2009
     */
    public int deleteByPrimaryKey(String id) {
        TAccessories key = new TAccessories();
        key.setId(id);
        int rows = getSqlMapClientTemplate().delete("t_accessories.ibatorgenerated_deleteByPrimaryKey", key);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table t_accessories
     *
     * @ibatorgenerated Sat Dec 26 17:27:05 CST 2009
     */
    public void insert(TAccessories record) {
        getSqlMapClientTemplate().insert("t_accessories.ibatorgenerated_insert", record);
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table t_accessories
     *
     * @ibatorgenerated Sat Dec 26 17:27:05 CST 2009
     */
    public void insertSelective(TAccessories record) {
        getSqlMapClientTemplate().insert("t_accessories.ibatorgenerated_insertSelective", record);
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table t_accessories
     *
     * @ibatorgenerated Sat Dec 26 17:27:05 CST 2009
     */
    public List selectByExample(TAccessoriesExample example) {
        List list = getSqlMapClientTemplate().queryForList("t_accessories.ibatorgenerated_selectByExample", example);
        return list;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table t_accessories
     *
     * @ibatorgenerated Sat Dec 26 17:27:05 CST 2009
     */
    public TAccessories selectByPrimaryKey(String id) {
        TAccessories key = new TAccessories();
        key.setId(id);
        TAccessories record = (TAccessories) getSqlMapClientTemplate().queryForObject("t_accessories.ibatorgenerated_selectByPrimaryKey", key);
        return record;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table t_accessories
     *
     * @ibatorgenerated Sat Dec 26 17:27:05 CST 2009
     */
    public int updateByExampleSelective(TAccessories record, TAccessoriesExample example) {
        UpdateByExampleParms parms = new UpdateByExampleParms(record, example);
        int rows = getSqlMapClientTemplate().update("t_accessories.ibatorgenerated_updateByExampleSelective", parms);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table t_accessories
     *
     * @ibatorgenerated Sat Dec 26 17:27:05 CST 2009
     */
    public int updateByExample(TAccessories record, TAccessoriesExample example) {
        UpdateByExampleParms parms = new UpdateByExampleParms(record, example);
        int rows = getSqlMapClientTemplate().update("t_accessories.ibatorgenerated_updateByExample", parms);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table t_accessories
     *
     * @ibatorgenerated Sat Dec 26 17:27:05 CST 2009
     */
    public int updateByPrimaryKeySelective(TAccessories record) {
        int rows = getSqlMapClientTemplate().update("t_accessories.ibatorgenerated_updateByPrimaryKeySelective", record);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table t_accessories
     *
     * @ibatorgenerated Sat Dec 26 17:27:05 CST 2009
     */
    public int updateByPrimaryKey(TAccessories record) {
        int rows = getSqlMapClientTemplate().update("t_accessories.ibatorgenerated_updateByPrimaryKey", record);
        return rows;
    }

    /**
     * This class was generated by Apache iBATIS ibator.
     * This class corresponds to the database table t_accessories
     *
     * @ibatorgenerated Sat Dec 26 17:27:05 CST 2009
     */
    private static class UpdateByExampleParms extends TAccessoriesExample {
        private Object record;

        public UpdateByExampleParms(Object record, TAccessoriesExample example) {
            super(example);
            this.record = record;
        }

        public Object getRecord() {
            return record;
        }
    }

	@Override
	public List<AccessoriesDto> getAccessoriesByBusId(
			Map<String, Object> paramMap) {
		return this.getSqlMapClientTemplate().queryForList("accessories.getAccessoriesByBusId", paramMap);
	}
}