package com.tl.resource.dao;

import com.tl.resource.dao.pojo.TAuditFlowInfor;
import com.tl.resource.dao.pojo.TAuditFlowInforExample;
import java.util.List;
import org.springframework.orm.ibatis.support.SqlMapClientDaoSupport;

public class TAuditFlowInforDAOImpl extends SqlMapClientDaoSupport implements TAuditFlowInforDAO {

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table t_audit_flow_infor
     *
     * @ibatorgenerated Tue Oct 20 11:57:32 CST 2009
     */
    public TAuditFlowInforDAOImpl() {
        super();
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table t_audit_flow_infor
     *
     * @ibatorgenerated Tue Oct 20 11:57:32 CST 2009
     */
    public int countByExample(TAuditFlowInforExample example) {
        Integer count = (Integer)  getSqlMapClientTemplate().queryForObject("t_audit_flow_infor.ibatorgenerated_countByExample", example);
        return count.intValue();
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table t_audit_flow_infor
     *
     * @ibatorgenerated Tue Oct 20 11:57:32 CST 2009
     */
    public int deleteByExample(TAuditFlowInforExample example) {
        int rows = getSqlMapClientTemplate().delete("t_audit_flow_infor.ibatorgenerated_deleteByExample", example);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table t_audit_flow_infor
     *
     * @ibatorgenerated Tue Oct 20 11:57:32 CST 2009
     */
    public int deleteByPrimaryKey(String id) {
        TAuditFlowInfor key = new TAuditFlowInfor();
        key.setId(id);
        int rows = getSqlMapClientTemplate().delete("t_audit_flow_infor.ibatorgenerated_deleteByPrimaryKey", key);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table t_audit_flow_infor
     *
     * @ibatorgenerated Tue Oct 20 11:57:32 CST 2009
     */
    public void insert(TAuditFlowInfor record) {
        getSqlMapClientTemplate().insert("t_audit_flow_infor.ibatorgenerated_insert", record);
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table t_audit_flow_infor
     *
     * @ibatorgenerated Tue Oct 20 11:57:32 CST 2009
     */
    public void insertSelective(TAuditFlowInfor record) {
        getSqlMapClientTemplate().insert("t_audit_flow_infor.ibatorgenerated_insertSelective", record);
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table t_audit_flow_infor
     *
     * @ibatorgenerated Tue Oct 20 11:57:32 CST 2009
     */
    public List selectByExample(TAuditFlowInforExample example) {
        List list = getSqlMapClientTemplate().queryForList("t_audit_flow_infor.ibatorgenerated_selectByExample", example);
        return list;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table t_audit_flow_infor
     *
     * @ibatorgenerated Tue Oct 20 11:57:32 CST 2009
     */
    public TAuditFlowInfor selectByPrimaryKey(String id) {
        TAuditFlowInfor key = new TAuditFlowInfor();
        key.setId(id);
        TAuditFlowInfor record = (TAuditFlowInfor) getSqlMapClientTemplate().queryForObject("t_audit_flow_infor.ibatorgenerated_selectByPrimaryKey", key);
        return record;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table t_audit_flow_infor
     *
     * @ibatorgenerated Tue Oct 20 11:57:32 CST 2009
     */
    public int updateByExampleSelective(TAuditFlowInfor record, TAuditFlowInforExample example) {
        UpdateByExampleParms parms = new UpdateByExampleParms(record, example);
        int rows = getSqlMapClientTemplate().update("t_audit_flow_infor.ibatorgenerated_updateByExampleSelective", parms);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table t_audit_flow_infor
     *
     * @ibatorgenerated Tue Oct 20 11:57:32 CST 2009
     */
    public int updateByExample(TAuditFlowInfor record, TAuditFlowInforExample example) {
        UpdateByExampleParms parms = new UpdateByExampleParms(record, example);
        int rows = getSqlMapClientTemplate().update("t_audit_flow_infor.ibatorgenerated_updateByExample", parms);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table t_audit_flow_infor
     *
     * @ibatorgenerated Tue Oct 20 11:57:32 CST 2009
     */
    public int updateByPrimaryKeySelective(TAuditFlowInfor record) {
        int rows = getSqlMapClientTemplate().update("t_audit_flow_infor.ibatorgenerated_updateByPrimaryKeySelective", record);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table t_audit_flow_infor
     *
     * @ibatorgenerated Tue Oct 20 11:57:32 CST 2009
     */
    public int updateByPrimaryKey(TAuditFlowInfor record) {
        int rows = getSqlMapClientTemplate().update("t_audit_flow_infor.ibatorgenerated_updateByPrimaryKey", record);
        return rows;
    }

    /**
     * This class was generated by Apache iBATIS ibator.
     * This class corresponds to the database table t_audit_flow_infor
     *
     * @ibatorgenerated Tue Oct 20 11:57:32 CST 2009
     */
    private static class UpdateByExampleParms extends TAuditFlowInforExample {
        private Object record;

        public UpdateByExampleParms(Object record, TAuditFlowInforExample example) {
            super(example);
            this.record = record;
        }

        public Object getRecord() {
            return record;
        }
    }
    
    public List<com.tl.resource.audit.dto.TAuditFlowInforDto> getAuditInfor(String auditTypeId){
    	return getSqlMapClientTemplate().queryForList("t_audit_flow_infor.getAuditInfor", auditTypeId);
    }
}