package com.tl.resource.dao;

import java.util.List;
import java.util.Map;

import com.tl.common.util.PaginationSupport;
import com.tl.resource.business.dto.ContractDetailDto;
import com.tl.resource.business.dto.ContractProductDetailDto;
import com.tl.resource.business.dto.OrderDetialsDto;
import com.tl.resource.dao.pojo.TContractProductDetail;
import com.tl.resource.dao.pojo.TContractProductDetailExample;

public interface TContractProductDetailDAO {

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table t_contract_product_detail
	 * @ibatorgenerated  Wed Oct 14 14:13:27 CST 2009
	 */
	int countByExample(TContractProductDetailExample example);

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table t_contract_product_detail
	 * @ibatorgenerated  Wed Oct 14 14:13:27 CST 2009
	 */
	int deleteByExample(TContractProductDetailExample example);

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table t_contract_product_detail
	 * @ibatorgenerated  Wed Oct 14 14:13:27 CST 2009
	 */
	int deleteByPrimaryKey(String id);

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table t_contract_product_detail
	 * @ibatorgenerated  Wed Oct 14 14:13:27 CST 2009
	 */
	void insert(TContractProductDetail record);

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table t_contract_product_detail
	 * @ibatorgenerated  Wed Oct 14 14:13:27 CST 2009
	 */
	void insertSelective(TContractProductDetail record);

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table t_contract_product_detail
	 * @ibatorgenerated  Wed Oct 14 14:13:27 CST 2009
	 */
	List selectByExample(TContractProductDetailExample example);

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table t_contract_product_detail
	 * @ibatorgenerated  Wed Oct 14 14:13:27 CST 2009
	 */
	TContractProductDetail selectByPrimaryKey(String id);

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table t_contract_product_detail
	 * @ibatorgenerated  Wed Oct 14 14:13:27 CST 2009
	 */
	int updateByExampleSelective(TContractProductDetail record,
			TContractProductDetailExample example);

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table t_contract_product_detail
	 * @ibatorgenerated  Wed Oct 14 14:13:27 CST 2009
	 */
	int updateByExample(TContractProductDetail record,
			TContractProductDetailExample example);

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table t_contract_product_detail
	 * @ibatorgenerated  Wed Oct 14 14:13:27 CST 2009
	 */
	int updateByPrimaryKeySelective(TContractProductDetail record);

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table t_contract_product_detail
	 * @ibatorgenerated  Wed Oct 14 14:13:27 CST 2009
	 */
	int updateByPrimaryKey(TContractProductDetail record);

	List<ContractProductDetailDto> getProductDetail(String contractId, String contractSortId);
	/**
	 * 获得合同明细，带已到货数量，已交货数量
	 * @param contractId
	 * @param contractSortId
	 * @return
	 */
	List<ContractProductDetailDto> getConProductArrivalDeliveryDetail(String contractId, String contractSortId);
	
	PaginationSupport getConProductArrivalDeliveryDetail4Page(Map params, int startIndex,int pageSize);
	
	List<ContractProductDetailDto> getProductDetail4Page(String contractId, String contractSortId,int startIndex,int pageSize);
	
	
	/**
	 * 根据合同和供应商查找合同详细
	 * @param parmMap
	 * @return
	 */
	public List<OrderDetialsDto> getContractDetailList(Map<String, Object> parmMap);
	
	/**
	 * 根据合同和供应商查找合同详细总数
	 * @param parmMap
	 * @return
	 */
	public Integer getContractDetailListCount(Map<String, Object> parmMap);

	PaginationSupport findContractDetail(Map params, int startIndex,int pageSize);
	
	
	/**
	 * 根据合同ID查看合同详细
	 * @param parmMap
	 * @return
	 */
	public List<ContractProductDetailDto> getContractDetail(Map<String, Object> parmMap);
	
	public Integer getContractDetailCount(Map<String, Object> parmMap);
	
	/**
	 * 根据合同ID查看合同详细(合同订单)
	 * @param parmMap
	 * @return
	 */
	public List<ContractProductDetailDto> getCOrderContractDetail(Map<String, Object> parmMap);
	
	public Integer getCOrderContractDetailCount(Map<String, Object> parmMap);
	
	
	public List<ContractProductDetailDto> getCOrderContractDetailList(Map<String, Object> parmMap);

	public Integer getCOrderContractDetailListCount(Map<String, Object> parmMap);

	public List<ContractProductDetailDto> getWillOutStockContractDetail(String contractId);
	
	/**
	 * 加工订单（将合同中加工品带入订单）
	 * @param parmMap
	 * @return
	 */
	public List<OrderDetialsDto> getPartContractDetail(Map<String, Object> parmMap);
	
	List<ContractProductDetailDto> getProductDetailConId(String id);
}