package com.tl.resource.dao;

import java.util.HashMap;
import java.util.List;
import java.util.Map;

import org.springframework.orm.ibatis.support.SqlMapClientDaoSupport;

import com.tl.resource.dao.pojo.TCustomersInfor;
import com.tl.resource.dao.pojo.TCustomersInforExample;

public class TCustomersInforDAOImpl extends SqlMapClientDaoSupport implements TCustomersInforDAO {

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table t_customers_infor
	 * @ibatorgenerated  Wed Oct 14 14:13:27 CST 2009
	 */
	public TCustomersInforDAOImpl() {
		super();
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table t_customers_infor
	 * @ibatorgenerated  Wed Oct 14 14:13:27 CST 2009
	 */
	public int countByExample(TCustomersInforExample example) {
		Integer count = (Integer) getSqlMapClientTemplate().queryForObject(
				"t_customers_infor.ibatorgenerated_countByExample", example);
		return count.intValue();
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table t_customers_infor
	 * @ibatorgenerated  Wed Oct 14 14:13:27 CST 2009
	 */
	public int deleteByExample(TCustomersInforExample example) {
		int rows = getSqlMapClientTemplate().delete(
				"t_customers_infor.ibatorgenerated_deleteByExample", example);
		return rows;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table t_customers_infor
	 * @ibatorgenerated  Wed Oct 14 14:13:27 CST 2009
	 */
	public int deleteByPrimaryKey(String id) {
		TCustomersInfor key = new TCustomersInfor();
		key.setId(id);
		int rows = getSqlMapClientTemplate().delete(
				"t_customers_infor.ibatorgenerated_deleteByPrimaryKey", key);
		return rows;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table t_customers_infor
	 * @ibatorgenerated  Wed Oct 14 14:13:27 CST 2009
	 */
	public void insert(TCustomersInfor record) {
		getSqlMapClientTemplate().insert(
				"t_customers_infor.ibatorgenerated_insert", record);
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table t_customers_infor
	 * @ibatorgenerated  Wed Oct 14 14:13:27 CST 2009
	 */
	public void insertSelective(TCustomersInfor record) {
		getSqlMapClientTemplate().insert(
				"t_customers_infor.ibatorgenerated_insertSelective", record);
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table t_customers_infor
	 * @ibatorgenerated  Wed Oct 14 14:13:27 CST 2009
	 */
	public List selectByExample(TCustomersInforExample example) {
		List list = getSqlMapClientTemplate().queryForList(
				"t_customers_infor.ibatorgenerated_selectByExample", example);
		return list;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table t_customers_infor
	 * @ibatorgenerated  Wed Oct 14 14:13:27 CST 2009
	 */
	public TCustomersInfor selectByPrimaryKey(String id) {
		TCustomersInfor key = new TCustomersInfor();
		key.setId(id);
		TCustomersInfor record = (TCustomersInfor) getSqlMapClientTemplate()
				.queryForObject(
						"t_customers_infor.ibatorgenerated_selectByPrimaryKey",
						key);
		return record;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table t_customers_infor
	 * @ibatorgenerated  Wed Oct 14 14:13:27 CST 2009
	 */
	public int updateByExampleSelective(TCustomersInfor record,
			TCustomersInforExample example) {
		UpdateByExampleParms parms = new UpdateByExampleParms(record, example);
		int rows = getSqlMapClientTemplate().update(
				"t_customers_infor.ibatorgenerated_updateByExampleSelective",
				parms);
		return rows;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table t_customers_infor
	 * @ibatorgenerated  Wed Oct 14 14:13:27 CST 2009
	 */
	public int updateByExample(TCustomersInfor record,
			TCustomersInforExample example) {
		UpdateByExampleParms parms = new UpdateByExampleParms(record, example);
		int rows = getSqlMapClientTemplate().update(
				"t_customers_infor.ibatorgenerated_updateByExample", parms);
		return rows;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table t_customers_infor
	 * @ibatorgenerated  Wed Oct 14 14:13:27 CST 2009
	 */
	public int updateByPrimaryKeySelective(TCustomersInfor record) {
		int rows = getSqlMapClientTemplate().update("t_customers_infor.ibatorgenerated_updateByPrimaryKeySelective",record);
		return rows;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table t_customers_infor
	 * @ibatorgenerated  Wed Oct 14 14:13:27 CST 2009
	 */
	public int updateByPrimaryKey(TCustomersInfor record) {
		int rows = getSqlMapClientTemplate().update(
				"t_customers_infor.ibatorgenerated_updateByPrimaryKey", record);
		return rows;
	}

	/**
	 * This class was generated by Apache iBATIS ibator. This class corresponds to the database table t_customers_infor
	 * @ibatorgenerated  Wed Oct 14 14:13:27 CST 2009
	 */
	private static class UpdateByExampleParms extends TCustomersInforExample {
		private Object record;

		public UpdateByExampleParms(Object record,
				TCustomersInforExample example) {
			super(example);
			this.record = record;
		}

		public Object getRecord() {
			return record;
		}
	}

	@Override
	public int getCustomersCount(Map<String, Object> parmMap) {
		Integer count = (Integer) getSqlMapClientTemplate().queryForObject(
				"t_customers_infor.getCustomerInfoTotal",parmMap);
		return count.intValue();
	}

	@Override
	public List<TCustomersInfor> getCustomersList(Map<String, Object> parmMap) {
		List list = getSqlMapClientTemplate().queryForList(
				"t_customers_infor.getCustomerBySearch", parmMap);
		return list;
	}
	
	@Override
	public List<TCustomersInfor> getAssessmentCustomersList(
			Map<String, Object> parmMap) {
		List list = getSqlMapClientTemplate().queryForList(
				"t_customers_infor.getAssessmentCustomerBySearch", parmMap);
		return list;
	}

	@Override
	public List<TCustomersInfor> getAllCustomersListByCustomersName(
			Map<String, Object> parmMap) {
		List list = getSqlMapClientTemplate().queryForList(
				"t_customers_infor.getAllCustomersListByCustomersName", parmMap);
		return list;
	}

	@Override
	public void updateByCustomersDegreeId(Map<String, Object> parmMap) {
		getSqlMapClientTemplate().update("t_customers_infor.updateByCustomersDegreeId", parmMap);
	}
}