package com.tl.resource.dao;

import com.tl.resource.business.dto.CurSalesPriceHistoryDto;
import com.tl.resource.dao.pojo.TCusSalesPriceHistory;
import com.tl.resource.dao.pojo.TCusSalesPriceHistoryExample;
import java.util.List;
import java.util.Map;

public interface TCusSalesPriceHistoryDAO {
    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table t_cus_sales_price_history
     *
     * @ibatorgenerated Fri Oct 16 10:53:03 CST 2009
     */
    int countByExample(TCusSalesPriceHistoryExample example);

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table t_cus_sales_price_history
     *
     * @ibatorgenerated Fri Oct 16 10:53:03 CST 2009
     */
    int deleteByExample(TCusSalesPriceHistoryExample example);

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table t_cus_sales_price_history
     *
     * @ibatorgenerated Fri Oct 16 10:53:03 CST 2009
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table t_cus_sales_price_history
     *
     * @ibatorgenerated Fri Oct 16 10:53:03 CST 2009
     */
    void insert(TCusSalesPriceHistory record);

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table t_cus_sales_price_history
     *
     * @ibatorgenerated Fri Oct 16 10:53:03 CST 2009
     */
    void insertSelective(TCusSalesPriceHistory record);

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table t_cus_sales_price_history
     *
     * @ibatorgenerated Fri Oct 16 10:53:03 CST 2009
     */
    List selectByExample(TCusSalesPriceHistoryExample example);

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table t_cus_sales_price_history
     *
     * @ibatorgenerated Fri Oct 16 10:53:03 CST 2009
     */
    TCusSalesPriceHistory selectByPrimaryKey(String id);

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table t_cus_sales_price_history
     *
     * @ibatorgenerated Fri Oct 16 10:53:03 CST 2009
     */
    int updateByExampleSelective(TCusSalesPriceHistory record, TCusSalesPriceHistoryExample example);

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table t_cus_sales_price_history
     *
     * @ibatorgenerated Fri Oct 16 10:53:03 CST 2009
     */
    int updateByExample(TCusSalesPriceHistory record, TCusSalesPriceHistoryExample example);

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table t_cus_sales_price_history
     *
     * @ibatorgenerated Fri Oct 16 10:53:03 CST 2009
     */
    int updateByPrimaryKeySelective(TCusSalesPriceHistory record);

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table t_cus_sales_price_history
     *
     * @ibatorgenerated Fri Oct 16 10:53:03 CST 2009
     */
    int updateByPrimaryKey(TCusSalesPriceHistory record);
    /**
     * 根据条件获取产品种类信息
     * @param parmMap
     * @return
     */
	List<CurSalesPriceHistoryDto> getCusSalesHistoryProductByPage(
			Map<String, Object> parmMap);

	/**
	 * 获取已销售产品种类总数
	 * @param parmMap 
	 * @return
	 */
	int getCusSalesHistoryProductTotal(Map<String, Object> parmMap);

	/**
	 * 根据产品ID获取销售记录详细信息
	 * @param parmMap
	 * @return
	 */
	List<CurSalesPriceHistoryDto> getCusSalesHistoryProductByPageAndProductId(
			Map<String, Object> parmMap);
	/**
	 * 根据产品id获取销售记录总数
	 * @param parmMap
	 * @return
	 */
	int getCusSalesHistoryProductTotalByProductId(Map<String, Object> parmMap);
}