package com.tl.resource.dao;

import com.tl.common.util.PaginationSupport;
import com.tl.resource.business.dto.DeliveryProductSortDto;
import com.tl.resource.dao.pojo.TDeliveryInfor;
import com.tl.resource.dao.pojo.TDeliveryInforExample;
import com.tl.resource.dao.pojo.TOrderInfor;
import com.tl.resource.dao.pojo.TOutStockInfor;

import java.util.List;
import java.util.Map;

import org.springframework.orm.ibatis.support.SqlMapClientDaoSupport;

public class TDeliveryInforDAOImpl extends SqlMapClientDaoSupport implements TDeliveryInforDAO {

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table t_delivery_infor
	 * @ibatorgenerated  Wed Oct 14 14:13:27 CST 2009
	 */
	public TDeliveryInforDAOImpl() {
		super();
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table t_delivery_infor
	 * @ibatorgenerated  Wed Oct 14 14:13:27 CST 2009
	 */
	public int countByExample(TDeliveryInforExample example) {
		Integer count = (Integer) getSqlMapClientTemplate().queryForObject(
				"t_delivery_infor.ibatorgenerated_countByExample", example);
		return count.intValue();
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table t_delivery_infor
	 * @ibatorgenerated  Wed Oct 14 14:13:27 CST 2009
	 */
	public int deleteByExample(TDeliveryInforExample example) {
		int rows = getSqlMapClientTemplate().delete(
				"t_delivery_infor.ibatorgenerated_deleteByExample", example);
		return rows;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table t_delivery_infor
	 * @ibatorgenerated  Wed Oct 14 14:13:27 CST 2009
	 */
	public int deleteByPrimaryKey(String id) {
		TDeliveryInfor key = new TDeliveryInfor();
		key.setId(id);
		int rows = getSqlMapClientTemplate().delete(
				"t_delivery_infor.ibatorgenerated_deleteByPrimaryKey", key);
		return rows;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table t_delivery_infor
	 * @ibatorgenerated  Wed Oct 14 14:13:27 CST 2009
	 */
	public void insert(TDeliveryInfor record) {
		getSqlMapClientTemplate().insert(
				"t_delivery_infor.ibatorgenerated_insert", record);
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table t_delivery_infor
	 * @ibatorgenerated  Wed Oct 14 14:13:27 CST 2009
	 */
	public void insertSelective(TDeliveryInfor record) {
		getSqlMapClientTemplate().insert(
				"t_delivery_infor.ibatorgenerated_insertSelective", record);
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table t_delivery_infor
	 * @ibatorgenerated  Wed Oct 14 14:13:27 CST 2009
	 */
	public List selectByExample(TDeliveryInforExample example) {
		List list = getSqlMapClientTemplate().queryForList(
				"t_delivery_infor.ibatorgenerated_selectByExample", example);
		return list;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table t_delivery_infor
	 * @ibatorgenerated  Wed Oct 14 14:13:27 CST 2009
	 */
	public TDeliveryInfor selectByPrimaryKey(String id) {
		TDeliveryInfor key = new TDeliveryInfor();
		key.setId(id);
		TDeliveryInfor record = (TDeliveryInfor) getSqlMapClientTemplate()
				.queryForObject(
						"t_delivery_infor.ibatorgenerated_selectByPrimaryKey",
						key);
		List<TOrderInfor> orderList = getSqlMapClientTemplate().queryForList("t_order_infor.getOrderContract");
		for (TOrderInfor tOrderInfor : orderList) {
			try {
				if(tOrderInfor.getContractCode().trim().equals(record.getContractCode().trim())) {
					record.setOrderCode(tOrderInfor.getOrderCode());
				}
			} catch (Exception e) {}
		}
		return record;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table t_delivery_infor
	 * @ibatorgenerated  Wed Oct 14 14:13:27 CST 2009
	 */
	public int updateByExampleSelective(TDeliveryInfor record,
			TDeliveryInforExample example) {
		UpdateByExampleParms parms = new UpdateByExampleParms(record, example);
		int rows = getSqlMapClientTemplate().update(
				"t_delivery_infor.ibatorgenerated_updateByExampleSelective",
				parms);
		return rows;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table t_delivery_infor
	 * @ibatorgenerated  Wed Oct 14 14:13:27 CST 2009
	 */
	public int updateByExample(TDeliveryInfor record,
			TDeliveryInforExample example) {
		UpdateByExampleParms parms = new UpdateByExampleParms(record, example);
		int rows = getSqlMapClientTemplate().update(
				"t_delivery_infor.ibatorgenerated_updateByExample", parms);
		return rows;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table t_delivery_infor
	 * @ibatorgenerated  Wed Oct 14 14:13:27 CST 2009
	 */
	public int updateByPrimaryKeySelective(TDeliveryInfor record) {
		int rows = getSqlMapClientTemplate().update(
				"t_delivery_infor.ibatorgenerated_updateByPrimaryKeySelective",
				record);
		return rows;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table t_delivery_infor
	 * @ibatorgenerated  Wed Oct 14 14:13:27 CST 2009
	 */
	public int updateByPrimaryKey(TDeliveryInfor record) {
		int rows = getSqlMapClientTemplate().update(
				"t_delivery_infor.ibatorgenerated_updateByPrimaryKey", record);
		return rows;
	}

	/**
	 * This class was generated by Apache iBATIS ibator. This class corresponds to the database table t_delivery_infor
	 * @ibatorgenerated  Wed Oct 14 14:13:27 CST 2009
	 */
	private static class UpdateByExampleParms extends TDeliveryInforExample {
		private Object record;

		public UpdateByExampleParms(Object record, TDeliveryInforExample example) {
			super(example);
			this.record = record;
		}

		public Object getRecord() {
			return record;
		}
	}

	@Override
	public List<DeliveryProductSortDto> getContractProductSorts(String id) {
		// TODO Auto-generated method stub
		return null;
	}

	@Override
	public PaginationSupport findDeliveryInfors(Map params, int startIndex,
			int pageSize) {
		// TODO Auto-generated method stub
		params.put("startIndex", startIndex);
		params.put("pageSize", pageSize);
		List<TDeliveryInfor> list = getSqlMapClientTemplate().queryForList("t_delivery_infor.getDeliverysList",params);
		Integer count = (Integer) getSqlMapClientTemplate().queryForObject("t_delivery_infor.getDeliveryListCount", params);
		List<TOrderInfor> orderList = getSqlMapClientTemplate().queryForList("t_order_infor.getOrderContract");
		
		for (TDeliveryInfor tDeliveryInfor : list) {
			for (TOrderInfor tOrderInfor : orderList) {
				try{
					if(tDeliveryInfor.getContractCode().trim().equals(tOrderInfor.getContractCode().trim())) {
						tDeliveryInfor.setOrderCode(tOrderInfor.getOrderCode());
						System.out.println("getContractCode========8777777777====" + tDeliveryInfor.getOrderCode());
					}
				}catch(Exception e){}
			}
		}
		
		PaginationSupport ps = new PaginationSupport(list,count, pageSize, startIndex);
		return ps;
	}
}