package com.tl.resource.dao;

import com.tl.resource.business.dto.OrderPriceHistoryDto;
import com.tl.resource.dao.pojo.TOrderPriceHistory;
import com.tl.resource.dao.pojo.TOrderPriceHistoryExample;
import java.util.List;
import java.util.Map;

public interface TOrderPriceHistoryDAO {

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table t_order_price_history
	 * @ibatorgenerated  Fri Oct 16 10:53:02 CST 2009
	 */
	int countByExample(TOrderPriceHistoryExample example);

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table t_order_price_history
	 * @ibatorgenerated  Fri Oct 16 10:53:02 CST 2009
	 */
	int deleteByExample(TOrderPriceHistoryExample example);

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table t_order_price_history
	 * @ibatorgenerated  Fri Oct 16 10:53:02 CST 2009
	 */
	int deleteByPrimaryKey(String id);

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table t_order_price_history
	 * @ibatorgenerated  Fri Oct 16 10:53:02 CST 2009
	 */
	void insert(TOrderPriceHistory record);

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table t_order_price_history
	 * @ibatorgenerated  Fri Oct 16 10:53:02 CST 2009
	 */
	void insertSelective(TOrderPriceHistory record);

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table t_order_price_history
	 * @ibatorgenerated  Fri Oct 16 10:53:02 CST 2009
	 */
	List selectByExample(TOrderPriceHistoryExample example);

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table t_order_price_history
	 * @ibatorgenerated  Fri Oct 16 10:53:02 CST 2009
	 */
	TOrderPriceHistory selectByPrimaryKey(String id);

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table t_order_price_history
	 * @ibatorgenerated  Fri Oct 16 10:53:02 CST 2009
	 */
	int updateByExampleSelective(TOrderPriceHistory record,
			TOrderPriceHistoryExample example);

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table t_order_price_history
	 * @ibatorgenerated  Fri Oct 16 10:53:02 CST 2009
	 */
	int updateByExample(TOrderPriceHistory record,
			TOrderPriceHistoryExample example);

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table t_order_price_history
	 * @ibatorgenerated  Fri Oct 16 10:53:02 CST 2009
	 */
	int updateByPrimaryKeySelective(TOrderPriceHistory record);

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table t_order_price_history
	 * @ibatorgenerated  Fri Oct 16 10:53:02 CST 2009
	 */
	int updateByPrimaryKey(TOrderPriceHistory record);

	List<OrderPriceHistoryDto> getOrderPriceHistoryProductByPage(
			Map<String, Object> parmMap);

	int getOrderPriceHistoryProductTotal(Map<String, Object> parmMap);

	List<OrderPriceHistoryDto> getOrderHistoryProductByPageAndProductId(
			Map<String, Object> parmMap);

	int getOrderHistoryProductTotalByProductId(Map<String, Object> parmMap);
}