package com.tl.resource.dao;

import com.tl.resource.business.dto.ArrivalInforDto;
import com.tl.resource.dao.pojo.TProductArrivalInfor;
import com.tl.resource.dao.pojo.TProductArrivalInforExample;
import java.util.List;
import java.util.Map;

public interface TProductArrivalInforDAO {

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table t_product_arrival_infor
	 * @ibatorgenerated  Fri Nov 06 19:04:07 CST 2009
	 */
	int countByExample(TProductArrivalInforExample example);

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table t_product_arrival_infor
	 * @ibatorgenerated  Fri Nov 06 19:04:07 CST 2009
	 */
	int deleteByExample(TProductArrivalInforExample example);

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table t_product_arrival_infor
	 * @ibatorgenerated  Fri Nov 06 19:04:07 CST 2009
	 */
	int deleteByPrimaryKey(String id);

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table t_product_arrival_infor
	 * @ibatorgenerated  Fri Nov 06 19:04:07 CST 2009
	 */
	void insert(TProductArrivalInfor record);

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table t_product_arrival_infor
	 * @ibatorgenerated  Fri Nov 06 19:04:07 CST 2009
	 */
	void insertSelective(TProductArrivalInfor record);

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table t_product_arrival_infor
	 * @ibatorgenerated  Fri Nov 06 19:04:07 CST 2009
	 */
	List selectByExample(TProductArrivalInforExample example);

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table t_product_arrival_infor
	 * @ibatorgenerated  Fri Nov 06 19:04:07 CST 2009
	 */
	TProductArrivalInfor selectByPrimaryKey(String id);

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table t_product_arrival_infor
	 * @ibatorgenerated  Fri Nov 06 19:04:07 CST 2009
	 */
	int updateByExampleSelective(TProductArrivalInfor record,
			TProductArrivalInforExample example);

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table t_product_arrival_infor
	 * @ibatorgenerated  Fri Nov 06 19:04:07 CST 2009
	 */
	int updateByExample(TProductArrivalInfor record,
			TProductArrivalInforExample example);

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table t_product_arrival_infor
	 * @ibatorgenerated  Fri Nov 06 19:04:07 CST 2009
	 */
	int updateByPrimaryKeySelective(TProductArrivalInfor record);

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table t_product_arrival_infor
	 * @ibatorgenerated  Fri Nov 06 19:04:07 CST 2009
	 */
	int updateByPrimaryKey(TProductArrivalInfor record);
	
	/**
	 * 根据搜索条件获取到货单信息
	 * @param paramMap
	 * @return
	 */
	public List<TProductArrivalInfor> getArrivalInfoBySearch(Map<String, Object> paramMap);
	
	/**
	 *  根据搜索条件获取到货单信息数量
	 * @param paramMap
	 * @return
	 */
	public Integer getArrInfoTotalBySearch(Map<String, Object> paramMap);
	
	/**
	 * 根据Id获取到货单信息并抓取其对应的产品
	 * @param arrInfoId
	 * @return
	 */
	public TProductArrivalInfor getArrInfoWithProById(String arrInfoId);
	
	/**
	 * 根据ID获取到货单信息
	 * @param arrInfoId
	 * @return
	 */
	public ArrivalInforDto getArrInfoWithOrderType(String arrInfoId);
	
	/**
	 * 根据搜索条件获取直接入库单信息
	 * @param paramMap
	 * @return
	 */
	public List<TProductArrivalInfor> getDirectArrivalBySearch(Map<String, Object> paramMap);
	
	/**
	 *  根据搜索条件获取直接入库单信息数量
	 * @param paramMap
	 * @return
	 */
	public Integer getDirectArrTotalBySearch(Map<String, Object> paramMap);
	
	public TProductArrivalInfor getDirectArrInfoById(String id);
	
	/**
     * 修改入库单的状态
     * @param arrInfo
     * @return
     */
    public Integer updateStatus(TProductArrivalInfor arrInfo);
    
    Integer isCanInvalidArr(String arrId);
    
    Integer isCanInvaStockArr(String arrId);
}