package com.tl.resource.dao;

import com.tl.resource.business.dto.ProductArrivalDetailDto;
import com.tl.resource.dao.pojo.TProductArrivalDetail;
import com.tl.resource.dao.pojo.TProductArrivalDetailExample;
import java.util.List;
import org.springframework.orm.ibatis.support.SqlMapClientDaoSupport;

public class TProductArrivalDetailDAOImpl extends SqlMapClientDaoSupport implements TProductArrivalDetailDAO {

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table t_product_arrival_detail
     *
     * @ibatorgenerated Wed Oct 14 14:13:27 CST 2009
     */
    public TProductArrivalDetailDAOImpl() {
        super();
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table t_product_arrival_detail
     *
     * @ibatorgenerated Wed Oct 14 14:13:27 CST 2009
     */
    public int countByExample(TProductArrivalDetailExample example) {
        Integer count = (Integer)  getSqlMapClientTemplate().queryForObject("t_product_arrival_detail.ibatorgenerated_countByExample", example);
        return count.intValue();
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table t_product_arrival_detail
     *
     * @ibatorgenerated Wed Oct 14 14:13:27 CST 2009
     */
    public int deleteByExample(TProductArrivalDetailExample example) {
        int rows = getSqlMapClientTemplate().delete("t_product_arrival_detail.ibatorgenerated_deleteByExample", example);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table t_product_arrival_detail
     *
     * @ibatorgenerated Wed Oct 14 14:13:27 CST 2009
     */
    public int deleteByPrimaryKey(String id) {
        TProductArrivalDetail key = new TProductArrivalDetail();
        key.setId(id);
        int rows = getSqlMapClientTemplate().delete("t_product_arrival_detail.ibatorgenerated_deleteByPrimaryKey", key);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table t_product_arrival_detail
     *
     * @ibatorgenerated Wed Oct 14 14:13:27 CST 2009
     */
    public void insert(TProductArrivalDetail record) {
        getSqlMapClientTemplate().insert("t_product_arrival_detail.ibatorgenerated_insert", record);
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table t_product_arrival_detail
     *
     * @ibatorgenerated Wed Oct 14 14:13:27 CST 2009
     */
    public void insertSelective(TProductArrivalDetail record) {
        getSqlMapClientTemplate().insert("t_product_arrival_detail.ibatorgenerated_insertSelective", record);
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table t_product_arrival_detail
     *
     * @ibatorgenerated Wed Oct 14 14:13:27 CST 2009
     */
    public List selectByExample(TProductArrivalDetailExample example) {
        List list = getSqlMapClientTemplate().queryForList("t_product_arrival_detail.ibatorgenerated_selectByExample", example);
        return list;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table t_product_arrival_detail
     *
     * @ibatorgenerated Wed Oct 14 14:13:27 CST 2009
     */
    public TProductArrivalDetail selectByPrimaryKey(String id) {
        TProductArrivalDetail key = new TProductArrivalDetail();
        key.setId(id);
        TProductArrivalDetail record = (TProductArrivalDetail) getSqlMapClientTemplate().queryForObject("t_product_arrival_detail.ibatorgenerated_selectByPrimaryKey", key);
        return record;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table t_product_arrival_detail
     *
     * @ibatorgenerated Wed Oct 14 14:13:27 CST 2009
     */
    public int updateByExampleSelective(TProductArrivalDetail record, TProductArrivalDetailExample example) {
        UpdateByExampleParms parms = new UpdateByExampleParms(record, example);
        int rows = getSqlMapClientTemplate().update("t_product_arrival_detail.ibatorgenerated_updateByExampleSelective", parms);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table t_product_arrival_detail
     *
     * @ibatorgenerated Wed Oct 14 14:13:27 CST 2009
     */
    public int updateByExample(TProductArrivalDetail record, TProductArrivalDetailExample example) {
        UpdateByExampleParms parms = new UpdateByExampleParms(record, example);
        int rows = getSqlMapClientTemplate().update("t_product_arrival_detail.ibatorgenerated_updateByExample", parms);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table t_product_arrival_detail
     *
     * @ibatorgenerated Wed Oct 14 14:13:27 CST 2009
     */
    public int updateByPrimaryKeySelective(TProductArrivalDetail record) {
        int rows = getSqlMapClientTemplate().update("t_product_arrival_detail.ibatorgenerated_updateByPrimaryKeySelective", record);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table t_product_arrival_detail
     *
     * @ibatorgenerated Wed Oct 14 14:13:27 CST 2009
     */
    public int updateByPrimaryKey(TProductArrivalDetail record) {
        int rows = getSqlMapClientTemplate().update("t_product_arrival_detail.ibatorgenerated_updateByPrimaryKey", record);
        return rows;
    }

    /**
     * This class was generated by Apache iBATIS ibator.
     * This class corresponds to the database table t_product_arrival_detail
     *
     * @ibatorgenerated Wed Oct 14 14:13:27 CST 2009
     */
    private static class UpdateByExampleParms extends TProductArrivalDetailExample {
        private Object record;

        public UpdateByExampleParms(Object record, TProductArrivalDetailExample example) {
            super(example);
            this.record = record;
        }

        public Object getRecord() {
            return record;
        }
    }

	@Override
	public List<ProductArrivalDetailDto> getArrivalDetail(String arrivalId) {
		return this.getSqlMapClientTemplate().queryForList("t_product_arrival_detail.getArrivalDetail", arrivalId);
	}

	@Override
	public TProductArrivalDetail getArrDetailWithChildren(String arrivalId) {
		return (TProductArrivalDetail)this.getSqlMapClientTemplate().queryForObject("t_product_arrival_detail.getArrDetailWithChildren", arrivalId);
	}

	@Override
	public List<ProductArrivalDetailDto> getArrivalDetailByView(String arrivalId) {
		return this.getSqlMapClientTemplate().queryForList("t_product_arrival_detail.getArrivalDetailByView", arrivalId);
	}

	@Override
	public List<TProductArrivalDetail> getDirectArrDetail(String arrivalId) {
		return this.getSqlMapClientTemplate().queryForList("t_product_arrival_detail.getArrivalDetailByArrId", arrivalId);
	}

	@Override
	public List<ProductArrivalDetailDto> getDetail4Direct(String arrivalId) {
		return this.getSqlMapClientTemplate().queryForList("t_product_arrival_detail.getDirectArrDetail", arrivalId);
	}

	@Override
	public List<TProductArrivalDetail> getCanInvaArrDetail(String arrId) {
		return this.getSqlMapClientTemplate().queryForList("t_product_arrival_detail.getCanInvaArrDetail", arrId);
	}
}