package com.tl.resource.dao;

import com.tl.resource.business.dto.SupplierAssessmentDto;
import com.tl.resource.dao.pojo.TSupplierAssessment;

import java.util.List;
import java.util.Map;

public interface TSupplierAssessmentDAO {

	
	int deleteByPrimaryKey(TSupplierAssessment id);

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table t_contract_infor
	 * @ibatorgenerated  Wed Oct 14 14:13:27 CST 2009
	 */
	void insert(TSupplierAssessment record);


	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table t_contract_infor
	 * @ibatorgenerated  Wed Oct 14 14:13:27 CST 2009
	 */
	TSupplierAssessment selectByPrimaryKey(String id);

	/**

	int updateByPrimaryKeySelective(TSupplierAssessment record);

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table t_contract_infor
	 * @ibatorgenerated  Wed Oct 14 14:13:27 CST 2009
	 */
	int updateByPrimaryKey(TSupplierAssessment record);

	
	/**
	 * 根据查询条件得到合同需要下订单的合同列表
	 * @param parmMap
	 * @return
	 */
	public List<SupplierAssessmentDto> getAssessmentList(Map<String, Object> parmMap);

	public int getAssessmentListCount(Map<String, Object> parmMap) ;
	

	
	
}