package com.tl.resource.dao;

import com.tl.resource.business.dto.SuppliersBrandDto;
import com.tl.resource.dao.pojo.TSuppliersBrand;
import com.tl.resource.dao.pojo.TSuppliersBrandExample;
import java.util.List;
import java.util.Map;

import org.springframework.orm.ibatis.support.SqlMapClientDaoSupport;

public class TSuppliersBrandDAOImpl extends SqlMapClientDaoSupport implements TSuppliersBrandDAO {

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table t_suppliers_brand
     *
     * @ibatorgenerated Thu Nov 05 15:39:31 CST 2009
     */
    public TSuppliersBrandDAOImpl() {
        super();
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table t_suppliers_brand
     *
     * @ibatorgenerated Thu Nov 05 15:39:31 CST 2009
     */
    public int countByExample(TSuppliersBrandExample example) {
        Integer count = (Integer)  getSqlMapClientTemplate().queryForObject("t_suppliers_brand.ibatorgenerated_countByExample", example);
        return count.intValue();
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table t_suppliers_brand
     *
     * @ibatorgenerated Thu Nov 05 15:39:31 CST 2009
     */
    public int deleteByExample(TSuppliersBrandExample example) {
        int rows = getSqlMapClientTemplate().delete("t_suppliers_brand.ibatorgenerated_deleteByExample", example);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table t_suppliers_brand
     *
     * @ibatorgenerated Thu Nov 05 15:39:31 CST 2009
     */
    public int deleteByPrimaryKey(String id) {
        TSuppliersBrand key = new TSuppliersBrand();
        key.setId(id);
        int rows = getSqlMapClientTemplate().delete("t_suppliers_brand.ibatorgenerated_deleteByPrimaryKey", key);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table t_suppliers_brand
     *
     * @ibatorgenerated Thu Nov 05 15:39:31 CST 2009
     */
    public void insert(TSuppliersBrand record) {
        getSqlMapClientTemplate().insert("t_suppliers_brand.ibatorgenerated_insert", record);
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table t_suppliers_brand
     *
     * @ibatorgenerated Thu Nov 05 15:39:31 CST 2009
     */
    public void insertSelective(TSuppliersBrand record) {
        getSqlMapClientTemplate().insert("t_suppliers_brand.ibatorgenerated_insertSelective", record);
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table t_suppliers_brand
     *
     * @ibatorgenerated Thu Nov 05 15:39:31 CST 2009
     */
    public List selectByExample(TSuppliersBrandExample example) {
        List list = getSqlMapClientTemplate().queryForList("t_suppliers_brand.ibatorgenerated_selectByExample", example);
        return list;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table t_suppliers_brand
     *
     * @ibatorgenerated Thu Nov 05 15:39:31 CST 2009
     */
    public TSuppliersBrand selectByPrimaryKey(String id) {
        TSuppliersBrand key = new TSuppliersBrand();
        key.setId(id);
        TSuppliersBrand record = (TSuppliersBrand) getSqlMapClientTemplate().queryForObject("t_suppliers_brand.ibatorgenerated_selectByPrimaryKey", key);
        return record;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table t_suppliers_brand
     *
     * @ibatorgenerated Thu Nov 05 15:39:31 CST 2009
     */
    public int updateByExampleSelective(TSuppliersBrand record, TSuppliersBrandExample example) {
        UpdateByExampleParms parms = new UpdateByExampleParms(record, example);
        int rows = getSqlMapClientTemplate().update("t_suppliers_brand.ibatorgenerated_updateByExampleSelective", parms);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table t_suppliers_brand
     *
     * @ibatorgenerated Thu Nov 05 15:39:31 CST 2009
     */
    public int updateByExample(TSuppliersBrand record, TSuppliersBrandExample example) {
        UpdateByExampleParms parms = new UpdateByExampleParms(record, example);
        int rows = getSqlMapClientTemplate().update("t_suppliers_brand.ibatorgenerated_updateByExample", parms);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table t_suppliers_brand
     *
     * @ibatorgenerated Thu Nov 05 15:39:31 CST 2009
     */
    public int updateByPrimaryKeySelective(TSuppliersBrand record) {
        int rows = getSqlMapClientTemplate().update("t_suppliers_brand.ibatorgenerated_updateByPrimaryKeySelective", record);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table t_suppliers_brand
     *
     * @ibatorgenerated Thu Nov 05 15:39:31 CST 2009
     */
    public int updateByPrimaryKey(TSuppliersBrand record) {
        int rows = getSqlMapClientTemplate().update("t_suppliers_brand.ibatorgenerated_updateByPrimaryKey", record);
        return rows;
    }

    /**
     * This class was generated by Apache iBATIS ibator.
     * This class corresponds to the database table t_suppliers_brand
     *
     * @ibatorgenerated Thu Nov 05 15:39:31 CST 2009
     */
    private static class UpdateByExampleParms extends TSuppliersBrandExample {
        private Object record;

        public UpdateByExampleParms(Object record, TSuppliersBrandExample example) {
            super(example);
            this.record = record;
        }

        public Object getRecord() {
            return record;
        }
    }

	@Override
	public List<SuppliersBrandDto> getSuppliersBrandByPageAndSupplierId(
			Map<String, Object> parmMap) {
		List<SuppliersBrandDto> list = getSqlMapClientTemplate().queryForList("suppliersBrand.getSuppliersBrandByPageAndSupplierId", parmMap);
        return list;
	}

	@Override
	public int getSuppliersBrandTotalBySupplierId(Map<String, Object> parmMap) {
		 Integer count = (Integer)  getSqlMapClientTemplate().queryForObject("suppliersBrand.getSuppliersBrandTotalBySupplierId", parmMap);
	        return count.intValue();
	}

	@Override
	public void deleteSupplierBrandBySupplierId(String supplierIdPar) {
		getSqlMapClientTemplate().delete("suppliersBrand.deleteSupplierBrandBySupplierId", supplierIdPar);
	}
}