package com.tl.resource.dao;

import com.tl.resource.dao.pojo.TWorkTrustDetail;
import com.tl.resource.dao.pojo.TWorkTrustDetailExample;
import java.util.List;
import org.springframework.orm.ibatis.support.SqlMapClientDaoSupport;

public class TWorkTrustDetailDAOImpl extends SqlMapClientDaoSupport implements TWorkTrustDetailDAO {

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table t_work_trust_detail
	 * @ibatorgenerated  Wed Mar 10 19:02:58 CST 2010
	 */
	public TWorkTrustDetailDAOImpl() {
		super();
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table t_work_trust_detail
	 * @ibatorgenerated  Wed Mar 10 19:02:58 CST 2010
	 */
	public int countByExample(TWorkTrustDetailExample example) {
		Integer count = (Integer) getSqlMapClientTemplate().queryForObject(
				"t_work_trust_detail.ibatorgenerated_countByExample", example);
		return count.intValue();
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table t_work_trust_detail
	 * @ibatorgenerated  Wed Mar 10 19:02:58 CST 2010
	 */
	public int deleteByExample(TWorkTrustDetailExample example) {
		int rows = getSqlMapClientTemplate().delete(
				"t_work_trust_detail.ibatorgenerated_deleteByExample", example);
		return rows;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table t_work_trust_detail
	 * @ibatorgenerated  Wed Mar 10 19:02:58 CST 2010
	 */
	public int deleteByPrimaryKey(String id) {
		TWorkTrustDetail key = new TWorkTrustDetail();
		key.setId(id);
		int rows = getSqlMapClientTemplate().delete(
				"t_work_trust_detail.ibatorgenerated_deleteByPrimaryKey", key);
		return rows;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table t_work_trust_detail
	 * @ibatorgenerated  Wed Mar 10 19:02:58 CST 2010
	 */
	public void insert(TWorkTrustDetail record) {
		getSqlMapClientTemplate().insert(
				"t_work_trust_detail.ibatorgenerated_insert", record);
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table t_work_trust_detail
	 * @ibatorgenerated  Wed Mar 10 19:02:58 CST 2010
	 */
	public void insertSelective(TWorkTrustDetail record) {
		getSqlMapClientTemplate().insert(
				"t_work_trust_detail.ibatorgenerated_insertSelective", record);
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table t_work_trust_detail
	 * @ibatorgenerated  Wed Mar 10 19:02:58 CST 2010
	 */
	public List selectByExample(TWorkTrustDetailExample example) {
		List list = getSqlMapClientTemplate().queryForList(
				"t_work_trust_detail.ibatorgenerated_selectByExample", example);
		return list;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table t_work_trust_detail
	 * @ibatorgenerated  Wed Mar 10 19:02:58 CST 2010
	 */
	public TWorkTrustDetail selectByPrimaryKey(String id) {
		TWorkTrustDetail key = new TWorkTrustDetail();
		key.setId(id);
		TWorkTrustDetail record = (TWorkTrustDetail) getSqlMapClientTemplate()
				.queryForObject(
						"t_work_trust_detail.ibatorgenerated_selectByPrimaryKey",
						key);
		return record;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table t_work_trust_detail
	 * @ibatorgenerated  Wed Mar 10 19:02:58 CST 2010
	 */
	public int updateByExampleSelective(TWorkTrustDetail record,
			TWorkTrustDetailExample example) {
		UpdateByExampleParms parms = new UpdateByExampleParms(record, example);
		int rows = getSqlMapClientTemplate().update(
				"t_work_trust_detail.ibatorgenerated_updateByExampleSelective",
				parms);
		return rows;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table t_work_trust_detail
	 * @ibatorgenerated  Wed Mar 10 19:02:58 CST 2010
	 */
	public int updateByExample(TWorkTrustDetail record,
			TWorkTrustDetailExample example) {
		UpdateByExampleParms parms = new UpdateByExampleParms(record, example);
		int rows = getSqlMapClientTemplate().update(
				"t_work_trust_detail.ibatorgenerated_updateByExample", parms);
		return rows;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table t_work_trust_detail
	 * @ibatorgenerated  Wed Mar 10 19:02:58 CST 2010
	 */
	public int updateByPrimaryKeySelective(TWorkTrustDetail record) {
		int rows = getSqlMapClientTemplate()
				.update(
						"t_work_trust_detail.ibatorgenerated_updateByPrimaryKeySelective",
						record);
		return rows;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table t_work_trust_detail
	 * @ibatorgenerated  Wed Mar 10 19:02:58 CST 2010
	 */
	public int updateByPrimaryKey(TWorkTrustDetail record) {
		int rows = getSqlMapClientTemplate().update(
				"t_work_trust_detail.ibatorgenerated_updateByPrimaryKey",
				record);
		return rows;
	}

	/**
	 * This class was generated by Apache iBATIS ibator. This class corresponds to the database table t_work_trust_detail
	 * @ibatorgenerated  Wed Mar 10 19:02:58 CST 2010
	 */
	private static class UpdateByExampleParms extends TWorkTrustDetailExample {
		private Object record;

		public UpdateByExampleParms(Object record,
				TWorkTrustDetailExample example) {
			super(example);
			this.record = record;
		}

		public Object getRecord() {
			return record;
		}
	}
}