package com.tl.resource.business.dto;

import java.math.BigDecimal;
import java.text.SimpleDateFormat;
import java.util.Date;

public class ReserveOrderDto {
	
	private String id;
	
	private String orderCode;
	
	private String contractCode;
	
	private Integer currencyId;

	private String currencyName;
	
	private String orderDate;
	
	private Integer orderType;
	
	private Integer status;
	
	private String supplierName;
	
	private String supplierId;
	
	private Integer urgentLevel;
	
	private String contactPerson;
	
	private BigDecimal totalMoney;
	
	private BigDecimal taxRate;
	
	private BigDecimal productMoney;
	
	private String deliveryDate;
	
	private String mome;
	
	private Date editDate;
	
	private String editDateCopy;

	private String userId;
	
	private String userName;

	public String getEditDateCopy() {
		return editDateCopy;
	}


	public void setEditDateCopy() {
		SimpleDateFormat dateFormat = new SimpleDateFormat("yyyy-MM-dd");
		if(!"".equals(this.editDate)) {
			this.editDateCopy = dateFormat.format(this.editDate).toString();
		}
	}
	
	
	public String getId() {
		return id;
	}

	
	public void setId(String id) {
		this.id = id;
	}

	
	public String getOrderCode() {
		return orderCode;
	}

	
	public void setOrderCode(String orderCode) {
		this.orderCode = orderCode;
	}

	
	public String getContractCode() {
		return contractCode;
	}

	
	public void setContractCode(String contractCode) {
		this.contractCode = contractCode;
	}

	
	public String getCurrencyName() {
		return currencyName;
	}

	public void setCurrencyName(String currencyName) {
		this.currencyName = currencyName;
	}

	
	public String getOrderDate() {
		return orderDate;
	}

	
	public void setOrderDate(String orderDate) {
		this.orderDate = orderDate;
	}

	
	public Integer getOrderType() {
		return orderType;
	}

	
	public void setOrderType(Integer orderType) {
		this.orderType = orderType;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method returns the value of the database column t_order_infor.status
	 * @return  the value of t_order_infor.status
	 * @ibatorgenerated  Wed Oct 14 14:13:27 CST 2009
	 */
	public Integer getStatus() {
		return status;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method sets the value of the database column t_order_infor.status
	 * @param status  the value for t_order_infor.status
	 * @ibatorgenerated  Wed Oct 14 14:13:27 CST 2009
	 */
	public void setStatus(Integer status) {
		this.status = status;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method returns the value of the database column t_order_infor.supplier_name
	 * @return  the value of t_order_infor.supplier_name
	 * @ibatorgenerated  Wed Oct 14 14:13:27 CST 2009
	 */
	public String getSupplierName() {
		return supplierName;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method sets the value of the database column t_order_infor.supplier_name
	 * @param supplierName  the value for t_order_infor.supplier_name
	 * @ibatorgenerated  Wed Oct 14 14:13:27 CST 2009
	 */
	public void setSupplierName(String supplierName) {
		this.supplierName = supplierName;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method returns the value of the database column t_order_infor.supplier_id
	 * @return  the value of t_order_infor.supplier_id
	 * @ibatorgenerated  Wed Oct 14 14:13:27 CST 2009
	 */
	public String getSupplierId() {
		return supplierId;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method sets the value of the database column t_order_infor.supplier_id
	 * @param supplierId  the value for t_order_infor.supplier_id
	 * @ibatorgenerated  Wed Oct 14 14:13:27 CST 2009
	 */
	public void setSupplierId(String supplierId) {
		this.supplierId = supplierId;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method returns the value of the database column t_order_infor.urgent_level
	 * @return  the value of t_order_infor.urgent_level
	 * @ibatorgenerated  Wed Oct 14 14:13:27 CST 2009
	 */
	public Integer getUrgentLevel() {
		return urgentLevel;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method sets the value of the database column t_order_infor.urgent_level
	 * @param urgentLevel  the value for t_order_infor.urgent_level
	 * @ibatorgenerated  Wed Oct 14 14:13:27 CST 2009
	 */
	public void setUrgentLevel(Integer urgentLevel) {
		this.urgentLevel = urgentLevel;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method returns the value of the database column t_order_infor.contact_person
	 * @return  the value of t_order_infor.contact_person
	 * @ibatorgenerated  Wed Oct 14 14:13:27 CST 2009
	 */
	public String getContactPerson() {
		return contactPerson;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method sets the value of the database column t_order_infor.contact_person
	 * @param contactPerson  the value for t_order_infor.contact_person
	 * @ibatorgenerated  Wed Oct 14 14:13:27 CST 2009
	 */
	public void setContactPerson(String contactPerson) {
		this.contactPerson = contactPerson;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method returns the value of the database column t_order_infor.total_money
	 * @return  the value of t_order_infor.total_money
	 * @ibatorgenerated  Wed Oct 14 14:13:27 CST 2009
	 */
	public BigDecimal getTotalMoney() {
		return totalMoney;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method sets the value of the database column t_order_infor.total_money
	 * @param totalMoney  the value for t_order_infor.total_money
	 * @ibatorgenerated  Wed Oct 14 14:13:27 CST 2009
	 */
	public void setTotalMoney(BigDecimal totalMoney) {
		this.totalMoney = totalMoney;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method returns the value of the database column t_order_infor.tax_rate
	 * @return  the value of t_order_infor.tax_rate
	 * @ibatorgenerated  Wed Oct 14 14:13:27 CST 2009
	 */
	public BigDecimal getTaxRate() {
		return taxRate;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method sets the value of the database column t_order_infor.tax_rate
	 * @param taxRate  the value for t_order_infor.tax_rate
	 * @ibatorgenerated  Wed Oct 14 14:13:27 CST 2009
	 */
	public void setTaxRate(BigDecimal taxRate) {
		this.taxRate = taxRate;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method returns the value of the database column t_order_infor.product_money
	 * @return  the value of t_order_infor.product_money
	 * @ibatorgenerated  Wed Oct 14 14:13:27 CST 2009
	 */
	public BigDecimal getProductMoney() {
		return productMoney;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method sets the value of the database column t_order_infor.product_money
	 * @param productMoney  the value for t_order_infor.product_money
	 * @ibatorgenerated  Wed Oct 14 14:13:27 CST 2009
	 */
	public void setProductMoney(BigDecimal productMoney) {
		this.productMoney = productMoney;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method returns the value of the database column t_order_infor.delivery_date
	 * @return  the value of t_order_infor.delivery_date
	 * @ibatorgenerated  Wed Oct 14 14:13:27 CST 2009
	 */
	public String getDeliveryDate() {
		return deliveryDate;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method sets the value of the database column t_order_infor.delivery_date
	 * @param deliveryDate  the value for t_order_infor.delivery_date
	 * @ibatorgenerated  Wed Oct 14 14:13:27 CST 2009
	 */
	public void setDeliveryDate(String deliveryDate) {
		this.deliveryDate = deliveryDate;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method returns the value of the database column t_order_infor.mome
	 * @return  the value of t_order_infor.mome
	 * @ibatorgenerated  Wed Oct 14 14:13:27 CST 2009
	 */
	public String getMome() {
		return mome;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method sets the value of the database column t_order_infor.mome
	 * @param mome  the value for t_order_infor.mome
	 * @ibatorgenerated  Wed Oct 14 14:13:27 CST 2009
	 */
	public void setMome(String mome) {
		this.mome = mome;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method returns the value of the database column t_order_infor.edit_date
	 * @return  the value of t_order_infor.edit_date
	 * @ibatorgenerated  Wed Oct 14 14:13:27 CST 2009
	 */
	public Date getEditDate() {
		return editDate;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method sets the value of the database column t_order_infor.edit_date
	 * @param editDate  the value for t_order_infor.edit_date
	 * @ibatorgenerated  Wed Oct 14 14:13:27 CST 2009
	 */
	public void setEditDate(Date editDate) {
		this.editDate = editDate;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method returns the value of the database column t_order_infor.user_id
	 * @return  the value of t_order_infor.user_id
	 * @ibatorgenerated  Wed Oct 14 14:13:27 CST 2009
	 */
	public String getUserId() {
		return userId;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method sets the value of the database column t_order_infor.user_id
	 * @param userId  the value for t_order_infor.user_id
	 * @ibatorgenerated  Wed Oct 14 14:13:27 CST 2009
	 */
	public void setUserId(String userId) {
		this.userId = userId;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method returns the value of the database column t_order_infor.user_name
	 * @return  the value of t_order_infor.user_name
	 * @ibatorgenerated  Wed Oct 14 14:13:27 CST 2009
	 */
	public String getUserName() {
		return userName;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method sets the value of the database column t_order_infor.user_name
	 * @param userName  the value for t_order_infor.user_name
	 * @ibatorgenerated  Wed Oct 14 14:13:27 CST 2009
	 */
	public void setUserName(String userName) {
		this.userName = userName;
	}
	
	public Integer getCurrencyId() {
		return currencyId;
	}


	public void setCurrencyId(Integer currencyId) {
		this.currencyId = currencyId;
	}
}
