package com.tl.resource.dao;

import com.tl.resource.dao.pojo.TAuditInstanceHistory;
import com.tl.resource.dao.pojo.TAuditInstanceHistoryExample;
import java.util.List;
import org.springframework.orm.ibatis.support.SqlMapClientDaoSupport;

public class TAuditInstanceHistoryDAOImpl extends SqlMapClientDaoSupport implements TAuditInstanceHistoryDAO {

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table t_audit_instance_history
     *
     * @ibatorgenerated Sat Mar 27 11:22:07 CST 2010
     */
    public TAuditInstanceHistoryDAOImpl() {
        super();
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table t_audit_instance_history
     *
     * @ibatorgenerated Sat Mar 27 11:22:07 CST 2010
     */
    public int countByExample(TAuditInstanceHistoryExample example) {
        Integer count = (Integer)  getSqlMapClientTemplate().queryForObject("t_audit_instance_history.ibatorgenerated_countByExample", example);
        return count.intValue();
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table t_audit_instance_history
     *
     * @ibatorgenerated Sat Mar 27 11:22:07 CST 2010
     */
    public int deleteByExample(TAuditInstanceHistoryExample example) {
        int rows = getSqlMapClientTemplate().delete("t_audit_instance_history.ibatorgenerated_deleteByExample", example);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table t_audit_instance_history
     *
     * @ibatorgenerated Sat Mar 27 11:22:07 CST 2010
     */
    public void insert(TAuditInstanceHistory record) {
        getSqlMapClientTemplate().insert("t_audit_instance_history.ibatorgenerated_insert", record);
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table t_audit_instance_history
     *
     * @ibatorgenerated Sat Mar 27 11:22:07 CST 2010
     */
    public void insertSelective(TAuditInstanceHistory record) {
        getSqlMapClientTemplate().insert("t_audit_instance_history.ibatorgenerated_insertSelective", record);
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table t_audit_instance_history
     *
     * @ibatorgenerated Sat Mar 27 11:22:07 CST 2010
     */
    public List selectByExample(TAuditInstanceHistoryExample example) {
        List list = getSqlMapClientTemplate().queryForList("t_audit_instance_history.ibatorgenerated_selectByExample", example);
        return list;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table t_audit_instance_history
     *
     * @ibatorgenerated Sat Mar 27 11:22:07 CST 2010
     */
    public int updateByExampleSelective(TAuditInstanceHistory record, TAuditInstanceHistoryExample example) {
        UpdateByExampleParms parms = new UpdateByExampleParms(record, example);
        int rows = getSqlMapClientTemplate().update("t_audit_instance_history.ibatorgenerated_updateByExampleSelective", parms);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table t_audit_instance_history
     *
     * @ibatorgenerated Sat Mar 27 11:22:07 CST 2010
     */
    public int updateByExample(TAuditInstanceHistory record, TAuditInstanceHistoryExample example) {
        UpdateByExampleParms parms = new UpdateByExampleParms(record, example);
        int rows = getSqlMapClientTemplate().update("t_audit_instance_history.ibatorgenerated_updateByExample", parms);
        return rows;
    }

    /**
     * This class was generated by Apache iBATIS ibator.
     * This class corresponds to the database table t_audit_instance_history
     *
     * @ibatorgenerated Sat Mar 27 11:22:07 CST 2010
     */
    private static class UpdateByExampleParms extends TAuditInstanceHistoryExample {
        private Object record;

        public UpdateByExampleParms(Object record, TAuditInstanceHistoryExample example) {
            super(example);
            this.record = record;
        }

        public Object getRecord() {
            return record;
        }
    }
}