package com.tl.resource.dao;

import com.tl.resource.dao.pojo.TAuditContentDef;
import com.tl.resource.dao.pojo.TAuditContentDefExample;
import java.util.List;
import org.springframework.orm.ibatis.support.SqlMapClientDaoSupport;

public class TAuditContentDefDAOImpl extends SqlMapClientDaoSupport implements TAuditContentDefDAO {

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table t_audit_content_def
     *
     * @ibatorgenerated Thu Apr 22 16:34:14 CST 2010
     */
    public TAuditContentDefDAOImpl() {
        super();
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table t_audit_content_def
     *
     * @ibatorgenerated Thu Apr 22 16:34:14 CST 2010
     */
    public int countByExample(TAuditContentDefExample example) {
        Integer count = (Integer)  getSqlMapClientTemplate().queryForObject("t_audit_content_def.ibatorgenerated_countByExample", example);
        return count.intValue();
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table t_audit_content_def
     *
     * @ibatorgenerated Thu Apr 22 16:34:14 CST 2010
     */
    public int deleteByExample(TAuditContentDefExample example) {
        int rows = getSqlMapClientTemplate().delete("t_audit_content_def.ibatorgenerated_deleteByExample", example);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table t_audit_content_def
     *
     * @ibatorgenerated Thu Apr 22 16:34:14 CST 2010
     */
    public int deleteByPrimaryKey(String id) {
        TAuditContentDef key = new TAuditContentDef();
        key.setId(id);
        int rows = getSqlMapClientTemplate().delete("t_audit_content_def.ibatorgenerated_deleteByPrimaryKey", key);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table t_audit_content_def
     *
     * @ibatorgenerated Thu Apr 22 16:34:14 CST 2010
     */
    public void insert(TAuditContentDef record) {
        getSqlMapClientTemplate().insert("t_audit_content_def.ibatorgenerated_insert", record);
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table t_audit_content_def
     *
     * @ibatorgenerated Thu Apr 22 16:34:14 CST 2010
     */
    public void insertSelective(TAuditContentDef record) {
        getSqlMapClientTemplate().insert("t_audit_content_def.ibatorgenerated_insertSelective", record);
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table t_audit_content_def
     *
     * @ibatorgenerated Thu Apr 22 16:34:14 CST 2010
     */
    public List selectByExample(TAuditContentDefExample example) {
        List list = getSqlMapClientTemplate().queryForList("t_audit_content_def.ibatorgenerated_selectByExample", example);
        return list;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table t_audit_content_def
     *
     * @ibatorgenerated Thu Apr 22 16:34:14 CST 2010
     */
    public TAuditContentDef selectByPrimaryKey(String id) {
        TAuditContentDef key = new TAuditContentDef();
        key.setId(id);
        TAuditContentDef record = (TAuditContentDef) getSqlMapClientTemplate().queryForObject("t_audit_content_def.ibatorgenerated_selectByPrimaryKey", key);
        return record;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table t_audit_content_def
     *
     * @ibatorgenerated Thu Apr 22 16:34:14 CST 2010
     */
    public int updateByExampleSelective(TAuditContentDef record, TAuditContentDefExample example) {
        UpdateByExampleParms parms = new UpdateByExampleParms(record, example);
        int rows = getSqlMapClientTemplate().update("t_audit_content_def.ibatorgenerated_updateByExampleSelective", parms);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table t_audit_content_def
     *
     * @ibatorgenerated Thu Apr 22 16:34:14 CST 2010
     */
    public int updateByExample(TAuditContentDef record, TAuditContentDefExample example) {
        UpdateByExampleParms parms = new UpdateByExampleParms(record, example);
        int rows = getSqlMapClientTemplate().update("t_audit_content_def.ibatorgenerated_updateByExample", parms);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table t_audit_content_def
     *
     * @ibatorgenerated Thu Apr 22 16:34:14 CST 2010
     */
    public int updateByPrimaryKeySelective(TAuditContentDef record) {
        int rows = getSqlMapClientTemplate().update("t_audit_content_def.ibatorgenerated_updateByPrimaryKeySelective", record);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table t_audit_content_def
     *
     * @ibatorgenerated Thu Apr 22 16:34:14 CST 2010
     */
    public int updateByPrimaryKey(TAuditContentDef record) {
        int rows = getSqlMapClientTemplate().update("t_audit_content_def.ibatorgenerated_updateByPrimaryKey", record);
        return rows;
    }

    /**
     * This class was generated by Apache iBATIS ibator.
     * This class corresponds to the database table t_audit_content_def
     *
     * @ibatorgenerated Thu Apr 22 16:34:14 CST 2010
     */
    private static class UpdateByExampleParms extends TAuditContentDefExample {
        private Object record;

        public UpdateByExampleParms(Object record, TAuditContentDefExample example) {
            super(example);
            this.record = record;
        }

        public Object getRecord() {
            return record;
        }
    }

	@Override
	public List<TAuditContentDef> selectByAuditDetailId(String auditDetailId) {
		// TODO Auto-generated method stub
		List list = getSqlMapClientTemplate().queryForList("t_audit_content_def.selectByAuditDetailId", auditDetailId);
        return list;
	}
	@Override
	public List<TAuditContentDef> selectByAuditInsId(String id) {
		// TODO Auto-generated method stub
		List list = getSqlMapClientTemplate().queryForList("t_audit_content_def.selectByAuditInsId", id);
        return list;
	}
	@Override
	public List<TAuditContentDef> selectByAuditHisId(String id) {
		// TODO Auto-generated method stub
		List list = getSqlMapClientTemplate().queryForList("t_audit_content_def.selectByAuditHisId", id);
        return list;
	}
}