package com.tl.resource.dao;

import com.tl.resource.dao.pojo.TAuditFlowDetail;
import com.tl.resource.dao.pojo.TAuditFlowDetailExample;
import java.util.List;
import org.springframework.orm.ibatis.support.SqlMapClientDaoSupport;

public class TAuditFlowDetailDAOImpl extends SqlMapClientDaoSupport implements TAuditFlowDetailDAO {

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table t_audit_flow_detail
     *
     * @ibatorgenerated Tue Oct 20 11:57:32 CST 2009
     */
    public TAuditFlowDetailDAOImpl() {
        super();
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table t_audit_flow_detail
     *
     * @ibatorgenerated Tue Oct 20 11:57:32 CST 2009
     */
    public int countByExample(TAuditFlowDetailExample example) {
        Integer count = (Integer)  getSqlMapClientTemplate().queryForObject("t_audit_flow_detail.ibatorgenerated_countByExample", example);
        return count.intValue();
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table t_audit_flow_detail
     *
     * @ibatorgenerated Tue Oct 20 11:57:32 CST 2009
     */
    public int deleteByExample(TAuditFlowDetailExample example) {
        int rows = getSqlMapClientTemplate().delete("t_audit_flow_detail.ibatorgenerated_deleteByExample", example);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table t_audit_flow_detail
     *
     * @ibatorgenerated Tue Oct 20 11:57:32 CST 2009
     */
    public int deleteByPrimaryKey(String id) {
        TAuditFlowDetail key = new TAuditFlowDetail();
        key.setId(id);
        int rows = getSqlMapClientTemplate().delete("t_audit_flow_detail.ibatorgenerated_deleteByPrimaryKey", key);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table t_audit_flow_detail
     *
     * @ibatorgenerated Tue Oct 20 11:57:32 CST 2009
     */
    public void insert(TAuditFlowDetail record) {
        getSqlMapClientTemplate().insert("t_audit_flow_detail.ibatorgenerated_insert", record);
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table t_audit_flow_detail
     *
     * @ibatorgenerated Tue Oct 20 11:57:32 CST 2009
     */
    public void insertSelective(TAuditFlowDetail record) {
        getSqlMapClientTemplate().insert("t_audit_flow_detail.ibatorgenerated_insertSelective", record);
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table t_audit_flow_detail
     *
     * @ibatorgenerated Tue Oct 20 11:57:32 CST 2009
     */
    public List selectByExample(TAuditFlowDetailExample example) {
        List list = getSqlMapClientTemplate().queryForList("t_audit_flow_detail.ibatorgenerated_selectByExample", example);
        return list;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table t_audit_flow_detail
     *
     * @ibatorgenerated Tue Oct 20 11:57:32 CST 2009
     */
    public TAuditFlowDetail selectByPrimaryKey(String id) {
        TAuditFlowDetail key = new TAuditFlowDetail();
        key.setId(id);
        TAuditFlowDetail record = (TAuditFlowDetail) getSqlMapClientTemplate().queryForObject("t_audit_flow_detail.ibatorgenerated_selectByPrimaryKey", key);
        return record;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table t_audit_flow_detail
     *
     * @ibatorgenerated Tue Oct 20 11:57:32 CST 2009
     */
    public int updateByExampleSelective(TAuditFlowDetail record, TAuditFlowDetailExample example) {
        UpdateByExampleParms parms = new UpdateByExampleParms(record, example);
        int rows = getSqlMapClientTemplate().update("t_audit_flow_detail.ibatorgenerated_updateByExampleSelective", parms);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table t_audit_flow_detail
     *
     * @ibatorgenerated Tue Oct 20 11:57:32 CST 2009
     */
    public int updateByExample(TAuditFlowDetail record, TAuditFlowDetailExample example) {
        UpdateByExampleParms parms = new UpdateByExampleParms(record, example);
        int rows = getSqlMapClientTemplate().update("t_audit_flow_detail.ibatorgenerated_updateByExample", parms);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table t_audit_flow_detail
     *
     * @ibatorgenerated Tue Oct 20 11:57:32 CST 2009
     */
    public int updateByPrimaryKeySelective(TAuditFlowDetail record) {
        int rows = getSqlMapClientTemplate().update("t_audit_flow_detail.ibatorgenerated_updateByPrimaryKeySelective", record);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table t_audit_flow_detail
     *
     * @ibatorgenerated Tue Oct 20 11:57:32 CST 2009
     */
    public int updateByPrimaryKey(TAuditFlowDetail record) {
        int rows = getSqlMapClientTemplate().update("t_audit_flow_detail.ibatorgenerated_updateByPrimaryKey", record);
        return rows;
    }

    /**
     * This class was generated by Apache iBATIS ibator.
     * This class corresponds to the database table t_audit_flow_detail
     *
     * @ibatorgenerated Tue Oct 20 11:57:32 CST 2009
     */
    private static class UpdateByExampleParms extends TAuditFlowDetailExample {
        private Object record;

        public UpdateByExampleParms(Object record, TAuditFlowDetailExample example) {
            super(example);
            this.record = record;
        }

        public Object getRecord() {
            return record;
        }
    }
    
   
}