package com.tl.resource.dao;

import com.tl.resource.dao.pojo.TContractAccountsInfor;
import com.tl.resource.dao.pojo.TContractAccountsInforExample;

import java.math.BigDecimal;
import java.util.List;
import java.util.Map;

public interface TContractAccountsInforDAO {
    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table t_contract_accounts_infor
     *
     * @ibatorgenerated Thu Nov 26 20:05:56 CST 2009
     */
    int countByExample(TContractAccountsInforExample example);

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table t_contract_accounts_infor
     *
     * @ibatorgenerated Thu Nov 26 20:05:56 CST 2009
     */
    int deleteByExample(TContractAccountsInforExample example);

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table t_contract_accounts_infor
     *
     * @ibatorgenerated Thu Nov 26 20:05:56 CST 2009
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table t_contract_accounts_infor
     *
     * @ibatorgenerated Thu Nov 26 20:05:56 CST 2009
     */
    void insert(TContractAccountsInfor record);

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table t_contract_accounts_infor
     *
     * @ibatorgenerated Thu Nov 26 20:05:56 CST 2009
     */
    void insertSelective(TContractAccountsInfor record);

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table t_contract_accounts_infor
     *
     * @ibatorgenerated Thu Nov 26 20:05:56 CST 2009
     */
    List selectByExample(TContractAccountsInforExample example);

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table t_contract_accounts_infor
     *
     * @ibatorgenerated Thu Nov 26 20:05:56 CST 2009
     */
    TContractAccountsInfor selectByPrimaryKey(String id);

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table t_contract_accounts_infor
     *
     * @ibatorgenerated Thu Nov 26 20:05:56 CST 2009
     */
    int updateByExampleSelective(TContractAccountsInfor record, TContractAccountsInforExample example);

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table t_contract_accounts_infor
     *
     * @ibatorgenerated Thu Nov 26 20:05:56 CST 2009
     */
    int updateByExample(TContractAccountsInfor record, TContractAccountsInforExample example);

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table t_contract_accounts_infor
     *
     * @ibatorgenerated Thu Nov 26 20:05:56 CST 2009
     */
    int updateByPrimaryKeySelective(TContractAccountsInfor record);

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table t_contract_accounts_infor
     *
     * @ibatorgenerated Thu Nov 26 20:05:56 CST 2009
     */
    int updateByPrimaryKey(TContractAccountsInfor record);
    
      
    List findContractList(Map<String, Object> str);
    
    int findContractListCount(Map<String, Object> str);
    
    BigDecimal getContractNeedMoney(String contractId);
}