package com.tl.resource.dao;

import com.tl.resource.dao.pojo.TContractProjectSortInfor;
import com.tl.resource.dao.pojo.TContractProjectSortInforExample;
import java.util.List;

public interface TContractProjectSortInforDAO {

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table t_contract_project_sort_infor
	 * @ibatorgenerated  Wed Oct 14 14:13:27 CST 2009
	 */
	int countByExample(TContractProjectSortInforExample example);

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table t_contract_project_sort_infor
	 * @ibatorgenerated  Wed Oct 14 14:13:27 CST 2009
	 */
	int deleteByExample(TContractProjectSortInforExample example);

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table t_contract_project_sort_infor
	 * @ibatorgenerated  Wed Oct 14 14:13:27 CST 2009
	 */
	int deleteByPrimaryKey(String id);

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table t_contract_project_sort_infor
	 * @ibatorgenerated  Wed Oct 14 14:13:27 CST 2009
	 */
	void insert(TContractProjectSortInfor record);

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table t_contract_project_sort_infor
	 * @ibatorgenerated  Wed Oct 14 14:13:27 CST 2009
	 */
	void insertSelective(TContractProjectSortInfor record);

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table t_contract_project_sort_infor
	 * @ibatorgenerated  Wed Oct 14 14:13:27 CST 2009
	 */
	List selectByExample(TContractProjectSortInforExample example);

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table t_contract_project_sort_infor
	 * @ibatorgenerated  Wed Oct 14 14:13:27 CST 2009
	 */
	TContractProjectSortInfor selectByPrimaryKey(String id);

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table t_contract_project_sort_infor
	 * @ibatorgenerated  Wed Oct 14 14:13:27 CST 2009
	 */
	int updateByExampleSelective(TContractProjectSortInfor record,
			TContractProjectSortInforExample example);

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table t_contract_project_sort_infor
	 * @ibatorgenerated  Wed Oct 14 14:13:27 CST 2009
	 */
	int updateByExample(TContractProjectSortInfor record,
			TContractProjectSortInforExample example);

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table t_contract_project_sort_infor
	 * @ibatorgenerated  Wed Oct 14 14:13:27 CST 2009
	 */
	int updateByPrimaryKeySelective(TContractProjectSortInfor record);

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table t_contract_project_sort_infor
	 * @ibatorgenerated  Wed Oct 14 14:13:27 CST 2009
	 */
	int updateByPrimaryKey(TContractProjectSortInfor record);
	
	
	/**
	 * 根据合同ID得到合同详细分类
	 * @param contractId
	 * @return
	 */
	public List<TContractProjectSortInfor> getCPSIList(String contractId);
}