package com.tl.resource.dao;

import com.tl.resource.business.dto.CustormerAssessmentDto;
import com.tl.resource.dao.pojo.TCustormerAssessment;

import java.util.List;
import java.util.Map;

public interface TCustormerAssessmentDAO {

	
	int deleteByPrimaryKey(TCustormerAssessment id);

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table t_contract_infor
	 * @ibatorgenerated  Wed Oct 14 14:13:27 CST 2009
	 */
	void insert(TCustormerAssessment record);


	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table t_contract_infor
	 * @ibatorgenerated  Wed Oct 14 14:13:27 CST 2009
	 */
	TCustormerAssessment selectByPrimaryKey(String id);

	/**

	int updateByPrimaryKeySelective(TCustormerAssessment record);

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table t_contract_infor
	 * @ibatorgenerated  Wed Oct 14 14:13:27 CST 2009
	 */
	int updateByPrimaryKey(TCustormerAssessment record);

	
	/**
	 * 根据查询条件得到合同需要下订单的合同列表
	 * @param parmMap
	 * @return
	 */
	public List<CustormerAssessmentDto> getAssessmentList(Map<String, Object> parmMap);

	public int getAssessmentListCount(Map<String, Object> parmMap) ;
	

	
	
}