package com.tl.resource.dao;

import java.util.List;
import java.util.Map;

import org.springframework.orm.ibatis.support.SqlMapClientDaoSupport;

import com.tl.resource.dao.pojo.TCustomersDegree;
import com.tl.resource.dao.pojo.TCustomersDegreeExample;

public class TCustomersDegreeDAOImpl extends SqlMapClientDaoSupport implements TCustomersDegreeDAO {

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table t_customers_degree
	 * @ibatorgenerated  Wed Oct 14 14:13:27 CST 2009
	 */
	public TCustomersDegreeDAOImpl() {
		super();
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table t_customers_degree
	 * @ibatorgenerated  Wed Oct 14 14:13:27 CST 2009
	 */
	public int countByExample(TCustomersDegreeExample example) {
		Integer count = (Integer) getSqlMapClientTemplate().queryForObject(
				"t_customers_degree.ibatorgenerated_countByExample", example);
		return count.intValue();
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table t_customers_degree
	 * @ibatorgenerated  Wed Oct 14 14:13:27 CST 2009
	 */
	public int deleteByExample(TCustomersDegreeExample example) {
		int rows = getSqlMapClientTemplate().delete(
				"t_customers_degree.ibatorgenerated_deleteByExample", example);
		return rows;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table t_customers_degree
	 * @ibatorgenerated  Wed Oct 14 14:13:27 CST 2009
	 */
	public int deleteByPrimaryKey(String id) {
		TCustomersDegree key = new TCustomersDegree();
		key.setId(id);
		int rows = getSqlMapClientTemplate().delete(
				"t_customers_degree.ibatorgenerated_deleteByPrimaryKey", key);
		return rows;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table t_customers_degree
	 * @ibatorgenerated  Wed Oct 14 14:13:27 CST 2009
	 */
	public void insert(TCustomersDegree record) {
		getSqlMapClientTemplate().insert(
				"t_customers_degree.ibatorgenerated_insert", record);
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table t_customers_degree
	 * @ibatorgenerated  Wed Oct 14 14:13:27 CST 2009
	 */
	public void insertSelective(TCustomersDegree record) {
		getSqlMapClientTemplate().insert(
				"t_customers_degree.ibatorgenerated_insertSelective", record);
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table t_customers_degree
	 * @ibatorgenerated  Wed Oct 14 14:13:27 CST 2009
	 */
	public List selectByExample(TCustomersDegreeExample example) {
		List list = getSqlMapClientTemplate().queryForList(
				"t_customers_degree.ibatorgenerated_selectByExample", example);
		return list;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table t_customers_degree
	 * @ibatorgenerated  Wed Oct 14 14:13:27 CST 2009
	 */
	public TCustomersDegree selectByPrimaryKey(String id) {
		TCustomersDegree key = new TCustomersDegree();
		key.setId(id);
		TCustomersDegree record = (TCustomersDegree) getSqlMapClientTemplate()
				.queryForObject(
						"t_customers_degree.ibatorgenerated_selectByPrimaryKey",
						key);
		return record;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table t_customers_degree
	 * @ibatorgenerated  Wed Oct 14 14:13:27 CST 2009
	 */
	public int updateByExampleSelective(TCustomersDegree record,
			TCustomersDegreeExample example) {
		UpdateByExampleParms parms = new UpdateByExampleParms(record, example);
		int rows = getSqlMapClientTemplate().update(
				"t_customers_degree.ibatorgenerated_updateByExampleSelective",
				parms);
		return rows;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table t_customers_degree
	 * @ibatorgenerated  Wed Oct 14 14:13:27 CST 2009
	 */
	public int updateByExample(TCustomersDegree record,
			TCustomersDegreeExample example) {
		UpdateByExampleParms parms = new UpdateByExampleParms(record, example);
		int rows = getSqlMapClientTemplate().update(
				"t_customers_degree.ibatorgenerated_updateByExample", parms);
		return rows;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table t_customers_degree
	 * @ibatorgenerated  Wed Oct 14 14:13:27 CST 2009
	 */
	public int updateByPrimaryKeySelective(TCustomersDegree record) {
		int rows = getSqlMapClientTemplate()
				.update(
						"t_customers_degree.ibatorgenerated_updateByPrimaryKeySelective",
						record);
		return rows;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table t_customers_degree
	 * @ibatorgenerated  Wed Oct 14 14:13:27 CST 2009
	 */
	public int updateByPrimaryKey(TCustomersDegree record) {
		int rows = getSqlMapClientTemplate()
				.update(
						"t_customers_degree.ibatorgenerated_updateByPrimaryKey",
						record);
		return rows;
	}

	/**
	 * This class was generated by Apache iBATIS ibator. This class corresponds to the database table t_customers_degree
	 * @ibatorgenerated  Wed Oct 14 14:13:27 CST 2009
	 */
	private static class UpdateByExampleParms extends TCustomersDegreeExample {
		private Object record;

		public UpdateByExampleParms(Object record,
				TCustomersDegreeExample example) {
			super(example);
			this.record = record;
		}

		public Object getRecord() {
			return record;
		}
	}

	@Override
	public List<TCustomersDegree> getAllCustomersDegree(Map<String, Object> parmMap) {
		List<TCustomersDegree> list = getSqlMapClientTemplate().queryForList(
				"t_customers_degree.getAllCustomersDegree",parmMap);
		return list;
	}
}