package com.tl.resource.dao;

import com.tl.resource.business.dto.InvoiceInforDto;
import com.tl.resource.dao.pojo.TInvoiceInfo;
import com.tl.resource.dao.pojo.TInvoiceInfoExample;

import java.util.List;
import java.util.Map;

public interface TInvoiceInfoDAO {
    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table t_invoice_info
     *
     * @ibatorgenerated Tue Dec 22 16:09:56 CST 2009
     */
    int countByExample(TInvoiceInfoExample example);

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table t_invoice_info
     *
     * @ibatorgenerated Tue Dec 22 16:09:56 CST 2009
     */
    int deleteByExample(TInvoiceInfoExample example);

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table t_invoice_info
     *
     * @ibatorgenerated Tue Dec 22 16:09:56 CST 2009
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table t_invoice_info
     *
     * @ibatorgenerated Tue Dec 22 16:09:56 CST 2009
     */
    void insert(TInvoiceInfo record);

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table t_invoice_info
     *
     * @ibatorgenerated Tue Dec 22 16:09:56 CST 2009
     */
    void insertSelective(TInvoiceInfo record);

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table t_invoice_info
     *
     * @ibatorgenerated Tue Dec 22 16:09:56 CST 2009
     */
    List selectByExample(TInvoiceInfoExample example);

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table t_invoice_info
     *
     * @ibatorgenerated Tue Dec 22 16:09:56 CST 2009
     */
    TInvoiceInfo selectByPrimaryKey(String id);

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table t_invoice_info
     *
     * @ibatorgenerated Tue Dec 22 16:09:56 CST 2009
     */
    int updateByExampleSelective(TInvoiceInfo record, TInvoiceInfoExample example);

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table t_invoice_info
     *
     * @ibatorgenerated Tue Dec 22 16:09:56 CST 2009
     */
    int updateByExample(TInvoiceInfo record, TInvoiceInfoExample example);

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table t_invoice_info
     *
     * @ibatorgenerated Tue Dec 22 16:09:56 CST 2009
     */
    int updateByPrimaryKeySelective(TInvoiceInfo record);

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table t_invoice_info
     *
     * @ibatorgenerated Tue Dec 22 16:09:56 CST 2009
     */
    int updateByPrimaryKey(TInvoiceInfo record);

	List<TInvoiceInfo> getInvoiceList(Map params);
}