package com.tl.resource.dao;

import java.util.HashMap;
import java.util.List;
import java.util.Map;

import org.springframework.orm.ibatis.support.SqlMapClientDaoSupport;

import com.tl.resource.business.dto.OutStockDetailDto;
import com.tl.resource.dao.pojo.TOutStockDetail;
import com.tl.resource.dao.pojo.TOutStockDetailExample;

public class TOutStockDetailDAOImpl extends SqlMapClientDaoSupport implements TOutStockDetailDAO {

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table t_out_stock_detail
     *
     * @ibatorgenerated Tue Nov 17 16:02:20 CST 2009
     */
    public TOutStockDetailDAOImpl() {
        super();
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table t_out_stock_detail
     *
     * @ibatorgenerated Tue Nov 17 16:02:20 CST 2009
     */
    public int countByExample(TOutStockDetailExample example) {
        Integer count = (Integer)  getSqlMapClientTemplate().queryForObject("t_out_stock_detail.ibatorgenerated_countByExample", example);
        return count.intValue();
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table t_out_stock_detail
     *
     * @ibatorgenerated Tue Nov 17 16:02:20 CST 2009
     */
    public int deleteByExample(TOutStockDetailExample example) {
        int rows = getSqlMapClientTemplate().delete("t_out_stock_detail.ibatorgenerated_deleteByExample", example);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table t_out_stock_detail
     *
     * @ibatorgenerated Tue Nov 17 16:02:20 CST 2009
     */
    public int deleteByPrimaryKey(String id) {
        TOutStockDetail key = new TOutStockDetail();
        key.setId(id);
        int rows = getSqlMapClientTemplate().delete("t_out_stock_detail.ibatorgenerated_deleteByPrimaryKey", key);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table t_out_stock_detail
     *
     * @ibatorgenerated Tue Nov 17 16:02:20 CST 2009
     */
    public void insert(TOutStockDetail record) {
        getSqlMapClientTemplate().insert("t_out_stock_detail.ibatorgenerated_insert", record);
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table t_out_stock_detail
     *
     * @ibatorgenerated Tue Nov 17 16:02:20 CST 2009
     */
    public void insertSelective(TOutStockDetail record) {
        getSqlMapClientTemplate().insert("t_out_stock_detail.ibatorgenerated_insertSelective", record);
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table t_out_stock_detail
     *
     * @ibatorgenerated Tue Nov 17 16:02:20 CST 2009
     */
    public List selectByExample(TOutStockDetailExample example) {
        List list = getSqlMapClientTemplate().queryForList("t_out_stock_detail.ibatorgenerated_selectByExample", example);
        return list;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table t_out_stock_detail
     *
     * @ibatorgenerated Tue Nov 17 16:02:20 CST 2009
     */
    public TOutStockDetail selectByPrimaryKey(String id) {
        TOutStockDetail key = new TOutStockDetail();
        key.setId(id);
        TOutStockDetail record = (TOutStockDetail) getSqlMapClientTemplate().queryForObject("t_out_stock_detail.ibatorgenerated_selectByPrimaryKey", key);
        return record;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table t_out_stock_detail
     *
     * @ibatorgenerated Tue Nov 17 16:02:20 CST 2009
     */
    public int updateByExampleSelective(TOutStockDetail record, TOutStockDetailExample example) {
        UpdateByExampleParms parms = new UpdateByExampleParms(record, example);
        int rows = getSqlMapClientTemplate().update("t_out_stock_detail.ibatorgenerated_updateByExampleSelective", parms);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table t_out_stock_detail
     *
     * @ibatorgenerated Tue Nov 17 16:02:20 CST 2009
     */
    public int updateByExample(TOutStockDetail record, TOutStockDetailExample example) {
        UpdateByExampleParms parms = new UpdateByExampleParms(record, example);
        int rows = getSqlMapClientTemplate().update("t_out_stock_detail.ibatorgenerated_updateByExample", parms);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table t_out_stock_detail
     *
     * @ibatorgenerated Tue Nov 17 16:02:20 CST 2009
     */
    public int updateByPrimaryKeySelective(TOutStockDetail record) {
        int rows = getSqlMapClientTemplate().update("t_out_stock_detail.ibatorgenerated_updateByPrimaryKeySelective", record);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table t_out_stock_detail
     *
     * @ibatorgenerated Tue Nov 17 16:02:20 CST 2009
     */
    public int updateByPrimaryKey(TOutStockDetail record) {
        int rows = getSqlMapClientTemplate().update("t_out_stock_detail.ibatorgenerated_updateByPrimaryKey", record);
        return rows;
    }

    /**
     * This class was generated by Apache iBATIS ibator.
     * This class corresponds to the database table t_out_stock_detail
     *
     * @ibatorgenerated Tue Nov 17 16:02:20 CST 2009
     */
    private static class UpdateByExampleParms extends TOutStockDetailExample {
        private Object record;

        public UpdateByExampleParms(Object record, TOutStockDetailExample example) {
            super(example);
            this.record = record;
        }

        public Object getRecord() {
            return record;
        }
    }

	@Override
	public List selectDetailHasReserveInforByRecord(TOutStockDetail record) {
		// TODO Auto-generated method stub
		List list = getSqlMapClientTemplate().queryForList("t_out_stock_detail.getOutStockDetailHasReserveInfor", record);
        return list;
	}

	@Override
	public List<OutStockDetailDto> selectDetailHasOrderDetailInfor1(
			String orderId) {
		List<OutStockDetailDto> list = getSqlMapClientTemplate().queryForList("t_out_stock_detail.orderOutStockDetail", orderId);
        return list;
	}

	@Override
	public List<OutStockDetailDto> selectMeterialOutStockDetail(String orderId,
			String outStockInforId) {
		Map<String,String> params = new HashMap<String,String>(); 
		params.put("stockOrderInforId", orderId);
		params.put("outStockInforId", outStockInforId);
		List<OutStockDetailDto> list = getSqlMapClientTemplate().queryForList("t_out_stock_detail.meterialOutStockDetail", params);
        return list;
	}
}