package com.tl.resource.dao;

import com.tl.resource.business.dto.ProductArrivalDetailDto;
import com.tl.resource.dao.pojo.TProductArrivalDetail;
import com.tl.resource.dao.pojo.TProductArrivalDetailExample;
import java.util.List;

public interface TProductArrivalDetailDAO {
    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table t_product_arrival_detail
     *
     * @ibatorgenerated Wed Oct 14 14:13:27 CST 2009
     */
    int countByExample(TProductArrivalDetailExample example);

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table t_product_arrival_detail
     *
     * @ibatorgenerated Wed Oct 14 14:13:27 CST 2009
     */
    int deleteByExample(TProductArrivalDetailExample example);

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table t_product_arrival_detail
     *
     * @ibatorgenerated Wed Oct 14 14:13:27 CST 2009
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table t_product_arrival_detail
     *
     * @ibatorgenerated Wed Oct 14 14:13:27 CST 2009
     */
    void insert(TProductArrivalDetail record);

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table t_product_arrival_detail
     *
     * @ibatorgenerated Wed Oct 14 14:13:27 CST 2009
     */
    void insertSelective(TProductArrivalDetail record);

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table t_product_arrival_detail
     *
     * @ibatorgenerated Wed Oct 14 14:13:27 CST 2009
     */
    List selectByExample(TProductArrivalDetailExample example);

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table t_product_arrival_detail
     *
     * @ibatorgenerated Wed Oct 14 14:13:27 CST 2009
     */
    TProductArrivalDetail selectByPrimaryKey(String id);

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table t_product_arrival_detail
     *
     * @ibatorgenerated Wed Oct 14 14:13:27 CST 2009
     */
    int updateByExampleSelective(TProductArrivalDetail record, TProductArrivalDetailExample example);

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table t_product_arrival_detail
     *
     * @ibatorgenerated Wed Oct 14 14:13:27 CST 2009
     */
    int updateByExample(TProductArrivalDetail record, TProductArrivalDetailExample example);

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table t_product_arrival_detail
     *
     * @ibatorgenerated Wed Oct 14 14:13:27 CST 2009
     */
    int updateByPrimaryKeySelective(TProductArrivalDetail record);

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table t_product_arrival_detail
     *
     * @ibatorgenerated Wed Oct 14 14:13:27 CST 2009
     */
    int updateByPrimaryKey(TProductArrivalDetail record);
    
    /**
     * 获取到货详细
     * @param arrivalId
     * @return
     */
    public List<ProductArrivalDetailDto> getArrivalDetail(String arrivalId);
    
    /**
     * 获取到货信息级联其孩子节点
     * @param arrivalId
     * @return
     */
    public TProductArrivalDetail getArrDetailWithChildren(String arrivalId);
    
    /**
     * 根据到货单ID获取到货单详细(查看明细调用)
     * @param arrivalId
     * @return
     */
    List<ProductArrivalDetailDto> getArrivalDetailByView(String arrivalId);
    
    /**
     * 获取直接入库详细(getArrivalDetailByArrId)
     * @param arrivalId
     * @return
     */
    List<TProductArrivalDetail> getDirectArrDetail(String arrivalId);
    
    //getDirectArrDetail
    List<ProductArrivalDetailDto> getDetail4Direct(String arrivalId);
    
    List<TProductArrivalDetail> getCanInvaArrDetail(String arrId);
 }