package com.tl.resource.dao;

import com.tl.common.util.PaginationSupport;
import com.tl.resource.business.dto.QuoCodeTreeDto;
import com.tl.resource.business.dto.QuotationDto;
import com.tl.resource.dao.pojo.TCustomersInfor;
import com.tl.resource.dao.pojo.TQuotationInfor;
import com.tl.resource.dao.pojo.TQuotationInforExample;

import java.util.ArrayList;
import java.util.List;
import java.util.Map;

import org.springframework.orm.ibatis.support.SqlMapClientDaoSupport;

public class TQuotationInforDAOImpl extends SqlMapClientDaoSupport implements TQuotationInforDAO {

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table t_quotation_infor
	 * @ibatorgenerated  Wed Oct 14 14:13:27 CST 2009
	 */
	public TQuotationInforDAOImpl() {
		super();
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table t_quotation_infor
	 * @ibatorgenerated  Wed Oct 14 14:13:27 CST 2009
	 */
	public int countByExample(TQuotationInforExample example) {
		Integer count = (Integer) getSqlMapClientTemplate().queryForObject(
				"t_quotation_infor.ibatorgenerated_countByExample", example);
		return count.intValue();
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table t_quotation_infor
	 * @ibatorgenerated  Wed Oct 14 14:13:27 CST 2009
	 */
	public int deleteByExample(TQuotationInforExample example) {
		int rows = getSqlMapClientTemplate().delete(
				"t_quotation_infor.ibatorgenerated_deleteByExample", example);
		return rows;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table t_quotation_infor
	 * @ibatorgenerated  Wed Oct 14 14:13:27 CST 2009
	 */
	public int deleteByPrimaryKey(String id) {
		TQuotationInfor key = new TQuotationInfor();
		key.setId(id);
		int rows = getSqlMapClientTemplate().delete(
				"t_quotation_infor.ibatorgenerated_deleteByPrimaryKey", key);
		return rows;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table t_quotation_infor
	 * @ibatorgenerated  Wed Oct 14 14:13:27 CST 2009
	 */
	public void insert(TQuotationInfor record) {
		getSqlMapClientTemplate().insert(
				"t_quotation_infor.ibatorgenerated_insert", record);
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table t_quotation_infor
	 * @ibatorgenerated  Wed Oct 14 14:13:27 CST 2009
	 */
	public void insertSelective(TQuotationInfor record) {
		getSqlMapClientTemplate().insert(
				"t_quotation_infor.ibatorgenerated_insertSelective", record);
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table t_quotation_infor
	 * @ibatorgenerated  Wed Oct 14 14:13:27 CST 2009
	 */
	public List selectByExample(TQuotationInforExample example) {
		List list = getSqlMapClientTemplate().queryForList(
				"t_quotation_infor.ibatorgenerated_selectByExample", example);
		return list;
	}
	
	public List selectByExample(TQuotationInforExample example,int start,int end) {
		List list = getSqlMapClientTemplate().queryForList(
				"t_quotation_infor.ibatorgenerated_selectByExample", example,start,end);
		return list;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table t_quotation_infor
	 * @ibatorgenerated  Wed Oct 14 14:13:27 CST 2009
	 */
	public TQuotationInfor selectByPrimaryKey(String id) {
		TQuotationInfor key = new TQuotationInfor();
		key.setId(id);
		TQuotationInfor record = (TQuotationInfor) getSqlMapClientTemplate()
				.queryForObject(
						"t_quotation_infor.ibatorgenerated_selectByPrimaryKey",
						key);
		return record;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table t_quotation_infor
	 * @ibatorgenerated  Wed Oct 14 14:13:27 CST 2009
	 */
	public int updateByExampleSelective(TQuotationInfor record,
			TQuotationInforExample example) {
		UpdateByExampleParms parms = new UpdateByExampleParms(record, example);
		int rows = getSqlMapClientTemplate().update(
				"t_quotation_infor.ibatorgenerated_updateByExampleSelective",
				parms);
		return rows;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table t_quotation_infor
	 * @ibatorgenerated  Wed Oct 14 14:13:27 CST 2009
	 */
	public int updateByExample(TQuotationInfor record,
			TQuotationInforExample example) {
		UpdateByExampleParms parms = new UpdateByExampleParms(record, example);
		int rows = getSqlMapClientTemplate().update(
				"t_quotation_infor.ibatorgenerated_updateByExample", parms);
		return rows;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table t_quotation_infor
	 * @ibatorgenerated  Wed Oct 14 14:13:27 CST 2009
	 */
	public int updateByPrimaryKeySelective(TQuotationInfor record) {
		int rows = getSqlMapClientTemplate()
				.update(
						"t_quotation_infor.ibatorgenerated_updateByPrimaryKeySelective",
						record);
		return rows;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table t_quotation_infor
	 * @ibatorgenerated  Wed Oct 14 14:13:27 CST 2009
	 */
	public int updateByPrimaryKey(TQuotationInfor record) {
		int rows = getSqlMapClientTemplate().update(
				"t_quotation_infor.ibatorgenerated_updateByPrimaryKey", record);
		return rows;
	}

	/**
	 * This class was generated by Apache iBATIS ibator. This class corresponds to the database table t_quotation_infor
	 * @ibatorgenerated  Wed Oct 14 14:13:27 CST 2009
	 */
	private static class UpdateByExampleParms extends TQuotationInforExample {
		private Object record;

		public UpdateByExampleParms(Object record,
				TQuotationInforExample example) {
			super(example);
			this.record = record;
		}

		public Object getRecord() {
			return record;
		}
	}

	@Override
	public List<QuotationDto> getQuotationByPage(Map<String, Object> parmMap) {
		List<QuotationDto> list = new ArrayList<QuotationDto>();
		list = this.getSqlMapClientTemplate().queryForList("quotation.getQuotationByPage", parmMap);
		return list;
	}

	@Override
	public List<TCustomersInfor> getCustomerInfoByBage(
			Map<String, Object> parmMap) {
		List<TCustomersInfor> list = new ArrayList<TCustomersInfor>();
		list = this.getSqlMapClientTemplate().queryForList("t_customers_infor.getCustomerBySearch", parmMap);
		return list;
	}

	@Override
	public TQuotationInfor insertQuotation(TQuotationInfor quotationInfor) {
		return (TQuotationInfor)this.getSqlMapClientTemplate().insert("t_quotation_infor.ibatorgenerated_insertSelective", quotationInfor);
	}

	@Override
	public int getQuotaionTotal(Map<String, Object> parmMap) {
		return (Integer)this.getSqlMapClientTemplate().queryForObject("quotation.getQuotaionTotal", parmMap);
	}

	@Override
	public int getCustomerInfoTotal(Map<String, Object> parmMap) {
		return (Integer)this.getSqlMapClientTemplate().queryForObject("t_customers_infor.getCustomerInfoTotal", parmMap);
	}

	@Override
	public void deleteQuotation(TQuotationInfor quoInfo) throws Exception{
		this.getSqlMapClientTemplate().delete("t_quotation_infor.ibatorgenerated_deleteByPrimaryKey", quoInfo);
	}

	@Override
	public QuotationDto getQuoInfoById(String id) {
		QuotationDto quoInfo = null;
		quoInfo = (QuotationDto)this.getSqlMapClientTemplate().queryForObject("quotation.getQuoInfoById", id);
		return quoInfo;
	}

	@Override
	public void updateQuoInfo(TQuotationInfor quoInfo) {
		this.getSqlMapClientTemplate().update("t_quotation_infor.ibatorgenerated_updateByPrimaryKeySelective", quoInfo);
	}

	@Override
	public TQuotationInfor getQuoInforGroupBy(List<String> ids) {
		// TODO Auto-generated method stub
		List list = this.getSqlMapClientTemplate().queryForList("t_quotation_infor.getTheQuotationinforGroupBy", ids);
		if(list == null || list.size() != 1){
			return null;
		}
		return (TQuotationInfor) list.get(0);
	}

	@Override
	public TCustomersInfor getCustomerByCusCode(String customerCode) {
		return (TCustomersInfor)this.getSqlMapClientTemplate().queryForObject("t_customers_infor.getCustomerByCusCode", customerCode);
	}

	@Override
	public TQuotationInfor getQuotationById(TQuotationInfor quoInfo) {
		return (TQuotationInfor)this.getSqlMapClientTemplate().queryForObject("t_quotation_infor.ibatorgenerated_selectByPrimaryKey", quoInfo);
	}

	@Override
	public int updateStatus(String id, int i) {
		// TODO Auto-generated method stub
		TQuotationInfor record = new TQuotationInfor();
		record.setStatus(i);
		record.setId(id);
		int rows = getSqlMapClientTemplate().update(
				"t_quotation_infor.updateStatus", record);
		return rows;
	}

	
	@Override
	public List<TQuotationInfor> getQuotationListForOrder(
			Map<String, Object> parmMap) {
		return this.getSqlMapClientTemplate().queryForList("t_quotation_infor.getQuotationListForOrder", parmMap);
	}
	
	@Override
	public int getQuotationListCountForOrder(Map<String, Object> parmMap) {
		// TODO Auto-generated method stub
		Integer in = (Integer) this.getSqlMapClientTemplate().queryForObject("t_quotation_infor.getQuotationListCountForOrder", parmMap);
		return in.intValue();
	}

	@Override
	public int getExpectedQuo2QuoCount(Map<String, Object> params) {
		Integer in = (Integer) this.getSqlMapClientTemplate().queryForObject("t_quotation_infor.getExpectedQuo2QuoCount", params);
		return in.intValue();
	}

	@Override
	public int getTryTools2DeliveryCount(Map<String, Object> params) {
		Integer in = (Integer) this.getSqlMapClientTemplate().queryForObject("t_quotation_infor.getTryTools2DeliveryCount", params);
		return in.intValue();
	}

	@Override
	public int getTryTools2UploadReportCount(Map<String, Object> params) {
		Integer in = (Integer) this.getSqlMapClientTemplate().queryForObject("t_quotation_infor.getTryTools2UploadReportCount", params);
		return in.intValue();
	}

	@Override
	public int updateImpQuoCode(Map<String, Object> parmMap) {
		return this.getSqlMapClientTemplate().update("quotation.updateImpQuoCode", parmMap);
	}

	@Override
	public boolean isAllDeliveryed(String string) {
		java.math.BigDecimal in = (java.math.BigDecimal) this.getSqlMapClientTemplate().queryForObject("t_quotation_infor.quoAllDeliveryed", string);
		if(in.doubleValue() == 0){
			return true;
		}
		return false;
	}

	@Override
	public List<QuotationDto> getQuoInfoByImpQuoId(ArrayList<String> arrayList) {
		return this.getSqlMapClientTemplate().queryForList("quotation.getQuoInfoByImpQuoId", arrayList);
	}

	@Override
	public List<QuoCodeTreeDto> getDeliveryCode(String quoId) {
		return this.getSqlMapClientTemplate().queryForList("quoCodeTree.getDeliveryCode", quoId);
	}

	@Override
	public List<QuoCodeTreeDto> getDeliveryCodeByQuoId(String quoId) {
		return this.getSqlMapClientTemplate().queryForList("quoCodeTree.getDeliveryCodeByQuoId", quoId);
	}

	@Override
	public Integer getNumByReserveQuo(String quoId) {
		return (Integer)this.getSqlMapClientTemplate().queryForObject("quotation.getNumByReserveQuo", quoId);
	}

	@Override
	public void updateImpQuoCode(TQuotationInfor quoInfo) {
		this.getSqlMapClientTemplate().update("t_quotation_infor.updateImpQuoCode", quoInfo);
	}

	@Override
	public Integer updateExportQuoCode(Map<String, Object> parmMap) {
		return (Integer)this.getSqlMapClientTemplate().update("quotation.updateExportQuoCode", parmMap);
	}

	@Override
	public List<TQuotationInfor> getQuoInfoByCode(String quoCode) {
		TQuotationInforExample example = new TQuotationInforExample();
		example.createCriteria().andQuotationCodeEqualTo(quoCode);
		List<TQuotationInfor> list = this.selectByExample(example);
		return list;
	}
	
}