package com.tl.resource.dao;

import com.tl.resource.business.dto.QuoCodeTreeDto;
import com.tl.resource.business.dto.QuotationDto;
import com.tl.resource.dao.pojo.TCustomersInfor;
import com.tl.resource.dao.pojo.TQuotationInfor;
import com.tl.resource.dao.pojo.TQuotationInforExample;
import com.tl.resource.dao.pojo.TQuotationProductDetail;

import java.util.ArrayList;
import java.util.List;
import java.util.Map;

public interface TQuotationInforDAO {

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table t_quotation_infor
	 * @ibatorgenerated  Wed Oct 14 14:13:27 CST 2009
	 */
	int countByExample(TQuotationInforExample example);

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table t_quotation_infor
	 * @ibatorgenerated  Wed Oct 14 14:13:27 CST 2009
	 */
	int deleteByExample(TQuotationInforExample example);

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table t_quotation_infor
	 * @ibatorgenerated  Wed Oct 14 14:13:27 CST 2009
	 */
	int deleteByPrimaryKey(String id);

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table t_quotation_infor
	 * @ibatorgenerated  Wed Oct 14 14:13:27 CST 2009
	 */
	void insert(TQuotationInfor record);

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table t_quotation_infor
	 * @ibatorgenerated  Wed Oct 14 14:13:27 CST 2009
	 */
	void insertSelective(TQuotationInfor record);

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table t_quotation_infor
	 * @ibatorgenerated  Wed Oct 14 14:13:27 CST 2009
	 */
	List selectByExample(TQuotationInforExample example);
	
	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table t_quotation_infor
	 * @ibatorgenerated  Wed Oct 14 14:13:27 CST 2009
	 */
	List selectByExample(TQuotationInforExample example,int start,int limit);

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table t_quotation_infor
	 * @ibatorgenerated  Wed Oct 14 14:13:27 CST 2009
	 */
	TQuotationInfor selectByPrimaryKey(String id);

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table t_quotation_infor
	 * @ibatorgenerated  Wed Oct 14 14:13:27 CST 2009
	 */
	int updateByExampleSelective(TQuotationInfor record,
			TQuotationInforExample example);

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table t_quotation_infor
	 * @ibatorgenerated  Wed Oct 14 14:13:27 CST 2009
	 */
	int updateByExample(TQuotationInfor record, TQuotationInforExample example);

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table t_quotation_infor
	 * @ibatorgenerated  Wed Oct 14 14:13:27 CST 2009
	 */
	int updateByPrimaryKeySelective(TQuotationInfor record);

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table t_quotation_infor
	 * @ibatorgenerated  Wed Oct 14 14:13:27 CST 2009
	 */
	int updateByPrimaryKey(TQuotationInfor record);
	
	/**
	 * 获取报价信息
	 * @param parmMap 参数MAP 包含查询条件和分布信息
	 * @return 符合条件的报价单信息列表
	 */
	public List<QuotationDto> getQuotationByPage(Map<String, Object> parmMap);
	
	/**
	 * 得到客户信息
	 * @param parmMap 参数MAP 包含查询条件和分布信息
	 * @return 符合条件的客户信息列表
	 */
	public List<TCustomersInfor> getCustomerInfoByBage(Map<String, Object> parmMap);
	
	/**
	 * 得到客户总数
	 * @param parmMap
	 * @return
	 */
	public int getCustomerInfoTotal(Map<String, Object> parmMap);
	
	/**
	 * 根据用户编号获取用户信息
	 * @param customerCode
	 * @return
	 */
	public TCustomersInfor getCustomerByCusCode(String customerCode);
	
	/**
	 * 添加报价信息
	 * @param quotationInfor
	 * @return
	 */
	public TQuotationInfor insertQuotation(TQuotationInfor quotationInfor);
	
	/**
	 * 获取报价总数
	 * @param parmMap 参数Map
	 * @return
	 */
	public int getQuotaionTotal(Map<String, Object> parmMap);
	
	/**
	 * 删除报价信息
	 * @param id
	 */
	public void deleteQuotation(TQuotationInfor quoInfo) throws Exception;
	
	/**
	 * 根据ID获取报价信息
	 * @param id
	 * @return 报价信息DTO
	 */
	public QuotationDto getQuoInfoById(String id);
	
	/**
	 * 根据ID获取报价信息
	 * @param id
	 * @return 报价信息PO
	 */
	public TQuotationInfor getQuotationById(TQuotationInfor quoInfo);
	
	/**
	 * 修改报价信息
	 * @param quoInfo
	 */
	public void updateQuoInfo(TQuotationInfor quoInfo);
	/**
	 * 多个报价单，对金额进行分类汇总
	 */
	public TQuotationInfor getQuoInforGroupBy(List<String> ids);

	int updateStatus(String id, int i);
	
	/**
	 * 报价单列表（做订单，无自制品）
	 * @param parmMap
	 * @return
	 */
	public List<TQuotationInfor> getQuotationListForOrder(Map<String, Object> parmMap);
	
	/**
	 * 报价单列表数量（做订单，无自制品）
	 * @param parmMap
	 * @return
	 */
	public int getQuotationListCountForOrder(Map<String, Object> parmMap);
/**
 * 预定报价 到期 未转正式报价 个数
 * @param params
 * @return
 */
	int getExpectedQuo2QuoCount(Map<String, Object> params);
/**
 * 试刀申请已到试刀开始时间，还为交货，给物流提示
 * @param params
 * @return
 */
int getTryTools2DeliveryCount(Map<String, Object> params);
/**
 * 试刀申请 已到结束时间 还未传 试刀报告
 * @param params
 * @return
 */
int getTryTools2UploadReportCount(Map<String, Object> params);

	/**
	 * 修改报价单导入预订报价单
	 * @param parmMap
	 */
	int updateImpQuoCode(Map<String, Object> parmMap);

	boolean isAllDeliveryed(String string);

	List<QuotationDto> getQuoInfoByImpQuoId(ArrayList<String> arrayList);
	
	List<QuoCodeTreeDto> getDeliveryCode(String quoId);
	
	List<QuoCodeTreeDto> getDeliveryCodeByQuoId(String quoId);
	
	/**
	 * 预订报价单下的产品有多少还未转正式报价单
	 * @param quoId
	 * @return
	 */
	Integer getNumByReserveQuo(String quoId);
	
	/**
	 * 修改导入导入（导出）报价单单号
	 * @param quoInfo
	 */
	void updateImpQuoCode(TQuotationInfor quoInfo);
	
	/**
	 * 修改预订报价单导出报价单号
	 * @param parmMap
	 * @return
	 */
	Integer updateExportQuoCode(Map<String, Object> parmMap);
	
	/**
	 * 根据编号获取报价单
	 * @param quoCode
	 * @return
	 */
	List<TQuotationInfor> getQuoInfoByCode(String quoCode);
}