package com.tl.resource.dao;

import com.tl.resource.dao.pojo.TResourcePurview;
import com.tl.resource.dao.pojo.TResourcePurviewExample;
import java.util.List;
import org.springframework.orm.ibatis.support.SqlMapClientDaoSupport;

public class TResourcePurviewDAOImpl extends SqlMapClientDaoSupport implements TResourcePurviewDAO {

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table t_resource_purview
     *
     * @ibatorgenerated Fri Dec 25 14:16:06 CST 2009
     */
    public TResourcePurviewDAOImpl() {
        super();
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table t_resource_purview
     *
     * @ibatorgenerated Fri Dec 25 14:16:06 CST 2009
     */
    public int countByExample(TResourcePurviewExample example) {
        Integer count = (Integer)  getSqlMapClientTemplate().queryForObject("t_resource_purview.ibatorgenerated_countByExample", example);
        return count.intValue();
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table t_resource_purview
     *
     * @ibatorgenerated Fri Dec 25 14:16:06 CST 2009
     */
    public int deleteByExample(TResourcePurviewExample example) {
        int rows = getSqlMapClientTemplate().delete("t_resource_purview.ibatorgenerated_deleteByExample", example);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table t_resource_purview
     *
     * @ibatorgenerated Fri Dec 25 14:16:06 CST 2009
     */
    public int deleteByPrimaryKey(String id) {
        TResourcePurview key = new TResourcePurview();
        key.setId(id);
        int rows = getSqlMapClientTemplate().delete("t_resource_purview.ibatorgenerated_deleteByPrimaryKey", key);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table t_resource_purview
     *
     * @ibatorgenerated Fri Dec 25 14:16:06 CST 2009
     */
    public void insert(TResourcePurview record) {
        getSqlMapClientTemplate().insert("t_resource_purview.ibatorgenerated_insert", record);
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table t_resource_purview
     *
     * @ibatorgenerated Fri Dec 25 14:16:06 CST 2009
     */
    public void insertSelective(TResourcePurview record) {
        getSqlMapClientTemplate().insert("t_resource_purview.ibatorgenerated_insertSelective", record);
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table t_resource_purview
     *
     * @ibatorgenerated Fri Dec 25 14:16:06 CST 2009
     */
    public List selectByExample(TResourcePurviewExample example) {
        List list = getSqlMapClientTemplate().queryForList("t_resource_purview.ibatorgenerated_selectByExample", example);
        return list;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table t_resource_purview
     *
     * @ibatorgenerated Fri Dec 25 14:16:06 CST 2009
     */
    public TResourcePurview selectByPrimaryKey(String id) {
        TResourcePurview key = new TResourcePurview();
        key.setId(id);
        TResourcePurview record = (TResourcePurview) getSqlMapClientTemplate().queryForObject("t_resource_purview.ibatorgenerated_selectByPrimaryKey", key);
        return record;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table t_resource_purview
     *
     * @ibatorgenerated Fri Dec 25 14:16:06 CST 2009
     */
    public int updateByExampleSelective(TResourcePurview record, TResourcePurviewExample example) {
        UpdateByExampleParms parms = new UpdateByExampleParms(record, example);
        int rows = getSqlMapClientTemplate().update("t_resource_purview.ibatorgenerated_updateByExampleSelective", parms);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table t_resource_purview
     *
     * @ibatorgenerated Fri Dec 25 14:16:06 CST 2009
     */
    public int updateByExample(TResourcePurview record, TResourcePurviewExample example) {
        UpdateByExampleParms parms = new UpdateByExampleParms(record, example);
        int rows = getSqlMapClientTemplate().update("t_resource_purview.ibatorgenerated_updateByExample", parms);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table t_resource_purview
     *
     * @ibatorgenerated Fri Dec 25 14:16:06 CST 2009
     */
    public int updateByPrimaryKeySelective(TResourcePurview record) {
        int rows = getSqlMapClientTemplate().update("t_resource_purview.ibatorgenerated_updateByPrimaryKeySelective", record);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table t_resource_purview
     *
     * @ibatorgenerated Fri Dec 25 14:16:06 CST 2009
     */
    public int updateByPrimaryKey(TResourcePurview record) {
        int rows = getSqlMapClientTemplate().update("t_resource_purview.ibatorgenerated_updateByPrimaryKey", record);
        return rows;
    }

    /**
     * This class was generated by Apache iBATIS ibator.
     * This class corresponds to the database table t_resource_purview
     *
     * @ibatorgenerated Fri Dec 25 14:16:06 CST 2009
     */
    private static class UpdateByExampleParms extends TResourcePurviewExample {
        private Object record;

        public UpdateByExampleParms(Object record, TResourcePurviewExample example) {
            super(example);
            this.record = record;
        }

        public Object getRecord() {
            return record;
        }
    }
}