package com.tl.resource.dao;

import java.util.List;
import java.util.Map;

import com.tl.common.util.PaginationSupport;
import com.tl.resource.dao.pojo.TWorkTrustRecord;
import com.tl.resource.dao.pojo.TWorkTrustRecordExample;

public interface TWorkTrustRecordDAO {

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table t_work_trust_record
	 * @ibatorgenerated  Wed Mar 10 19:02:58 CST 2010
	 */
	int countByExample(TWorkTrustRecordExample example);

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table t_work_trust_record
	 * @ibatorgenerated  Wed Mar 10 19:02:58 CST 2010
	 */
	int deleteByExample(TWorkTrustRecordExample example);

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table t_work_trust_record
	 * @ibatorgenerated  Wed Mar 10 19:02:58 CST 2010
	 */
	int deleteByPrimaryKey(String id);

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table t_work_trust_record
	 * @ibatorgenerated  Wed Mar 10 19:02:58 CST 2010
	 */
	void insert(TWorkTrustRecord record);

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table t_work_trust_record
	 * @ibatorgenerated  Wed Mar 10 19:02:58 CST 2010
	 */
	void insertSelective(TWorkTrustRecord record);

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table t_work_trust_record
	 * @ibatorgenerated  Wed Mar 10 19:02:58 CST 2010
	 */
	List selectByExample(TWorkTrustRecordExample example);

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table t_work_trust_record
	 * @ibatorgenerated  Wed Mar 10 19:02:58 CST 2010
	 */
	TWorkTrustRecord selectByPrimaryKey(String id);

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table t_work_trust_record
	 * @ibatorgenerated  Wed Mar 10 19:02:58 CST 2010
	 */
	int updateByExampleSelective(TWorkTrustRecord record,
			TWorkTrustRecordExample example);

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table t_work_trust_record
	 * @ibatorgenerated  Wed Mar 10 19:02:58 CST 2010
	 */
	int updateByExample(TWorkTrustRecord record, TWorkTrustRecordExample example);

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table t_work_trust_record
	 * @ibatorgenerated  Wed Mar 10 19:02:58 CST 2010
	 */
	int updateByPrimaryKeySelective(TWorkTrustRecord record);

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table t_work_trust_record
	 * @ibatorgenerated  Wed Mar 10 19:02:58 CST 2010
	 */
	int updateByPrimaryKey(TWorkTrustRecord record);
	
	PaginationSupport getUserListWorkTrust(Map params, int startIndex,int pageSize);
}