package com.tl.resource.dao.pojo;

import java.util.Date;

public class TAccessories {
    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column t_accessories.id
     *
     * @ibatorgenerated Sat Dec 26 17:27:05 CST 2009
     */
    private String id;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column t_accessories.path
     *
     * @ibatorgenerated Sat Dec 26 17:27:05 CST 2009
     */
    private String path;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column t_accessories.file_name
     *
     * @ibatorgenerated Sat Dec 26 17:27:05 CST 2009
     */
    private String fileName;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column t_accessories.file_size
     *
     * @ibatorgenerated Sat Dec 26 17:27:05 CST 2009
     */
    private Long fileSize;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column t_accessories.upload_time
     *
     * @ibatorgenerated Sat Dec 26 17:27:05 CST 2009
     */
    private Date uploadTime;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column t_accessories.user_id
     *
     * @ibatorgenerated Sat Dec 26 17:27:05 CST 2009
     */
    private String userId;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column t_accessories.user_name
     *
     * @ibatorgenerated Sat Dec 26 17:27:05 CST 2009
     */
    private String userName;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column t_accessories.business_id
     *
     * @ibatorgenerated Sat Dec 26 17:27:05 CST 2009
     */
    private String businessId;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column t_accessories.business_type
     *
     * @ibatorgenerated Sat Dec 26 17:27:05 CST 2009
     */
    private Integer businessType;

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column t_accessories.id
     *
     * @return the value of t_accessories.id
     *
     * @ibatorgenerated Sat Dec 26 17:27:05 CST 2009
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column t_accessories.id
     *
     * @param id the value for t_accessories.id
     *
     * @ibatorgenerated Sat Dec 26 17:27:05 CST 2009
     */
    public void setId(String id) {
        this.id = id;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column t_accessories.path
     *
     * @return the value of t_accessories.path
     *
     * @ibatorgenerated Sat Dec 26 17:27:05 CST 2009
     */
    public String getPath() {
        return path;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column t_accessories.path
     *
     * @param path the value for t_accessories.path
     *
     * @ibatorgenerated Sat Dec 26 17:27:05 CST 2009
     */
    public void setPath(String path) {
        this.path = path;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column t_accessories.file_name
     *
     * @return the value of t_accessories.file_name
     *
     * @ibatorgenerated Sat Dec 26 17:27:05 CST 2009
     */
    public String getFileName() {
        return fileName;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column t_accessories.file_name
     *
     * @param fileName the value for t_accessories.file_name
     *
     * @ibatorgenerated Sat Dec 26 17:27:05 CST 2009
     */
    public void setFileName(String fileName) {
        this.fileName = fileName;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column t_accessories.file_size
     *
     * @return the value of t_accessories.file_size
     *
     * @ibatorgenerated Sat Dec 26 17:27:05 CST 2009
     */
    public Long getFileSize() {
        return fileSize;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column t_accessories.file_size
     *
     * @param fileSize the value for t_accessories.file_size
     *
     * @ibatorgenerated Sat Dec 26 17:27:05 CST 2009
     */
    public void setFileSize(Long fileSize) {
        this.fileSize = fileSize;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column t_accessories.upload_time
     *
     * @return the value of t_accessories.upload_time
     *
     * @ibatorgenerated Sat Dec 26 17:27:05 CST 2009
     */
    public Date getUploadTime() {
        return uploadTime;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column t_accessories.upload_time
     *
     * @param uploadTime the value for t_accessories.upload_time
     *
     * @ibatorgenerated Sat Dec 26 17:27:05 CST 2009
     */
    public void setUploadTime(Date uploadTime) {
        this.uploadTime = uploadTime;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column t_accessories.user_id
     *
     * @return the value of t_accessories.user_id
     *
     * @ibatorgenerated Sat Dec 26 17:27:05 CST 2009
     */
    public String getUserId() {
        return userId;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column t_accessories.user_id
     *
     * @param userId the value for t_accessories.user_id
     *
     * @ibatorgenerated Sat Dec 26 17:27:05 CST 2009
     */
    public void setUserId(String userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column t_accessories.user_name
     *
     * @return the value of t_accessories.user_name
     *
     * @ibatorgenerated Sat Dec 26 17:27:05 CST 2009
     */
    public String getUserName() {
        return userName;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column t_accessories.user_name
     *
     * @param userName the value for t_accessories.user_name
     *
     * @ibatorgenerated Sat Dec 26 17:27:05 CST 2009
     */
    public void setUserName(String userName) {
        this.userName = userName;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column t_accessories.business_id
     *
     * @return the value of t_accessories.business_id
     *
     * @ibatorgenerated Sat Dec 26 17:27:05 CST 2009
     */
    public String getBusinessId() {
        return businessId;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column t_accessories.business_id
     *
     * @param businessId the value for t_accessories.business_id
     *
     * @ibatorgenerated Sat Dec 26 17:27:05 CST 2009
     */
    public void setBusinessId(String businessId) {
        this.businessId = businessId;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column t_accessories.business_type
     *
     * @return the value of t_accessories.business_type
     *
     * @ibatorgenerated Sat Dec 26 17:27:05 CST 2009
     */
    public Integer getBusinessType() {
        return businessType;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column t_accessories.business_type
     *
     * @param businessType the value for t_accessories.business_type
     *
     * @ibatorgenerated Sat Dec 26 17:27:05 CST 2009
     */
    public void setBusinessType(Integer businessType) {
        this.businessType = businessType;
    }
}