package com.tl.resource.dao.pojo;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

public class TAuditTypeExample {

	/**
	 * This field was generated by Apache iBATIS ibator. This field corresponds to the database table t_audit_type
	 * @ibatorgenerated  Mon Mar 29 15:48:25 CST 2010
	 */
	protected String orderByClause;
	/**
	 * This field was generated by Apache iBATIS ibator. This field corresponds to the database table t_audit_type
	 * @ibatorgenerated  Mon Mar 29 15:48:25 CST 2010
	 */
	protected List oredCriteria;

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table t_audit_type
	 * @ibatorgenerated  Mon Mar 29 15:48:25 CST 2010
	 */
	public TAuditTypeExample() {
		oredCriteria = new ArrayList();
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table t_audit_type
	 * @ibatorgenerated  Mon Mar 29 15:48:25 CST 2010
	 */
	protected TAuditTypeExample(TAuditTypeExample example) {
		this.orderByClause = example.orderByClause;
		this.oredCriteria = example.oredCriteria;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table t_audit_type
	 * @ibatorgenerated  Mon Mar 29 15:48:25 CST 2010
	 */
	public void setOrderByClause(String orderByClause) {
		this.orderByClause = orderByClause;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table t_audit_type
	 * @ibatorgenerated  Mon Mar 29 15:48:25 CST 2010
	 */
	public String getOrderByClause() {
		return orderByClause;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table t_audit_type
	 * @ibatorgenerated  Mon Mar 29 15:48:25 CST 2010
	 */
	public List getOredCriteria() {
		return oredCriteria;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table t_audit_type
	 * @ibatorgenerated  Mon Mar 29 15:48:25 CST 2010
	 */
	public void or(Criteria criteria) {
		oredCriteria.add(criteria);
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table t_audit_type
	 * @ibatorgenerated  Mon Mar 29 15:48:25 CST 2010
	 */
	public Criteria createCriteria() {
		Criteria criteria = createCriteriaInternal();
		if (oredCriteria.size() == 0) {
			oredCriteria.add(criteria);
		}
		return criteria;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table t_audit_type
	 * @ibatorgenerated  Mon Mar 29 15:48:25 CST 2010
	 */
	protected Criteria createCriteriaInternal() {
		Criteria criteria = new Criteria();
		return criteria;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table t_audit_type
	 * @ibatorgenerated  Mon Mar 29 15:48:25 CST 2010
	 */
	public void clear() {
		oredCriteria.clear();
	}

	/**
	 * This class was generated by Apache iBATIS ibator. This class corresponds to the database table t_audit_type
	 * @ibatorgenerated  Mon Mar 29 15:48:25 CST 2010
	 */
	public static class Criteria {
		protected List criteriaWithoutValue;
		protected List criteriaWithSingleValue;
		protected List criteriaWithListValue;
		protected List criteriaWithBetweenValue;

		protected Criteria() {
			super();
			criteriaWithoutValue = new ArrayList();
			criteriaWithSingleValue = new ArrayList();
			criteriaWithListValue = new ArrayList();
			criteriaWithBetweenValue = new ArrayList();
		}

		public boolean isValid() {
			return criteriaWithoutValue.size() > 0
					|| criteriaWithSingleValue.size() > 0
					|| criteriaWithListValue.size() > 0
					|| criteriaWithBetweenValue.size() > 0;
		}

		public List getCriteriaWithoutValue() {
			return criteriaWithoutValue;
		}

		public List getCriteriaWithSingleValue() {
			return criteriaWithSingleValue;
		}

		public List getCriteriaWithListValue() {
			return criteriaWithListValue;
		}

		public List getCriteriaWithBetweenValue() {
			return criteriaWithBetweenValue;
		}

		protected void addCriterion(String condition) {
			if (condition == null) {
				throw new RuntimeException("Value for condition cannot be null");
			}
			criteriaWithoutValue.add(condition);
		}

		protected void addCriterion(String condition, Object value,
				String property) {
			if (value == null) {
				throw new RuntimeException("Value for " + property
						+ " cannot be null");
			}
			Map map = new HashMap();
			map.put("condition", condition);
			map.put("value", value);
			criteriaWithSingleValue.add(map);
		}

		protected void addCriterion(String condition, List values,
				String property) {
			if (values == null || values.size() == 0) {
				throw new RuntimeException("Value list for " + property
						+ " cannot be null or empty");
			}
			Map map = new HashMap();
			map.put("condition", condition);
			map.put("values", values);
			criteriaWithListValue.add(map);
		}

		protected void addCriterion(String condition, Object value1,
				Object value2, String property) {
			if (value1 == null || value2 == null) {
				throw new RuntimeException("Between values for " + property
						+ " cannot be null");
			}
			List list = new ArrayList();
			list.add(value1);
			list.add(value2);
			Map map = new HashMap();
			map.put("condition", condition);
			map.put("values", list);
			criteriaWithBetweenValue.add(map);
		}

		public Criteria andIdIsNull() {
			addCriterion("id is null");
			return this;
		}

		public Criteria andIdIsNotNull() {
			addCriterion("id is not null");
			return this;
		}

		public Criteria andIdEqualTo(String value) {
			addCriterion("id =", value, "id");
			return this;
		}

		public Criteria andIdNotEqualTo(String value) {
			addCriterion("id <>", value, "id");
			return this;
		}

		public Criteria andIdGreaterThan(String value) {
			addCriterion("id >", value, "id");
			return this;
		}

		public Criteria andIdGreaterThanOrEqualTo(String value) {
			addCriterion("id >=", value, "id");
			return this;
		}

		public Criteria andIdLessThan(String value) {
			addCriterion("id <", value, "id");
			return this;
		}

		public Criteria andIdLessThanOrEqualTo(String value) {
			addCriterion("id <=", value, "id");
			return this;
		}

		public Criteria andIdLike(String value) {
			addCriterion("id like", value, "id");
			return this;
		}

		public Criteria andIdNotLike(String value) {
			addCriterion("id not like", value, "id");
			return this;
		}

		public Criteria andIdIn(List values) {
			addCriterion("id in", values, "id");
			return this;
		}

		public Criteria andIdNotIn(List values) {
			addCriterion("id not in", values, "id");
			return this;
		}

		public Criteria andIdBetween(String value1, String value2) {
			addCriterion("id between", value1, value2, "id");
			return this;
		}

		public Criteria andIdNotBetween(String value1, String value2) {
			addCriterion("id not between", value1, value2, "id");
			return this;
		}

		public Criteria andAuditTypeNameIsNull() {
			addCriterion("audit_type_name is null");
			return this;
		}

		public Criteria andAuditTypeNameIsNotNull() {
			addCriterion("audit_type_name is not null");
			return this;
		}

		public Criteria andAuditTypeNameEqualTo(String value) {
			addCriterion("audit_type_name =", value, "auditTypeName");
			return this;
		}

		public Criteria andAuditTypeNameNotEqualTo(String value) {
			addCriterion("audit_type_name <>", value, "auditTypeName");
			return this;
		}

		public Criteria andAuditTypeNameGreaterThan(String value) {
			addCriterion("audit_type_name >", value, "auditTypeName");
			return this;
		}

		public Criteria andAuditTypeNameGreaterThanOrEqualTo(String value) {
			addCriterion("audit_type_name >=", value, "auditTypeName");
			return this;
		}

		public Criteria andAuditTypeNameLessThan(String value) {
			addCriterion("audit_type_name <", value, "auditTypeName");
			return this;
		}

		public Criteria andAuditTypeNameLessThanOrEqualTo(String value) {
			addCriterion("audit_type_name <=", value, "auditTypeName");
			return this;
		}

		public Criteria andAuditTypeNameLike(String value) {
			addCriterion("audit_type_name like", value, "auditTypeName");
			return this;
		}

		public Criteria andAuditTypeNameNotLike(String value) {
			addCriterion("audit_type_name not like", value, "auditTypeName");
			return this;
		}

		public Criteria andAuditTypeNameIn(List values) {
			addCriterion("audit_type_name in", values, "auditTypeName");
			return this;
		}

		public Criteria andAuditTypeNameNotIn(List values) {
			addCriterion("audit_type_name not in", values, "auditTypeName");
			return this;
		}

		public Criteria andAuditTypeNameBetween(String value1, String value2) {
			addCriterion("audit_type_name between", value1, value2,
					"auditTypeName");
			return this;
		}

		public Criteria andAuditTypeNameNotBetween(String value1, String value2) {
			addCriterion("audit_type_name not between", value1, value2,
					"auditTypeName");
			return this;
		}

		public Criteria andClassNameIsNull() {
			addCriterion("class_name is null");
			return this;
		}

		public Criteria andClassNameIsNotNull() {
			addCriterion("class_name is not null");
			return this;
		}

		public Criteria andClassNameEqualTo(String value) {
			addCriterion("class_name =", value, "className");
			return this;
		}

		public Criteria andClassNameNotEqualTo(String value) {
			addCriterion("class_name <>", value, "className");
			return this;
		}

		public Criteria andClassNameGreaterThan(String value) {
			addCriterion("class_name >", value, "className");
			return this;
		}

		public Criteria andClassNameGreaterThanOrEqualTo(String value) {
			addCriterion("class_name >=", value, "className");
			return this;
		}

		public Criteria andClassNameLessThan(String value) {
			addCriterion("class_name <", value, "className");
			return this;
		}

		public Criteria andClassNameLessThanOrEqualTo(String value) {
			addCriterion("class_name <=", value, "className");
			return this;
		}

		public Criteria andClassNameLike(String value) {
			addCriterion("class_name like", value, "className");
			return this;
		}

		public Criteria andClassNameNotLike(String value) {
			addCriterion("class_name not like", value, "className");
			return this;
		}

		public Criteria andClassNameIn(List values) {
			addCriterion("class_name in", values, "className");
			return this;
		}

		public Criteria andClassNameNotIn(List values) {
			addCriterion("class_name not in", values, "className");
			return this;
		}

		public Criteria andClassNameBetween(String value1, String value2) {
			addCriterion("class_name between", value1, value2, "className");
			return this;
		}

		public Criteria andClassNameNotBetween(String value1, String value2) {
			addCriterion("class_name not between", value1, value2, "className");
			return this;
		}

		public Criteria andSerialNumberIsNull() {
			addCriterion("serial_number is null");
			return this;
		}

		public Criteria andSerialNumberIsNotNull() {
			addCriterion("serial_number is not null");
			return this;
		}

		public Criteria andSerialNumberEqualTo(Integer value) {
			addCriterion("serial_number =", value, "serialNumber");
			return this;
		}

		public Criteria andSerialNumberNotEqualTo(Integer value) {
			addCriterion("serial_number <>", value, "serialNumber");
			return this;
		}

		public Criteria andSerialNumberGreaterThan(Integer value) {
			addCriterion("serial_number >", value, "serialNumber");
			return this;
		}

		public Criteria andSerialNumberGreaterThanOrEqualTo(Integer value) {
			addCriterion("serial_number >=", value, "serialNumber");
			return this;
		}

		public Criteria andSerialNumberLessThan(Integer value) {
			addCriterion("serial_number <", value, "serialNumber");
			return this;
		}

		public Criteria andSerialNumberLessThanOrEqualTo(Integer value) {
			addCriterion("serial_number <=", value, "serialNumber");
			return this;
		}

		public Criteria andSerialNumberIn(List values) {
			addCriterion("serial_number in", values, "serialNumber");
			return this;
		}

		public Criteria andSerialNumberNotIn(List values) {
			addCriterion("serial_number not in", values, "serialNumber");
			return this;
		}

		public Criteria andSerialNumberBetween(Integer value1, Integer value2) {
			addCriterion("serial_number between", value1, value2,
					"serialNumber");
			return this;
		}

		public Criteria andSerialNumberNotBetween(Integer value1, Integer value2) {
			addCriterion("serial_number not between", value1, value2,
					"serialNumber");
			return this;
		}
	}
}