package com.tl.resource.dao.pojo;

import java.math.BigDecimal;
import java.text.DateFormat;
import java.text.SimpleDateFormat;
import java.util.Date;

public class TContractInfor {
	private static final DateFormat df = new SimpleDateFormat("yyyy-MM-dd HH:mm");
	private String editDateString;

	/**
	 * This field was generated by Apache iBATIS ibator. This field corresponds to the database column t_contract_infor.id
	 * @ibatorgenerated  Tue Dec 15 20:18:03 CST 2009
	 */
	private String id;
	/**
	 * This field was generated by Apache iBATIS ibator. This field corresponds to the database column t_contract_infor.contract_code
	 * @ibatorgenerated  Tue Dec 15 20:18:03 CST 2009
	 */
	private String contractCode;
	/**
	 * This field was generated by Apache iBATIS ibator. This field corresponds to the database column t_contract_infor.seller_name
	 * @ibatorgenerated  Tue Dec 15 20:18:03 CST 2009
	 */
	private String sellerName;
	/**
	 * This field was generated by Apache iBATIS ibator. This field corresponds to the database column t_contract_infor.currency_name
	 * @ibatorgenerated  Tue Dec 15 20:18:03 CST 2009
	 */
	private String currencyId;
	private String currencyName;
	/**
	 * This field was generated by Apache iBATIS ibator. This field corresponds to the database column t_contract_infor.sign_date
	 * @ibatorgenerated  Tue Dec 15 20:18:03 CST 2009
	 */
	private String signDate;
	/**
	 * This field was generated by Apache iBATIS ibator. This field corresponds to the database column t_contract_infor.urgent_level
	 * @ibatorgenerated  Tue Dec 15 20:18:03 CST 2009
	 */
	private Integer urgentLevel;
	/**
	 * This field was generated by Apache iBATIS ibator. This field corresponds to the database column t_contract_infor.customer_code
	 * @ibatorgenerated  Tue Dec 15 20:18:03 CST 2009
	 */
	private String customerCode;
	/**
	 * This field was generated by Apache iBATIS ibator. This field corresponds to the database column t_contract_infor.customer_name
	 * @ibatorgenerated  Tue Dec 15 20:18:03 CST 2009
	 */
	private String customerName;
	/**
	 * This field was generated by Apache iBATIS ibator. This field corresponds to the database column t_contract_infor.status
	 * @ibatorgenerated  Tue Dec 15 20:18:03 CST 2009
	 */
	private Integer status;
	/**
	 * This field was generated by Apache iBATIS ibator. This field corresponds to the database column t_contract_infor.sign_address
	 * @ibatorgenerated  Tue Dec 15 20:18:03 CST 2009
	 */
	private String signAddress;
	/**
	 * This field was generated by Apache iBATIS ibator. This field corresponds to the database column t_contract_infor.reference
	 * @ibatorgenerated  Tue Dec 15 20:18:03 CST 2009
	 */
	private String reference;
	/**
	 * This field was generated by Apache iBATIS ibator. This field corresponds to the database column t_contract_infor.traffic_mode
	 * @ibatorgenerated  Tue Dec 15 20:18:03 CST 2009
	 */
	private String trafficMode;
	/**
	 * This field was generated by Apache iBATIS ibator. This field corresponds to the database column t_contract_infor.closing_account_mode_id
	 * @ibatorgenerated  Tue Dec 15 20:18:03 CST 2009
	 */
	private Integer closingAccountModeId;
	/**
	 * This field was generated by Apache iBATIS ibator. This field corresponds to the database column t_contract_infor.closing_account_mode
	 * @ibatorgenerated  Tue Dec 15 20:18:03 CST 2009
	 */
	private String closingAccountMode;
	/**
	 * This field was generated by Apache iBATIS ibator. This field corresponds to the database column t_contract_infor.delivery_address_type
	 * @ibatorgenerated  Tue Dec 15 20:18:03 CST 2009
	 */
	private String deliveryAddressType;
	/**
	 * This field was generated by Apache iBATIS ibator. This field corresponds to the database column t_contract_infor.other_convention
	 * @ibatorgenerated  Tue Dec 15 20:18:03 CST 2009
	 */
	private String otherConvention;
	/**
	 * This field was generated by Apache iBATIS ibator. This field corresponds to the database column t_contract_infor.effect_conditions
	 * @ibatorgenerated  Tue Dec 15 20:18:03 CST 2009
	 */
	private String effectConditions;
	/**
	 * This field was generated by Apache iBATIS ibator. This field corresponds to the database column t_contract_infor.product_money
	 * @ibatorgenerated  Tue Dec 15 20:18:03 CST 2009
	 */
	private BigDecimal productMoney;
	/**
	 * This field was generated by Apache iBATIS ibator. This field corresponds to the database column t_contract_infor.tax_rate
	 * @ibatorgenerated  Tue Dec 15 20:18:03 CST 2009
	 */
	private BigDecimal taxRate;
	/**
	 * This field was generated by Apache iBATIS ibator. This field corresponds to the database column t_contract_infor.tax_money
	 * @ibatorgenerated  Tue Dec 15 20:18:03 CST 2009
	 */
	private BigDecimal taxMoney;
	/**
	 * This field was generated by Apache iBATIS ibator. This field corresponds to the database column t_contract_infor.total_money
	 * @ibatorgenerated  Tue Dec 15 20:18:03 CST 2009
	 */
	private BigDecimal totalMoney;
	/**
	 * This field was generated by Apache iBATIS ibator. This field corresponds to the database column t_contract_infor.overall_rebate
	 * @ibatorgenerated  Tue Dec 15 20:18:03 CST 2009
	 */
	private BigDecimal overallRebate;
	/**
	 * This field was generated by Apache iBATIS ibator. This field corresponds to the database column t_contract_infor.final_money
	 * @ibatorgenerated  Tue Dec 15 20:18:03 CST 2009
	 */
	private BigDecimal finalMoney;
	/**
	 * This field was generated by Apache iBATIS ibator. This field corresponds to the database column t_contract_infor.memo
	 * @ibatorgenerated  Tue Dec 15 20:18:03 CST 2009
	 */
	private String memo;
	/**
	 * This field was generated by Apache iBATIS ibator. This field corresponds to the database column t_contract_infor.edit_date
	 * @ibatorgenerated  Tue Dec 15 20:18:03 CST 2009
	 */
	private Date editDate;
	/**
	 * This field was generated by Apache iBATIS ibator. This field corresponds to the database column t_contract_infor.user_id
	 * @ibatorgenerated  Tue Dec 15 20:18:03 CST 2009
	 */
	private String backMoneyDate;
	private String userId;
	/**
	 * This field was generated by Apache iBATIS ibator. This field corresponds to the database column t_contract_infor.user_name
	 * @ibatorgenerated  Tue Dec 15 20:18:03 CST 2009
	 */
	private String userName;
	/**
	 * This field was generated by Apache iBATIS ibator. This field corresponds to the database column t_contract_infor.contract_type
	 * @ibatorgenerated  Tue Dec 15 20:18:03 CST 2009
	 */
	private Integer contractType;
	
	/**
	 * This field was generated by Apache iBATIS ibator. This field corresponds to the database column t_contract_infor.customer_fax
	 * @ibatorgenerated  Tue Dec 15 20:18:03 CST 2009
	 */
	private String customerFax;
	/**
	 * This field was generated by Apache iBATIS ibator. This field corresponds to the database column t_contract_infor.customer_phone
	 * @ibatorgenerated  Tue Dec 15 20:18:03 CST 2009
	 */
	private String customerPhone;
	/**
	 * This field was generated by Apache iBATIS ibator. This field corresponds to the database column t_contract_infor.own_contact_person
	 * @ibatorgenerated  Tue Dec 15 20:18:03 CST 2009
	 */
	private String ownContactPerson;
	/**
	 * This field was generated by Apache iBATIS ibator. This field corresponds to the database column t_contract_infor.cus_contact_person
	 * @ibatorgenerated  Tue Dec 15 20:18:03 CST 2009
	 */
	private String cusContactPerson;

	/**
	 * This method was generated by Apache iBATIS ibator. This method returns the value of the database column t_contract_infor.id
	 * @return  the value of t_contract_infor.id
	 * @ibatorgenerated  Tue Dec 15 20:18:03 CST 2009
	 */
	 private String sellerId;
	 
	 private Integer fileCount;
	 
	public String getId() {
		return id;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method sets the value of the database column t_contract_infor.id
	 * @param id  the value for t_contract_infor.id
	 * @ibatorgenerated  Tue Dec 15 20:18:03 CST 2009
	 */
	public void setId(String id) {
		this.id = id;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method returns the value of the database column t_contract_infor.contract_code
	 * @return  the value of t_contract_infor.contract_code
	 * @ibatorgenerated  Tue Dec 15 20:18:03 CST 2009
	 */
	public String getContractCode() {
		return contractCode;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method sets the value of the database column t_contract_infor.contract_code
	 * @param contractCode  the value for t_contract_infor.contract_code
	 * @ibatorgenerated  Tue Dec 15 20:18:03 CST 2009
	 */
	public void setContractCode(String contractCode) {
		this.contractCode = contractCode;
	}

	public String getBackMoneyDate() {
		return backMoneyDate;
	}

	public void setBackMoneyDate(String backMoneyDate) {
		this.backMoneyDate = backMoneyDate;
	}

	

	/**
	 * This method was generated by Apache iBATIS ibator. This method returns the value of the database column t_contract_infor.seller_name
	 * @return  the value of t_contract_infor.seller_name
	 * @ibatorgenerated  Tue Dec 15 20:18:03 CST 2009
	 */
	public String getSellerName() {
		return sellerName;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method sets the value of the database column t_contract_infor.seller_name
	 * @param sellerName  the value for t_contract_infor.seller_name
	 * @ibatorgenerated  Tue Dec 15 20:18:03 CST 2009
	 */
	public void setSellerName(String sellerName) {
		this.sellerName = sellerName;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method returns the value of the database column t_contract_infor.currency_name
	 * @return  the value of t_contract_infor.currency_name
	 * @ibatorgenerated  Tue Dec 15 20:18:03 CST 2009
	 */
	public String getCurrencyName() {
		return currencyName;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method sets the value of the database column t_contract_infor.currency_name
	 * @param currencyName  the value for t_contract_infor.currency_name
	 * @ibatorgenerated  Tue Dec 15 20:18:03 CST 2009
	 */
	public void setCurrencyName(String currencyName) {
		this.currencyName = currencyName;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method returns the value of the database column t_contract_infor.sign_date
	 * @return  the value of t_contract_infor.sign_date
	 * @ibatorgenerated  Tue Dec 15 20:18:03 CST 2009
	 */
	public String getSignDate() {
		return signDate;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method sets the value of the database column t_contract_infor.sign_date
	 * @param signDate  the value for t_contract_infor.sign_date
	 * @ibatorgenerated  Tue Dec 15 20:18:03 CST 2009
	 */
	public void setSignDate(String signDate) {
		this.signDate = signDate;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method returns the value of the database column t_contract_infor.urgent_level
	 * @return  the value of t_contract_infor.urgent_level
	 * @ibatorgenerated  Tue Dec 15 20:18:03 CST 2009
	 */
	public Integer getUrgentLevel() {
		return urgentLevel;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method sets the value of the database column t_contract_infor.urgent_level
	 * @param urgentLevel  the value for t_contract_infor.urgent_level
	 * @ibatorgenerated  Tue Dec 15 20:18:03 CST 2009
	 */
	public void setUrgentLevel(Integer urgentLevel) {
		this.urgentLevel = urgentLevel;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method returns the value of the database column t_contract_infor.customer_code
	 * @return  the value of t_contract_infor.customer_code
	 * @ibatorgenerated  Tue Dec 15 20:18:03 CST 2009
	 */
	public String getCustomerCode() {
		return customerCode;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method sets the value of the database column t_contract_infor.customer_code
	 * @param customerCode  the value for t_contract_infor.customer_code
	 * @ibatorgenerated  Tue Dec 15 20:18:03 CST 2009
	 */
	public void setCustomerCode(String customerCode) {
		this.customerCode = customerCode;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method returns the value of the database column t_contract_infor.customer_name
	 * @return  the value of t_contract_infor.customer_name
	 * @ibatorgenerated  Tue Dec 15 20:18:03 CST 2009
	 */
	public String getCustomerName() {
		return customerName;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method sets the value of the database column t_contract_infor.customer_name
	 * @param customerName  the value for t_contract_infor.customer_name
	 * @ibatorgenerated  Tue Dec 15 20:18:03 CST 2009
	 */
	public void setCustomerName(String customerName) {
		this.customerName = customerName;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method returns the value of the database column t_contract_infor.status
	 * @return  the value of t_contract_infor.status
	 * @ibatorgenerated  Tue Dec 15 20:18:03 CST 2009
	 */
	public Integer getStatus() {
		return status;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method sets the value of the database column t_contract_infor.status
	 * @param status  the value for t_contract_infor.status
	 * @ibatorgenerated  Tue Dec 15 20:18:03 CST 2009
	 */
	public void setStatus(Integer status) {
		this.status = status;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method returns the value of the database column t_contract_infor.sign_address
	 * @return  the value of t_contract_infor.sign_address
	 * @ibatorgenerated  Tue Dec 15 20:18:03 CST 2009
	 */
	public String getSignAddress() {
		return signAddress;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method sets the value of the database column t_contract_infor.sign_address
	 * @param signAddress  the value for t_contract_infor.sign_address
	 * @ibatorgenerated  Tue Dec 15 20:18:03 CST 2009
	 */
	public void setSignAddress(String signAddress) {
		this.signAddress = signAddress;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method returns the value of the database column t_contract_infor.reference
	 * @return  the value of t_contract_infor.reference
	 * @ibatorgenerated  Tue Dec 15 20:18:03 CST 2009
	 */
	public String getReference() {
		return reference;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method sets the value of the database column t_contract_infor.reference
	 * @param reference  the value for t_contract_infor.reference
	 * @ibatorgenerated  Tue Dec 15 20:18:03 CST 2009
	 */
	public void setReference(String reference) {
		this.reference = reference;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method returns the value of the database column t_contract_infor.traffic_mode
	 * @return  the value of t_contract_infor.traffic_mode
	 * @ibatorgenerated  Tue Dec 15 20:18:03 CST 2009
	 */
	public String getTrafficMode() {
		return trafficMode;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method sets the value of the database column t_contract_infor.traffic_mode
	 * @param trafficMode  the value for t_contract_infor.traffic_mode
	 * @ibatorgenerated  Tue Dec 15 20:18:03 CST 2009
	 */
	public void setTrafficMode(String trafficMode) {
		this.trafficMode = trafficMode;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method returns the value of the database column t_contract_infor.closing_account_mode_id
	 * @return  the value of t_contract_infor.closing_account_mode_id
	 * @ibatorgenerated  Tue Dec 15 20:18:03 CST 2009
	 */
	public Integer getClosingAccountModeId() {
		return closingAccountModeId;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method sets the value of the database column t_contract_infor.closing_account_mode_id
	 * @param closingAccountModeId  the value for t_contract_infor.closing_account_mode_id
	 * @ibatorgenerated  Tue Dec 15 20:18:03 CST 2009
	 */
	public void setClosingAccountModeId(Integer closingAccountModeId) {
		this.closingAccountModeId = closingAccountModeId;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method returns the value of the database column t_contract_infor.closing_account_mode
	 * @return  the value of t_contract_infor.closing_account_mode
	 * @ibatorgenerated  Tue Dec 15 20:18:03 CST 2009
	 */
	public String getClosingAccountMode() {
		return closingAccountMode;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method sets the value of the database column t_contract_infor.closing_account_mode
	 * @param closingAccountMode  the value for t_contract_infor.closing_account_mode
	 * @ibatorgenerated  Tue Dec 15 20:18:03 CST 2009
	 */
	public void setClosingAccountMode(String closingAccountMode) {
		this.closingAccountMode = closingAccountMode;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method returns the value of the database column t_contract_infor.delivery_address_type
	 * @return  the value of t_contract_infor.delivery_address_type
	 * @ibatorgenerated  Tue Dec 15 20:18:03 CST 2009
	 */
	public String getDeliveryAddressType() {
		return deliveryAddressType;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method sets the value of the database column t_contract_infor.delivery_address_type
	 * @param deliveryAddressType  the value for t_contract_infor.delivery_address_type
	 * @ibatorgenerated  Tue Dec 15 20:18:03 CST 2009
	 */
	public void setDeliveryAddressType(String deliveryAddressType) {
		this.deliveryAddressType = deliveryAddressType;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method returns the value of the database column t_contract_infor.other_convention
	 * @return  the value of t_contract_infor.other_convention
	 * @ibatorgenerated  Tue Dec 15 20:18:03 CST 2009
	 */
	public String getOtherConvention() {
		return otherConvention;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method sets the value of the database column t_contract_infor.other_convention
	 * @param otherConvention  the value for t_contract_infor.other_convention
	 * @ibatorgenerated  Tue Dec 15 20:18:03 CST 2009
	 */
	public void setOtherConvention(String otherConvention) {
		this.otherConvention = otherConvention;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method returns the value of the database column t_contract_infor.effect_conditions
	 * @return  the value of t_contract_infor.effect_conditions
	 * @ibatorgenerated  Tue Dec 15 20:18:03 CST 2009
	 */
	public String getEffectConditions() {
		return effectConditions;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method sets the value of the database column t_contract_infor.effect_conditions
	 * @param effectConditions  the value for t_contract_infor.effect_conditions
	 * @ibatorgenerated  Tue Dec 15 20:18:03 CST 2009
	 */
	public void setEffectConditions(String effectConditions) {
		this.effectConditions = effectConditions;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method returns the value of the database column t_contract_infor.product_money
	 * @return  the value of t_contract_infor.product_money
	 * @ibatorgenerated  Tue Dec 15 20:18:03 CST 2009
	 */
	public BigDecimal getProductMoney() {
		return productMoney;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method sets the value of the database column t_contract_infor.product_money
	 * @param productMoney  the value for t_contract_infor.product_money
	 * @ibatorgenerated  Tue Dec 15 20:18:03 CST 2009
	 */
	public void setProductMoney(BigDecimal productMoney) {
		this.productMoney = productMoney;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method returns the value of the database column t_contract_infor.tax_rate
	 * @return  the value of t_contract_infor.tax_rate
	 * @ibatorgenerated  Tue Dec 15 20:18:03 CST 2009
	 */
	public BigDecimal getTaxRate() {
		return taxRate;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method sets the value of the database column t_contract_infor.tax_rate
	 * @param taxRate  the value for t_contract_infor.tax_rate
	 * @ibatorgenerated  Tue Dec 15 20:18:03 CST 2009
	 */
	public void setTaxRate(BigDecimal taxRate) {
		this.taxRate = taxRate;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method returns the value of the database column t_contract_infor.tax_money
	 * @return  the value of t_contract_infor.tax_money
	 * @ibatorgenerated  Tue Dec 15 20:18:03 CST 2009
	 */
	public BigDecimal getTaxMoney() {
		return taxMoney;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method sets the value of the database column t_contract_infor.tax_money
	 * @param taxMoney  the value for t_contract_infor.tax_money
	 * @ibatorgenerated  Tue Dec 15 20:18:03 CST 2009
	 */
	public void setTaxMoney(BigDecimal taxMoney) {
		this.taxMoney = taxMoney;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method returns the value of the database column t_contract_infor.total_money
	 * @return  the value of t_contract_infor.total_money
	 * @ibatorgenerated  Tue Dec 15 20:18:03 CST 2009
	 */
	public BigDecimal getTotalMoney() {
		return totalMoney;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method sets the value of the database column t_contract_infor.total_money
	 * @param totalMoney  the value for t_contract_infor.total_money
	 * @ibatorgenerated  Tue Dec 15 20:18:03 CST 2009
	 */
	public void setTotalMoney(BigDecimal totalMoney) {
		this.totalMoney = totalMoney;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method returns the value of the database column t_contract_infor.overall_rebate
	 * @return  the value of t_contract_infor.overall_rebate
	 * @ibatorgenerated  Tue Dec 15 20:18:03 CST 2009
	 */
	public BigDecimal getOverallRebate() {
		return overallRebate;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method sets the value of the database column t_contract_infor.overall_rebate
	 * @param overallRebate  the value for t_contract_infor.overall_rebate
	 * @ibatorgenerated  Tue Dec 15 20:18:03 CST 2009
	 */
	public void setOverallRebate(BigDecimal overallRebate) {
		this.overallRebate = overallRebate;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method returns the value of the database column t_contract_infor.final_money
	 * @return  the value of t_contract_infor.final_money
	 * @ibatorgenerated  Tue Dec 15 20:18:03 CST 2009
	 */
	public BigDecimal getFinalMoney() {
		return finalMoney;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method sets the value of the database column t_contract_infor.final_money
	 * @param finalMoney  the value for t_contract_infor.final_money
	 * @ibatorgenerated  Tue Dec 15 20:18:03 CST 2009
	 */
	public void setFinalMoney(BigDecimal finalMoney) {
		this.finalMoney = finalMoney;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method returns the value of the database column t_contract_infor.memo
	 * @return  the value of t_contract_infor.memo
	 * @ibatorgenerated  Tue Dec 15 20:18:03 CST 2009
	 */
	public String getMemo() {
		return memo;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method sets the value of the database column t_contract_infor.memo
	 * @param memo  the value for t_contract_infor.memo
	 * @ibatorgenerated  Tue Dec 15 20:18:03 CST 2009
	 */
	public void setMemo(String memo) {
		this.memo = memo;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method returns the value of the database column t_contract_infor.edit_date
	 * @return  the value of t_contract_infor.edit_date
	 * @ibatorgenerated  Tue Dec 15 20:18:03 CST 2009
	 */
	public Date getEditDate() {
		return editDate;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method sets the value of the database column t_contract_infor.edit_date
	 * @param editDate  the value for t_contract_infor.edit_date
	 * @ibatorgenerated  Tue Dec 15 20:18:03 CST 2009
	 */
	public void setEditDate(Date editDate) {
		if(editDate != null){
		    editDateString = df.format(editDate);
		}
		this.editDate = editDate;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method returns the value of the database column t_contract_infor.user_id
	 * @return  the value of t_contract_infor.user_id
	 * @ibatorgenerated  Tue Dec 15 20:18:03 CST 2009
	 */
	public String getUserId() {
		return userId;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method sets the value of the database column t_contract_infor.user_id
	 * @param userId  the value for t_contract_infor.user_id
	 * @ibatorgenerated  Tue Dec 15 20:18:03 CST 2009
	 */
	public void setUserId(String userId) {
		this.userId = userId;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method returns the value of the database column t_contract_infor.user_name
	 * @return  the value of t_contract_infor.user_name
	 * @ibatorgenerated  Tue Dec 15 20:18:03 CST 2009
	 */
	public String getUserName() {
		return userName;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method sets the value of the database column t_contract_infor.user_name
	 * @param userName  the value for t_contract_infor.user_name
	 * @ibatorgenerated  Tue Dec 15 20:18:03 CST 2009
	 */
	public void setUserName(String userName) {
		this.userName = userName;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method returns the value of the database column t_contract_infor.contract_type
	 * @return  the value of t_contract_infor.contract_type
	 * @ibatorgenerated  Tue Dec 15 20:18:03 CST 2009
	 */
	public Integer getContractType() {
		return contractType;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method sets the value of the database column t_contract_infor.contract_type
	 * @param contractType  the value for t_contract_infor.contract_type
	 * @ibatorgenerated  Tue Dec 15 20:18:03 CST 2009
	 */
	public void setContractType(Integer contractType) {
		this.contractType = contractType;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method returns the value of the database column t_contract_infor.customer_fax
	 * @return  the value of t_contract_infor.customer_fax
	 * @ibatorgenerated  Tue Dec 15 20:18:03 CST 2009
	 */
	public String getCustomerFax() {
		return customerFax;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method sets the value of the database column t_contract_infor.customer_fax
	 * @param customerFax  the value for t_contract_infor.customer_fax
	 * @ibatorgenerated  Tue Dec 15 20:18:03 CST 2009
	 */
	public void setCustomerFax(String customerFax) {
		this.customerFax = customerFax;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method returns the value of the database column t_contract_infor.customer_phone
	 * @return  the value of t_contract_infor.customer_phone
	 * @ibatorgenerated  Tue Dec 15 20:18:03 CST 2009
	 */
	public String getCustomerPhone() {
		return customerPhone;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method sets the value of the database column t_contract_infor.customer_phone
	 * @param customerPhone  the value for t_contract_infor.customer_phone
	 * @ibatorgenerated  Tue Dec 15 20:18:03 CST 2009
	 */
	public void setCustomerPhone(String customerPhone) {
		this.customerPhone = customerPhone;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method returns the value of the database column t_contract_infor.own_contact_person
	 * @return  the value of t_contract_infor.own_contact_person
	 * @ibatorgenerated  Tue Dec 15 20:18:03 CST 2009
	 */
	public String getOwnContactPerson() {
		return ownContactPerson;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method sets the value of the database column t_contract_infor.own_contact_person
	 * @param ownContactPerson  the value for t_contract_infor.own_contact_person
	 * @ibatorgenerated  Tue Dec 15 20:18:03 CST 2009
	 */
	public void setOwnContactPerson(String ownContactPerson) {
		this.ownContactPerson = ownContactPerson;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method returns the value of the database column t_contract_infor.cus_contact_person
	 * @return  the value of t_contract_infor.cus_contact_person
	 * @ibatorgenerated  Tue Dec 15 20:18:03 CST 2009
	 */
	public String getCusContactPerson() {
		return cusContactPerson;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method sets the value of the database column t_contract_infor.cus_contact_person
	 * @param cusContactPerson  the value for t_contract_infor.cus_contact_person
	 * @ibatorgenerated  Tue Dec 15 20:18:03 CST 2009
	 */
	public void setCusContactPerson(String cusContactPerson) {
		this.cusContactPerson = cusContactPerson;
	}

	public String getEditDateString() {
		return editDateString;
	}

	public void setEditDateString(String editDateString) {
		this.editDateString = editDateString;
	}

	public String getCurrencyId() {
		return currencyId;
	}

	public void setCurrencyId(String currencyId) {
		this.currencyId = currencyId;
	}

	public String getSellerId() {
		return sellerId;
	}

	public void setSellerId(String sellerId) {
		this.sellerId = sellerId;
	}

	public Integer getFileCount() {
		return fileCount;
	}
	public void setFileCount(Integer fileCount) {
		this.fileCount = fileCount;
	}
	
}