package com.tl.resource.dao.pojo;

import java.math.BigDecimal;
import java.util.Date;
import java.util.List;

import com.tl.resource.business.dto.InvoiceDetailDto;

public class TInvoiceInfo {

	/**
	 * This field was generated by Apache iBATIS ibator. This field corresponds to the database column t_invoice_info.id
	 * @ibatorgenerated  Mon Jan 25 18:09:10 CST 2010
	 */
	private String id;
	/**
	 * This field was generated by Apache iBATIS ibator. This field corresponds to the database column t_invoice_info.contract_id
	 * @ibatorgenerated  Mon Jan 25 18:09:10 CST 2010
	 */
	private String contractId;
	/**
	 * This field was generated by Apache iBATIS ibator. This field corresponds to the database column t_invoice_info.contract_code
	 * @ibatorgenerated  Mon Jan 25 18:09:10 CST 2010
	 */
	private String contractCode;
	/**
	 * This field was generated by Apache iBATIS ibator. This field corresponds to the database column t_invoice_info.invoice_code
	 * @ibatorgenerated  Mon Jan 25 18:09:10 CST 2010
	 */
	private String invoiceCode;
	/**
	 * This field was generated by Apache iBATIS ibator. This field corresponds to the database column t_invoice_info.invoice_money
	 * @ibatorgenerated  Mon Jan 25 18:09:10 CST 2010
	 */
	private BigDecimal invoiceMoney;
	/**
	 * This field was generated by Apache iBATIS ibator. This field corresponds to the database column t_invoice_info.invoice_date
	 * @ibatorgenerated  Mon Jan 25 18:09:10 CST 2010
	 */
	private Date invoiceDate;
	/**
	 * This field was generated by Apache iBATIS ibator. This field corresponds to the database column t_invoice_info.user_id
	 * @ibatorgenerated  Mon Jan 25 18:09:10 CST 2010
	 */
	private String userId;
	/**
	 * This field was generated by Apache iBATIS ibator. This field corresponds to the database column t_invoice_info.user_name
	 * @ibatorgenerated  Mon Jan 25 18:09:10 CST 2010
	 */
	private String userName;
	/**
	 * This field was generated by Apache iBATIS ibator. This field corresponds to the database column t_invoice_info.memo
	 * @ibatorgenerated  Mon Jan 25 18:09:10 CST 2010
	 */
	private String memo;
	/**
	 * This field was generated by Apache iBATIS ibator. This field corresponds to the database column t_invoice_info.invoice_type
	 * @ibatorgenerated  Mon Jan 25 18:09:10 CST 2010
	 */
	private Integer invoiceType;

	
	private List<InvoiceDetailDto> invoiceDetail;
	
    private List<TOrderInfor> orderInfoDtos ;
    
    
	public List<InvoiceDetailDto> getInvoiceDetail() {
		return invoiceDetail;
	}

	public void setInvoiceDetail(List<InvoiceDetailDto> invoiceDetail) {
		this.invoiceDetail = invoiceDetail;
	}

	public List<TOrderInfor> getOrderInfoDtos() {
		return orderInfoDtos;
	}

	public void setOrderInfoDtos(List<TOrderInfor> orderInfoDtos) {
		this.orderInfoDtos = orderInfoDtos;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method returns the value of the database column t_invoice_info.id
	 * @return  the value of t_invoice_info.id
	 * @ibatorgenerated  Mon Jan 25 18:09:10 CST 2010
	 */
	public String getId() {
		return id;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method sets the value of the database column t_invoice_info.id
	 * @param id  the value for t_invoice_info.id
	 * @ibatorgenerated  Mon Jan 25 18:09:10 CST 2010
	 */
	public void setId(String id) {
		this.id = id;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method returns the value of the database column t_invoice_info.contract_id
	 * @return  the value of t_invoice_info.contract_id
	 * @ibatorgenerated  Mon Jan 25 18:09:10 CST 2010
	 */
	public String getContractId() {
		return contractId;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method sets the value of the database column t_invoice_info.contract_id
	 * @param contractId  the value for t_invoice_info.contract_id
	 * @ibatorgenerated  Mon Jan 25 18:09:10 CST 2010
	 */
	public void setContractId(String contractId) {
		this.contractId = contractId;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method returns the value of the database column t_invoice_info.contract_code
	 * @return  the value of t_invoice_info.contract_code
	 * @ibatorgenerated  Mon Jan 25 18:09:10 CST 2010
	 */
	public String getContractCode() {
		return contractCode;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method sets the value of the database column t_invoice_info.contract_code
	 * @param contractCode  the value for t_invoice_info.contract_code
	 * @ibatorgenerated  Mon Jan 25 18:09:10 CST 2010
	 */
	public void setContractCode(String contractCode) {
		this.contractCode = contractCode;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method returns the value of the database column t_invoice_info.invoice_code
	 * @return  the value of t_invoice_info.invoice_code
	 * @ibatorgenerated  Mon Jan 25 18:09:10 CST 2010
	 */
	public String getInvoiceCode() {
		return invoiceCode;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method sets the value of the database column t_invoice_info.invoice_code
	 * @param invoiceCode  the value for t_invoice_info.invoice_code
	 * @ibatorgenerated  Mon Jan 25 18:09:10 CST 2010
	 */
	public void setInvoiceCode(String invoiceCode) {
		this.invoiceCode = invoiceCode;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method returns the value of the database column t_invoice_info.invoice_money
	 * @return  the value of t_invoice_info.invoice_money
	 * @ibatorgenerated  Mon Jan 25 18:09:10 CST 2010
	 */
	public BigDecimal getInvoiceMoney() {
		return invoiceMoney;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method sets the value of the database column t_invoice_info.invoice_money
	 * @param invoiceMoney  the value for t_invoice_info.invoice_money
	 * @ibatorgenerated  Mon Jan 25 18:09:10 CST 2010
	 */
	public void setInvoiceMoney(BigDecimal invoiceMoney) {
		this.invoiceMoney = invoiceMoney;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method returns the value of the database column t_invoice_info.invoice_date
	 * @return  the value of t_invoice_info.invoice_date
	 * @ibatorgenerated  Mon Jan 25 18:09:10 CST 2010
	 */
	public Date getInvoiceDate() {
		return invoiceDate;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method sets the value of the database column t_invoice_info.invoice_date
	 * @param invoiceDate  the value for t_invoice_info.invoice_date
	 * @ibatorgenerated  Mon Jan 25 18:09:10 CST 2010
	 */
	public void setInvoiceDate(Date invoiceDate) {
		this.invoiceDate = invoiceDate;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method returns the value of the database column t_invoice_info.user_id
	 * @return  the value of t_invoice_info.user_id
	 * @ibatorgenerated  Mon Jan 25 18:09:10 CST 2010
	 */
	public String getUserId() {
		return userId;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method sets the value of the database column t_invoice_info.user_id
	 * @param userId  the value for t_invoice_info.user_id
	 * @ibatorgenerated  Mon Jan 25 18:09:10 CST 2010
	 */
	public void setUserId(String userId) {
		this.userId = userId;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method returns the value of the database column t_invoice_info.user_name
	 * @return  the value of t_invoice_info.user_name
	 * @ibatorgenerated  Mon Jan 25 18:09:10 CST 2010
	 */
	public String getUserName() {
		return userName;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method sets the value of the database column t_invoice_info.user_name
	 * @param userName  the value for t_invoice_info.user_name
	 * @ibatorgenerated  Mon Jan 25 18:09:10 CST 2010
	 */
	public void setUserName(String userName) {
		this.userName = userName;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method returns the value of the database column t_invoice_info.memo
	 * @return  the value of t_invoice_info.memo
	 * @ibatorgenerated  Mon Jan 25 18:09:10 CST 2010
	 */
	public String getMemo() {
		return memo;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method sets the value of the database column t_invoice_info.memo
	 * @param memo  the value for t_invoice_info.memo
	 * @ibatorgenerated  Mon Jan 25 18:09:10 CST 2010
	 */
	public void setMemo(String memo) {
		this.memo = memo;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method returns the value of the database column t_invoice_info.invoice_type
	 * @return  the value of t_invoice_info.invoice_type
	 * @ibatorgenerated  Mon Jan 25 18:09:10 CST 2010
	 */
	public Integer getInvoiceType() {
		return invoiceType;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method sets the value of the database column t_invoice_info.invoice_type
	 * @param invoiceType  the value for t_invoice_info.invoice_type
	 * @ibatorgenerated  Mon Jan 25 18:09:10 CST 2010
	 */
	public void setInvoiceType(Integer invoiceType) {
		this.invoiceType = invoiceType;
	}
}