package com.tl.resource.dao.pojo;

public class TResourcePurview {
    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column t_resource_purview.id
     *
     * @ibatorgenerated Fri Dec 25 14:16:06 CST 2009
     */
    private String id;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column t_resource_purview.user_id
     *
     * @ibatorgenerated Fri Dec 25 14:16:06 CST 2009
     */
    private String userId;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column t_resource_purview.resource_type
     *
     * @ibatorgenerated Fri Dec 25 14:16:06 CST 2009
     */
    private Integer resourceType;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column t_resource_purview.target_user_id
     *
     * @ibatorgenerated Fri Dec 25 14:16:06 CST 2009
     */
    private String targetUserId;

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column t_resource_purview.id
     *
     * @return the value of t_resource_purview.id
     *
     * @ibatorgenerated Fri Dec 25 14:16:06 CST 2009
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column t_resource_purview.id
     *
     * @param id the value for t_resource_purview.id
     *
     * @ibatorgenerated Fri Dec 25 14:16:06 CST 2009
     */
    public void setId(String id) {
        this.id = id;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column t_resource_purview.user_id
     *
     * @return the value of t_resource_purview.user_id
     *
     * @ibatorgenerated Fri Dec 25 14:16:06 CST 2009
     */
    public String getUserId() {
        return userId;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column t_resource_purview.user_id
     *
     * @param userId the value for t_resource_purview.user_id
     *
     * @ibatorgenerated Fri Dec 25 14:16:06 CST 2009
     */
    public void setUserId(String userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column t_resource_purview.resource_type
     *
     * @return the value of t_resource_purview.resource_type
     *
     * @ibatorgenerated Fri Dec 25 14:16:06 CST 2009
     */
    public Integer getResourceType() {
        return resourceType;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column t_resource_purview.resource_type
     *
     * @param resourceType the value for t_resource_purview.resource_type
     *
     * @ibatorgenerated Fri Dec 25 14:16:06 CST 2009
     */
    public void setResourceType(Integer resourceType) {
        this.resourceType = resourceType;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column t_resource_purview.target_user_id
     *
     * @return the value of t_resource_purview.target_user_id
     *
     * @ibatorgenerated Fri Dec 25 14:16:06 CST 2009
     */
    public String getTargetUserId() {
        return targetUserId;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column t_resource_purview.target_user_id
     *
     * @param targetUserId the value for t_resource_purview.target_user_id
     *
     * @ibatorgenerated Fri Dec 25 14:16:06 CST 2009
     */
    public void setTargetUserId(String targetUserId) {
        this.targetUserId = targetUserId;
    }
}