package com.tl.resource.dao.pojo;

import java.text.DateFormat;
import java.text.SimpleDateFormat;
import java.util.Date;

public class TWorkTrustRecord {
	private static final DateFormat df = new SimpleDateFormat("yyyy-MM-dd HH:mm");
	/**
	 * This field was generated by Apache iBATIS ibator. This field corresponds to the database column t_work_trust_record.id
	 * @ibatorgenerated  Wed Mar 10 19:02:58 CST 2010
	 */
	private String id;
	/**
	 * This field was generated by Apache iBATIS ibator. This field corresponds to the database column t_work_trust_record.op_person_id
	 * @ibatorgenerated  Wed Mar 10 19:02:58 CST 2010
	 */
	private String opPersonId;
	/**
	 * This field was generated by Apache iBATIS ibator. This field corresponds to the database column t_work_trust_record.op_person
	 * @ibatorgenerated  Wed Mar 10 19:02:58 CST 2010
	 */
	private String opPerson;
	/**
	 * This field was generated by Apache iBATIS ibator. This field corresponds to the database column t_work_trust_record.op_time
	 * @ibatorgenerated  Wed Mar 10 19:02:58 CST 2010
	 */
	private Date opTime;
	/**
	 * This field was generated by Apache iBATIS ibator. This field corresponds to the database column t_work_trust_record.op_type
	 * @ibatorgenerated  Wed Mar 10 19:02:58 CST 2010
	 */
	private Integer opType;
	/**
	 * This field was generated by Apache iBATIS ibator. This field corresponds to the database column t_work_trust_record.authorize_person_id
	 * @ibatorgenerated  Wed Mar 10 19:02:58 CST 2010
	 */
	private String authorizePersonId;
	/**
	 * This field was generated by Apache iBATIS ibator. This field corresponds to the database column t_work_trust_record.authorize_person
	 * @ibatorgenerated  Wed Mar 10 19:02:58 CST 2010
	 */
	private String authorizePerson;
	/**
	 * This field was generated by Apache iBATIS ibator. This field corresponds to the database column t_work_trust_record.get_right_person_id
	 * @ibatorgenerated  Wed Mar 10 19:02:58 CST 2010
	 */
	private String getRightPersonId;
	/**
	 * This field was generated by Apache iBATIS ibator. This field corresponds to the database column t_work_trust_record.get_right_person
	 * @ibatorgenerated  Wed Mar 10 19:02:58 CST 2010
	 */
	private String getRightPerson;

	/**
	 * This method was generated by Apache iBATIS ibator. This method returns the value of the database column t_work_trust_record.id
	 * @return  the value of t_work_trust_record.id
	 * @ibatorgenerated  Wed Mar 10 19:02:58 CST 2010
	 */
	private String editDateString;
	public String getId() {
		return id;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method sets the value of the database column t_work_trust_record.id
	 * @param id  the value for t_work_trust_record.id
	 * @ibatorgenerated  Wed Mar 10 19:02:58 CST 2010
	 */
	public void setId(String id) {
		this.id = id;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method returns the value of the database column t_work_trust_record.op_person_id
	 * @return  the value of t_work_trust_record.op_person_id
	 * @ibatorgenerated  Wed Mar 10 19:02:58 CST 2010
	 */
	public String getOpPersonId() {
		return opPersonId;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method sets the value of the database column t_work_trust_record.op_person_id
	 * @param opPersonId  the value for t_work_trust_record.op_person_id
	 * @ibatorgenerated  Wed Mar 10 19:02:58 CST 2010
	 */
	public void setOpPersonId(String opPersonId) {
		this.opPersonId = opPersonId;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method returns the value of the database column t_work_trust_record.op_person
	 * @return  the value of t_work_trust_record.op_person
	 * @ibatorgenerated  Wed Mar 10 19:02:58 CST 2010
	 */
	public String getOpPerson() {
		return opPerson;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method sets the value of the database column t_work_trust_record.op_person
	 * @param opPerson  the value for t_work_trust_record.op_person
	 * @ibatorgenerated  Wed Mar 10 19:02:58 CST 2010
	 */
	public void setOpPerson(String opPerson) {
		this.opPerson = opPerson;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method returns the value of the database column t_work_trust_record.op_time
	 * @return  the value of t_work_trust_record.op_time
	 * @ibatorgenerated  Wed Mar 10 19:02:58 CST 2010
	 */
	public Date getOpTime() {
		return opTime;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method sets the value of the database column t_work_trust_record.op_time
	 * @param opTime  the value for t_work_trust_record.op_time
	 * @ibatorgenerated  Wed Mar 10 19:02:58 CST 2010
	 */
	public void setOpTime(Date opTime) {
		this.opTime = opTime;
		if(opTime != null){
		    editDateString = df.format(opTime);
		}
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method returns the value of the database column t_work_trust_record.op_type
	 * @return  the value of t_work_trust_record.op_type
	 * @ibatorgenerated  Wed Mar 10 19:02:58 CST 2010
	 */
	public Integer getOpType() {
		return opType;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method sets the value of the database column t_work_trust_record.op_type
	 * @param opType  the value for t_work_trust_record.op_type
	 * @ibatorgenerated  Wed Mar 10 19:02:58 CST 2010
	 */
	public void setOpType(Integer opType) {
		this.opType = opType;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method returns the value of the database column t_work_trust_record.authorize_person_id
	 * @return  the value of t_work_trust_record.authorize_person_id
	 * @ibatorgenerated  Wed Mar 10 19:02:58 CST 2010
	 */
	public String getAuthorizePersonId() {
		return authorizePersonId;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method sets the value of the database column t_work_trust_record.authorize_person_id
	 * @param authorizePersonId  the value for t_work_trust_record.authorize_person_id
	 * @ibatorgenerated  Wed Mar 10 19:02:58 CST 2010
	 */
	public void setAuthorizePersonId(String authorizePersonId) {
		this.authorizePersonId = authorizePersonId;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method returns the value of the database column t_work_trust_record.authorize_person
	 * @return  the value of t_work_trust_record.authorize_person
	 * @ibatorgenerated  Wed Mar 10 19:02:58 CST 2010
	 */
	public String getAuthorizePerson() {
		return authorizePerson;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method sets the value of the database column t_work_trust_record.authorize_person
	 * @param authorizePerson  the value for t_work_trust_record.authorize_person
	 * @ibatorgenerated  Wed Mar 10 19:02:58 CST 2010
	 */
	public void setAuthorizePerson(String authorizePerson) {
		this.authorizePerson = authorizePerson;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method returns the value of the database column t_work_trust_record.get_right_person_id
	 * @return  the value of t_work_trust_record.get_right_person_id
	 * @ibatorgenerated  Wed Mar 10 19:02:58 CST 2010
	 */
	public String getGetRightPersonId() {
		return getRightPersonId;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method sets the value of the database column t_work_trust_record.get_right_person_id
	 * @param getRightPersonId  the value for t_work_trust_record.get_right_person_id
	 * @ibatorgenerated  Wed Mar 10 19:02:58 CST 2010
	 */
	public void setGetRightPersonId(String getRightPersonId) {
		this.getRightPersonId = getRightPersonId;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method returns the value of the database column t_work_trust_record.get_right_person
	 * @return  the value of t_work_trust_record.get_right_person
	 * @ibatorgenerated  Wed Mar 10 19:02:58 CST 2010
	 */
	public String getGetRightPerson() {
		return getRightPerson;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method sets the value of the database column t_work_trust_record.get_right_person
	 * @param getRightPerson  the value for t_work_trust_record.get_right_person
	 * @ibatorgenerated  Wed Mar 10 19:02:58 CST 2010
	 */
	public void setGetRightPerson(String getRightPerson) {
		this.getRightPerson = getRightPerson;
	}

	public String getEditDateString() {
		return editDateString;
	}

	public void setEditDateString(String editDateString) {
		this.editDateString = editDateString;
	}
	
}