package com.tl.resource.dao.pojo;

public class TBillsCodeDef {
    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column t_bills_code_def.id
     *
     * @ibatorgenerated Sun Nov 22 16:19:50 CST 2009
     */
    private String id;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column t_bills_code_def.bill_type
     *
     * @ibatorgenerated Sun Nov 22 16:19:50 CST 2009
     */
    private String billType;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column t_bills_code_def.bill_type_name
     *
     * @ibatorgenerated Sun Nov 22 16:19:50 CST 2009
     */
    private String billTypeName;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column t_bills_code_def.bill_def_normal
     *
     * @ibatorgenerated Sun Nov 22 16:19:50 CST 2009
     */
    private String billDefNormal;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column t_bills_code_def.serial_number
     *
     * @ibatorgenerated Sun Nov 22 16:19:50 CST 2009
     */
    private Integer serialNumber;
    
    private String businessMoudleName;

  

	public String getBusinessMoudleName() {
		return businessMoudleName;
	}

	public void setBusinessMoudleName(String businessMoudleName) {
		this.businessMoudleName = businessMoudleName;
	}

	/**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column t_bills_code_def.id
     *
     * @return the value of t_bills_code_def.id
     *
     * @ibatorgenerated Sun Nov 22 16:19:50 CST 2009
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column t_bills_code_def.id
     *
     * @param id the value for t_bills_code_def.id
     *
     * @ibatorgenerated Sun Nov 22 16:19:50 CST 2009
     */
    public void setId(String id) {
        this.id = id;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column t_bills_code_def.bill_type
     *
     * @return the value of t_bills_code_def.bill_type
     *
     * @ibatorgenerated Sun Nov 22 16:19:50 CST 2009
     */
    public String getBillType() {
        return billType;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column t_bills_code_def.bill_type
     *
     * @param billType the value for t_bills_code_def.bill_type
     *
     * @ibatorgenerated Sun Nov 22 16:19:50 CST 2009
     */
    public void setBillType(String billType) {
        this.billType = billType;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column t_bills_code_def.bill_type_name
     *
     * @return the value of t_bills_code_def.bill_type_name
     *
     * @ibatorgenerated Sun Nov 22 16:19:50 CST 2009
     */
    public String getBillTypeName() {
        return billTypeName;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column t_bills_code_def.bill_type_name
     *
     * @param billTypeName the value for t_bills_code_def.bill_type_name
     *
     * @ibatorgenerated Sun Nov 22 16:19:50 CST 2009
     */
    public void setBillTypeName(String billTypeName) {
        this.billTypeName = billTypeName;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column t_bills_code_def.bill_def_normal
     *
     * @return the value of t_bills_code_def.bill_def_normal
     *
     * @ibatorgenerated Sun Nov 22 16:19:50 CST 2009
     */
    public String getBillDefNormal() {
        return billDefNormal;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column t_bills_code_def.bill_def_normal
     *
     * @param billDefNormal the value for t_bills_code_def.bill_def_normal
     *
     * @ibatorgenerated Sun Nov 22 16:19:50 CST 2009
     */
    public void setBillDefNormal(String billDefNormal) {
        this.billDefNormal = billDefNormal;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column t_bills_code_def.serial_number
     *
     * @return the value of t_bills_code_def.serial_number
     *
     * @ibatorgenerated Sun Nov 22 16:19:50 CST 2009
     */
    public Integer getSerialNumber() {
        return serialNumber;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column t_bills_code_def.serial_number
     *
     * @param serialNumber the value for t_bills_code_def.serial_number
     *
     * @ibatorgenerated Sun Nov 22 16:19:50 CST 2009
     */
    public void setSerialNumber(Integer serialNumber) {
        this.serialNumber = serialNumber;
    }
}