package com.tl.resource.dao.pojo;

import java.math.BigDecimal;
import java.text.DateFormat;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.List;

public class TProductArrivalInfor {
	private static final DateFormat df = new SimpleDateFormat("yyyy-MM-dd HH:mm");
	private String editDateString;
	private List<TProductArrivalDetail> arrivalProducts;
	/**
	 * This field was generated by Apache iBATIS ibator. This field corresponds to the database column t_product_arrival_infor.id
	 * @ibatorgenerated  Wed Nov 11 09:54:59 CST 2009
	 */
	private String id;
	/**
	 * This field was generated by Apache iBATIS ibator. This field corresponds to the database column t_product_arrival_infor.arrival_code
	 * @ibatorgenerated  Wed Nov 11 09:54:59 CST 2009
	 */
	private String arrivalCode;
	/**
	 * This field was generated by Apache iBATIS ibator. This field corresponds to the database column t_product_arrival_infor.order_code
	 * @ibatorgenerated  Wed Nov 11 09:54:59 CST 2009
	 */
	private String orderCode;
	/**
	 * This field was generated by Apache iBATIS ibator. This field corresponds to the database column t_product_arrival_infor.status
	 * @ibatorgenerated  Wed Nov 11 09:54:59 CST 2009
	 */
	private Integer status;
	/**
	 * This field was generated by Apache iBATIS ibator. This field corresponds to the database column t_product_arrival_infor.contract_code
	 * @ibatorgenerated  Wed Nov 11 09:54:59 CST 2009
	 */
	private String contractCode;
	/**
	 * This field was generated by Apache iBATIS ibator. This field corresponds to the database column t_product_arrival_infor.edit_date
	 * @ibatorgenerated  Wed Nov 11 09:54:59 CST 2009
	 */
	private Date editDate;
	/**
	 * This field was generated by Apache iBATIS ibator. This field corresponds to the database column t_product_arrival_infor.user_id
	 * @ibatorgenerated  Wed Nov 11 09:54:59 CST 2009
	 */
	private String userId;
	/**
	 * This field was generated by Apache iBATIS ibator. This field corresponds to the database column t_product_arrival_infor.user_name
	 * @ibatorgenerated  Wed Nov 11 09:54:59 CST 2009
	 */
	private String userName;
	/**
	 * This field was generated by Apache iBATIS ibator. This field corresponds to the database column t_product_arrival_infor.supplier_name
	 * @ibatorgenerated  Wed Nov 11 09:54:59 CST 2009
	 */
	private String supplierName;
	/**
	 * This field was generated by Apache iBATIS ibator. This field corresponds to the database column t_product_arrival_infor.supplier_id
	 * @ibatorgenerated  Wed Nov 11 09:54:59 CST 2009
	 */
	private String supplierId;
	/**
	 * This field was generated by Apache iBATIS ibator. This field corresponds to the database column t_product_arrival_infor.delivery_date
	 * @ibatorgenerated  Wed Nov 11 09:54:59 CST 2009
	 */
	private String deliveryDate;
	/**
	 * This field was generated by Apache iBATIS ibator. This field corresponds to the database column t_product_arrival_infor.memo
	 * @ibatorgenerated  Wed Nov 11 09:54:59 CST 2009
	 */
	private String memo;
	/**
	 * This field was generated by Apache iBATIS ibator. This field corresponds to the database column t_product_arrival_infor.order_infor_id
	 * @ibatorgenerated  Wed Nov 11 09:54:59 CST 2009
	 */
	private String orderInforId;
	
	private String customerName;
	private String customerCode;
	
	private String quotationId;
	private String quotationCode;
	
	private Integer arrivalType;

	/**
	 * This method was generated by Apache iBATIS ibator. This method returns the value of the database column t_product_arrival_infor.id
	 * @return  the value of t_product_arrival_infor.id
	 * @ibatorgenerated  Wed Nov 11 09:54:59 CST 2009
	 */
	public String getId() {
		return id;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method sets the value of the database column t_product_arrival_infor.id
	 * @param id  the value for t_product_arrival_infor.id
	 * @ibatorgenerated  Wed Nov 11 09:54:59 CST 2009
	 */
	public void setId(String id) {
		this.id = id;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method returns the value of the database column t_product_arrival_infor.arrival_code
	 * @return  the value of t_product_arrival_infor.arrival_code
	 * @ibatorgenerated  Wed Nov 11 09:54:59 CST 2009
	 */
	public String getArrivalCode() {
		return arrivalCode;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method sets the value of the database column t_product_arrival_infor.arrival_code
	 * @param arrivalCode  the value for t_product_arrival_infor.arrival_code
	 * @ibatorgenerated  Wed Nov 11 09:54:59 CST 2009
	 */
	public void setArrivalCode(String arrivalCode) {
		this.arrivalCode = arrivalCode;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method returns the value of the database column t_product_arrival_infor.order_code
	 * @return  the value of t_product_arrival_infor.order_code
	 * @ibatorgenerated  Wed Nov 11 09:54:59 CST 2009
	 */
	public String getOrderCode() {
		return orderCode;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method sets the value of the database column t_product_arrival_infor.order_code
	 * @param orderCode  the value for t_product_arrival_infor.order_code
	 * @ibatorgenerated  Wed Nov 11 09:54:59 CST 2009
	 */
	public void setOrderCode(String orderCode) {
		this.orderCode = orderCode;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method returns the value of the database column t_product_arrival_infor.status
	 * @return  the value of t_product_arrival_infor.status
	 * @ibatorgenerated  Wed Nov 11 09:54:59 CST 2009
	 */
	public Integer getStatus() {
		return status;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method sets the value of the database column t_product_arrival_infor.status
	 * @param status  the value for t_product_arrival_infor.status
	 * @ibatorgenerated  Wed Nov 11 09:54:59 CST 2009
	 */
	public void setStatus(Integer status) {
		this.status = status;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method returns the value of the database column t_product_arrival_infor.contract_code
	 * @return  the value of t_product_arrival_infor.contract_code
	 * @ibatorgenerated  Wed Nov 11 09:54:59 CST 2009
	 */
	public String getContractCode() {
		return contractCode;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method sets the value of the database column t_product_arrival_infor.contract_code
	 * @param contractCode  the value for t_product_arrival_infor.contract_code
	 * @ibatorgenerated  Wed Nov 11 09:54:59 CST 2009
	 */
	public void setContractCode(String contractCode) {
		this.contractCode = contractCode;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method returns the value of the database column t_product_arrival_infor.edit_date
	 * @return  the value of t_product_arrival_infor.edit_date
	 * @ibatorgenerated  Wed Nov 11 09:54:59 CST 2009
	 */
	public Date getEditDate() {
		return editDate;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method sets the value of the database column t_product_arrival_infor.edit_date
	 * @param editDate  the value for t_product_arrival_infor.edit_date
	 * @ibatorgenerated  Wed Nov 11 09:54:59 CST 2009
	 */
	public void setEditDate(Date editDate) {
		this.editDate = editDate;
		
		if(editDate != null) {
			this.editDateString = df.format(editDate);
		}
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method returns the value of the database column t_product_arrival_infor.user_id
	 * @return  the value of t_product_arrival_infor.user_id
	 * @ibatorgenerated  Wed Nov 11 09:54:59 CST 2009
	 */
	public String getUserId() {
		return userId;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method sets the value of the database column t_product_arrival_infor.user_id
	 * @param userId  the value for t_product_arrival_infor.user_id
	 * @ibatorgenerated  Wed Nov 11 09:54:59 CST 2009
	 */
	public void setUserId(String userId) {
		this.userId = userId;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method returns the value of the database column t_product_arrival_infor.user_name
	 * @return  the value of t_product_arrival_infor.user_name
	 * @ibatorgenerated  Wed Nov 11 09:54:59 CST 2009
	 */
	public String getUserName() {
		return userName;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method sets the value of the database column t_product_arrival_infor.user_name
	 * @param userName  the value for t_product_arrival_infor.user_name
	 * @ibatorgenerated  Wed Nov 11 09:54:59 CST 2009
	 */
	public void setUserName(String userName) {
		this.userName = userName;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method returns the value of the database column t_product_arrival_infor.supplier_name
	 * @return  the value of t_product_arrival_infor.supplier_name
	 * @ibatorgenerated  Wed Nov 11 09:54:59 CST 2009
	 */
	public String getSupplierName() {
		return supplierName;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method sets the value of the database column t_product_arrival_infor.supplier_name
	 * @param supplierName  the value for t_product_arrival_infor.supplier_name
	 * @ibatorgenerated  Wed Nov 11 09:54:59 CST 2009
	 */
	public void setSupplierName(String supplierName) {
		this.supplierName = supplierName;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method returns the value of the database column t_product_arrival_infor.supplier_id
	 * @return  the value of t_product_arrival_infor.supplier_id
	 * @ibatorgenerated  Wed Nov 11 09:54:59 CST 2009
	 */
	public String getSupplierId() {
		return supplierId;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method sets the value of the database column t_product_arrival_infor.supplier_id
	 * @param supplierId  the value for t_product_arrival_infor.supplier_id
	 * @ibatorgenerated  Wed Nov 11 09:54:59 CST 2009
	 */
	public void setSupplierId(String supplierId) {
		this.supplierId = supplierId;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method returns the value of the database column t_product_arrival_infor.delivery_date
	 * @return  the value of t_product_arrival_infor.delivery_date
	 * @ibatorgenerated  Wed Nov 11 09:54:59 CST 2009
	 */
	public String getDeliveryDate() {
		return deliveryDate;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method sets the value of the database column t_product_arrival_infor.delivery_date
	 * @param deliveryDate  the value for t_product_arrival_infor.delivery_date
	 * @ibatorgenerated  Wed Nov 11 09:54:59 CST 2009
	 */
	public void setDeliveryDate(String deliveryDate) {
		this.deliveryDate = deliveryDate;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method returns the value of the database column t_product_arrival_infor.memo
	 * @return  the value of t_product_arrival_infor.memo
	 * @ibatorgenerated  Wed Nov 11 09:54:59 CST 2009
	 */
	public String getMemo() {
		return memo;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method sets the value of the database column t_product_arrival_infor.memo
	 * @param memo  the value for t_product_arrival_infor.memo
	 * @ibatorgenerated  Wed Nov 11 09:54:59 CST 2009
	 */
	public void setMemo(String memo) {
		this.memo = memo;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method returns the value of the database column t_product_arrival_infor.order_infor_id
	 * @return  the value of t_product_arrival_infor.order_infor_id
	 * @ibatorgenerated  Wed Nov 11 09:54:59 CST 2009
	 */
	public String getOrderInforId() {
		return orderInforId;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method sets the value of the database column t_product_arrival_infor.order_infor_id
	 * @param orderInforId  the value for t_product_arrival_infor.order_infor_id
	 * @ibatorgenerated  Wed Nov 11 09:54:59 CST 2009
	 */
	public void setOrderInforId(String orderInforId) {
		this.orderInforId = orderInforId;
	}

	public String getEditDateString() {
		return editDateString;
	}

	public void setEditDateString(String editDateString) {
		this.editDateString = editDateString;
	}

	public List<TProductArrivalDetail> getArrivalProducts() {
		return arrivalProducts;
	}

	public void setArrivalProducts(List<TProductArrivalDetail> arrivalProducts) {
		this.arrivalProducts = arrivalProducts;
	}

	public String getCustomerName() {
		return customerName;
	}

	public void setCustomerName(String customerName) {
		this.customerName = customerName;
	}

	public String getCustomerCode() {
		return customerCode;
	}

	public void setCustomerCode(String customerCode) {
		this.customerCode = customerCode;
	}

	public String getQuotationId() {
		return quotationId;
	}

	public void setQuotationId(String quotationId) {
		this.quotationId = quotationId;
	}

	public String getQuotationCode() {
		return quotationCode;
	}

	public void setQuotationCode(String quotationCode) {
		this.quotationCode = quotationCode;
	}

	public Integer getArrivalType() {
		return arrivalType;
	}

	public void setArrivalType(Integer arrivalType) {
		this.arrivalType = arrivalType;
	}
}