package com.tl.resource.dao.pojo;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import java.math.BigDecimal;

public class TTaxRateExample {

	/**
	 * This field was generated by Apache iBATIS ibator. This field corresponds to the database table t_tax_rate
	 * @ibatorgenerated  Thu Jul 22 15:47:57 CST 2010
	 */
	protected String orderByClause;
	/**
	 * This field was generated by Apache iBATIS ibator. This field corresponds to the database table t_tax_rate
	 * @ibatorgenerated  Thu Jul 22 15:47:57 CST 2010
	 */
	protected List oredCriteria;

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table t_tax_rate
	 * @ibatorgenerated  Thu Jul 22 15:47:57 CST 2010
	 */
	public TTaxRateExample() {
		oredCriteria = new ArrayList();
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table t_tax_rate
	 * @ibatorgenerated  Thu Jul 22 15:47:57 CST 2010
	 */
	protected TTaxRateExample(TTaxRateExample example) {
		this.orderByClause = example.orderByClause;
		this.oredCriteria = example.oredCriteria;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table t_tax_rate
	 * @ibatorgenerated  Thu Jul 22 15:47:57 CST 2010
	 */
	public void setOrderByClause(String orderByClause) {
		this.orderByClause = orderByClause;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table t_tax_rate
	 * @ibatorgenerated  Thu Jul 22 15:47:57 CST 2010
	 */
	public String getOrderByClause() {
		return orderByClause;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table t_tax_rate
	 * @ibatorgenerated  Thu Jul 22 15:47:57 CST 2010
	 */
	public List getOredCriteria() {
		return oredCriteria;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table t_tax_rate
	 * @ibatorgenerated  Thu Jul 22 15:47:57 CST 2010
	 */
	public void or(Criteria criteria) {
		oredCriteria.add(criteria);
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table t_tax_rate
	 * @ibatorgenerated  Thu Jul 22 15:47:57 CST 2010
	 */
	public Criteria createCriteria() {
		Criteria criteria = createCriteriaInternal();
		if (oredCriteria.size() == 0) {
			oredCriteria.add(criteria);
		}
		return criteria;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table t_tax_rate
	 * @ibatorgenerated  Thu Jul 22 15:47:57 CST 2010
	 */
	protected Criteria createCriteriaInternal() {
		Criteria criteria = new Criteria();
		return criteria;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table t_tax_rate
	 * @ibatorgenerated  Thu Jul 22 15:47:57 CST 2010
	 */
	public void clear() {
		oredCriteria.clear();
	}

	/**
	 * This class was generated by Apache iBATIS ibator. This class corresponds to the database table t_tax_rate
	 * @ibatorgenerated  Thu Jul 22 15:47:57 CST 2010
	 */
	public static class Criteria {
		protected List criteriaWithoutValue;
		protected List criteriaWithSingleValue;
		protected List criteriaWithListValue;
		protected List criteriaWithBetweenValue;

		protected Criteria() {
			super();
			criteriaWithoutValue = new ArrayList();
			criteriaWithSingleValue = new ArrayList();
			criteriaWithListValue = new ArrayList();
			criteriaWithBetweenValue = new ArrayList();
		}

		public boolean isValid() {
			return criteriaWithoutValue.size() > 0
					|| criteriaWithSingleValue.size() > 0
					|| criteriaWithListValue.size() > 0
					|| criteriaWithBetweenValue.size() > 0;
		}

		public List getCriteriaWithoutValue() {
			return criteriaWithoutValue;
		}

		public List getCriteriaWithSingleValue() {
			return criteriaWithSingleValue;
		}

		public List getCriteriaWithListValue() {
			return criteriaWithListValue;
		}

		public List getCriteriaWithBetweenValue() {
			return criteriaWithBetweenValue;
		}

		protected void addCriterion(String condition) {
			if (condition == null) {
				throw new RuntimeException("Value for condition cannot be null");
			}
			criteriaWithoutValue.add(condition);
		}

		protected void addCriterion(String condition, Object value,
				String property) {
			if (value == null) {
				throw new RuntimeException("Value for " + property
						+ " cannot be null");
			}
			Map map = new HashMap();
			map.put("condition", condition);
			map.put("value", value);
			criteriaWithSingleValue.add(map);
		}

		protected void addCriterion(String condition, List values,
				String property) {
			if (values == null || values.size() == 0) {
				throw new RuntimeException("Value list for " + property
						+ " cannot be null or empty");
			}
			Map map = new HashMap();
			map.put("condition", condition);
			map.put("values", values);
			criteriaWithListValue.add(map);
		}

		protected void addCriterion(String condition, Object value1,
				Object value2, String property) {
			if (value1 == null || value2 == null) {
				throw new RuntimeException("Between values for " + property
						+ " cannot be null");
			}
			List list = new ArrayList();
			list.add(value1);
			list.add(value2);
			Map map = new HashMap();
			map.put("condition", condition);
			map.put("values", list);
			criteriaWithBetweenValue.add(map);
		}

		public Criteria andIdIsNull() {
			addCriterion("id is null");
			return this;
		}

		public Criteria andIdIsNotNull() {
			addCriterion("id is not null");
			return this;
		}

		public Criteria andIdEqualTo(String value) {
			addCriterion("id =", value, "id");
			return this;
		}

		public Criteria andIdNotEqualTo(String value) {
			addCriterion("id <>", value, "id");
			return this;
		}

		public Criteria andIdGreaterThan(String value) {
			addCriterion("id >", value, "id");
			return this;
		}

		public Criteria andIdGreaterThanOrEqualTo(String value) {
			addCriterion("id >=", value, "id");
			return this;
		}

		public Criteria andIdLessThan(String value) {
			addCriterion("id <", value, "id");
			return this;
		}

		public Criteria andIdLessThanOrEqualTo(String value) {
			addCriterion("id <=", value, "id");
			return this;
		}

		public Criteria andIdLike(String value) {
			addCriterion("id like", value, "id");
			return this;
		}

		public Criteria andIdNotLike(String value) {
			addCriterion("id not like", value, "id");
			return this;
		}

		public Criteria andIdIn(List values) {
			addCriterion("id in", values, "id");
			return this;
		}

		public Criteria andIdNotIn(List values) {
			addCriterion("id not in", values, "id");
			return this;
		}

		public Criteria andIdBetween(String value1, String value2) {
			addCriterion("id between", value1, value2, "id");
			return this;
		}

		public Criteria andIdNotBetween(String value1, String value2) {
			addCriterion("id not between", value1, value2, "id");
			return this;
		}

		public Criteria andRateIsNull() {
			addCriterion("rate is null");
			return this;
		}

		public Criteria andRateIsNotNull() {
			addCriterion("rate is not null");
			return this;
		}

		public Criteria andRateEqualTo(BigDecimal value) {
			addCriterion("rate =", value, "rate");
			return this;
		}

		public Criteria andRateNotEqualTo(BigDecimal value) {
			addCriterion("rate <>", value, "rate");
			return this;
		}

		public Criteria andRateGreaterThan(BigDecimal value) {
			addCriterion("rate >", value, "rate");
			return this;
		}

		public Criteria andRateGreaterThanOrEqualTo(BigDecimal value) {
			addCriterion("rate >=", value, "rate");
			return this;
		}

		public Criteria andRateLessThan(BigDecimal value) {
			addCriterion("rate <", value, "rate");
			return this;
		}

		public Criteria andRateLessThanOrEqualTo(BigDecimal value) {
			addCriterion("rate <=", value, "rate");
			return this;
		}

		public Criteria andRateIn(List values) {
			addCriterion("rate in", values, "rate");
			return this;
		}

		public Criteria andRateNotIn(List values) {
			addCriterion("rate not in", values, "rate");
			return this;
		}

		public Criteria andRateBetween(BigDecimal value1, BigDecimal value2) {
			addCriterion("rate between", value1, value2, "rate");
			return this;
		}

		public Criteria andRateNotBetween(BigDecimal value1, BigDecimal value2) {
			addCriterion("rate not between", value1, value2, "rate");
			return this;
		}

		public Criteria andMemoIsNull() {
			addCriterion("memo is null");
			return this;
		}

		public Criteria andMemoIsNotNull() {
			addCriterion("memo is not null");
			return this;
		}

		public Criteria andMemoEqualTo(String value) {
			addCriterion("memo =", value, "memo");
			return this;
		}

		public Criteria andMemoNotEqualTo(String value) {
			addCriterion("memo <>", value, "memo");
			return this;
		}

		public Criteria andMemoGreaterThan(String value) {
			addCriterion("memo >", value, "memo");
			return this;
		}

		public Criteria andMemoGreaterThanOrEqualTo(String value) {
			addCriterion("memo >=", value, "memo");
			return this;
		}

		public Criteria andMemoLessThan(String value) {
			addCriterion("memo <", value, "memo");
			return this;
		}

		public Criteria andMemoLessThanOrEqualTo(String value) {
			addCriterion("memo <=", value, "memo");
			return this;
		}

		public Criteria andMemoLike(String value) {
			addCriterion("memo like", value, "memo");
			return this;
		}

		public Criteria andMemoNotLike(String value) {
			addCriterion("memo not like", value, "memo");
			return this;
		}

		public Criteria andMemoIn(List values) {
			addCriterion("memo in", values, "memo");
			return this;
		}

		public Criteria andMemoNotIn(List values) {
			addCriterion("memo not in", values, "memo");
			return this;
		}

		public Criteria andMemoBetween(String value1, String value2) {
			addCriterion("memo between", value1, value2, "memo");
			return this;
		}

		public Criteria andMemoNotBetween(String value1, String value2) {
			addCriterion("memo not between", value1, value2, "memo");
			return this;
		}
	}
}