package com.tl.resource.dao.pojo;

import java.math.BigDecimal;
import java.util.ArrayList;
import java.util.Date;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

public class TContractInforExample {
    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database table t_contract_infor
     *
     * @ibatorgenerated Fri Aug 13 10:33:02 CST 2010
     */
    protected String orderByClause;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database table t_contract_infor
     *
     * @ibatorgenerated Fri Aug 13 10:33:02 CST 2010
     */
    protected List oredCriteria;

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table t_contract_infor
     *
     * @ibatorgenerated Fri Aug 13 10:33:02 CST 2010
     */
    public TContractInforExample() {
        oredCriteria = new ArrayList();
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table t_contract_infor
     *
     * @ibatorgenerated Fri Aug 13 10:33:02 CST 2010
     */
    protected TContractInforExample(TContractInforExample example) {
        this.orderByClause = example.orderByClause;
        this.oredCriteria = example.oredCriteria;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table t_contract_infor
     *
     * @ibatorgenerated Fri Aug 13 10:33:02 CST 2010
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table t_contract_infor
     *
     * @ibatorgenerated Fri Aug 13 10:33:02 CST 2010
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table t_contract_infor
     *
     * @ibatorgenerated Fri Aug 13 10:33:02 CST 2010
     */
    public List getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table t_contract_infor
     *
     * @ibatorgenerated Fri Aug 13 10:33:02 CST 2010
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table t_contract_infor
     *
     * @ibatorgenerated Fri Aug 13 10:33:02 CST 2010
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table t_contract_infor
     *
     * @ibatorgenerated Fri Aug 13 10:33:02 CST 2010
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table t_contract_infor
     *
     * @ibatorgenerated Fri Aug 13 10:33:02 CST 2010
     */
    public void clear() {
        oredCriteria.clear();
    }

    /**
     * This class was generated by Apache iBATIS ibator.
     * This class corresponds to the database table t_contract_infor
     *
     * @ibatorgenerated Fri Aug 13 10:33:02 CST 2010
     */
    public static class Criteria {
        protected List criteriaWithoutValue;

        protected List criteriaWithSingleValue;

        protected List criteriaWithListValue;

        protected List criteriaWithBetweenValue;

        protected Criteria() {
            super();
            criteriaWithoutValue = new ArrayList();
            criteriaWithSingleValue = new ArrayList();
            criteriaWithListValue = new ArrayList();
            criteriaWithBetweenValue = new ArrayList();
        }

        public boolean isValid() {
            return criteriaWithoutValue.size() > 0
                || criteriaWithSingleValue.size() > 0
                || criteriaWithListValue.size() > 0
                || criteriaWithBetweenValue.size() > 0;
        }

        public List getCriteriaWithoutValue() {
            return criteriaWithoutValue;
        }

        public List getCriteriaWithSingleValue() {
            return criteriaWithSingleValue;
        }

        public List getCriteriaWithListValue() {
            return criteriaWithListValue;
        }

        public List getCriteriaWithBetweenValue() {
            return criteriaWithBetweenValue;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteriaWithoutValue.add(condition);
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            Map map = new HashMap();
            map.put("condition", condition);
            map.put("value", value);
            criteriaWithSingleValue.add(map);
        }

        protected void addCriterion(String condition, List values, String property) {
            if (values == null || values.size() == 0) {
                throw new RuntimeException("Value list for " + property + " cannot be null or empty");
            }
            Map map = new HashMap();
            map.put("condition", condition);
            map.put("values", values);
            criteriaWithListValue.add(map);
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            List list = new ArrayList();
            list.add(value1);
            list.add(value2);
            Map map = new HashMap();
            map.put("condition", condition);
            map.put("values", list);
            criteriaWithBetweenValue.add(map);
        }

        public Criteria andIdIsNull() {
            addCriterion("id is null");
            return this;
        }

        public Criteria andIdIsNotNull() {
            addCriterion("id is not null");
            return this;
        }

        public Criteria andIdEqualTo(String value) {
            addCriterion("id =", value, "id");
            return this;
        }

        public Criteria andIdNotEqualTo(String value) {
            addCriterion("id <>", value, "id");
            return this;
        }

        public Criteria andIdGreaterThan(String value) {
            addCriterion("id >", value, "id");
            return this;
        }

        public Criteria andIdGreaterThanOrEqualTo(String value) {
            addCriterion("id >=", value, "id");
            return this;
        }

        public Criteria andIdLessThan(String value) {
            addCriterion("id <", value, "id");
            return this;
        }

        public Criteria andIdLessThanOrEqualTo(String value) {
            addCriterion("id <=", value, "id");
            return this;
        }

        public Criteria andIdLike(String value) {
            addCriterion("id like", value, "id");
            return this;
        }

        public Criteria andIdNotLike(String value) {
            addCriterion("id not like", value, "id");
            return this;
        }

        public Criteria andIdIn(List values) {
            addCriterion("id in", values, "id");
            return this;
        }

        public Criteria andIdNotIn(List values) {
            addCriterion("id not in", values, "id");
            return this;
        }

        public Criteria andIdBetween(String value1, String value2) {
            addCriterion("id between", value1, value2, "id");
            return this;
        }

        public Criteria andIdNotBetween(String value1, String value2) {
            addCriterion("id not between", value1, value2, "id");
            return this;
        }

        public Criteria andContractCodeIsNull() {
            addCriterion("contract_code is null");
            return this;
        }

        public Criteria andContractCodeIsNotNull() {
            addCriterion("contract_code is not null");
            return this;
        }

        public Criteria andContractCodeEqualTo(String value) {
            addCriterion("contract_code =", value, "contractCode");
            return this;
        }

        public Criteria andContractCodeNotEqualTo(String value) {
            addCriterion("contract_code <>", value, "contractCode");
            return this;
        }

        public Criteria andContractCodeGreaterThan(String value) {
            addCriterion("contract_code >", value, "contractCode");
            return this;
        }

        public Criteria andContractCodeGreaterThanOrEqualTo(String value) {
            addCriterion("contract_code >=", value, "contractCode");
            return this;
        }

        public Criteria andContractCodeLessThan(String value) {
            addCriterion("contract_code <", value, "contractCode");
            return this;
        }

        public Criteria andContractCodeLessThanOrEqualTo(String value) {
            addCriterion("contract_code <=", value, "contractCode");
            return this;
        }

        public Criteria andContractCodeLike(String value) {
            addCriterion("contract_code like", value, "contractCode");
            return this;
        }

        public Criteria andContractCodeNotLike(String value) {
            addCriterion("contract_code not like", value, "contractCode");
            return this;
        }

        public Criteria andContractCodeIn(List values) {
            addCriterion("contract_code in", values, "contractCode");
            return this;
        }

        public Criteria andContractCodeNotIn(List values) {
            addCriterion("contract_code not in", values, "contractCode");
            return this;
        }

        public Criteria andContractCodeBetween(String value1, String value2) {
            addCriterion("contract_code between", value1, value2, "contractCode");
            return this;
        }

        public Criteria andContractCodeNotBetween(String value1, String value2) {
            addCriterion("contract_code not between", value1, value2, "contractCode");
            return this;
        }

        public Criteria andSellerNameIsNull() {
            addCriterion("seller_name is null");
            return this;
        }

        public Criteria andSellerNameIsNotNull() {
            addCriterion("seller_name is not null");
            return this;
        }

        public Criteria andSellerNameEqualTo(String value) {
            addCriterion("seller_name =", value, "sellerName");
            return this;
        }

        public Criteria andSellerNameNotEqualTo(String value) {
            addCriterion("seller_name <>", value, "sellerName");
            return this;
        }

        public Criteria andSellerNameGreaterThan(String value) {
            addCriterion("seller_name >", value, "sellerName");
            return this;
        }

        public Criteria andSellerNameGreaterThanOrEqualTo(String value) {
            addCriterion("seller_name >=", value, "sellerName");
            return this;
        }

        public Criteria andSellerNameLessThan(String value) {
            addCriterion("seller_name <", value, "sellerName");
            return this;
        }

        public Criteria andSellerNameLessThanOrEqualTo(String value) {
            addCriterion("seller_name <=", value, "sellerName");
            return this;
        }

        public Criteria andSellerNameLike(String value) {
            addCriterion("seller_name like", value, "sellerName");
            return this;
        }

        public Criteria andSellerNameNotLike(String value) {
            addCriterion("seller_name not like", value, "sellerName");
            return this;
        }

        public Criteria andSellerNameIn(List values) {
            addCriterion("seller_name in", values, "sellerName");
            return this;
        }

        public Criteria andSellerNameNotIn(List values) {
            addCriterion("seller_name not in", values, "sellerName");
            return this;
        }

        public Criteria andSellerNameBetween(String value1, String value2) {
            addCriterion("seller_name between", value1, value2, "sellerName");
            return this;
        }

        public Criteria andSellerNameNotBetween(String value1, String value2) {
            addCriterion("seller_name not between", value1, value2, "sellerName");
            return this;
        }

        public Criteria andCurrencyIdIsNull() {
            addCriterion("currency_id is null");
            return this;
        }

        public Criteria andCurrencyIdIsNotNull() {
            addCriterion("currency_id is not null");
            return this;
        }

        public Criteria andCurrencyIdEqualTo(String value) {
            addCriterion("currency_id =", value, "currencyId");
            return this;
        }

        public Criteria andCurrencyIdNotEqualTo(String value) {
            addCriterion("currency_id <>", value, "currencyId");
            return this;
        }

        public Criteria andCurrencyIdGreaterThan(String value) {
            addCriterion("currency_id >", value, "currencyId");
            return this;
        }

        public Criteria andCurrencyIdGreaterThanOrEqualTo(String value) {
            addCriterion("currency_id >=", value, "currencyId");
            return this;
        }

        public Criteria andCurrencyIdLessThan(String value) {
            addCriterion("currency_id <", value, "currencyId");
            return this;
        }

        public Criteria andCurrencyIdLessThanOrEqualTo(String value) {
            addCriterion("currency_id <=", value, "currencyId");
            return this;
        }

        public Criteria andCurrencyIdLike(String value) {
            addCriterion("currency_id like", value, "currencyId");
            return this;
        }

        public Criteria andCurrencyIdNotLike(String value) {
            addCriterion("currency_id not like", value, "currencyId");
            return this;
        }

        public Criteria andCurrencyIdIn(List values) {
            addCriterion("currency_id in", values, "currencyId");
            return this;
        }

        public Criteria andCurrencyIdNotIn(List values) {
            addCriterion("currency_id not in", values, "currencyId");
            return this;
        }

        public Criteria andCurrencyIdBetween(String value1, String value2) {
            addCriterion("currency_id between", value1, value2, "currencyId");
            return this;
        }

        public Criteria andCurrencyIdNotBetween(String value1, String value2) {
            addCriterion("currency_id not between", value1, value2, "currencyId");
            return this;
        }

        public Criteria andCurrencyNameIsNull() {
            addCriterion("currency_name is null");
            return this;
        }

        public Criteria andCurrencyNameIsNotNull() {
            addCriterion("currency_name is not null");
            return this;
        }

        public Criteria andCurrencyNameEqualTo(String value) {
            addCriterion("currency_name =", value, "currencyName");
            return this;
        }

        public Criteria andCurrencyNameNotEqualTo(String value) {
            addCriterion("currency_name <>", value, "currencyName");
            return this;
        }

        public Criteria andCurrencyNameGreaterThan(String value) {
            addCriterion("currency_name >", value, "currencyName");
            return this;
        }

        public Criteria andCurrencyNameGreaterThanOrEqualTo(String value) {
            addCriterion("currency_name >=", value, "currencyName");
            return this;
        }

        public Criteria andCurrencyNameLessThan(String value) {
            addCriterion("currency_name <", value, "currencyName");
            return this;
        }

        public Criteria andCurrencyNameLessThanOrEqualTo(String value) {
            addCriterion("currency_name <=", value, "currencyName");
            return this;
        }

        public Criteria andCurrencyNameLike(String value) {
            addCriterion("currency_name like", value, "currencyName");
            return this;
        }

        public Criteria andCurrencyNameNotLike(String value) {
            addCriterion("currency_name not like", value, "currencyName");
            return this;
        }

        public Criteria andCurrencyNameIn(List values) {
            addCriterion("currency_name in", values, "currencyName");
            return this;
        }

        public Criteria andCurrencyNameNotIn(List values) {
            addCriterion("currency_name not in", values, "currencyName");
            return this;
        }

        public Criteria andCurrencyNameBetween(String value1, String value2) {
            addCriterion("currency_name between", value1, value2, "currencyName");
            return this;
        }

        public Criteria andCurrencyNameNotBetween(String value1, String value2) {
            addCriterion("currency_name not between", value1, value2, "currencyName");
            return this;
        }

        public Criteria andSignDateIsNull() {
            addCriterion("sign_date is null");
            return this;
        }

        public Criteria andSignDateIsNotNull() {
            addCriterion("sign_date is not null");
            return this;
        }

        public Criteria andSignDateEqualTo(String value) {
            addCriterion("sign_date =", value, "signDate");
            return this;
        }

        public Criteria andSignDateNotEqualTo(String value) {
            addCriterion("sign_date <>", value, "signDate");
            return this;
        }

        public Criteria andSignDateGreaterThan(String value) {
            addCriterion("sign_date >", value, "signDate");
            return this;
        }

        public Criteria andSignDateGreaterThanOrEqualTo(String value) {
            addCriterion("sign_date >=", value, "signDate");
            return this;
        }

        public Criteria andSignDateLessThan(String value) {
            addCriterion("sign_date <", value, "signDate");
            return this;
        }

        public Criteria andSignDateLessThanOrEqualTo(String value) {
            addCriterion("sign_date <=", value, "signDate");
            return this;
        }

        public Criteria andSignDateLike(String value) {
            addCriterion("sign_date like", value, "signDate");
            return this;
        }

        public Criteria andSignDateNotLike(String value) {
            addCriterion("sign_date not like", value, "signDate");
            return this;
        }

        public Criteria andSignDateIn(List values) {
            addCriterion("sign_date in", values, "signDate");
            return this;
        }

        public Criteria andSignDateNotIn(List values) {
            addCriterion("sign_date not in", values, "signDate");
            return this;
        }

        public Criteria andSignDateBetween(String value1, String value2) {
            addCriterion("sign_date between", value1, value2, "signDate");
            return this;
        }

        public Criteria andSignDateNotBetween(String value1, String value2) {
            addCriterion("sign_date not between", value1, value2, "signDate");
            return this;
        }

        public Criteria andUrgentLevelIsNull() {
            addCriterion("urgent_level is null");
            return this;
        }

        public Criteria andUrgentLevelIsNotNull() {
            addCriterion("urgent_level is not null");
            return this;
        }

        public Criteria andUrgentLevelEqualTo(Integer value) {
            addCriterion("urgent_level =", value, "urgentLevel");
            return this;
        }

        public Criteria andUrgentLevelNotEqualTo(Integer value) {
            addCriterion("urgent_level <>", value, "urgentLevel");
            return this;
        }

        public Criteria andUrgentLevelGreaterThan(Integer value) {
            addCriterion("urgent_level >", value, "urgentLevel");
            return this;
        }

        public Criteria andUrgentLevelGreaterThanOrEqualTo(Integer value) {
            addCriterion("urgent_level >=", value, "urgentLevel");
            return this;
        }

        public Criteria andUrgentLevelLessThan(Integer value) {
            addCriterion("urgent_level <", value, "urgentLevel");
            return this;
        }

        public Criteria andUrgentLevelLessThanOrEqualTo(Integer value) {
            addCriterion("urgent_level <=", value, "urgentLevel");
            return this;
        }

        public Criteria andUrgentLevelIn(List values) {
            addCriterion("urgent_level in", values, "urgentLevel");
            return this;
        }

        public Criteria andUrgentLevelNotIn(List values) {
            addCriterion("urgent_level not in", values, "urgentLevel");
            return this;
        }

        public Criteria andUrgentLevelBetween(Integer value1, Integer value2) {
            addCriterion("urgent_level between", value1, value2, "urgentLevel");
            return this;
        }

        public Criteria andUrgentLevelNotBetween(Integer value1, Integer value2) {
            addCriterion("urgent_level not between", value1, value2, "urgentLevel");
            return this;
        }

        public Criteria andCustomerCodeIsNull() {
            addCriterion("customer_code is null");
            return this;
        }

        public Criteria andCustomerCodeIsNotNull() {
            addCriterion("customer_code is not null");
            return this;
        }

        public Criteria andCustomerCodeEqualTo(String value) {
            addCriterion("customer_code =", value, "customerCode");
            return this;
        }

        public Criteria andCustomerCodeNotEqualTo(String value) {
            addCriterion("customer_code <>", value, "customerCode");
            return this;
        }

        public Criteria andCustomerCodeGreaterThan(String value) {
            addCriterion("customer_code >", value, "customerCode");
            return this;
        }

        public Criteria andCustomerCodeGreaterThanOrEqualTo(String value) {
            addCriterion("customer_code >=", value, "customerCode");
            return this;
        }

        public Criteria andCustomerCodeLessThan(String value) {
            addCriterion("customer_code <", value, "customerCode");
            return this;
        }

        public Criteria andCustomerCodeLessThanOrEqualTo(String value) {
            addCriterion("customer_code <=", value, "customerCode");
            return this;
        }

        public Criteria andCustomerCodeLike(String value) {
            addCriterion("customer_code like", value, "customerCode");
            return this;
        }

        public Criteria andCustomerCodeNotLike(String value) {
            addCriterion("customer_code not like", value, "customerCode");
            return this;
        }

        public Criteria andCustomerCodeIn(List values) {
            addCriterion("customer_code in", values, "customerCode");
            return this;
        }

        public Criteria andCustomerCodeNotIn(List values) {
            addCriterion("customer_code not in", values, "customerCode");
            return this;
        }

        public Criteria andCustomerCodeBetween(String value1, String value2) {
            addCriterion("customer_code between", value1, value2, "customerCode");
            return this;
        }

        public Criteria andCustomerCodeNotBetween(String value1, String value2) {
            addCriterion("customer_code not between", value1, value2, "customerCode");
            return this;
        }

        public Criteria andCustomerNameIsNull() {
            addCriterion("customer_name is null");
            return this;
        }

        public Criteria andCustomerNameIsNotNull() {
            addCriterion("customer_name is not null");
            return this;
        }

        public Criteria andCustomerNameEqualTo(String value) {
            addCriterion("customer_name =", value, "customerName");
            return this;
        }

        public Criteria andCustomerNameNotEqualTo(String value) {
            addCriterion("customer_name <>", value, "customerName");
            return this;
        }

        public Criteria andCustomerNameGreaterThan(String value) {
            addCriterion("customer_name >", value, "customerName");
            return this;
        }

        public Criteria andCustomerNameGreaterThanOrEqualTo(String value) {
            addCriterion("customer_name >=", value, "customerName");
            return this;
        }

        public Criteria andCustomerNameLessThan(String value) {
            addCriterion("customer_name <", value, "customerName");
            return this;
        }

        public Criteria andCustomerNameLessThanOrEqualTo(String value) {
            addCriterion("customer_name <=", value, "customerName");
            return this;
        }

        public Criteria andCustomerNameLike(String value) {
            addCriterion("customer_name like", value, "customerName");
            return this;
        }

        public Criteria andCustomerNameNotLike(String value) {
            addCriterion("customer_name not like", value, "customerName");
            return this;
        }

        public Criteria andCustomerNameIn(List values) {
            addCriterion("customer_name in", values, "customerName");
            return this;
        }

        public Criteria andCustomerNameNotIn(List values) {
            addCriterion("customer_name not in", values, "customerName");
            return this;
        }

        public Criteria andCustomerNameBetween(String value1, String value2) {
            addCriterion("customer_name between", value1, value2, "customerName");
            return this;
        }

        public Criteria andCustomerNameNotBetween(String value1, String value2) {
            addCriterion("customer_name not between", value1, value2, "customerName");
            return this;
        }

        public Criteria andStatusIsNull() {
            addCriterion("status is null");
            return this;
        }

        public Criteria andStatusIsNotNull() {
            addCriterion("status is not null");
            return this;
        }

        public Criteria andStatusEqualTo(Integer value) {
            addCriterion("status =", value, "status");
            return this;
        }

        public Criteria andStatusNotEqualTo(Integer value) {
            addCriterion("status <>", value, "status");
            return this;
        }

        public Criteria andStatusGreaterThan(Integer value) {
            addCriterion("status >", value, "status");
            return this;
        }

        public Criteria andStatusGreaterThanOrEqualTo(Integer value) {
            addCriterion("status >=", value, "status");
            return this;
        }

        public Criteria andStatusLessThan(Integer value) {
            addCriterion("status <", value, "status");
            return this;
        }

        public Criteria andStatusLessThanOrEqualTo(Integer value) {
            addCriterion("status <=", value, "status");
            return this;
        }

        public Criteria andStatusIn(List values) {
            addCriterion("status in", values, "status");
            return this;
        }

        public Criteria andStatusNotIn(List values) {
            addCriterion("status not in", values, "status");
            return this;
        }

        public Criteria andStatusBetween(Integer value1, Integer value2) {
            addCriterion("status between", value1, value2, "status");
            return this;
        }

        public Criteria andStatusNotBetween(Integer value1, Integer value2) {
            addCriterion("status not between", value1, value2, "status");
            return this;
        }

        public Criteria andSignAddressIsNull() {
            addCriterion("sign_address is null");
            return this;
        }

        public Criteria andSignAddressIsNotNull() {
            addCriterion("sign_address is not null");
            return this;
        }

        public Criteria andSignAddressEqualTo(String value) {
            addCriterion("sign_address =", value, "signAddress");
            return this;
        }

        public Criteria andSignAddressNotEqualTo(String value) {
            addCriterion("sign_address <>", value, "signAddress");
            return this;
        }

        public Criteria andSignAddressGreaterThan(String value) {
            addCriterion("sign_address >", value, "signAddress");
            return this;
        }

        public Criteria andSignAddressGreaterThanOrEqualTo(String value) {
            addCriterion("sign_address >=", value, "signAddress");
            return this;
        }

        public Criteria andSignAddressLessThan(String value) {
            addCriterion("sign_address <", value, "signAddress");
            return this;
        }

        public Criteria andSignAddressLessThanOrEqualTo(String value) {
            addCriterion("sign_address <=", value, "signAddress");
            return this;
        }

        public Criteria andSignAddressLike(String value) {
            addCriterion("sign_address like", value, "signAddress");
            return this;
        }

        public Criteria andSignAddressNotLike(String value) {
            addCriterion("sign_address not like", value, "signAddress");
            return this;
        }

        public Criteria andSignAddressIn(List values) {
            addCriterion("sign_address in", values, "signAddress");
            return this;
        }

        public Criteria andSignAddressNotIn(List values) {
            addCriterion("sign_address not in", values, "signAddress");
            return this;
        }

        public Criteria andSignAddressBetween(String value1, String value2) {
            addCriterion("sign_address between", value1, value2, "signAddress");
            return this;
        }

        public Criteria andSignAddressNotBetween(String value1, String value2) {
            addCriterion("sign_address not between", value1, value2, "signAddress");
            return this;
        }

        public Criteria andReferenceIsNull() {
            addCriterion("reference is null");
            return this;
        }

        public Criteria andReferenceIsNotNull() {
            addCriterion("reference is not null");
            return this;
        }

        public Criteria andReferenceEqualTo(String value) {
            addCriterion("reference =", value, "reference");
            return this;
        }

        public Criteria andReferenceNotEqualTo(String value) {
            addCriterion("reference <>", value, "reference");
            return this;
        }

        public Criteria andReferenceGreaterThan(String value) {
            addCriterion("reference >", value, "reference");
            return this;
        }

        public Criteria andReferenceGreaterThanOrEqualTo(String value) {
            addCriterion("reference >=", value, "reference");
            return this;
        }

        public Criteria andReferenceLessThan(String value) {
            addCriterion("reference <", value, "reference");
            return this;
        }

        public Criteria andReferenceLessThanOrEqualTo(String value) {
            addCriterion("reference <=", value, "reference");
            return this;
        }

        public Criteria andReferenceLike(String value) {
            addCriterion("reference like", value, "reference");
            return this;
        }

        public Criteria andReferenceNotLike(String value) {
            addCriterion("reference not like", value, "reference");
            return this;
        }

        public Criteria andReferenceIn(List values) {
            addCriterion("reference in", values, "reference");
            return this;
        }

        public Criteria andReferenceNotIn(List values) {
            addCriterion("reference not in", values, "reference");
            return this;
        }

        public Criteria andReferenceBetween(String value1, String value2) {
            addCriterion("reference between", value1, value2, "reference");
            return this;
        }

        public Criteria andReferenceNotBetween(String value1, String value2) {
            addCriterion("reference not between", value1, value2, "reference");
            return this;
        }

        public Criteria andTrafficModeIsNull() {
            addCriterion("traffic_mode is null");
            return this;
        }

        public Criteria andTrafficModeIsNotNull() {
            addCriterion("traffic_mode is not null");
            return this;
        }

        public Criteria andTrafficModeEqualTo(String value) {
            addCriterion("traffic_mode =", value, "trafficMode");
            return this;
        }

        public Criteria andTrafficModeNotEqualTo(String value) {
            addCriterion("traffic_mode <>", value, "trafficMode");
            return this;
        }

        public Criteria andTrafficModeGreaterThan(String value) {
            addCriterion("traffic_mode >", value, "trafficMode");
            return this;
        }

        public Criteria andTrafficModeGreaterThanOrEqualTo(String value) {
            addCriterion("traffic_mode >=", value, "trafficMode");
            return this;
        }

        public Criteria andTrafficModeLessThan(String value) {
            addCriterion("traffic_mode <", value, "trafficMode");
            return this;
        }

        public Criteria andTrafficModeLessThanOrEqualTo(String value) {
            addCriterion("traffic_mode <=", value, "trafficMode");
            return this;
        }

        public Criteria andTrafficModeLike(String value) {
            addCriterion("traffic_mode like", value, "trafficMode");
            return this;
        }

        public Criteria andTrafficModeNotLike(String value) {
            addCriterion("traffic_mode not like", value, "trafficMode");
            return this;
        }

        public Criteria andTrafficModeIn(List values) {
            addCriterion("traffic_mode in", values, "trafficMode");
            return this;
        }

        public Criteria andTrafficModeNotIn(List values) {
            addCriterion("traffic_mode not in", values, "trafficMode");
            return this;
        }

        public Criteria andTrafficModeBetween(String value1, String value2) {
            addCriterion("traffic_mode between", value1, value2, "trafficMode");
            return this;
        }

        public Criteria andTrafficModeNotBetween(String value1, String value2) {
            addCriterion("traffic_mode not between", value1, value2, "trafficMode");
            return this;
        }

        public Criteria andClosingAccountModeIdIsNull() {
            addCriterion("closing_account_mode_id is null");
            return this;
        }

        public Criteria andClosingAccountModeIdIsNotNull() {
            addCriterion("closing_account_mode_id is not null");
            return this;
        }

        public Criteria andClosingAccountModeIdEqualTo(Integer value) {
            addCriterion("closing_account_mode_id =", value, "closingAccountModeId");
            return this;
        }

        public Criteria andClosingAccountModeIdNotEqualTo(Integer value) {
            addCriterion("closing_account_mode_id <>", value, "closingAccountModeId");
            return this;
        }

        public Criteria andClosingAccountModeIdGreaterThan(Integer value) {
            addCriterion("closing_account_mode_id >", value, "closingAccountModeId");
            return this;
        }

        public Criteria andClosingAccountModeIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("closing_account_mode_id >=", value, "closingAccountModeId");
            return this;
        }

        public Criteria andClosingAccountModeIdLessThan(Integer value) {
            addCriterion("closing_account_mode_id <", value, "closingAccountModeId");
            return this;
        }

        public Criteria andClosingAccountModeIdLessThanOrEqualTo(Integer value) {
            addCriterion("closing_account_mode_id <=", value, "closingAccountModeId");
            return this;
        }

        public Criteria andClosingAccountModeIdIn(List values) {
            addCriterion("closing_account_mode_id in", values, "closingAccountModeId");
            return this;
        }

        public Criteria andClosingAccountModeIdNotIn(List values) {
            addCriterion("closing_account_mode_id not in", values, "closingAccountModeId");
            return this;
        }

        public Criteria andClosingAccountModeIdBetween(Integer value1, Integer value2) {
            addCriterion("closing_account_mode_id between", value1, value2, "closingAccountModeId");
            return this;
        }

        public Criteria andClosingAccountModeIdNotBetween(Integer value1, Integer value2) {
            addCriterion("closing_account_mode_id not between", value1, value2, "closingAccountModeId");
            return this;
        }

        public Criteria andClosingAccountModeIsNull() {
            addCriterion("closing_account_mode is null");
            return this;
        }

        public Criteria andClosingAccountModeIsNotNull() {
            addCriterion("closing_account_mode is not null");
            return this;
        }

        public Criteria andClosingAccountModeEqualTo(String value) {
            addCriterion("closing_account_mode =", value, "closingAccountMode");
            return this;
        }

        public Criteria andClosingAccountModeNotEqualTo(String value) {
            addCriterion("closing_account_mode <>", value, "closingAccountMode");
            return this;
        }

        public Criteria andClosingAccountModeGreaterThan(String value) {
            addCriterion("closing_account_mode >", value, "closingAccountMode");
            return this;
        }

        public Criteria andClosingAccountModeGreaterThanOrEqualTo(String value) {
            addCriterion("closing_account_mode >=", value, "closingAccountMode");
            return this;
        }

        public Criteria andClosingAccountModeLessThan(String value) {
            addCriterion("closing_account_mode <", value, "closingAccountMode");
            return this;
        }

        public Criteria andClosingAccountModeLessThanOrEqualTo(String value) {
            addCriterion("closing_account_mode <=", value, "closingAccountMode");
            return this;
        }

        public Criteria andClosingAccountModeLike(String value) {
            addCriterion("closing_account_mode like", value, "closingAccountMode");
            return this;
        }

        public Criteria andClosingAccountModeNotLike(String value) {
            addCriterion("closing_account_mode not like", value, "closingAccountMode");
            return this;
        }

        public Criteria andClosingAccountModeIn(List values) {
            addCriterion("closing_account_mode in", values, "closingAccountMode");
            return this;
        }

        public Criteria andClosingAccountModeNotIn(List values) {
            addCriterion("closing_account_mode not in", values, "closingAccountMode");
            return this;
        }

        public Criteria andClosingAccountModeBetween(String value1, String value2) {
            addCriterion("closing_account_mode between", value1, value2, "closingAccountMode");
            return this;
        }

        public Criteria andClosingAccountModeNotBetween(String value1, String value2) {
            addCriterion("closing_account_mode not between", value1, value2, "closingAccountMode");
            return this;
        }

        public Criteria andDeliveryAddressTypeIsNull() {
            addCriterion("delivery_address_type is null");
            return this;
        }

        public Criteria andDeliveryAddressTypeIsNotNull() {
            addCriterion("delivery_address_type is not null");
            return this;
        }

        public Criteria andDeliveryAddressTypeEqualTo(String value) {
            addCriterion("delivery_address_type =", value, "deliveryAddressType");
            return this;
        }

        public Criteria andDeliveryAddressTypeNotEqualTo(String value) {
            addCriterion("delivery_address_type <>", value, "deliveryAddressType");
            return this;
        }

        public Criteria andDeliveryAddressTypeGreaterThan(String value) {
            addCriterion("delivery_address_type >", value, "deliveryAddressType");
            return this;
        }

        public Criteria andDeliveryAddressTypeGreaterThanOrEqualTo(String value) {
            addCriterion("delivery_address_type >=", value, "deliveryAddressType");
            return this;
        }

        public Criteria andDeliveryAddressTypeLessThan(String value) {
            addCriterion("delivery_address_type <", value, "deliveryAddressType");
            return this;
        }

        public Criteria andDeliveryAddressTypeLessThanOrEqualTo(String value) {
            addCriterion("delivery_address_type <=", value, "deliveryAddressType");
            return this;
        }

        public Criteria andDeliveryAddressTypeLike(String value) {
            addCriterion("delivery_address_type like", value, "deliveryAddressType");
            return this;
        }

        public Criteria andDeliveryAddressTypeNotLike(String value) {
            addCriterion("delivery_address_type not like", value, "deliveryAddressType");
            return this;
        }

        public Criteria andDeliveryAddressTypeIn(List values) {
            addCriterion("delivery_address_type in", values, "deliveryAddressType");
            return this;
        }

        public Criteria andDeliveryAddressTypeNotIn(List values) {
            addCriterion("delivery_address_type not in", values, "deliveryAddressType");
            return this;
        }

        public Criteria andDeliveryAddressTypeBetween(String value1, String value2) {
            addCriterion("delivery_address_type between", value1, value2, "deliveryAddressType");
            return this;
        }

        public Criteria andDeliveryAddressTypeNotBetween(String value1, String value2) {
            addCriterion("delivery_address_type not between", value1, value2, "deliveryAddressType");
            return this;
        }

        public Criteria andOtherConventionIsNull() {
            addCriterion("other_convention is null");
            return this;
        }

        public Criteria andOtherConventionIsNotNull() {
            addCriterion("other_convention is not null");
            return this;
        }

        public Criteria andOtherConventionEqualTo(String value) {
            addCriterion("other_convention =", value, "otherConvention");
            return this;
        }

        public Criteria andOtherConventionNotEqualTo(String value) {
            addCriterion("other_convention <>", value, "otherConvention");
            return this;
        }

        public Criteria andOtherConventionGreaterThan(String value) {
            addCriterion("other_convention >", value, "otherConvention");
            return this;
        }

        public Criteria andOtherConventionGreaterThanOrEqualTo(String value) {
            addCriterion("other_convention >=", value, "otherConvention");
            return this;
        }

        public Criteria andOtherConventionLessThan(String value) {
            addCriterion("other_convention <", value, "otherConvention");
            return this;
        }

        public Criteria andOtherConventionLessThanOrEqualTo(String value) {
            addCriterion("other_convention <=", value, "otherConvention");
            return this;
        }

        public Criteria andOtherConventionLike(String value) {
            addCriterion("other_convention like", value, "otherConvention");
            return this;
        }

        public Criteria andOtherConventionNotLike(String value) {
            addCriterion("other_convention not like", value, "otherConvention");
            return this;
        }

        public Criteria andOtherConventionIn(List values) {
            addCriterion("other_convention in", values, "otherConvention");
            return this;
        }

        public Criteria andOtherConventionNotIn(List values) {
            addCriterion("other_convention not in", values, "otherConvention");
            return this;
        }

        public Criteria andOtherConventionBetween(String value1, String value2) {
            addCriterion("other_convention between", value1, value2, "otherConvention");
            return this;
        }

        public Criteria andOtherConventionNotBetween(String value1, String value2) {
            addCriterion("other_convention not between", value1, value2, "otherConvention");
            return this;
        }

        public Criteria andEffectConditionsIsNull() {
            addCriterion("effect_conditions is null");
            return this;
        }

        public Criteria andEffectConditionsIsNotNull() {
            addCriterion("effect_conditions is not null");
            return this;
        }

        public Criteria andEffectConditionsEqualTo(String value) {
            addCriterion("effect_conditions =", value, "effectConditions");
            return this;
        }

        public Criteria andEffectConditionsNotEqualTo(String value) {
            addCriterion("effect_conditions <>", value, "effectConditions");
            return this;
        }

        public Criteria andEffectConditionsGreaterThan(String value) {
            addCriterion("effect_conditions >", value, "effectConditions");
            return this;
        }

        public Criteria andEffectConditionsGreaterThanOrEqualTo(String value) {
            addCriterion("effect_conditions >=", value, "effectConditions");
            return this;
        }

        public Criteria andEffectConditionsLessThan(String value) {
            addCriterion("effect_conditions <", value, "effectConditions");
            return this;
        }

        public Criteria andEffectConditionsLessThanOrEqualTo(String value) {
            addCriterion("effect_conditions <=", value, "effectConditions");
            return this;
        }

        public Criteria andEffectConditionsLike(String value) {
            addCriterion("effect_conditions like", value, "effectConditions");
            return this;
        }

        public Criteria andEffectConditionsNotLike(String value) {
            addCriterion("effect_conditions not like", value, "effectConditions");
            return this;
        }

        public Criteria andEffectConditionsIn(List values) {
            addCriterion("effect_conditions in", values, "effectConditions");
            return this;
        }

        public Criteria andEffectConditionsNotIn(List values) {
            addCriterion("effect_conditions not in", values, "effectConditions");
            return this;
        }

        public Criteria andEffectConditionsBetween(String value1, String value2) {
            addCriterion("effect_conditions between", value1, value2, "effectConditions");
            return this;
        }

        public Criteria andEffectConditionsNotBetween(String value1, String value2) {
            addCriterion("effect_conditions not between", value1, value2, "effectConditions");
            return this;
        }

        public Criteria andProductMoneyIsNull() {
            addCriterion("product_money is null");
            return this;
        }

        public Criteria andProductMoneyIsNotNull() {
            addCriterion("product_money is not null");
            return this;
        }

        public Criteria andProductMoneyEqualTo(BigDecimal value) {
            addCriterion("product_money =", value, "productMoney");
            return this;
        }

        public Criteria andProductMoneyNotEqualTo(BigDecimal value) {
            addCriterion("product_money <>", value, "productMoney");
            return this;
        }

        public Criteria andProductMoneyGreaterThan(BigDecimal value) {
            addCriterion("product_money >", value, "productMoney");
            return this;
        }

        public Criteria andProductMoneyGreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("product_money >=", value, "productMoney");
            return this;
        }

        public Criteria andProductMoneyLessThan(BigDecimal value) {
            addCriterion("product_money <", value, "productMoney");
            return this;
        }

        public Criteria andProductMoneyLessThanOrEqualTo(BigDecimal value) {
            addCriterion("product_money <=", value, "productMoney");
            return this;
        }

        public Criteria andProductMoneyIn(List values) {
            addCriterion("product_money in", values, "productMoney");
            return this;
        }

        public Criteria andProductMoneyNotIn(List values) {
            addCriterion("product_money not in", values, "productMoney");
            return this;
        }

        public Criteria andProductMoneyBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("product_money between", value1, value2, "productMoney");
            return this;
        }

        public Criteria andProductMoneyNotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("product_money not between", value1, value2, "productMoney");
            return this;
        }

        public Criteria andTaxRateIsNull() {
            addCriterion("tax_rate is null");
            return this;
        }

        public Criteria andTaxRateIsNotNull() {
            addCriterion("tax_rate is not null");
            return this;
        }

        public Criteria andTaxRateEqualTo(BigDecimal value) {
            addCriterion("tax_rate =", value, "taxRate");
            return this;
        }

        public Criteria andTaxRateNotEqualTo(BigDecimal value) {
            addCriterion("tax_rate <>", value, "taxRate");
            return this;
        }

        public Criteria andTaxRateGreaterThan(BigDecimal value) {
            addCriterion("tax_rate >", value, "taxRate");
            return this;
        }

        public Criteria andTaxRateGreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("tax_rate >=", value, "taxRate");
            return this;
        }

        public Criteria andTaxRateLessThan(BigDecimal value) {
            addCriterion("tax_rate <", value, "taxRate");
            return this;
        }

        public Criteria andTaxRateLessThanOrEqualTo(BigDecimal value) {
            addCriterion("tax_rate <=", value, "taxRate");
            return this;
        }

        public Criteria andTaxRateIn(List values) {
            addCriterion("tax_rate in", values, "taxRate");
            return this;
        }

        public Criteria andTaxRateNotIn(List values) {
            addCriterion("tax_rate not in", values, "taxRate");
            return this;
        }

        public Criteria andTaxRateBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("tax_rate between", value1, value2, "taxRate");
            return this;
        }

        public Criteria andTaxRateNotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("tax_rate not between", value1, value2, "taxRate");
            return this;
        }

        public Criteria andTaxMoneyIsNull() {
            addCriterion("tax_money is null");
            return this;
        }

        public Criteria andTaxMoneyIsNotNull() {
            addCriterion("tax_money is not null");
            return this;
        }

        public Criteria andTaxMoneyEqualTo(BigDecimal value) {
            addCriterion("tax_money =", value, "taxMoney");
            return this;
        }

        public Criteria andTaxMoneyNotEqualTo(BigDecimal value) {
            addCriterion("tax_money <>", value, "taxMoney");
            return this;
        }

        public Criteria andTaxMoneyGreaterThan(BigDecimal value) {
            addCriterion("tax_money >", value, "taxMoney");
            return this;
        }

        public Criteria andTaxMoneyGreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("tax_money >=", value, "taxMoney");
            return this;
        }

        public Criteria andTaxMoneyLessThan(BigDecimal value) {
            addCriterion("tax_money <", value, "taxMoney");
            return this;
        }

        public Criteria andTaxMoneyLessThanOrEqualTo(BigDecimal value) {
            addCriterion("tax_money <=", value, "taxMoney");
            return this;
        }

        public Criteria andTaxMoneyIn(List values) {
            addCriterion("tax_money in", values, "taxMoney");
            return this;
        }

        public Criteria andTaxMoneyNotIn(List values) {
            addCriterion("tax_money not in", values, "taxMoney");
            return this;
        }

        public Criteria andTaxMoneyBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("tax_money between", value1, value2, "taxMoney");
            return this;
        }

        public Criteria andTaxMoneyNotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("tax_money not between", value1, value2, "taxMoney");
            return this;
        }

        public Criteria andTotalMoneyIsNull() {
            addCriterion("total_money is null");
            return this;
        }

        public Criteria andTotalMoneyIsNotNull() {
            addCriterion("total_money is not null");
            return this;
        }

        public Criteria andTotalMoneyEqualTo(BigDecimal value) {
            addCriterion("total_money =", value, "totalMoney");
            return this;
        }

        public Criteria andTotalMoneyNotEqualTo(BigDecimal value) {
            addCriterion("total_money <>", value, "totalMoney");
            return this;
        }

        public Criteria andTotalMoneyGreaterThan(BigDecimal value) {
            addCriterion("total_money >", value, "totalMoney");
            return this;
        }

        public Criteria andTotalMoneyGreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("total_money >=", value, "totalMoney");
            return this;
        }

        public Criteria andTotalMoneyLessThan(BigDecimal value) {
            addCriterion("total_money <", value, "totalMoney");
            return this;
        }

        public Criteria andTotalMoneyLessThanOrEqualTo(BigDecimal value) {
            addCriterion("total_money <=", value, "totalMoney");
            return this;
        }

        public Criteria andTotalMoneyIn(List values) {
            addCriterion("total_money in", values, "totalMoney");
            return this;
        }

        public Criteria andTotalMoneyNotIn(List values) {
            addCriterion("total_money not in", values, "totalMoney");
            return this;
        }

        public Criteria andTotalMoneyBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("total_money between", value1, value2, "totalMoney");
            return this;
        }

        public Criteria andTotalMoneyNotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("total_money not between", value1, value2, "totalMoney");
            return this;
        }

        public Criteria andOverallRebateIsNull() {
            addCriterion("overall_rebate is null");
            return this;
        }

        public Criteria andOverallRebateIsNotNull() {
            addCriterion("overall_rebate is not null");
            return this;
        }

        public Criteria andOverallRebateEqualTo(BigDecimal value) {
            addCriterion("overall_rebate =", value, "overallRebate");
            return this;
        }

        public Criteria andOverallRebateNotEqualTo(BigDecimal value) {
            addCriterion("overall_rebate <>", value, "overallRebate");
            return this;
        }

        public Criteria andOverallRebateGreaterThan(BigDecimal value) {
            addCriterion("overall_rebate >", value, "overallRebate");
            return this;
        }

        public Criteria andOverallRebateGreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("overall_rebate >=", value, "overallRebate");
            return this;
        }

        public Criteria andOverallRebateLessThan(BigDecimal value) {
            addCriterion("overall_rebate <", value, "overallRebate");
            return this;
        }

        public Criteria andOverallRebateLessThanOrEqualTo(BigDecimal value) {
            addCriterion("overall_rebate <=", value, "overallRebate");
            return this;
        }

        public Criteria andOverallRebateIn(List values) {
            addCriterion("overall_rebate in", values, "overallRebate");
            return this;
        }

        public Criteria andOverallRebateNotIn(List values) {
            addCriterion("overall_rebate not in", values, "overallRebate");
            return this;
        }

        public Criteria andOverallRebateBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("overall_rebate between", value1, value2, "overallRebate");
            return this;
        }

        public Criteria andOverallRebateNotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("overall_rebate not between", value1, value2, "overallRebate");
            return this;
        }

        public Criteria andFinalMoneyIsNull() {
            addCriterion("final_money is null");
            return this;
        }

        public Criteria andFinalMoneyIsNotNull() {
            addCriterion("final_money is not null");
            return this;
        }

        public Criteria andFinalMoneyEqualTo(BigDecimal value) {
            addCriterion("final_money =", value, "finalMoney");
            return this;
        }

        public Criteria andFinalMoneyNotEqualTo(BigDecimal value) {
            addCriterion("final_money <>", value, "finalMoney");
            return this;
        }

        public Criteria andFinalMoneyGreaterThan(BigDecimal value) {
            addCriterion("final_money >", value, "finalMoney");
            return this;
        }

        public Criteria andFinalMoneyGreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("final_money >=", value, "finalMoney");
            return this;
        }

        public Criteria andFinalMoneyLessThan(BigDecimal value) {
            addCriterion("final_money <", value, "finalMoney");
            return this;
        }

        public Criteria andFinalMoneyLessThanOrEqualTo(BigDecimal value) {
            addCriterion("final_money <=", value, "finalMoney");
            return this;
        }

        public Criteria andFinalMoneyIn(List values) {
            addCriterion("final_money in", values, "finalMoney");
            return this;
        }

        public Criteria andFinalMoneyNotIn(List values) {
            addCriterion("final_money not in", values, "finalMoney");
            return this;
        }

        public Criteria andFinalMoneyBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("final_money between", value1, value2, "finalMoney");
            return this;
        }

        public Criteria andFinalMoneyNotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("final_money not between", value1, value2, "finalMoney");
            return this;
        }

        public Criteria andMemoIsNull() {
            addCriterion("memo is null");
            return this;
        }

        public Criteria andMemoIsNotNull() {
            addCriterion("memo is not null");
            return this;
        }

        public Criteria andMemoEqualTo(String value) {
            addCriterion("memo =", value, "memo");
            return this;
        }

        public Criteria andMemoNotEqualTo(String value) {
            addCriterion("memo <>", value, "memo");
            return this;
        }

        public Criteria andMemoGreaterThan(String value) {
            addCriterion("memo >", value, "memo");
            return this;
        }

        public Criteria andMemoGreaterThanOrEqualTo(String value) {
            addCriterion("memo >=", value, "memo");
            return this;
        }

        public Criteria andMemoLessThan(String value) {
            addCriterion("memo <", value, "memo");
            return this;
        }

        public Criteria andMemoLessThanOrEqualTo(String value) {
            addCriterion("memo <=", value, "memo");
            return this;
        }

        public Criteria andMemoLike(String value) {
            addCriterion("memo like", value, "memo");
            return this;
        }

        public Criteria andMemoNotLike(String value) {
            addCriterion("memo not like", value, "memo");
            return this;
        }

        public Criteria andMemoIn(List values) {
            addCriterion("memo in", values, "memo");
            return this;
        }

        public Criteria andMemoNotIn(List values) {
            addCriterion("memo not in", values, "memo");
            return this;
        }

        public Criteria andMemoBetween(String value1, String value2) {
            addCriterion("memo between", value1, value2, "memo");
            return this;
        }

        public Criteria andMemoNotBetween(String value1, String value2) {
            addCriterion("memo not between", value1, value2, "memo");
            return this;
        }

        public Criteria andEditDateIsNull() {
            addCriterion("edit_date is null");
            return this;
        }

        public Criteria andEditDateIsNotNull() {
            addCriterion("edit_date is not null");
            return this;
        }

        public Criteria andEditDateEqualTo(Date value) {
            addCriterion("edit_date =", value, "editDate");
            return this;
        }

        public Criteria andEditDateNotEqualTo(Date value) {
            addCriterion("edit_date <>", value, "editDate");
            return this;
        }

        public Criteria andEditDateGreaterThan(Date value) {
            addCriterion("edit_date >", value, "editDate");
            return this;
        }

        public Criteria andEditDateGreaterThanOrEqualTo(Date value) {
            addCriterion("edit_date >=", value, "editDate");
            return this;
        }

        public Criteria andEditDateLessThan(Date value) {
            addCriterion("edit_date <", value, "editDate");
            return this;
        }

        public Criteria andEditDateLessThanOrEqualTo(Date value) {
            addCriterion("edit_date <=", value, "editDate");
            return this;
        }

        public Criteria andEditDateIn(List values) {
            addCriterion("edit_date in", values, "editDate");
            return this;
        }

        public Criteria andEditDateNotIn(List values) {
            addCriterion("edit_date not in", values, "editDate");
            return this;
        }

        public Criteria andEditDateBetween(Date value1, Date value2) {
            addCriterion("edit_date between", value1, value2, "editDate");
            return this;
        }

        public Criteria andEditDateNotBetween(Date value1, Date value2) {
            addCriterion("edit_date not between", value1, value2, "editDate");
            return this;
        }

        public Criteria andUserIdIsNull() {
            addCriterion("user_id is null");
            return this;
        }

        public Criteria andUserIdIsNotNull() {
            addCriterion("user_id is not null");
            return this;
        }

        public Criteria andUserIdEqualTo(String value) {
            addCriterion("user_id =", value, "userId");
            return this;
        }

        public Criteria andUserIdNotEqualTo(String value) {
            addCriterion("user_id <>", value, "userId");
            return this;
        }

        public Criteria andUserIdGreaterThan(String value) {
            addCriterion("user_id >", value, "userId");
            return this;
        }

        public Criteria andUserIdGreaterThanOrEqualTo(String value) {
            addCriterion("user_id >=", value, "userId");
            return this;
        }

        public Criteria andUserIdLessThan(String value) {
            addCriterion("user_id <", value, "userId");
            return this;
        }

        public Criteria andUserIdLessThanOrEqualTo(String value) {
            addCriterion("user_id <=", value, "userId");
            return this;
        }

        public Criteria andUserIdLike(String value) {
            addCriterion("user_id like", value, "userId");
            return this;
        }

        public Criteria andUserIdNotLike(String value) {
            addCriterion("user_id not like", value, "userId");
            return this;
        }

        public Criteria andUserIdIn(List values) {
            addCriterion("user_id in", values, "userId");
            return this;
        }

        public Criteria andUserIdNotIn(List values) {
            addCriterion("user_id not in", values, "userId");
            return this;
        }

        public Criteria andUserIdBetween(String value1, String value2) {
            addCriterion("user_id between", value1, value2, "userId");
            return this;
        }

        public Criteria andUserIdNotBetween(String value1, String value2) {
            addCriterion("user_id not between", value1, value2, "userId");
            return this;
        }

        public Criteria andUserNameIsNull() {
            addCriterion("user_name is null");
            return this;
        }

        public Criteria andUserNameIsNotNull() {
            addCriterion("user_name is not null");
            return this;
        }

        public Criteria andUserNameEqualTo(String value) {
            addCriterion("user_name =", value, "userName");
            return this;
        }

        public Criteria andUserNameNotEqualTo(String value) {
            addCriterion("user_name <>", value, "userName");
            return this;
        }

        public Criteria andUserNameGreaterThan(String value) {
            addCriterion("user_name >", value, "userName");
            return this;
        }

        public Criteria andUserNameGreaterThanOrEqualTo(String value) {
            addCriterion("user_name >=", value, "userName");
            return this;
        }

        public Criteria andUserNameLessThan(String value) {
            addCriterion("user_name <", value, "userName");
            return this;
        }

        public Criteria andUserNameLessThanOrEqualTo(String value) {
            addCriterion("user_name <=", value, "userName");
            return this;
        }

        public Criteria andUserNameLike(String value) {
            addCriterion("user_name like", value, "userName");
            return this;
        }

        public Criteria andUserNameNotLike(String value) {
            addCriterion("user_name not like", value, "userName");
            return this;
        }

        public Criteria andUserNameIn(List values) {
            addCriterion("user_name in", values, "userName");
            return this;
        }

        public Criteria andUserNameNotIn(List values) {
            addCriterion("user_name not in", values, "userName");
            return this;
        }

        public Criteria andUserNameBetween(String value1, String value2) {
            addCriterion("user_name between", value1, value2, "userName");
            return this;
        }

        public Criteria andUserNameNotBetween(String value1, String value2) {
            addCriterion("user_name not between", value1, value2, "userName");
            return this;
        }

        public Criteria andContractTypeIsNull() {
            addCriterion("contract_type is null");
            return this;
        }

        public Criteria andContractTypeIsNotNull() {
            addCriterion("contract_type is not null");
            return this;
        }

        public Criteria andContractTypeEqualTo(Integer value) {
            addCriterion("contract_type =", value, "contractType");
            return this;
        }

        public Criteria andContractTypeNotEqualTo(Integer value) {
            addCriterion("contract_type <>", value, "contractType");
            return this;
        }

        public Criteria andContractTypeGreaterThan(Integer value) {
            addCriterion("contract_type >", value, "contractType");
            return this;
        }

        public Criteria andContractTypeGreaterThanOrEqualTo(Integer value) {
            addCriterion("contract_type >=", value, "contractType");
            return this;
        }

        public Criteria andContractTypeLessThan(Integer value) {
            addCriterion("contract_type <", value, "contractType");
            return this;
        }

        public Criteria andContractTypeLessThanOrEqualTo(Integer value) {
            addCriterion("contract_type <=", value, "contractType");
            return this;
        }

        public Criteria andContractTypeIn(List values) {
            addCriterion("contract_type in", values, "contractType");
            return this;
        }

        public Criteria andContractTypeNotIn(List values) {
            addCriterion("contract_type not in", values, "contractType");
            return this;
        }

        public Criteria andContractTypeBetween(Integer value1, Integer value2) {
            addCriterion("contract_type between", value1, value2, "contractType");
            return this;
        }

        public Criteria andContractTypeNotBetween(Integer value1, Integer value2) {
            addCriterion("contract_type not between", value1, value2, "contractType");
            return this;
        }

        public Criteria andCustomerFaxIsNull() {
            addCriterion("customer_fax is null");
            return this;
        }

        public Criteria andCustomerFaxIsNotNull() {
            addCriterion("customer_fax is not null");
            return this;
        }

        public Criteria andCustomerFaxEqualTo(String value) {
            addCriterion("customer_fax =", value, "customerFax");
            return this;
        }

        public Criteria andCustomerFaxNotEqualTo(String value) {
            addCriterion("customer_fax <>", value, "customerFax");
            return this;
        }

        public Criteria andCustomerFaxGreaterThan(String value) {
            addCriterion("customer_fax >", value, "customerFax");
            return this;
        }

        public Criteria andCustomerFaxGreaterThanOrEqualTo(String value) {
            addCriterion("customer_fax >=", value, "customerFax");
            return this;
        }

        public Criteria andCustomerFaxLessThan(String value) {
            addCriterion("customer_fax <", value, "customerFax");
            return this;
        }

        public Criteria andCustomerFaxLessThanOrEqualTo(String value) {
            addCriterion("customer_fax <=", value, "customerFax");
            return this;
        }

        public Criteria andCustomerFaxLike(String value) {
            addCriterion("customer_fax like", value, "customerFax");
            return this;
        }

        public Criteria andCustomerFaxNotLike(String value) {
            addCriterion("customer_fax not like", value, "customerFax");
            return this;
        }

        public Criteria andCustomerFaxIn(List values) {
            addCriterion("customer_fax in", values, "customerFax");
            return this;
        }

        public Criteria andCustomerFaxNotIn(List values) {
            addCriterion("customer_fax not in", values, "customerFax");
            return this;
        }

        public Criteria andCustomerFaxBetween(String value1, String value2) {
            addCriterion("customer_fax between", value1, value2, "customerFax");
            return this;
        }

        public Criteria andCustomerFaxNotBetween(String value1, String value2) {
            addCriterion("customer_fax not between", value1, value2, "customerFax");
            return this;
        }

        public Criteria andCustomerPhoneIsNull() {
            addCriterion("customer_phone is null");
            return this;
        }

        public Criteria andCustomerPhoneIsNotNull() {
            addCriterion("customer_phone is not null");
            return this;
        }

        public Criteria andCustomerPhoneEqualTo(String value) {
            addCriterion("customer_phone =", value, "customerPhone");
            return this;
        }

        public Criteria andCustomerPhoneNotEqualTo(String value) {
            addCriterion("customer_phone <>", value, "customerPhone");
            return this;
        }

        public Criteria andCustomerPhoneGreaterThan(String value) {
            addCriterion("customer_phone >", value, "customerPhone");
            return this;
        }

        public Criteria andCustomerPhoneGreaterThanOrEqualTo(String value) {
            addCriterion("customer_phone >=", value, "customerPhone");
            return this;
        }

        public Criteria andCustomerPhoneLessThan(String value) {
            addCriterion("customer_phone <", value, "customerPhone");
            return this;
        }

        public Criteria andCustomerPhoneLessThanOrEqualTo(String value) {
            addCriterion("customer_phone <=", value, "customerPhone");
            return this;
        }

        public Criteria andCustomerPhoneLike(String value) {
            addCriterion("customer_phone like", value, "customerPhone");
            return this;
        }

        public Criteria andCustomerPhoneNotLike(String value) {
            addCriterion("customer_phone not like", value, "customerPhone");
            return this;
        }

        public Criteria andCustomerPhoneIn(List values) {
            addCriterion("customer_phone in", values, "customerPhone");
            return this;
        }

        public Criteria andCustomerPhoneNotIn(List values) {
            addCriterion("customer_phone not in", values, "customerPhone");
            return this;
        }

        public Criteria andCustomerPhoneBetween(String value1, String value2) {
            addCriterion("customer_phone between", value1, value2, "customerPhone");
            return this;
        }

        public Criteria andCustomerPhoneNotBetween(String value1, String value2) {
            addCriterion("customer_phone not between", value1, value2, "customerPhone");
            return this;
        }

        public Criteria andOwnContactPersonIsNull() {
            addCriterion("own_contact_person is null");
            return this;
        }

        public Criteria andOwnContactPersonIsNotNull() {
            addCriterion("own_contact_person is not null");
            return this;
        }

        public Criteria andOwnContactPersonEqualTo(String value) {
            addCriterion("own_contact_person =", value, "ownContactPerson");
            return this;
        }

        public Criteria andOwnContactPersonNotEqualTo(String value) {
            addCriterion("own_contact_person <>", value, "ownContactPerson");
            return this;
        }

        public Criteria andOwnContactPersonGreaterThan(String value) {
            addCriterion("own_contact_person >", value, "ownContactPerson");
            return this;
        }

        public Criteria andOwnContactPersonGreaterThanOrEqualTo(String value) {
            addCriterion("own_contact_person >=", value, "ownContactPerson");
            return this;
        }

        public Criteria andOwnContactPersonLessThan(String value) {
            addCriterion("own_contact_person <", value, "ownContactPerson");
            return this;
        }

        public Criteria andOwnContactPersonLessThanOrEqualTo(String value) {
            addCriterion("own_contact_person <=", value, "ownContactPerson");
            return this;
        }

        public Criteria andOwnContactPersonLike(String value) {
            addCriterion("own_contact_person like", value, "ownContactPerson");
            return this;
        }

        public Criteria andOwnContactPersonNotLike(String value) {
            addCriterion("own_contact_person not like", value, "ownContactPerson");
            return this;
        }

        public Criteria andOwnContactPersonIn(List values) {
            addCriterion("own_contact_person in", values, "ownContactPerson");
            return this;
        }

        public Criteria andOwnContactPersonNotIn(List values) {
            addCriterion("own_contact_person not in", values, "ownContactPerson");
            return this;
        }

        public Criteria andOwnContactPersonBetween(String value1, String value2) {
            addCriterion("own_contact_person between", value1, value2, "ownContactPerson");
            return this;
        }

        public Criteria andOwnContactPersonNotBetween(String value1, String value2) {
            addCriterion("own_contact_person not between", value1, value2, "ownContactPerson");
            return this;
        }

        public Criteria andCusContactPersonIsNull() {
            addCriterion("cus_contact_person is null");
            return this;
        }

        public Criteria andCusContactPersonIsNotNull() {
            addCriterion("cus_contact_person is not null");
            return this;
        }

        public Criteria andCusContactPersonEqualTo(String value) {
            addCriterion("cus_contact_person =", value, "cusContactPerson");
            return this;
        }

        public Criteria andCusContactPersonNotEqualTo(String value) {
            addCriterion("cus_contact_person <>", value, "cusContactPerson");
            return this;
        }

        public Criteria andCusContactPersonGreaterThan(String value) {
            addCriterion("cus_contact_person >", value, "cusContactPerson");
            return this;
        }

        public Criteria andCusContactPersonGreaterThanOrEqualTo(String value) {
            addCriterion("cus_contact_person >=", value, "cusContactPerson");
            return this;
        }

        public Criteria andCusContactPersonLessThan(String value) {
            addCriterion("cus_contact_person <", value, "cusContactPerson");
            return this;
        }

        public Criteria andCusContactPersonLessThanOrEqualTo(String value) {
            addCriterion("cus_contact_person <=", value, "cusContactPerson");
            return this;
        }

        public Criteria andCusContactPersonLike(String value) {
            addCriterion("cus_contact_person like", value, "cusContactPerson");
            return this;
        }

        public Criteria andCusContactPersonNotLike(String value) {
            addCriterion("cus_contact_person not like", value, "cusContactPerson");
            return this;
        }

        public Criteria andCusContactPersonIn(List values) {
            addCriterion("cus_contact_person in", values, "cusContactPerson");
            return this;
        }

        public Criteria andCusContactPersonNotIn(List values) {
            addCriterion("cus_contact_person not in", values, "cusContactPerson");
            return this;
        }

        public Criteria andCusContactPersonBetween(String value1, String value2) {
            addCriterion("cus_contact_person between", value1, value2, "cusContactPerson");
            return this;
        }

        public Criteria andCusContactPersonNotBetween(String value1, String value2) {
            addCriterion("cus_contact_person not between", value1, value2, "cusContactPerson");
            return this;
        }

        public Criteria andSellerIdIsNull() {
            addCriterion("seller_id is null");
            return this;
        }

        public Criteria andSellerIdIsNotNull() {
            addCriterion("seller_id is not null");
            return this;
        }

        public Criteria andSellerIdEqualTo(String value) {
            addCriterion("seller_id =", value, "sellerId");
            return this;
        }

        public Criteria andSellerIdNotEqualTo(String value) {
            addCriterion("seller_id <>", value, "sellerId");
            return this;
        }

        public Criteria andSellerIdGreaterThan(String value) {
            addCriterion("seller_id >", value, "sellerId");
            return this;
        }

        public Criteria andSellerIdGreaterThanOrEqualTo(String value) {
            addCriterion("seller_id >=", value, "sellerId");
            return this;
        }

        public Criteria andSellerIdLessThan(String value) {
            addCriterion("seller_id <", value, "sellerId");
            return this;
        }

        public Criteria andSellerIdLessThanOrEqualTo(String value) {
            addCriterion("seller_id <=", value, "sellerId");
            return this;
        }

        public Criteria andSellerIdLike(String value) {
            addCriterion("seller_id like", value, "sellerId");
            return this;
        }

        public Criteria andSellerIdNotLike(String value) {
            addCriterion("seller_id not like", value, "sellerId");
            return this;
        }

        public Criteria andSellerIdIn(List values) {
            addCriterion("seller_id in", values, "sellerId");
            return this;
        }

        public Criteria andSellerIdNotIn(List values) {
            addCriterion("seller_id not in", values, "sellerId");
            return this;
        }

        public Criteria andSellerIdBetween(String value1, String value2) {
            addCriterion("seller_id between", value1, value2, "sellerId");
            return this;
        }

        public Criteria andSellerIdNotBetween(String value1, String value2) {
            addCriterion("seller_id not between", value1, value2, "sellerId");
            return this;
        }
    }
}