package com.tl.resource.dao.pojo;

import java.math.BigDecimal;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

public class TReserveInforExample {

	/**
	 * This field was generated by Apache iBATIS ibator. This field corresponds to the database table t_reserve_infor
	 * @ibatorgenerated  Tue Nov 17 15:25:05 CST 2009
	 */
	protected String orderByClause;
	/**
	 * This field was generated by Apache iBATIS ibator. This field corresponds to the database table t_reserve_infor
	 * @ibatorgenerated  Tue Nov 17 15:25:05 CST 2009
	 */
	protected List oredCriteria;

	protected Integer startIndex;
	
	protected Integer pageSize;
	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table t_reserve_infor
	 * @ibatorgenerated  Tue Nov 17 15:25:05 CST 2009
	 */
	public TReserveInforExample() {
		oredCriteria = new ArrayList();
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table t_reserve_infor
	 * @ibatorgenerated  Tue Nov 17 15:25:05 CST 2009
	 */
	protected TReserveInforExample(TReserveInforExample example) {
		this.orderByClause = example.orderByClause;
		this.oredCriteria = example.oredCriteria;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table t_reserve_infor
	 * @ibatorgenerated  Tue Nov 17 15:25:05 CST 2009
	 */
	public void setOrderByClause(String orderByClause) {
		this.orderByClause = orderByClause;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table t_reserve_infor
	 * @ibatorgenerated  Tue Nov 17 15:25:05 CST 2009
	 */
	public String getOrderByClause() {
		return orderByClause;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table t_reserve_infor
	 * @ibatorgenerated  Tue Nov 17 15:25:05 CST 2009
	 */
	public List getOredCriteria() {
		return oredCriteria;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table t_reserve_infor
	 * @ibatorgenerated  Tue Nov 17 15:25:05 CST 2009
	 */
	public void or(Criteria criteria) {
		oredCriteria.add(criteria);
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table t_reserve_infor
	 * @ibatorgenerated  Tue Nov 17 15:25:05 CST 2009
	 */
	public Criteria createCriteria() {
		Criteria criteria = createCriteriaInternal();
		if (oredCriteria.size() == 0) {
			oredCriteria.add(criteria);
		}
		return criteria;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table t_reserve_infor
	 * @ibatorgenerated  Tue Nov 17 15:25:05 CST 2009
	 */
	protected Criteria createCriteriaInternal() {
		Criteria criteria = new Criteria();
		return criteria;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table t_reserve_infor
	 * @ibatorgenerated  Tue Nov 17 15:25:05 CST 2009
	 */
	public void clear() {
		oredCriteria.clear();
	}

	/**
	 * This class was generated by Apache iBATIS ibator. This class corresponds to the database table t_reserve_infor
	 * @ibatorgenerated  Tue Nov 17 15:25:05 CST 2009
	 */
	public static class Criteria {
		protected List criteriaWithoutValue;
		protected List criteriaWithSingleValue;
		protected List criteriaWithListValue;
		protected List criteriaWithBetweenValue;

		protected Criteria() {
			super();
			criteriaWithoutValue = new ArrayList();
			criteriaWithSingleValue = new ArrayList();
			criteriaWithListValue = new ArrayList();
			criteriaWithBetweenValue = new ArrayList();
		}

		public boolean isValid() {
			return criteriaWithoutValue.size() > 0
					|| criteriaWithSingleValue.size() > 0
					|| criteriaWithListValue.size() > 0
					|| criteriaWithBetweenValue.size() > 0;
		}

		public List getCriteriaWithoutValue() {
			return criteriaWithoutValue;
		}

		public List getCriteriaWithSingleValue() {
			return criteriaWithSingleValue;
		}

		public List getCriteriaWithListValue() {
			return criteriaWithListValue;
		}

		public List getCriteriaWithBetweenValue() {
			return criteriaWithBetweenValue;
		}

		protected void addCriterion(String condition) {
			if (condition == null) {
				throw new RuntimeException("Value for condition cannot be null");
			}
			criteriaWithoutValue.add(condition);
		}

		protected void addCriterion(String condition, Object value,
				String property) {
			if (value == null) {
				throw new RuntimeException("Value for " + property
						+ " cannot be null");
			}
			Map map = new HashMap();
			map.put("condition", condition);
			map.put("value", value);
			criteriaWithSingleValue.add(map);
		}

		protected void addCriterion(String condition, List values,
				String property) {
			if (values == null || values.size() == 0) {
				throw new RuntimeException("Value list for " + property
						+ " cannot be null or empty");
			}
			Map map = new HashMap();
			map.put("condition", condition);
			map.put("values", values);
			criteriaWithListValue.add(map);
		}

		protected void addCriterion(String condition, Object value1,
				Object value2, String property) {
			if (value1 == null || value2 == null) {
				throw new RuntimeException("Between values for " + property
						+ " cannot be null");
			}
			List list = new ArrayList();
			list.add(value1);
			list.add(value2);
			Map map = new HashMap();
			map.put("condition", condition);
			map.put("values", list);
			criteriaWithBetweenValue.add(map);
		}

		public Criteria andIdIsNull() {
			addCriterion("id is null");
			return this;
		}

		public Criteria andIdIsNotNull() {
			addCriterion("id is not null");
			return this;
		}

		public Criteria andIdEqualTo(String value) {
			addCriterion("id =", value, "id");
			return this;
		}

		public Criteria andIdNotEqualTo(String value) {
			addCriterion("id <>", value, "id");
			return this;
		}

		public Criteria andIdGreaterThan(String value) {
			addCriterion("id >", value, "id");
			return this;
		}

		public Criteria andIdGreaterThanOrEqualTo(String value) {
			addCriterion("id >=", value, "id");
			return this;
		}

		public Criteria andIdLessThan(String value) {
			addCriterion("id <", value, "id");
			return this;
		}

		public Criteria andIdLessThanOrEqualTo(String value) {
			addCriterion("id <=", value, "id");
			return this;
		}

		public Criteria andIdLike(String value) {
			addCriterion("id like", value, "id");
			return this;
		}

		public Criteria andIdNotLike(String value) {
			addCriterion("id not like", value, "id");
			return this;
		}

		public Criteria andIdIn(List values) {
			addCriterion("id in", values, "id");
			return this;
		}

		public Criteria andIdNotIn(List values) {
			addCriterion("id not in", values, "id");
			return this;
		}

		public Criteria andIdBetween(String value1, String value2) {
			addCriterion("id between", value1, value2, "id");
			return this;
		}

		public Criteria andIdNotBetween(String value1, String value2) {
			addCriterion("id not between", value1, value2, "id");
			return this;
		}

		public Criteria andProductCodeIsNull() {
			addCriterion("product_code is null");
			return this;
		}

		public Criteria andProductCodeIsNotNull() {
			addCriterion("product_code is not null");
			return this;
		}

		public Criteria andProductCodeEqualTo(String value) {
			addCriterion("product_code =", value, "productCode");
			return this;
		}

		public Criteria andProductCodeNotEqualTo(String value) {
			addCriterion("product_code <>", value, "productCode");
			return this;
		}

		public Criteria andProductCodeGreaterThan(String value) {
			addCriterion("product_code >", value, "productCode");
			return this;
		}

		public Criteria andProductCodeGreaterThanOrEqualTo(String value) {
			addCriterion("product_code >=", value, "productCode");
			return this;
		}

		public Criteria andProductCodeLessThan(String value) {
			addCriterion("product_code <", value, "productCode");
			return this;
		}

		public Criteria andProductCodeLessThanOrEqualTo(String value) {
			addCriterion("product_code <=", value, "productCode");
			return this;
		}

		public Criteria andProductCodeLike(String value) {
			addCriterion("product_code like", value, "productCode");
			return this;
		}

		public Criteria andProductCodeNotLike(String value) {
			addCriterion("product_code not like", value, "productCode");
			return this;
		}

		public Criteria andProductCodeIn(List values) {
			addCriterion("product_code in", values, "productCode");
			return this;
		}

		public Criteria andProductCodeNotIn(List values) {
			addCriterion("product_code not in", values, "productCode");
			return this;
		}

		public Criteria andProductCodeBetween(String value1, String value2) {
			addCriterion("product_code between", value1, value2, "productCode");
			return this;
		}

		public Criteria andProductCodeNotBetween(String value1, String value2) {
			addCriterion("product_code not between", value1, value2,
					"productCode");
			return this;
		}

		public Criteria andBrandCodeIsNull() {
			addCriterion("brand_code is null");
			return this;
		}

		public Criteria andBrandCodeIsNotNull() {
			addCriterion("brand_code is not null");
			return this;
		}

		public Criteria andBrandCodeEqualTo(String value) {
			addCriterion("brand_code =", value, "brandCode");
			return this;
		}

		public Criteria andBrandCodeNotEqualTo(String value) {
			addCriterion("brand_code <>", value, "brandCode");
			return this;
		}

		public Criteria andBrandCodeGreaterThan(String value) {
			addCriterion("brand_code >", value, "brandCode");
			return this;
		}

		public Criteria andBrandCodeGreaterThanOrEqualTo(String value) {
			addCriterion("brand_code >=", value, "brandCode");
			return this;
		}

		public Criteria andBrandCodeLessThan(String value) {
			addCriterion("brand_code <", value, "brandCode");
			return this;
		}

		public Criteria andBrandCodeLessThanOrEqualTo(String value) {
			addCriterion("brand_code <=", value, "brandCode");
			return this;
		}

		public Criteria andBrandCodeLike(String value) {
			addCriterion("brand_code like", value, "brandCode");
			return this;
		}

		public Criteria andBrandCodeNotLike(String value) {
			addCriterion("brand_code not like", value, "brandCode");
			return this;
		}

		public Criteria andBrandCodeIn(List values) {
			addCriterion("brand_code in", values, "brandCode");
			return this;
		}

		public Criteria andBrandCodeNotIn(List values) {
			addCriterion("brand_code not in", values, "brandCode");
			return this;
		}

		public Criteria andBrandCodeBetween(String value1, String value2) {
			addCriterion("brand_code between", value1, value2, "brandCode");
			return this;
		}

		public Criteria andBrandCodeNotBetween(String value1, String value2) {
			addCriterion("brand_code not between", value1, value2, "brandCode");
			return this;
		}

		public Criteria andToolsIdIsNull() {
			addCriterion("tools_id is null");
			return this;
		}

		public Criteria andToolsIdIsNotNull() {
			addCriterion("tools_id is not null");
			return this;
		}

		public Criteria andToolsIdEqualTo(String value) {
			addCriterion("tools_id =", value, "toolsId");
			return this;
		}

		public Criteria andToolsIdNotEqualTo(String value) {
			addCriterion("tools_id <>", value, "toolsId");
			return this;
		}

		public Criteria andToolsIdGreaterThan(String value) {
			addCriterion("tools_id >", value, "toolsId");
			return this;
		}

		public Criteria andToolsIdGreaterThanOrEqualTo(String value) {
			addCriterion("tools_id >=", value, "toolsId");
			return this;
		}

		public Criteria andToolsIdLessThan(String value) {
			addCriterion("tools_id <", value, "toolsId");
			return this;
		}

		public Criteria andToolsIdLessThanOrEqualTo(String value) {
			addCriterion("tools_id <=", value, "toolsId");
			return this;
		}

		public Criteria andToolsIdLike(String value) {
			addCriterion("tools_id like", value, "toolsId");
			return this;
		}

		public Criteria andToolsIdNotLike(String value) {
			addCriterion("tools_id not like", value, "toolsId");
			return this;
		}

		public Criteria andToolsIdIn(List values) {
			addCriterion("tools_id in", values, "toolsId");
			return this;
		}

		public Criteria andToolsIdNotIn(List values) {
			addCriterion("tools_id not in", values, "toolsId");
			return this;
		}

		public Criteria andToolsIdBetween(String value1, String value2) {
			addCriterion("tools_id between", value1, value2, "toolsId");
			return this;
		}

		public Criteria andToolsIdNotBetween(String value1, String value2) {
			addCriterion("tools_id not between", value1, value2, "toolsId");
			return this;
		}

		public Criteria andParentToolsIdIsNull() {
			addCriterion("parent_tools_id is null");
			return this;
		}

		public Criteria andParentToolsIdIsNotNull() {
			addCriterion("parent_tools_id is not null");
			return this;
		}

		public Criteria andParentToolsIdEqualTo(String value) {
			addCriterion("parent_tools_id =", value, "parentToolsId");
			return this;
		}

		public Criteria andParentToolsIdNotEqualTo(String value) {
			addCriterion("parent_tools_id <>", value, "parentToolsId");
			return this;
		}

		public Criteria andParentToolsIdGreaterThan(String value) {
			addCriterion("parent_tools_id >", value, "parentToolsId");
			return this;
		}

		public Criteria andParentToolsIdGreaterThanOrEqualTo(String value) {
			addCriterion("parent_tools_id >=", value, "parentToolsId");
			return this;
		}

		public Criteria andParentToolsIdLessThan(String value) {
			addCriterion("parent_tools_id <", value, "parentToolsId");
			return this;
		}

		public Criteria andParentToolsIdLessThanOrEqualTo(String value) {
			addCriterion("parent_tools_id <=", value, "parentToolsId");
			return this;
		}

		public Criteria andParentToolsIdLike(String value) {
			addCriterion("parent_tools_id like", value, "parentToolsId");
			return this;
		}

		public Criteria andParentToolsIdNotLike(String value) {
			addCriterion("parent_tools_id not like", value, "parentToolsId");
			return this;
		}

		public Criteria andParentToolsIdIn(List values) {
			addCriterion("parent_tools_id in", values, "parentToolsId");
			return this;
		}

		public Criteria andParentToolsIdNotIn(List values) {
			addCriterion("parent_tools_id not in", values, "parentToolsId");
			return this;
		}

		public Criteria andParentToolsIdBetween(String value1, String value2) {
			addCriterion("parent_tools_id between", value1, value2,
					"parentToolsId");
			return this;
		}

		public Criteria andParentToolsIdNotBetween(String value1, String value2) {
			addCriterion("parent_tools_id not between", value1, value2,
					"parentToolsId");
			return this;
		}

		public Criteria andLeafIsNull() {
			addCriterion("leaf is null");
			return this;
		}

		public Criteria andLeafIsNotNull() {
			addCriterion("leaf is not null");
			return this;
		}

		public Criteria andLeafEqualTo(Integer value) {
			addCriterion("leaf =", value, "leaf");
			return this;
		}

		public Criteria andLeafNotEqualTo(Integer value) {
			addCriterion("leaf <>", value, "leaf");
			return this;
		}

		public Criteria andLeafGreaterThan(Integer value) {
			addCriterion("leaf >", value, "leaf");
			return this;
		}

		public Criteria andLeafGreaterThanOrEqualTo(Integer value) {
			addCriterion("leaf >=", value, "leaf");
			return this;
		}

		public Criteria andLeafLessThan(Integer value) {
			addCriterion("leaf <", value, "leaf");
			return this;
		}

		public Criteria andLeafLessThanOrEqualTo(Integer value) {
			addCriterion("leaf <=", value, "leaf");
			return this;
		}

		public Criteria andLeafIn(List values) {
			addCriterion("leaf in", values, "leaf");
			return this;
		}

		public Criteria andLeafNotIn(List values) {
			addCriterion("leaf not in", values, "leaf");
			return this;
		}

		public Criteria andLeafBetween(Integer value1, Integer value2) {
			addCriterion("leaf between", value1, value2, "leaf");
			return this;
		}

		public Criteria andLeafNotBetween(Integer value1, Integer value2) {
			addCriterion("leaf not between", value1, value2, "leaf");
			return this;
		}

		public Criteria andProductNameIsNull() {
			addCriterion("product_name is null");
			return this;
		}

		public Criteria andProductNameIsNotNull() {
			addCriterion("product_name is not null");
			return this;
		}

		public Criteria andProductNameEqualTo(String value) {
			addCriterion("product_name =", value, "productName");
			return this;
		}

		public Criteria andProductNameNotEqualTo(String value) {
			addCriterion("product_name <>", value, "productName");
			return this;
		}

		public Criteria andProductNameGreaterThan(String value) {
			addCriterion("product_name >", value, "productName");
			return this;
		}

		public Criteria andProductNameGreaterThanOrEqualTo(String value) {
			addCriterion("product_name >=", value, "productName");
			return this;
		}

		public Criteria andProductNameLessThan(String value) {
			addCriterion("product_name <", value, "productName");
			return this;
		}

		public Criteria andProductNameLessThanOrEqualTo(String value) {
			addCriterion("product_name <=", value, "productName");
			return this;
		}

		public Criteria andProductNameLike(String value) {
			addCriterion("product_name like", value, "productName");
			return this;
		}

		public Criteria andProductNameNotLike(String value) {
			addCriterion("product_name not like", value, "productName");
			return this;
		}

		public Criteria andProductNameIn(List values) {
			addCriterion("product_name in", values, "productName");
			return this;
		}

		public Criteria andProductNameNotIn(List values) {
			addCriterion("product_name not in", values, "productName");
			return this;
		}

		public Criteria andProductNameBetween(String value1, String value2) {
			addCriterion("product_name between", value1, value2, "productName");
			return this;
		}

		public Criteria andProductNameNotBetween(String value1, String value2) {
			addCriterion("product_name not between", value1, value2,
					"productName");
			return this;
		}

		public Criteria andProductUnitIsNull() {
			addCriterion("product_unit is null");
			return this;
		}

		public Criteria andProductUnitIsNotNull() {
			addCriterion("product_unit is not null");
			return this;
		}

		public Criteria andProductUnitEqualTo(String value) {
			addCriterion("product_unit =", value, "productUnit");
			return this;
		}

		public Criteria andProductUnitNotEqualTo(String value) {
			addCriterion("product_unit <>", value, "productUnit");
			return this;
		}

		public Criteria andProductUnitGreaterThan(String value) {
			addCriterion("product_unit >", value, "productUnit");
			return this;
		}

		public Criteria andProductUnitGreaterThanOrEqualTo(String value) {
			addCriterion("product_unit >=", value, "productUnit");
			return this;
		}

		public Criteria andProductUnitLessThan(String value) {
			addCriterion("product_unit <", value, "productUnit");
			return this;
		}

		public Criteria andProductUnitLessThanOrEqualTo(String value) {
			addCriterion("product_unit <=", value, "productUnit");
			return this;
		}

		public Criteria andProductUnitLike(String value) {
			addCriterion("product_unit like", value, "productUnit");
			return this;
		}

		public Criteria andProductUnitNotLike(String value) {
			addCriterion("product_unit not like", value, "productUnit");
			return this;
		}

		public Criteria andProductUnitIn(List values) {
			addCriterion("product_unit in", values, "productUnit");
			return this;
		}

		public Criteria andProductUnitNotIn(List values) {
			addCriterion("product_unit not in", values, "productUnit");
			return this;
		}

		public Criteria andProductUnitBetween(String value1, String value2) {
			addCriterion("product_unit between", value1, value2, "productUnit");
			return this;
		}

		public Criteria andProductUnitNotBetween(String value1, String value2) {
			addCriterion("product_unit not between", value1, value2,
					"productUnit");
			return this;
		}

		public Criteria andReserveCodeIsNull() {
			addCriterion("reserve_code is null");
			return this;
		}

		public Criteria andReserveCodeIsNotNull() {
			addCriterion("reserve_code is not null");
			return this;
		}

		public Criteria andReserveCodeEqualTo(String value) {
			addCriterion("reserve_code =", value, "reserveCode");
			return this;
		}

		public Criteria andReserveCodeNotEqualTo(String value) {
			addCriterion("reserve_code <>", value, "reserveCode");
			return this;
		}

		public Criteria andReserveCodeGreaterThan(String value) {
			addCriterion("reserve_code >", value, "reserveCode");
			return this;
		}

		public Criteria andReserveCodeGreaterThanOrEqualTo(String value) {
			addCriterion("reserve_code >=", value, "reserveCode");
			return this;
		}

		public Criteria andReserveCodeLessThan(String value) {
			addCriterion("reserve_code <", value, "reserveCode");
			return this;
		}

		public Criteria andReserveCodeLessThanOrEqualTo(String value) {
			addCriterion("reserve_code <=", value, "reserveCode");
			return this;
		}

		public Criteria andReserveCodeLike(String value) {
			addCriterion("reserve_code like", value, "reserveCode");
			return this;
		}

		public Criteria andReserveCodeNotLike(String value) {
			addCriterion("reserve_code not like", value, "reserveCode");
			return this;
		}

		public Criteria andReserveCodeIn(List values) {
			addCriterion("reserve_code in", values, "reserveCode");
			return this;
		}

		public Criteria andReserveCodeNotIn(List values) {
			addCriterion("reserve_code not in", values, "reserveCode");
			return this;
		}

		public Criteria andReserveCodeBetween(String value1, String value2) {
			addCriterion("reserve_code between", value1, value2, "reserveCode");
			return this;
		}

		public Criteria andReserveCodeNotBetween(String value1, String value2) {
			addCriterion("reserve_code not between", value1, value2,
					"reserveCode");
			return this;
		}

		public Criteria andAmountIsNull() {
			addCriterion("amount is null");
			return this;
		}

		public Criteria andAmountIsNotNull() {
			addCriterion("amount is not null");
			return this;
		}

		public Criteria andAmountEqualTo(BigDecimal value) {
			addCriterion("amount =", value, "amount");
			return this;
		}

		public Criteria andAmountNotEqualTo(BigDecimal value) {
			addCriterion("amount <>", value, "amount");
			return this;
		}

		public Criteria andAmountGreaterThan(BigDecimal value) {
			addCriterion("amount >", value, "amount");
			return this;
		}

		public Criteria andAmountGreaterThanOrEqualTo(BigDecimal value) {
			addCriterion("amount >=", value, "amount");
			return this;
		}

		public Criteria andAmountLessThan(BigDecimal value) {
			addCriterion("amount <", value, "amount");
			return this;
		}

		public Criteria andAmountLessThanOrEqualTo(BigDecimal value) {
			addCriterion("amount <=", value, "amount");
			return this;
		}

		public Criteria andAmountIn(List values) {
			addCriterion("amount in", values, "amount");
			return this;
		}

		public Criteria andAmountNotIn(List values) {
			addCriterion("amount not in", values, "amount");
			return this;
		}

		public Criteria andAmountBetween(BigDecimal value1, BigDecimal value2) {
			addCriterion("amount between", value1, value2, "amount");
			return this;
		}

		public Criteria andAmountNotBetween(BigDecimal value1, BigDecimal value2) {
			addCriterion("amount not between", value1, value2, "amount");
			return this;
		}

		public Criteria andPriceIsNull() {
			addCriterion("price is null");
			return this;
		}

		public Criteria andPriceIsNotNull() {
			addCriterion("price is not null");
			return this;
		}

		public Criteria andPriceEqualTo(BigDecimal value) {
			addCriterion("price =", value, "price");
			return this;
		}

		public Criteria andPriceNotEqualTo(BigDecimal value) {
			addCriterion("price <>", value, "price");
			return this;
		}

		public Criteria andPriceGreaterThan(BigDecimal value) {
			addCriterion("price >", value, "price");
			return this;
		}

		public Criteria andPriceGreaterThanOrEqualTo(BigDecimal value) {
			addCriterion("price >=", value, "price");
			return this;
		}

		public Criteria andPriceLessThan(BigDecimal value) {
			addCriterion("price <", value, "price");
			return this;
		}

		public Criteria andPriceLessThanOrEqualTo(BigDecimal value) {
			addCriterion("price <=", value, "price");
			return this;
		}

		public Criteria andPriceIn(List values) {
			addCriterion("price in", values, "price");
			return this;
		}

		public Criteria andPriceNotIn(List values) {
			addCriterion("price not in", values, "price");
			return this;
		}

		public Criteria andPriceBetween(BigDecimal value1, BigDecimal value2) {
			addCriterion("price between", value1, value2, "price");
			return this;
		}

		public Criteria andPriceNotBetween(BigDecimal value1, BigDecimal value2) {
			addCriterion("price not between", value1, value2, "price");
			return this;
		}

		public Criteria andProductSortIsNull() {
			addCriterion("product_sort is null");
			return this;
		}

		public Criteria andProductSortIsNotNull() {
			addCriterion("product_sort is not null");
			return this;
		}

		public Criteria andProductSortEqualTo(String value) {
			addCriterion("product_sort =", value, "productSort");
			return this;
		}

		public Criteria andProductSortNotEqualTo(String value) {
			addCriterion("product_sort <>", value, "productSort");
			return this;
		}

		public Criteria andProductSortGreaterThan(String value) {
			addCriterion("product_sort >", value, "productSort");
			return this;
		}

		public Criteria andProductSortGreaterThanOrEqualTo(String value) {
			addCriterion("product_sort >=", value, "productSort");
			return this;
		}

		public Criteria andProductSortLessThan(String value) {
			addCriterion("product_sort <", value, "productSort");
			return this;
		}

		public Criteria andProductSortLessThanOrEqualTo(String value) {
			addCriterion("product_sort <=", value, "productSort");
			return this;
		}

		public Criteria andProductSortLike(String value) {
			addCriterion("product_sort like", value, "productSort");
			return this;
		}

		public Criteria andProductSortNotLike(String value) {
			addCriterion("product_sort not like", value, "productSort");
			return this;
		}

		public Criteria andProductSortIn(List values) {
			addCriterion("product_sort in", values, "productSort");
			return this;
		}

		public Criteria andProductSortNotIn(List values) {
			addCriterion("product_sort not in", values, "productSort");
			return this;
		}

		public Criteria andProductSortBetween(String value1, String value2) {
			addCriterion("product_sort between", value1, value2, "productSort");
			return this;
		}

		public Criteria andProductSortNotBetween(String value1, String value2) {
			addCriterion("product_sort not between", value1, value2,
					"productSort");
			return this;
		}

		public Criteria andCurrencyNameIsNull() {
			addCriterion("currency_name is null");
			return this;
		}

		public Criteria andCurrencyNameIsNotNull() {
			addCriterion("currency_name is not null");
			return this;
		}

		public Criteria andCurrencyNameEqualTo(String value) {
			addCriterion("currency_name =", value, "currencyName");
			return this;
		}

		public Criteria andCurrencyNameNotEqualTo(String value) {
			addCriterion("currency_name <>", value, "currencyName");
			return this;
		}

		public Criteria andCurrencyNameGreaterThan(String value) {
			addCriterion("currency_name >", value, "currencyName");
			return this;
		}

		public Criteria andCurrencyNameGreaterThanOrEqualTo(String value) {
			addCriterion("currency_name >=", value, "currencyName");
			return this;
		}

		public Criteria andCurrencyNameLessThan(String value) {
			addCriterion("currency_name <", value, "currencyName");
			return this;
		}

		public Criteria andCurrencyNameLessThanOrEqualTo(String value) {
			addCriterion("currency_name <=", value, "currencyName");
			return this;
		}

		public Criteria andCurrencyNameLike(String value) {
			addCriterion("currency_name like", value, "currencyName");
			return this;
		}

		public Criteria andCurrencyNameNotLike(String value) {
			addCriterion("currency_name not like", value, "currencyName");
			return this;
		}

		public Criteria andCurrencyNameIn(List values) {
			addCriterion("currency_name in", values, "currencyName");
			return this;
		}

		public Criteria andCurrencyNameNotIn(List values) {
			addCriterion("currency_name not in", values, "currencyName");
			return this;
		}

		public Criteria andCurrencyNameBetween(String value1, String value2) {
			addCriterion("currency_name between", value1, value2,
					"currencyName");
			return this;
		}

		public Criteria andCurrencyNameNotBetween(String value1, String value2) {
			addCriterion("currency_name not between", value1, value2,
					"currencyName");
			return this;
		}

		public Criteria andProductBrandIsNull() {
			addCriterion("product_brand is null");
			return this;
		}

		public Criteria andProductBrandIsNotNull() {
			addCriterion("product_brand is not null");
			return this;
		}

		public Criteria andProductBrandEqualTo(String value) {
			addCriterion("product_brand =", value, "productBrand");
			return this;
		}

		public Criteria andProductBrandNotEqualTo(String value) {
			addCriterion("product_brand <>", value, "productBrand");
			return this;
		}

		public Criteria andProductBrandGreaterThan(String value) {
			addCriterion("product_brand >", value, "productBrand");
			return this;
		}

		public Criteria andProductBrandGreaterThanOrEqualTo(String value) {
			addCriterion("product_brand >=", value, "productBrand");
			return this;
		}

		public Criteria andProductBrandLessThan(String value) {
			addCriterion("product_brand <", value, "productBrand");
			return this;
		}

		public Criteria andProductBrandLessThanOrEqualTo(String value) {
			addCriterion("product_brand <=", value, "productBrand");
			return this;
		}

		public Criteria andProductBrandLike(String value) {
			addCriterion("product_brand like", value, "productBrand");
			return this;
		}

		public Criteria andProductBrandNotLike(String value) {
			addCriterion("product_brand not like", value, "productBrand");
			return this;
		}

		public Criteria andProductBrandIn(List values) {
			addCriterion("product_brand in", values, "productBrand");
			return this;
		}

		public Criteria andProductBrandNotIn(List values) {
			addCriterion("product_brand not in", values, "productBrand");
			return this;
		}

		public Criteria andProductBrandBetween(String value1, String value2) {
			addCriterion("product_brand between", value1, value2,
					"productBrand");
			return this;
		}

		public Criteria andProductBrandNotBetween(String value1, String value2) {
			addCriterion("product_brand not between", value1, value2,
					"productBrand");
			return this;
		}

		public Criteria andProductSourceIsNull() {
			addCriterion("product_source is null");
			return this;
		}

		public Criteria andProductSourceIsNotNull() {
			addCriterion("product_source is not null");
			return this;
		}

		public Criteria andProductSourceEqualTo(String value) {
			addCriterion("product_source =", value, "productSource");
			return this;
		}

		public Criteria andProductSourceNotEqualTo(String value) {
			addCriterion("product_source <>", value, "productSource");
			return this;
		}

		public Criteria andProductSourceGreaterThan(String value) {
			addCriterion("product_source >", value, "productSource");
			return this;
		}

		public Criteria andProductSourceGreaterThanOrEqualTo(String value) {
			addCriterion("product_source >=", value, "productSource");
			return this;
		}

		public Criteria andProductSourceLessThan(String value) {
			addCriterion("product_source <", value, "productSource");
			return this;
		}

		public Criteria andProductSourceLessThanOrEqualTo(String value) {
			addCriterion("product_source <=", value, "productSource");
			return this;
		}

		public Criteria andProductSourceLike(String value) {
			addCriterion("product_source like", value, "productSource");
			return this;
		}

		public Criteria andProductSourceNotLike(String value) {
			addCriterion("product_source not like", value, "productSource");
			return this;
		}

		public Criteria andProductSourceIn(List values) {
			addCriterion("product_source in", values, "productSource");
			return this;
		}

		public Criteria andProductSourceNotIn(List values) {
			addCriterion("product_source not in", values, "productSource");
			return this;
		}

		public Criteria andProductSourceBetween(String value1, String value2) {
			addCriterion("product_source between", value1, value2,
					"productSource");
			return this;
		}

		public Criteria andProductSourceNotBetween(String value1, String value2) {
			addCriterion("product_source not between", value1, value2,
					"productSource");
			return this;
		}

		public Criteria andProductPositionIsNull() {
			addCriterion("product_position is null");
			return this;
		}

		public Criteria andProductPositionIsNotNull() {
			addCriterion("product_position is not null");
			return this;
		}

		public Criteria andProductPositionEqualTo(String value) {
			addCriterion("product_position =", value, "productPosition");
			return this;
		}

		public Criteria andProductPositionNotEqualTo(String value) {
			addCriterion("product_position <>", value, "productPosition");
			return this;
		}

		public Criteria andProductPositionGreaterThan(String value) {
			addCriterion("product_position >", value, "productPosition");
			return this;
		}

		public Criteria andProductPositionGreaterThanOrEqualTo(String value) {
			addCriterion("product_position >=", value, "productPosition");
			return this;
		}

		public Criteria andProductPositionLessThan(String value) {
			addCriterion("product_position <", value, "productPosition");
			return this;
		}

		public Criteria andProductPositionLessThanOrEqualTo(String value) {
			addCriterion("product_position <=", value, "productPosition");
			return this;
		}

		public Criteria andProductPositionLike(String value) {
			addCriterion("product_position like", value, "productPosition");
			return this;
		}

		public Criteria andProductPositionNotLike(String value) {
			addCriterion("product_position not like", value, "productPosition");
			return this;
		}

		public Criteria andProductPositionIn(List values) {
			addCriterion("product_position in", values, "productPosition");
			return this;
		}

		public Criteria andProductPositionNotIn(List values) {
			addCriterion("product_position not in", values, "productPosition");
			return this;
		}

		public Criteria andProductPositionBetween(String value1, String value2) {
			addCriterion("product_position between", value1, value2,
					"productPosition");
			return this;
		}

		public Criteria andProductPositionNotBetween(String value1,
				String value2) {
			addCriterion("product_position not between", value1, value2,
					"productPosition");
			return this;
		}

		public Criteria andSlaveFileIsNull() {
			addCriterion("slave_file is null");
			return this;
		}

		public Criteria andSlaveFileIsNotNull() {
			addCriterion("slave_file is not null");
			return this;
		}

		public Criteria andSlaveFileEqualTo(String value) {
			addCriterion("slave_file =", value, "slaveFile");
			return this;
		}

		public Criteria andSlaveFileNotEqualTo(String value) {
			addCriterion("slave_file <>", value, "slaveFile");
			return this;
		}

		public Criteria andSlaveFileGreaterThan(String value) {
			addCriterion("slave_file >", value, "slaveFile");
			return this;
		}

		public Criteria andSlaveFileGreaterThanOrEqualTo(String value) {
			addCriterion("slave_file >=", value, "slaveFile");
			return this;
		}

		public Criteria andSlaveFileLessThan(String value) {
			addCriterion("slave_file <", value, "slaveFile");
			return this;
		}

		public Criteria andSlaveFileLessThanOrEqualTo(String value) {
			addCriterion("slave_file <=", value, "slaveFile");
			return this;
		}

		public Criteria andSlaveFileLike(String value) {
			addCriterion("slave_file like", value, "slaveFile");
			return this;
		}

		public Criteria andSlaveFileNotLike(String value) {
			addCriterion("slave_file not like", value, "slaveFile");
			return this;
		}

		public Criteria andSlaveFileIn(List values) {
			addCriterion("slave_file in", values, "slaveFile");
			return this;
		}

		public Criteria andSlaveFileNotIn(List values) {
			addCriterion("slave_file not in", values, "slaveFile");
			return this;
		}

		public Criteria andSlaveFileBetween(String value1, String value2) {
			addCriterion("slave_file between", value1, value2, "slaveFile");
			return this;
		}

		public Criteria andSlaveFileNotBetween(String value1, String value2) {
			addCriterion("slave_file not between", value1, value2, "slaveFile");
			return this;
		}

		public Criteria andMemoIsNull() {
			addCriterion("memo is null");
			return this;
		}

		public Criteria andMemoIsNotNull() {
			addCriterion("memo is not null");
			return this;
		}

		public Criteria andMemoEqualTo(String value) {
			addCriterion("memo =", value, "memo");
			return this;
		}

		public Criteria andMemoNotEqualTo(String value) {
			addCriterion("memo <>", value, "memo");
			return this;
		}

		public Criteria andMemoGreaterThan(String value) {
			addCriterion("memo >", value, "memo");
			return this;
		}

		public Criteria andMemoGreaterThanOrEqualTo(String value) {
			addCriterion("memo >=", value, "memo");
			return this;
		}

		public Criteria andMemoLessThan(String value) {
			addCriterion("memo <", value, "memo");
			return this;
		}

		public Criteria andMemoLessThanOrEqualTo(String value) {
			addCriterion("memo <=", value, "memo");
			return this;
		}

		public Criteria andMemoLike(String value) {
			addCriterion("memo like", value, "memo");
			return this;
		}

		public Criteria andMemoNotLike(String value) {
			addCriterion("memo not like", value, "memo");
			return this;
		}

		public Criteria andMemoIn(List values) {
			addCriterion("memo in", values, "memo");
			return this;
		}

		public Criteria andMemoNotIn(List values) {
			addCriterion("memo not in", values, "memo");
			return this;
		}

		public Criteria andMemoBetween(String value1, String value2) {
			addCriterion("memo between", value1, value2, "memo");
			return this;
		}

		public Criteria andMemoNotBetween(String value1, String value2) {
			addCriterion("memo not between", value1, value2, "memo");
			return this;
		}
	}

	public Integer getStartIndex() {
		return startIndex;
	}

	public void setStartIndex(Integer startIndex) {
		this.startIndex = startIndex;
	}

	public Integer getPageSize() {
		return pageSize;
	}

	public void setPageSize(Integer pageSize) {
		this.pageSize = pageSize;
	}
	
}