package com.tl.resource.dao.pojo;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

public class TSuppliersInforExample {

	/**
	 * This field was generated by Apache iBATIS ibator. This field corresponds to the database table t_suppliers_infor
	 * @ibatorgenerated  Wed Oct 14 14:13:27 CST 2009
	 */
	protected String orderByClause;
	/**
	 * This field was generated by Apache iBATIS ibator. This field corresponds to the database table t_suppliers_infor
	 * @ibatorgenerated  Wed Oct 14 14:13:27 CST 2009
	 */
	protected List oredCriteria;

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table t_suppliers_infor
	 * @ibatorgenerated  Wed Oct 14 14:13:27 CST 2009
	 */
	public TSuppliersInforExample() {
		oredCriteria = new ArrayList();
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table t_suppliers_infor
	 * @ibatorgenerated  Wed Oct 14 14:13:27 CST 2009
	 */
	protected TSuppliersInforExample(TSuppliersInforExample example) {
		this.orderByClause = example.orderByClause;
		this.oredCriteria = example.oredCriteria;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table t_suppliers_infor
	 * @ibatorgenerated  Wed Oct 14 14:13:27 CST 2009
	 */
	public void setOrderByClause(String orderByClause) {
		this.orderByClause = orderByClause;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table t_suppliers_infor
	 * @ibatorgenerated  Wed Oct 14 14:13:27 CST 2009
	 */
	public String getOrderByClause() {
		return orderByClause;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table t_suppliers_infor
	 * @ibatorgenerated  Wed Oct 14 14:13:27 CST 2009
	 */
	public List getOredCriteria() {
		return oredCriteria;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table t_suppliers_infor
	 * @ibatorgenerated  Wed Oct 14 14:13:27 CST 2009
	 */
	public void or(Criteria criteria) {
		oredCriteria.add(criteria);
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table t_suppliers_infor
	 * @ibatorgenerated  Wed Oct 14 14:13:27 CST 2009
	 */
	public Criteria createCriteria() {
		Criteria criteria = createCriteriaInternal();
		if (oredCriteria.size() == 0) {
			oredCriteria.add(criteria);
		}
		return criteria;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table t_suppliers_infor
	 * @ibatorgenerated  Wed Oct 14 14:13:27 CST 2009
	 */
	protected Criteria createCriteriaInternal() {
		Criteria criteria = new Criteria();
		return criteria;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table t_suppliers_infor
	 * @ibatorgenerated  Wed Oct 14 14:13:27 CST 2009
	 */
	public void clear() {
		oredCriteria.clear();
	}

	/**
	 * This class was generated by Apache iBATIS ibator. This class corresponds to the database table t_suppliers_infor
	 * @ibatorgenerated  Wed Oct 14 14:13:27 CST 2009
	 */
	public static class Criteria {
		protected List criteriaWithoutValue;
		protected List criteriaWithSingleValue;
		protected List criteriaWithListValue;
		protected List criteriaWithBetweenValue;

		protected Criteria() {
			super();
			criteriaWithoutValue = new ArrayList();
			criteriaWithSingleValue = new ArrayList();
			criteriaWithListValue = new ArrayList();
			criteriaWithBetweenValue = new ArrayList();
		}

		public boolean isValid() {
			return criteriaWithoutValue.size() > 0
					|| criteriaWithSingleValue.size() > 0
					|| criteriaWithListValue.size() > 0
					|| criteriaWithBetweenValue.size() > 0;
		}

		public List getCriteriaWithoutValue() {
			return criteriaWithoutValue;
		}

		public List getCriteriaWithSingleValue() {
			return criteriaWithSingleValue;
		}

		public List getCriteriaWithListValue() {
			return criteriaWithListValue;
		}

		public List getCriteriaWithBetweenValue() {
			return criteriaWithBetweenValue;
		}

		protected void addCriterion(String condition) {
			if (condition == null) {
				throw new RuntimeException("Value for condition cannot be null");
			}
			criteriaWithoutValue.add(condition);
		}

		protected void addCriterion(String condition, Object value,
				String property) {
			if (value == null) {
				throw new RuntimeException("Value for " + property
						+ " cannot be null");
			}
			Map map = new HashMap();
			map.put("condition", condition);
			map.put("value", value);
			criteriaWithSingleValue.add(map);
		}

		protected void addCriterion(String condition, List values,
				String property) {
			if (values == null || values.size() == 0) {
				throw new RuntimeException("Value list for " + property
						+ " cannot be null or empty");
			}
			Map map = new HashMap();
			map.put("condition", condition);
			map.put("values", values);
			criteriaWithListValue.add(map);
		}

		protected void addCriterion(String condition, Object value1,
				Object value2, String property) {
			if (value1 == null || value2 == null) {
				throw new RuntimeException("Between values for " + property
						+ " cannot be null");
			}
			List list = new ArrayList();
			list.add(value1);
			list.add(value2);
			Map map = new HashMap();
			map.put("condition", condition);
			map.put("values", list);
			criteriaWithBetweenValue.add(map);
		}

		public Criteria andIdIsNull() {
			addCriterion("id is null");
			return this;
		}

		public Criteria andIdIsNotNull() {
			addCriterion("id is not null");
			return this;
		}

		public Criteria andIdEqualTo(String value) {
			addCriterion("id =", value, "id");
			return this;
		}

		public Criteria andIdNotEqualTo(String value) {
			addCriterion("id <>", value, "id");
			return this;
		}

		public Criteria andIdGreaterThan(String value) {
			addCriterion("id >", value, "id");
			return this;
		}

		public Criteria andIdGreaterThanOrEqualTo(String value) {
			addCriterion("id >=", value, "id");
			return this;
		}

		public Criteria andIdLessThan(String value) {
			addCriterion("id <", value, "id");
			return this;
		}

		public Criteria andIdLessThanOrEqualTo(String value) {
			addCriterion("id <=", value, "id");
			return this;
		}

		public Criteria andIdLike(String value) {
			addCriterion("id like", value, "id");
			return this;
		}

		public Criteria andIdNotLike(String value) {
			addCriterion("id not like", value, "id");
			return this;
		}

		public Criteria andIdIn(List values) {
			addCriterion("id in", values, "id");
			return this;
		}

		public Criteria andIdNotIn(List values) {
			addCriterion("id not in", values, "id");
			return this;
		}

		public Criteria andIdBetween(String value1, String value2) {
			addCriterion("id between", value1, value2, "id");
			return this;
		}

		public Criteria andIdNotBetween(String value1, String value2) {
			addCriterion("id not between", value1, value2, "id");
			return this;
		}

		public Criteria andSupplierCodeIsNull() {
			addCriterion("supplier_code is null");
			return this;
		}

		public Criteria andSupplierCodeIsNotNull() {
			addCriterion("supplier_code is not null");
			return this;
		}

		public Criteria andSupplierCodeEqualTo(String value) {
			addCriterion("supplier_code =", value, "supplierCode");
			return this;
		}

		public Criteria andSupplierCodeNotEqualTo(String value) {
			addCriterion("supplier_code <>", value, "supplierCode");
			return this;
		}

		public Criteria andSupplierCodeGreaterThan(String value) {
			addCriterion("supplier_code >", value, "supplierCode");
			return this;
		}

		public Criteria andSupplierCodeGreaterThanOrEqualTo(String value) {
			addCriterion("supplier_code >=", value, "supplierCode");
			return this;
		}

		public Criteria andSupplierCodeLessThan(String value) {
			addCriterion("supplier_code <", value, "supplierCode");
			return this;
		}

		public Criteria andSupplierCodeLessThanOrEqualTo(String value) {
			addCriterion("supplier_code <=", value, "supplierCode");
			return this;
		}

		public Criteria andSupplierCodeLike(String value) {
			addCriterion("supplier_code like", value, "supplierCode");
			return this;
		}

		public Criteria andSupplierCodeNotLike(String value) {
			addCriterion("supplier_code not like", value, "supplierCode");
			return this;
		}

		public Criteria andSupplierCodeIn(List values) {
			addCriterion("supplier_code in", values, "supplierCode");
			return this;
		}

		public Criteria andSupplierCodeNotIn(List values) {
			addCriterion("supplier_code not in", values, "supplierCode");
			return this;
		}

		public Criteria andSupplierCodeBetween(String value1, String value2) {
			addCriterion("supplier_code between", value1, value2,
					"supplierCode");
			return this;
		}

		public Criteria andSupplierCodeNotBetween(String value1, String value2) {
			addCriterion("supplier_code not between", value1, value2,
					"supplierCode");
			return this;
		}

		public Criteria andSupplierNameIsNull() {
			addCriterion("supplier_name is null");
			return this;
		}

		public Criteria andSupplierNameIsNotNull() {
			addCriterion("supplier_name is not null");
			return this;
		}

		public Criteria andSupplierNameEqualTo(String value) {
			addCriterion("supplier_name =", value, "supplierName");
			return this;
		}

		public Criteria andSupplierNameNotEqualTo(String value) {
			addCriterion("supplier_name <>", value, "supplierName");
			return this;
		}

		public Criteria andSupplierNameGreaterThan(String value) {
			addCriterion("supplier_name >", value, "supplierName");
			return this;
		}

		public Criteria andSupplierNameGreaterThanOrEqualTo(String value) {
			addCriterion("supplier_name >=", value, "supplierName");
			return this;
		}

		public Criteria andSupplierNameLessThan(String value) {
			addCriterion("supplier_name <", value, "supplierName");
			return this;
		}

		public Criteria andSupplierNameLessThanOrEqualTo(String value) {
			addCriterion("supplier_name <=", value, "supplierName");
			return this;
		}

		public Criteria andSupplierNameLike(String value) {
			addCriterion("supplier_name like", value, "supplierName");
			return this;
		}

		public Criteria andSupplierNameNotLike(String value) {
			addCriterion("supplier_name not like", value, "supplierName");
			return this;
		}

		public Criteria andSupplierNameIn(List values) {
			addCriterion("supplier_name in", values, "supplierName");
			return this;
		}

		public Criteria andSupplierNameNotIn(List values) {
			addCriterion("supplier_name not in", values, "supplierName");
			return this;
		}

		public Criteria andSupplierNameBetween(String value1, String value2) {
			addCriterion("supplier_name between", value1, value2,
					"supplierName");
			return this;
		}

		public Criteria andSupplierNameNotBetween(String value1, String value2) {
			addCriterion("supplier_name not between", value1, value2,
					"supplierName");
			return this;
		}

		public Criteria andSupplierShortNameIsNull() {
			addCriterion("supplier_short_name is null");
			return this;
		}

		public Criteria andSupplierShortNameIsNotNull() {
			addCriterion("supplier_short_name is not null");
			return this;
		}

		public Criteria andSupplierShortNameEqualTo(String value) {
			addCriterion("supplier_short_name =", value, "supplierShortName");
			return this;
		}

		public Criteria andSupplierShortNameNotEqualTo(String value) {
			addCriterion("supplier_short_name <>", value, "supplierShortName");
			return this;
		}

		public Criteria andSupplierShortNameGreaterThan(String value) {
			addCriterion("supplier_short_name >", value, "supplierShortName");
			return this;
		}

		public Criteria andSupplierShortNameGreaterThanOrEqualTo(String value) {
			addCriterion("supplier_short_name >=", value, "supplierShortName");
			return this;
		}

		public Criteria andSupplierShortNameLessThan(String value) {
			addCriterion("supplier_short_name <", value, "supplierShortName");
			return this;
		}

		public Criteria andSupplierShortNameLessThanOrEqualTo(String value) {
			addCriterion("supplier_short_name <=", value, "supplierShortName");
			return this;
		}

		public Criteria andSupplierShortNameLike(String value) {
			addCriterion("supplier_short_name like", value, "supplierShortName");
			return this;
		}

		public Criteria andSupplierShortNameNotLike(String value) {
			addCriterion("supplier_short_name not like", value,
					"supplierShortName");
			return this;
		}

		public Criteria andSupplierShortNameIn(List values) {
			addCriterion("supplier_short_name in", values, "supplierShortName");
			return this;
		}

		public Criteria andSupplierShortNameNotIn(List values) {
			addCriterion("supplier_short_name not in", values,
					"supplierShortName");
			return this;
		}

		public Criteria andSupplierShortNameBetween(String value1, String value2) {
			addCriterion("supplier_short_name between", value1, value2,
					"supplierShortName");
			return this;
		}

		public Criteria andSupplierShortNameNotBetween(String value1,
				String value2) {
			addCriterion("supplier_short_name not between", value1, value2,
					"supplierShortName");
			return this;
		}

		public Criteria andContactPersonFirstIsNull() {
			addCriterion("contact_person_first is null");
			return this;
		}

		public Criteria andContactPersonFirstIsNotNull() {
			addCriterion("contact_person_first is not null");
			return this;
		}

		public Criteria andContactPersonFirstEqualTo(String value) {
			addCriterion("contact_person_first =", value, "contactPersonFirst");
			return this;
		}

		public Criteria andContactPersonFirstNotEqualTo(String value) {
			addCriterion("contact_person_first <>", value, "contactPersonFirst");
			return this;
		}

		public Criteria andContactPersonFirstGreaterThan(String value) {
			addCriterion("contact_person_first >", value, "contactPersonFirst");
			return this;
		}

		public Criteria andContactPersonFirstGreaterThanOrEqualTo(String value) {
			addCriterion("contact_person_first >=", value, "contactPersonFirst");
			return this;
		}

		public Criteria andContactPersonFirstLessThan(String value) {
			addCriterion("contact_person_first <", value, "contactPersonFirst");
			return this;
		}

		public Criteria andContactPersonFirstLessThanOrEqualTo(String value) {
			addCriterion("contact_person_first <=", value, "contactPersonFirst");
			return this;
		}

		public Criteria andContactPersonFirstLike(String value) {
			addCriterion("contact_person_first like", value,
					"contactPersonFirst");
			return this;
		}

		public Criteria andContactPersonFirstNotLike(String value) {
			addCriterion("contact_person_first not like", value,
					"contactPersonFirst");
			return this;
		}

		public Criteria andContactPersonFirstIn(List values) {
			addCriterion("contact_person_first in", values,
					"contactPersonFirst");
			return this;
		}

		public Criteria andContactPersonFirstNotIn(List values) {
			addCriterion("contact_person_first not in", values,
					"contactPersonFirst");
			return this;
		}

		public Criteria andContactPersonFirstBetween(String value1,
				String value2) {
			addCriterion("contact_person_first between", value1, value2,
					"contactPersonFirst");
			return this;
		}

		public Criteria andContactPersonFirstNotBetween(String value1,
				String value2) {
			addCriterion("contact_person_first not between", value1, value2,
					"contactPersonFirst");
			return this;
		}

		public Criteria andPhoneFirstIsNull() {
			addCriterion("phone_first is null");
			return this;
		}

		public Criteria andPhoneFirstIsNotNull() {
			addCriterion("phone_first is not null");
			return this;
		}

		public Criteria andPhoneFirstEqualTo(String value) {
			addCriterion("phone_first =", value, "phoneFirst");
			return this;
		}

		public Criteria andPhoneFirstNotEqualTo(String value) {
			addCriterion("phone_first <>", value, "phoneFirst");
			return this;
		}

		public Criteria andPhoneFirstGreaterThan(String value) {
			addCriterion("phone_first >", value, "phoneFirst");
			return this;
		}

		public Criteria andPhoneFirstGreaterThanOrEqualTo(String value) {
			addCriterion("phone_first >=", value, "phoneFirst");
			return this;
		}

		public Criteria andPhoneFirstLessThan(String value) {
			addCriterion("phone_first <", value, "phoneFirst");
			return this;
		}

		public Criteria andPhoneFirstLessThanOrEqualTo(String value) {
			addCriterion("phone_first <=", value, "phoneFirst");
			return this;
		}

		public Criteria andPhoneFirstLike(String value) {
			addCriterion("phone_first like", value, "phoneFirst");
			return this;
		}

		public Criteria andPhoneFirstNotLike(String value) {
			addCriterion("phone_first not like", value, "phoneFirst");
			return this;
		}

		public Criteria andPhoneFirstIn(List values) {
			addCriterion("phone_first in", values, "phoneFirst");
			return this;
		}

		public Criteria andPhoneFirstNotIn(List values) {
			addCriterion("phone_first not in", values, "phoneFirst");
			return this;
		}

		public Criteria andPhoneFirstBetween(String value1, String value2) {
			addCriterion("phone_first between", value1, value2, "phoneFirst");
			return this;
		}

		public Criteria andPhoneFirstNotBetween(String value1, String value2) {
			addCriterion("phone_first not between", value1, value2,
					"phoneFirst");
			return this;
		}

		public Criteria andFaxFirstIsNull() {
			addCriterion("fax_first is null");
			return this;
		}

		public Criteria andFaxFirstIsNotNull() {
			addCriterion("fax_first is not null");
			return this;
		}

		public Criteria andFaxFirstEqualTo(String value) {
			addCriterion("fax_first =", value, "faxFirst");
			return this;
		}

		public Criteria andFaxFirstNotEqualTo(String value) {
			addCriterion("fax_first <>", value, "faxFirst");
			return this;
		}

		public Criteria andFaxFirstGreaterThan(String value) {
			addCriterion("fax_first >", value, "faxFirst");
			return this;
		}

		public Criteria andFaxFirstGreaterThanOrEqualTo(String value) {
			addCriterion("fax_first >=", value, "faxFirst");
			return this;
		}

		public Criteria andFaxFirstLessThan(String value) {
			addCriterion("fax_first <", value, "faxFirst");
			return this;
		}

		public Criteria andFaxFirstLessThanOrEqualTo(String value) {
			addCriterion("fax_first <=", value, "faxFirst");
			return this;
		}

		public Criteria andFaxFirstLike(String value) {
			addCriterion("fax_first like", value, "faxFirst");
			return this;
		}

		public Criteria andFaxFirstNotLike(String value) {
			addCriterion("fax_first not like", value, "faxFirst");
			return this;
		}

		public Criteria andFaxFirstIn(List values) {
			addCriterion("fax_first in", values, "faxFirst");
			return this;
		}

		public Criteria andFaxFirstNotIn(List values) {
			addCriterion("fax_first not in", values, "faxFirst");
			return this;
		}

		public Criteria andFaxFirstBetween(String value1, String value2) {
			addCriterion("fax_first between", value1, value2, "faxFirst");
			return this;
		}

		public Criteria andFaxFirstNotBetween(String value1, String value2) {
			addCriterion("fax_first not between", value1, value2, "faxFirst");
			return this;
		}

		public Criteria andContactPersonSecIsNull() {
			addCriterion("contact_person_sec is null");
			return this;
		}

		public Criteria andContactPersonSecIsNotNull() {
			addCriterion("contact_person_sec is not null");
			return this;
		}

		public Criteria andContactPersonSecEqualTo(String value) {
			addCriterion("contact_person_sec =", value, "contactPersonSec");
			return this;
		}

		public Criteria andContactPersonSecNotEqualTo(String value) {
			addCriterion("contact_person_sec <>", value, "contactPersonSec");
			return this;
		}

		public Criteria andContactPersonSecGreaterThan(String value) {
			addCriterion("contact_person_sec >", value, "contactPersonSec");
			return this;
		}

		public Criteria andContactPersonSecGreaterThanOrEqualTo(String value) {
			addCriterion("contact_person_sec >=", value, "contactPersonSec");
			return this;
		}

		public Criteria andContactPersonSecLessThan(String value) {
			addCriterion("contact_person_sec <", value, "contactPersonSec");
			return this;
		}

		public Criteria andContactPersonSecLessThanOrEqualTo(String value) {
			addCriterion("contact_person_sec <=", value, "contactPersonSec");
			return this;
		}

		public Criteria andContactPersonSecLike(String value) {
			addCriterion("contact_person_sec like", value, "contactPersonSec");
			return this;
		}

		public Criteria andContactPersonSecNotLike(String value) {
			addCriterion("contact_person_sec not like", value,
					"contactPersonSec");
			return this;
		}

		public Criteria andContactPersonSecIn(List values) {
			addCriterion("contact_person_sec in", values, "contactPersonSec");
			return this;
		}

		public Criteria andContactPersonSecNotIn(List values) {
			addCriterion("contact_person_sec not in", values,
					"contactPersonSec");
			return this;
		}

		public Criteria andContactPersonSecBetween(String value1, String value2) {
			addCriterion("contact_person_sec between", value1, value2,
					"contactPersonSec");
			return this;
		}

		public Criteria andContactPersonSecNotBetween(String value1,
				String value2) {
			addCriterion("contact_person_sec not between", value1, value2,
					"contactPersonSec");
			return this;
		}

		public Criteria andPhoneSecIsNull() {
			addCriterion("phone_sec is null");
			return this;
		}

		public Criteria andPhoneSecIsNotNull() {
			addCriterion("phone_sec is not null");
			return this;
		}

		public Criteria andPhoneSecEqualTo(String value) {
			addCriterion("phone_sec =", value, "phoneSec");
			return this;
		}

		public Criteria andPhoneSecNotEqualTo(String value) {
			addCriterion("phone_sec <>", value, "phoneSec");
			return this;
		}

		public Criteria andPhoneSecGreaterThan(String value) {
			addCriterion("phone_sec >", value, "phoneSec");
			return this;
		}

		public Criteria andPhoneSecGreaterThanOrEqualTo(String value) {
			addCriterion("phone_sec >=", value, "phoneSec");
			return this;
		}

		public Criteria andPhoneSecLessThan(String value) {
			addCriterion("phone_sec <", value, "phoneSec");
			return this;
		}

		public Criteria andPhoneSecLessThanOrEqualTo(String value) {
			addCriterion("phone_sec <=", value, "phoneSec");
			return this;
		}

		public Criteria andPhoneSecLike(String value) {
			addCriterion("phone_sec like", value, "phoneSec");
			return this;
		}

		public Criteria andPhoneSecNotLike(String value) {
			addCriterion("phone_sec not like", value, "phoneSec");
			return this;
		}

		public Criteria andPhoneSecIn(List values) {
			addCriterion("phone_sec in", values, "phoneSec");
			return this;
		}

		public Criteria andPhoneSecNotIn(List values) {
			addCriterion("phone_sec not in", values, "phoneSec");
			return this;
		}

		public Criteria andPhoneSecBetween(String value1, String value2) {
			addCriterion("phone_sec between", value1, value2, "phoneSec");
			return this;
		}

		public Criteria andPhoneSecNotBetween(String value1, String value2) {
			addCriterion("phone_sec not between", value1, value2, "phoneSec");
			return this;
		}

		public Criteria andFaxSecIsNull() {
			addCriterion("fax_sec is null");
			return this;
		}

		public Criteria andFaxSecIsNotNull() {
			addCriterion("fax_sec is not null");
			return this;
		}

		public Criteria andFaxSecEqualTo(String value) {
			addCriterion("fax_sec =", value, "faxSec");
			return this;
		}

		public Criteria andFaxSecNotEqualTo(String value) {
			addCriterion("fax_sec <>", value, "faxSec");
			return this;
		}

		public Criteria andFaxSecGreaterThan(String value) {
			addCriterion("fax_sec >", value, "faxSec");
			return this;
		}

		public Criteria andFaxSecGreaterThanOrEqualTo(String value) {
			addCriterion("fax_sec >=", value, "faxSec");
			return this;
		}

		public Criteria andFaxSecLessThan(String value) {
			addCriterion("fax_sec <", value, "faxSec");
			return this;
		}

		public Criteria andFaxSecLessThanOrEqualTo(String value) {
			addCriterion("fax_sec <=", value, "faxSec");
			return this;
		}

		public Criteria andFaxSecLike(String value) {
			addCriterion("fax_sec like", value, "faxSec");
			return this;
		}

		public Criteria andFaxSecNotLike(String value) {
			addCriterion("fax_sec not like", value, "faxSec");
			return this;
		}

		public Criteria andFaxSecIn(List values) {
			addCriterion("fax_sec in", values, "faxSec");
			return this;
		}

		public Criteria andFaxSecNotIn(List values) {
			addCriterion("fax_sec not in", values, "faxSec");
			return this;
		}

		public Criteria andFaxSecBetween(String value1, String value2) {
			addCriterion("fax_sec between", value1, value2, "faxSec");
			return this;
		}

		public Criteria andFaxSecNotBetween(String value1, String value2) {
			addCriterion("fax_sec not between", value1, value2, "faxSec");
			return this;
		}

		public Criteria andBrandFirstIsNull() {
			addCriterion("brand_first is null");
			return this;
		}

		public Criteria andBrandFirstIsNotNull() {
			addCriterion("brand_first is not null");
			return this;
		}

		public Criteria andBrandFirstEqualTo(String value) {
			addCriterion("brand_first =", value, "brandFirst");
			return this;
		}

		public Criteria andBrandFirstNotEqualTo(String value) {
			addCriterion("brand_first <>", value, "brandFirst");
			return this;
		}

		public Criteria andBrandFirstGreaterThan(String value) {
			addCriterion("brand_first >", value, "brandFirst");
			return this;
		}

		public Criteria andBrandFirstGreaterThanOrEqualTo(String value) {
			addCriterion("brand_first >=", value, "brandFirst");
			return this;
		}

		public Criteria andBrandFirstLessThan(String value) {
			addCriterion("brand_first <", value, "brandFirst");
			return this;
		}

		public Criteria andBrandFirstLessThanOrEqualTo(String value) {
			addCriterion("brand_first <=", value, "brandFirst");
			return this;
		}

		public Criteria andBrandFirstLike(String value) {
			addCriterion("brand_first like", value, "brandFirst");
			return this;
		}

		public Criteria andBrandFirstNotLike(String value) {
			addCriterion("brand_first not like", value, "brandFirst");
			return this;
		}

		public Criteria andBrandFirstIn(List values) {
			addCriterion("brand_first in", values, "brandFirst");
			return this;
		}

		public Criteria andBrandFirstNotIn(List values) {
			addCriterion("brand_first not in", values, "brandFirst");
			return this;
		}

		public Criteria andBrandFirstBetween(String value1, String value2) {
			addCriterion("brand_first between", value1, value2, "brandFirst");
			return this;
		}

		public Criteria andBrandFirstNotBetween(String value1, String value2) {
			addCriterion("brand_first not between", value1, value2,
					"brandFirst");
			return this;
		}

		public Criteria andBrandSecIsNull() {
			addCriterion("brand_sec is null");
			return this;
		}

		public Criteria andBrandSecIsNotNull() {
			addCriterion("brand_sec is not null");
			return this;
		}

		public Criteria andBrandSecEqualTo(String value) {
			addCriterion("brand_sec =", value, "brandSec");
			return this;
		}

		public Criteria andBrandSecNotEqualTo(String value) {
			addCriterion("brand_sec <>", value, "brandSec");
			return this;
		}

		public Criteria andBrandSecGreaterThan(String value) {
			addCriterion("brand_sec >", value, "brandSec");
			return this;
		}

		public Criteria andBrandSecGreaterThanOrEqualTo(String value) {
			addCriterion("brand_sec >=", value, "brandSec");
			return this;
		}

		public Criteria andBrandSecLessThan(String value) {
			addCriterion("brand_sec <", value, "brandSec");
			return this;
		}

		public Criteria andBrandSecLessThanOrEqualTo(String value) {
			addCriterion("brand_sec <=", value, "brandSec");
			return this;
		}

		public Criteria andBrandSecLike(String value) {
			addCriterion("brand_sec like", value, "brandSec");
			return this;
		}

		public Criteria andBrandSecNotLike(String value) {
			addCriterion("brand_sec not like", value, "brandSec");
			return this;
		}

		public Criteria andBrandSecIn(List values) {
			addCriterion("brand_sec in", values, "brandSec");
			return this;
		}

		public Criteria andBrandSecNotIn(List values) {
			addCriterion("brand_sec not in", values, "brandSec");
			return this;
		}

		public Criteria andBrandSecBetween(String value1, String value2) {
			addCriterion("brand_sec between", value1, value2, "brandSec");
			return this;
		}

		public Criteria andBrandSecNotBetween(String value1, String value2) {
			addCriterion("brand_sec not between", value1, value2, "brandSec");
			return this;
		}

		public Criteria andBrandThirdIsNull() {
			addCriterion("brand_third is null");
			return this;
		}

		public Criteria andBrandThirdIsNotNull() {
			addCriterion("brand_third is not null");
			return this;
		}

		public Criteria andBrandThirdEqualTo(String value) {
			addCriterion("brand_third =", value, "brandThird");
			return this;
		}

		public Criteria andBrandThirdNotEqualTo(String value) {
			addCriterion("brand_third <>", value, "brandThird");
			return this;
		}

		public Criteria andBrandThirdGreaterThan(String value) {
			addCriterion("brand_third >", value, "brandThird");
			return this;
		}

		public Criteria andBrandThirdGreaterThanOrEqualTo(String value) {
			addCriterion("brand_third >=", value, "brandThird");
			return this;
		}

		public Criteria andBrandThirdLessThan(String value) {
			addCriterion("brand_third <", value, "brandThird");
			return this;
		}

		public Criteria andBrandThirdLessThanOrEqualTo(String value) {
			addCriterion("brand_third <=", value, "brandThird");
			return this;
		}

		public Criteria andBrandThirdLike(String value) {
			addCriterion("brand_third like", value, "brandThird");
			return this;
		}

		public Criteria andBrandThirdNotLike(String value) {
			addCriterion("brand_third not like", value, "brandThird");
			return this;
		}

		public Criteria andBrandThirdIn(List values) {
			addCriterion("brand_third in", values, "brandThird");
			return this;
		}

		public Criteria andBrandThirdNotIn(List values) {
			addCriterion("brand_third not in", values, "brandThird");
			return this;
		}

		public Criteria andBrandThirdBetween(String value1, String value2) {
			addCriterion("brand_third between", value1, value2, "brandThird");
			return this;
		}

		public Criteria andBrandThirdNotBetween(String value1, String value2) {
			addCriterion("brand_third not between", value1, value2,
					"brandThird");
			return this;
		}

		public Criteria andBrandFourthIsNull() {
			addCriterion("brand_fourth is null");
			return this;
		}

		public Criteria andBrandFourthIsNotNull() {
			addCriterion("brand_fourth is not null");
			return this;
		}

		public Criteria andBrandFourthEqualTo(String value) {
			addCriterion("brand_fourth =", value, "brandFourth");
			return this;
		}

		public Criteria andBrandFourthNotEqualTo(String value) {
			addCriterion("brand_fourth <>", value, "brandFourth");
			return this;
		}

		public Criteria andBrandFourthGreaterThan(String value) {
			addCriterion("brand_fourth >", value, "brandFourth");
			return this;
		}

		public Criteria andBrandFourthGreaterThanOrEqualTo(String value) {
			addCriterion("brand_fourth >=", value, "brandFourth");
			return this;
		}

		public Criteria andBrandFourthLessThan(String value) {
			addCriterion("brand_fourth <", value, "brandFourth");
			return this;
		}

		public Criteria andBrandFourthLessThanOrEqualTo(String value) {
			addCriterion("brand_fourth <=", value, "brandFourth");
			return this;
		}

		public Criteria andBrandFourthLike(String value) {
			addCriterion("brand_fourth like", value, "brandFourth");
			return this;
		}

		public Criteria andBrandFourthNotLike(String value) {
			addCriterion("brand_fourth not like", value, "brandFourth");
			return this;
		}

		public Criteria andBrandFourthIn(List values) {
			addCriterion("brand_fourth in", values, "brandFourth");
			return this;
		}

		public Criteria andBrandFourthNotIn(List values) {
			addCriterion("brand_fourth not in", values, "brandFourth");
			return this;
		}

		public Criteria andBrandFourthBetween(String value1, String value2) {
			addCriterion("brand_fourth between", value1, value2, "brandFourth");
			return this;
		}

		public Criteria andBrandFourthNotBetween(String value1, String value2) {
			addCriterion("brand_fourth not between", value1, value2,
					"brandFourth");
			return this;
		}

		public Criteria andContractAddressIsNull() {
			addCriterion("contract_address is null");
			return this;
		}

		public Criteria andContractAddressIsNotNull() {
			addCriterion("contract_address is not null");
			return this;
		}

		public Criteria andContractAddressEqualTo(String value) {
			addCriterion("contract_address =", value, "contractAddress");
			return this;
		}

		public Criteria andContractAddressNotEqualTo(String value) {
			addCriterion("contract_address <>", value, "contractAddress");
			return this;
		}

		public Criteria andContractAddressGreaterThan(String value) {
			addCriterion("contract_address >", value, "contractAddress");
			return this;
		}

		public Criteria andContractAddressGreaterThanOrEqualTo(String value) {
			addCriterion("contract_address >=", value, "contractAddress");
			return this;
		}

		public Criteria andContractAddressLessThan(String value) {
			addCriterion("contract_address <", value, "contractAddress");
			return this;
		}

		public Criteria andContractAddressLessThanOrEqualTo(String value) {
			addCriterion("contract_address <=", value, "contractAddress");
			return this;
		}

		public Criteria andContractAddressLike(String value) {
			addCriterion("contract_address like", value, "contractAddress");
			return this;
		}

		public Criteria andContractAddressNotLike(String value) {
			addCriterion("contract_address not like", value, "contractAddress");
			return this;
		}

		public Criteria andContractAddressIn(List values) {
			addCriterion("contract_address in", values, "contractAddress");
			return this;
		}

		public Criteria andContractAddressNotIn(List values) {
			addCriterion("contract_address not in", values, "contractAddress");
			return this;
		}

		public Criteria andContractAddressBetween(String value1, String value2) {
			addCriterion("contract_address between", value1, value2,
					"contractAddress");
			return this;
		}

		public Criteria andContractAddressNotBetween(String value1,
				String value2) {
			addCriterion("contract_address not between", value1, value2,
					"contractAddress");
			return this;
		}

		public Criteria andPostcodeIsNull() {
			addCriterion("postcode is null");
			return this;
		}

		public Criteria andPostcodeIsNotNull() {
			addCriterion("postcode is not null");
			return this;
		}

		public Criteria andPostcodeEqualTo(String value) {
			addCriterion("postcode =", value, "postcode");
			return this;
		}

		public Criteria andPostcodeNotEqualTo(String value) {
			addCriterion("postcode <>", value, "postcode");
			return this;
		}

		public Criteria andPostcodeGreaterThan(String value) {
			addCriterion("postcode >", value, "postcode");
			return this;
		}

		public Criteria andPostcodeGreaterThanOrEqualTo(String value) {
			addCriterion("postcode >=", value, "postcode");
			return this;
		}

		public Criteria andPostcodeLessThan(String value) {
			addCriterion("postcode <", value, "postcode");
			return this;
		}

		public Criteria andPostcodeLessThanOrEqualTo(String value) {
			addCriterion("postcode <=", value, "postcode");
			return this;
		}

		public Criteria andPostcodeLike(String value) {
			addCriterion("postcode like", value, "postcode");
			return this;
		}

		public Criteria andPostcodeNotLike(String value) {
			addCriterion("postcode not like", value, "postcode");
			return this;
		}

		public Criteria andPostcodeIn(List values) {
			addCriterion("postcode in", values, "postcode");
			return this;
		}

		public Criteria andPostcodeNotIn(List values) {
			addCriterion("postcode not in", values, "postcode");
			return this;
		}

		public Criteria andPostcodeBetween(String value1, String value2) {
			addCriterion("postcode between", value1, value2, "postcode");
			return this;
		}

		public Criteria andPostcodeNotBetween(String value1, String value2) {
			addCriterion("postcode not between", value1, value2, "postcode");
			return this;
		}

		public Criteria andComAdressIsNull() {
			addCriterion("com_adress is null");
			return this;
		}

		public Criteria andComAdressIsNotNull() {
			addCriterion("com_adress is not null");
			return this;
		}

		public Criteria andComAdressEqualTo(String value) {
			addCriterion("com_adress =", value, "comAdress");
			return this;
		}

		public Criteria andComAdressNotEqualTo(String value) {
			addCriterion("com_adress <>", value, "comAdress");
			return this;
		}

		public Criteria andComAdressGreaterThan(String value) {
			addCriterion("com_adress >", value, "comAdress");
			return this;
		}

		public Criteria andComAdressGreaterThanOrEqualTo(String value) {
			addCriterion("com_adress >=", value, "comAdress");
			return this;
		}

		public Criteria andComAdressLessThan(String value) {
			addCriterion("com_adress <", value, "comAdress");
			return this;
		}

		public Criteria andComAdressLessThanOrEqualTo(String value) {
			addCriterion("com_adress <=", value, "comAdress");
			return this;
		}

		public Criteria andComAdressLike(String value) {
			addCriterion("com_adress like", value, "comAdress");
			return this;
		}

		public Criteria andComAdressNotLike(String value) {
			addCriterion("com_adress not like", value, "comAdress");
			return this;
		}

		public Criteria andComAdressIn(List values) {
			addCriterion("com_adress in", values, "comAdress");
			return this;
		}

		public Criteria andComAdressNotIn(List values) {
			addCriterion("com_adress not in", values, "comAdress");
			return this;
		}

		public Criteria andComAdressBetween(String value1, String value2) {
			addCriterion("com_adress between", value1, value2, "comAdress");
			return this;
		}

		public Criteria andComAdressNotBetween(String value1, String value2) {
			addCriterion("com_adress not between", value1, value2, "comAdress");
			return this;
		}

		public Criteria andBankIsNull() {
			addCriterion("bank is null");
			return this;
		}

		public Criteria andBankIsNotNull() {
			addCriterion("bank is not null");
			return this;
		}

		public Criteria andBankEqualTo(String value) {
			addCriterion("bank =", value, "bank");
			return this;
		}

		public Criteria andBankNotEqualTo(String value) {
			addCriterion("bank <>", value, "bank");
			return this;
		}

		public Criteria andBankGreaterThan(String value) {
			addCriterion("bank >", value, "bank");
			return this;
		}

		public Criteria andBankGreaterThanOrEqualTo(String value) {
			addCriterion("bank >=", value, "bank");
			return this;
		}

		public Criteria andBankLessThan(String value) {
			addCriterion("bank <", value, "bank");
			return this;
		}

		public Criteria andBankLessThanOrEqualTo(String value) {
			addCriterion("bank <=", value, "bank");
			return this;
		}

		public Criteria andBankLike(String value) {
			addCriterion("bank like", value, "bank");
			return this;
		}

		public Criteria andBankNotLike(String value) {
			addCriterion("bank not like", value, "bank");
			return this;
		}

		public Criteria andBankIn(List values) {
			addCriterion("bank in", values, "bank");
			return this;
		}

		public Criteria andBankNotIn(List values) {
			addCriterion("bank not in", values, "bank");
			return this;
		}

		public Criteria andBankBetween(String value1, String value2) {
			addCriterion("bank between", value1, value2, "bank");
			return this;
		}

		public Criteria andBankNotBetween(String value1, String value2) {
			addCriterion("bank not between", value1, value2, "bank");
			return this;
		}

		public Criteria andAccountNumberIsNull() {
			addCriterion("account_number is null");
			return this;
		}

		public Criteria andAccountNumberIsNotNull() {
			addCriterion("account_number is not null");
			return this;
		}

		public Criteria andAccountNumberEqualTo(String value) {
			addCriterion("account_number =", value, "accountNumber");
			return this;
		}

		public Criteria andAccountNumberNotEqualTo(String value) {
			addCriterion("account_number <>", value, "accountNumber");
			return this;
		}

		public Criteria andAccountNumberGreaterThan(String value) {
			addCriterion("account_number >", value, "accountNumber");
			return this;
		}

		public Criteria andAccountNumberGreaterThanOrEqualTo(String value) {
			addCriterion("account_number >=", value, "accountNumber");
			return this;
		}

		public Criteria andAccountNumberLessThan(String value) {
			addCriterion("account_number <", value, "accountNumber");
			return this;
		}

		public Criteria andAccountNumberLessThanOrEqualTo(String value) {
			addCriterion("account_number <=", value, "accountNumber");
			return this;
		}

		public Criteria andAccountNumberLike(String value) {
			addCriterion("account_number like", value, "accountNumber");
			return this;
		}

		public Criteria andAccountNumberNotLike(String value) {
			addCriterion("account_number not like", value, "accountNumber");
			return this;
		}

		public Criteria andAccountNumberIn(List values) {
			addCriterion("account_number in", values, "accountNumber");
			return this;
		}

		public Criteria andAccountNumberNotIn(List values) {
			addCriterion("account_number not in", values, "accountNumber");
			return this;
		}

		public Criteria andAccountNumberBetween(String value1, String value2) {
			addCriterion("account_number between", value1, value2,
					"accountNumber");
			return this;
		}

		public Criteria andAccountNumberNotBetween(String value1, String value2) {
			addCriterion("account_number not between", value1, value2,
					"accountNumber");
			return this;
		}

		public Criteria andHomePageIsNull() {
			addCriterion("home_page is null");
			return this;
		}

		public Criteria andHomePageIsNotNull() {
			addCriterion("home_page is not null");
			return this;
		}

		public Criteria andHomePageEqualTo(String value) {
			addCriterion("home_page =", value, "homePage");
			return this;
		}

		public Criteria andHomePageNotEqualTo(String value) {
			addCriterion("home_page <>", value, "homePage");
			return this;
		}

		public Criteria andHomePageGreaterThan(String value) {
			addCriterion("home_page >", value, "homePage");
			return this;
		}

		public Criteria andHomePageGreaterThanOrEqualTo(String value) {
			addCriterion("home_page >=", value, "homePage");
			return this;
		}

		public Criteria andHomePageLessThan(String value) {
			addCriterion("home_page <", value, "homePage");
			return this;
		}

		public Criteria andHomePageLessThanOrEqualTo(String value) {
			addCriterion("home_page <=", value, "homePage");
			return this;
		}

		public Criteria andHomePageLike(String value) {
			addCriterion("home_page like", value, "homePage");
			return this;
		}

		public Criteria andHomePageNotLike(String value) {
			addCriterion("home_page not like", value, "homePage");
			return this;
		}

		public Criteria andHomePageIn(List values) {
			addCriterion("home_page in", values, "homePage");
			return this;
		}

		public Criteria andHomePageNotIn(List values) {
			addCriterion("home_page not in", values, "homePage");
			return this;
		}

		public Criteria andHomePageBetween(String value1, String value2) {
			addCriterion("home_page between", value1, value2, "homePage");
			return this;
		}

		public Criteria andHomePageNotBetween(String value1, String value2) {
			addCriterion("home_page not between", value1, value2, "homePage");
			return this;
		}

		public Criteria andEmailIsNull() {
			addCriterion("email is null");
			return this;
		}

		public Criteria andEmailIsNotNull() {
			addCriterion("email is not null");
			return this;
		}

		public Criteria andEmailEqualTo(String value) {
			addCriterion("email =", value, "email");
			return this;
		}

		public Criteria andEmailNotEqualTo(String value) {
			addCriterion("email <>", value, "email");
			return this;
		}

		public Criteria andEmailGreaterThan(String value) {
			addCriterion("email >", value, "email");
			return this;
		}

		public Criteria andEmailGreaterThanOrEqualTo(String value) {
			addCriterion("email >=", value, "email");
			return this;
		}

		public Criteria andEmailLessThan(String value) {
			addCriterion("email <", value, "email");
			return this;
		}

		public Criteria andEmailLessThanOrEqualTo(String value) {
			addCriterion("email <=", value, "email");
			return this;
		}

		public Criteria andEmailLike(String value) {
			addCriterion("email like", value, "email");
			return this;
		}

		public Criteria andEmailNotLike(String value) {
			addCriterion("email not like", value, "email");
			return this;
		}

		public Criteria andEmailIn(List values) {
			addCriterion("email in", values, "email");
			return this;
		}

		public Criteria andEmailNotIn(List values) {
			addCriterion("email not in", values, "email");
			return this;
		}

		public Criteria andEmailBetween(String value1, String value2) {
			addCriterion("email between", value1, value2, "email");
			return this;
		}

		public Criteria andEmailNotBetween(String value1, String value2) {
			addCriterion("email not between", value1, value2, "email");
			return this;
		}

		public Criteria andMemoIsNull() {
			addCriterion("memo is null");
			return this;
		}

		public Criteria andMemoIsNotNull() {
			addCriterion("memo is not null");
			return this;
		}

		public Criteria andMemoEqualTo(String value) {
			addCriterion("memo =", value, "memo");
			return this;
		}

		public Criteria andMemoNotEqualTo(String value) {
			addCriterion("memo <>", value, "memo");
			return this;
		}

		public Criteria andMemoGreaterThan(String value) {
			addCriterion("memo >", value, "memo");
			return this;
		}

		public Criteria andMemoGreaterThanOrEqualTo(String value) {
			addCriterion("memo >=", value, "memo");
			return this;
		}

		public Criteria andMemoLessThan(String value) {
			addCriterion("memo <", value, "memo");
			return this;
		}

		public Criteria andMemoLessThanOrEqualTo(String value) {
			addCriterion("memo <=", value, "memo");
			return this;
		}

		public Criteria andMemoLike(String value) {
			addCriterion("memo like", value, "memo");
			return this;
		}

		public Criteria andMemoNotLike(String value) {
			addCriterion("memo not like", value, "memo");
			return this;
		}

		public Criteria andMemoIn(List values) {
			addCriterion("memo in", values, "memo");
			return this;
		}

		public Criteria andMemoNotIn(List values) {
			addCriterion("memo not in", values, "memo");
			return this;
		}

		public Criteria andMemoBetween(String value1, String value2) {
			addCriterion("memo between", value1, value2, "memo");
			return this;
		}

		public Criteria andMemoNotBetween(String value1, String value2) {
			addCriterion("memo not between", value1, value2, "memo");
			return this;
		}
	}
}