package com.tl.resource.dao;

import com.tl.resource.dao.pojo.TAuditContentAuditHistoryGx;
import com.tl.resource.dao.pojo.TAuditContentAuditHistoryGxExample;
import java.util.List;
import org.springframework.orm.ibatis.support.SqlMapClientDaoSupport;

public class TAuditContentAuditHistoryGxDAOImpl extends SqlMapClientDaoSupport implements TAuditContentAuditHistoryGxDAO {

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table t_audit_content_audit_history_gx
     *
     * @ibatorgenerated Thu Apr 22 16:34:14 CST 2010
     */
    public TAuditContentAuditHistoryGxDAOImpl() {
        super();
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table t_audit_content_audit_history_gx
     *
     * @ibatorgenerated Thu Apr 22 16:34:14 CST 2010
     */
    public int countByExample(TAuditContentAuditHistoryGxExample example) {
        Integer count = (Integer)  getSqlMapClientTemplate().queryForObject("t_audit_content_audit_history_gx.ibatorgenerated_countByExample", example);
        return count.intValue();
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table t_audit_content_audit_history_gx
     *
     * @ibatorgenerated Thu Apr 22 16:34:14 CST 2010
     */
    public int deleteByExample(TAuditContentAuditHistoryGxExample example) {
        int rows = getSqlMapClientTemplate().delete("t_audit_content_audit_history_gx.ibatorgenerated_deleteByExample", example);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table t_audit_content_audit_history_gx
     *
     * @ibatorgenerated Thu Apr 22 16:34:14 CST 2010
     */
    public void insert(TAuditContentAuditHistoryGx record) {
        getSqlMapClientTemplate().insert("t_audit_content_audit_history_gx.ibatorgenerated_insert", record);
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table t_audit_content_audit_history_gx
     *
     * @ibatorgenerated Thu Apr 22 16:34:14 CST 2010
     */
    public void insertSelective(TAuditContentAuditHistoryGx record) {
        getSqlMapClientTemplate().insert("t_audit_content_audit_history_gx.ibatorgenerated_insertSelective", record);
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table t_audit_content_audit_history_gx
     *
     * @ibatorgenerated Thu Apr 22 16:34:14 CST 2010
     */
    public List selectByExample(TAuditContentAuditHistoryGxExample example) {
        List list = getSqlMapClientTemplate().queryForList("t_audit_content_audit_history_gx.ibatorgenerated_selectByExample", example);
        return list;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table t_audit_content_audit_history_gx
     *
     * @ibatorgenerated Thu Apr 22 16:34:14 CST 2010
     */
    public int updateByExampleSelective(TAuditContentAuditHistoryGx record, TAuditContentAuditHistoryGxExample example) {
        UpdateByExampleParms parms = new UpdateByExampleParms(record, example);
        int rows = getSqlMapClientTemplate().update("t_audit_content_audit_history_gx.ibatorgenerated_updateByExampleSelective", parms);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table t_audit_content_audit_history_gx
     *
     * @ibatorgenerated Thu Apr 22 16:34:14 CST 2010
     */
    public int updateByExample(TAuditContentAuditHistoryGx record, TAuditContentAuditHistoryGxExample example) {
        UpdateByExampleParms parms = new UpdateByExampleParms(record, example);
        int rows = getSqlMapClientTemplate().update("t_audit_content_audit_history_gx.ibatorgenerated_updateByExample", parms);
        return rows;
    }

    /**
     * This class was generated by Apache iBATIS ibator.
     * This class corresponds to the database table t_audit_content_audit_history_gx
     *
     * @ibatorgenerated Thu Apr 22 16:34:14 CST 2010
     */
    private static class UpdateByExampleParms extends TAuditContentAuditHistoryGxExample {
        private Object record;

        public UpdateByExampleParms(Object record, TAuditContentAuditHistoryGxExample example) {
            super(example);
            this.record = record;
        }

        public Object getRecord() {
            return record;
        }
    }
}