package com.tl.resource.dao;

import com.tl.resource.dao.pojo.TAuditBatchRecord;
import com.tl.resource.dao.pojo.TAuditBatchRecordExample;
import java.util.List;
import org.springframework.orm.ibatis.support.SqlMapClientDaoSupport;

public class TAuditBatchRecordDAOImpl extends SqlMapClientDaoSupport implements TAuditBatchRecordDAO {

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table t_audit_batch_record
     *
     * @ibatorgenerated Tue Oct 20 11:57:32 CST 2009
     */
    public TAuditBatchRecordDAOImpl() {
        super();
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table t_audit_batch_record
     *
     * @ibatorgenerated Tue Oct 20 11:57:32 CST 2009
     */
    public int countByExample(TAuditBatchRecordExample example) {
        Integer count = (Integer)  getSqlMapClientTemplate().queryForObject("t_audit_batch_record.ibatorgenerated_countByExample", example);
        return count.intValue();
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table t_audit_batch_record
     *
     * @ibatorgenerated Tue Oct 20 11:57:32 CST 2009
     */
    public int deleteByExample(TAuditBatchRecordExample example) {
        int rows = getSqlMapClientTemplate().delete("t_audit_batch_record.ibatorgenerated_deleteByExample", example);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table t_audit_batch_record
     *
     * @ibatorgenerated Tue Oct 20 11:57:32 CST 2009
     */
    public int deleteByPrimaryKey(String id) {
        TAuditBatchRecord key = new TAuditBatchRecord();
        key.setId(id);
        int rows = getSqlMapClientTemplate().delete("t_audit_batch_record.ibatorgenerated_deleteByPrimaryKey", key);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table t_audit_batch_record
     *
     * @ibatorgenerated Tue Oct 20 11:57:32 CST 2009
     */
    public void insert(TAuditBatchRecord record) {
        getSqlMapClientTemplate().insert("t_audit_batch_record.ibatorgenerated_insert", record);
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table t_audit_batch_record
     *
     * @ibatorgenerated Tue Oct 20 11:57:32 CST 2009
     */
    public void insertSelective(TAuditBatchRecord record) {
        getSqlMapClientTemplate().insert("t_audit_batch_record.ibatorgenerated_insertSelective", record);
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table t_audit_batch_record
     *
     * @ibatorgenerated Tue Oct 20 11:57:32 CST 2009
     */
    public List selectByExample(TAuditBatchRecordExample example) {
        List list = getSqlMapClientTemplate().queryForList("t_audit_batch_record.ibatorgenerated_selectByExample", example);
        return list;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table t_audit_batch_record
     *
     * @ibatorgenerated Tue Oct 20 11:57:32 CST 2009
     */
    public TAuditBatchRecord selectByPrimaryKey(String id) {
        TAuditBatchRecord key = new TAuditBatchRecord();
        key.setId(id);
        TAuditBatchRecord record = (TAuditBatchRecord) getSqlMapClientTemplate().queryForObject("t_audit_batch_record.ibatorgenerated_selectByPrimaryKey", key);
        return record;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table t_audit_batch_record
     *
     * @ibatorgenerated Tue Oct 20 11:57:32 CST 2009
     */
    public int updateByExampleSelective(TAuditBatchRecord record, TAuditBatchRecordExample example) {
        UpdateByExampleParms parms = new UpdateByExampleParms(record, example);
        int rows = getSqlMapClientTemplate().update("t_audit_batch_record.ibatorgenerated_updateByExampleSelective", parms);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table t_audit_batch_record
     *
     * @ibatorgenerated Tue Oct 20 11:57:32 CST 2009
     */
    public int updateByExample(TAuditBatchRecord record, TAuditBatchRecordExample example) {
        UpdateByExampleParms parms = new UpdateByExampleParms(record, example);
        int rows = getSqlMapClientTemplate().update("t_audit_batch_record.ibatorgenerated_updateByExample", parms);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table t_audit_batch_record
     *
     * @ibatorgenerated Tue Oct 20 11:57:32 CST 2009
     */
    public int updateByPrimaryKeySelective(TAuditBatchRecord record) {
        int rows = getSqlMapClientTemplate().update("t_audit_batch_record.ibatorgenerated_updateByPrimaryKeySelective", record);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table t_audit_batch_record
     *
     * @ibatorgenerated Tue Oct 20 11:57:32 CST 2009
     */
    public int updateByPrimaryKey(TAuditBatchRecord record) {
        int rows = getSqlMapClientTemplate().update("t_audit_batch_record.ibatorgenerated_updateByPrimaryKey", record);
        return rows;
    }

    /**
     * This class was generated by Apache iBATIS ibator.
     * This class corresponds to the database table t_audit_batch_record
     *
     * @ibatorgenerated Tue Oct 20 11:57:32 CST 2009
     */
    private static class UpdateByExampleParms extends TAuditBatchRecordExample {
        private Object record;

        public UpdateByExampleParms(Object record, TAuditBatchRecordExample example) {
            super(example);
            this.record = record;
        }

        public Object getRecord() {
            return record;
        }
    }
}