package com.tl.resource.dao;

import java.util.HashMap;
import java.util.List;
import java.util.Map;

import org.springframework.orm.ibatis.support.SqlMapClientDaoSupport;

import com.tl.resource.dao.pojo.TAuditInstance;
import com.tl.resource.dao.pojo.TAuditInstanceExample;

public class TAuditInstanceDAOImpl extends SqlMapClientDaoSupport implements TAuditInstanceDAO {

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table t_audit_instance
     *
     * @ibatorgenerated Tue Oct 20 11:57:32 CST 2009
     */
    public TAuditInstanceDAOImpl() {
        super();
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table t_audit_instance
     *
     * @ibatorgenerated Tue Oct 20 11:57:32 CST 2009
     */
    public int countByExample(TAuditInstanceExample example) {
        Integer count = (Integer)  getSqlMapClientTemplate().queryForObject("t_audit_instance.ibatorgenerated_countByExample", example);
        return count.intValue();
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table t_audit_instance
     *
     * @ibatorgenerated Tue Oct 20 11:57:32 CST 2009
     */
    public int deleteByExample(TAuditInstanceExample example) {
        int rows = getSqlMapClientTemplate().delete("t_audit_instance.ibatorgenerated_deleteByExample", example);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table t_audit_instance
     *
     * @ibatorgenerated Tue Oct 20 11:57:32 CST 2009
     */
    public int deleteByPrimaryKey(String id) {
        TAuditInstance key = new TAuditInstance();
        key.setId(id);
        int rows = getSqlMapClientTemplate().delete("t_audit_instance.ibatorgenerated_deleteByPrimaryKey", key);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table t_audit_instance
     *
     * @ibatorgenerated Tue Oct 20 11:57:32 CST 2009
     */
    public void insert(TAuditInstance record) {
        getSqlMapClientTemplate().insert("t_audit_instance.ibatorgenerated_insert", record);
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table t_audit_instance
     *
     * @ibatorgenerated Tue Oct 20 11:57:32 CST 2009
     */
    public void insertSelective(TAuditInstance record) {
        getSqlMapClientTemplate().insert("t_audit_instance.ibatorgenerated_insertSelective", record);
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table t_audit_instance
     *
     * @ibatorgenerated Tue Oct 20 11:57:32 CST 2009
     */
    public List selectByExample(TAuditInstanceExample example) {
        List list = getSqlMapClientTemplate().queryForList("t_audit_instance.ibatorgenerated_selectByExample", example);
        return list;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table t_audit_instance
     *
     * @ibatorgenerated Tue Oct 20 11:57:32 CST 2009
     */
    public TAuditInstance selectByPrimaryKey(String id) {
        TAuditInstance key = new TAuditInstance();
        key.setId(id);
        TAuditInstance record = (TAuditInstance) getSqlMapClientTemplate().queryForObject("t_audit_instance.ibatorgenerated_selectByPrimaryKey", key);
        return record;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table t_audit_instance
     *
     * @ibatorgenerated Tue Oct 20 11:57:32 CST 2009
     */
    public int updateByExampleSelective(TAuditInstance record, TAuditInstanceExample example) {
        UpdateByExampleParms parms = new UpdateByExampleParms(record, example);
        int rows = getSqlMapClientTemplate().update("t_audit_instance.ibatorgenerated_updateByExampleSelective", parms);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table t_audit_instance
     *
     * @ibatorgenerated Tue Oct 20 11:57:32 CST 2009
     */
    public int updateByExample(TAuditInstance record, TAuditInstanceExample example) {
        UpdateByExampleParms parms = new UpdateByExampleParms(record, example);
        int rows = getSqlMapClientTemplate().update("t_audit_instance.ibatorgenerated_updateByExample", parms);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table t_audit_instance
     *
     * @ibatorgenerated Tue Oct 20 11:57:32 CST 2009
     */
    public int updateByPrimaryKeySelective(TAuditInstance record) {
        int rows = getSqlMapClientTemplate().update("t_audit_instance.ibatorgenerated_updateByPrimaryKeySelective", record);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table t_audit_instance
     *
     * @ibatorgenerated Tue Oct 20 11:57:32 CST 2009
     */
    public int updateByPrimaryKey(TAuditInstance record) {
        int rows = getSqlMapClientTemplate().update("t_audit_instance.ibatorgenerated_updateByPrimaryKey", record);
        return rows;
    }

    /**
     * This class was generated by Apache iBATIS ibator.
     * This class corresponds to the database table t_audit_instance
     *
     * @ibatorgenerated Tue Oct 20 11:57:32 CST 2009
     */
    private static class UpdateByExampleParms extends TAuditInstanceExample {
        private Object record;

        public UpdateByExampleParms(Object record, TAuditInstanceExample example) {
            super(example);
            this.record = record;
        }

        public Object getRecord() {
            return record;
        }
    }

	@Override
	public Integer getMinOrder(String auditInforId, String bussinessId) {
		// TODO Auto-generated method stub
		Map<String,String> para = new HashMap<String,String>();
		para.put("auditInforId", auditInforId);
		para.put("bussinessId", bussinessId);
		return (Integer) getSqlMapClientTemplate().queryForObject("audit_fcc.getMinOrder",para);
	}

	@Override
	public List getAuditorsIns(String auditPersonId, String flowInforId,
			int startIndex, int pageSize) {
		// TODO Auto-generated method stub
		Map<String,String> params = new HashMap<String,String>();
		params.put("audit_person_id", auditPersonId);
		params.put("flow_infor_id", flowInforId);
		params.put("startIndex", String.valueOf(startIndex));
		params.put("pageSize", String.valueOf(pageSize));
		return getSqlMapClientTemplate().queryForList("t_audit_instance.getAuditorsIns", params);
	}

	@Override
	public int getAuditorsInsCount(String auditPersonId, String flowInforId) {
		Map<String,String> params = new HashMap<String,String>();
		params.put("audit_person_id", auditPersonId);
		params.put("flow_infor_id", flowInforId);
		Integer count = (Integer)  getSqlMapClientTemplate().queryForObject("t_audit_instance.getAuditorsInsCount", params);
        return count.intValue();
	}
}