package com.tl.resource.dao;

import com.tl.resource.dao.pojo.TAuditFlowDetail;
import com.tl.resource.dao.pojo.TAuditFlowDetailExample;
import java.util.List;

public interface TAuditFlowDetailDAO {
    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table t_audit_flow_detail
     *
     * @ibatorgenerated Tue Oct 20 11:57:32 CST 2009
     */
    int countByExample(TAuditFlowDetailExample example);

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table t_audit_flow_detail
     *
     * @ibatorgenerated Tue Oct 20 11:57:32 CST 2009
     */
    int deleteByExample(TAuditFlowDetailExample example);

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table t_audit_flow_detail
     *
     * @ibatorgenerated Tue Oct 20 11:57:32 CST 2009
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table t_audit_flow_detail
     *
     * @ibatorgenerated Tue Oct 20 11:57:32 CST 2009
     */
    void insert(TAuditFlowDetail record);

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table t_audit_flow_detail
     *
     * @ibatorgenerated Tue Oct 20 11:57:32 CST 2009
     */
    void insertSelective(TAuditFlowDetail record);

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table t_audit_flow_detail
     *
     * @ibatorgenerated Tue Oct 20 11:57:32 CST 2009
     */
    List selectByExample(TAuditFlowDetailExample example);

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table t_audit_flow_detail
     *
     * @ibatorgenerated Tue Oct 20 11:57:32 CST 2009
     */
    TAuditFlowDetail selectByPrimaryKey(String id);

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table t_audit_flow_detail
     *
     * @ibatorgenerated Tue Oct 20 11:57:32 CST 2009
     */
    int updateByExampleSelective(TAuditFlowDetail record, TAuditFlowDetailExample example);

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table t_audit_flow_detail
     *
     * @ibatorgenerated Tue Oct 20 11:57:32 CST 2009
     */
    int updateByExample(TAuditFlowDetail record, TAuditFlowDetailExample example);

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table t_audit_flow_detail
     *
     * @ibatorgenerated Tue Oct 20 11:57:32 CST 2009
     */
    int updateByPrimaryKeySelective(TAuditFlowDetail record);

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table t_audit_flow_detail
     *
     * @ibatorgenerated Tue Oct 20 11:57:32 CST 2009
     */
    int updateByPrimaryKey(TAuditFlowDetail record);
}