package com.tl.resource.dao;

import com.tl.resource.dao.pojo.TAuditType;
import com.tl.resource.dao.pojo.TAuditTypeExample;
import java.util.List;
import org.springframework.orm.ibatis.support.SqlMapClientDaoSupport;

public class TAuditTypeDAOImpl extends SqlMapClientDaoSupport implements TAuditTypeDAO {

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table t_audit_type
     *
     * @ibatorgenerated Tue Oct 20 11:57:32 CST 2009
     */
    public TAuditTypeDAOImpl() {
        super();
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table t_audit_type
     *
     * @ibatorgenerated Tue Oct 20 11:57:32 CST 2009
     */
    public int countByExample(TAuditTypeExample example) {
        Integer count = (Integer)  getSqlMapClientTemplate().queryForObject("t_audit_type.ibatorgenerated_countByExample", example);
        return count.intValue();
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table t_audit_type
     *
     * @ibatorgenerated Tue Oct 20 11:57:32 CST 2009
     */
    public int deleteByExample(TAuditTypeExample example) {
        int rows = getSqlMapClientTemplate().delete("t_audit_type.ibatorgenerated_deleteByExample", example);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table t_audit_type
     *
     * @ibatorgenerated Tue Oct 20 11:57:32 CST 2009
     */
    public int deleteByPrimaryKey(String id) {
        TAuditType key = new TAuditType();
        key.setId(id);
        int rows = getSqlMapClientTemplate().delete("t_audit_type.ibatorgenerated_deleteByPrimaryKey", key);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table t_audit_type
     *
     * @ibatorgenerated Tue Oct 20 11:57:32 CST 2009
     */
    public void insert(TAuditType record) {
        getSqlMapClientTemplate().insert("t_audit_type.ibatorgenerated_insert", record);
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table t_audit_type
     *
     * @ibatorgenerated Tue Oct 20 11:57:32 CST 2009
     */
    public void insertSelective(TAuditType record) {
        getSqlMapClientTemplate().insert("t_audit_type.ibatorgenerated_insertSelective", record);
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table t_audit_type
     *
     * @ibatorgenerated Tue Oct 20 11:57:32 CST 2009
     */
    public List selectByExample(TAuditTypeExample example) {
        List list = getSqlMapClientTemplate().queryForList("t_audit_type.ibatorgenerated_selectByExample", example);
        return list;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table t_audit_type
     *
     * @ibatorgenerated Tue Oct 20 11:57:32 CST 2009
     */
    public TAuditType selectByPrimaryKey(String id) {
        TAuditType key = new TAuditType();
        key.setId(id);
        TAuditType record = (TAuditType) getSqlMapClientTemplate().queryForObject("t_audit_type.ibatorgenerated_selectByPrimaryKey", key);
        return record;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table t_audit_type
     *
     * @ibatorgenerated Tue Oct 20 11:57:32 CST 2009
     */
    public int updateByExampleSelective(TAuditType record, TAuditTypeExample example) {
        UpdateByExampleParms parms = new UpdateByExampleParms(record, example);
        int rows = getSqlMapClientTemplate().update("t_audit_type.ibatorgenerated_updateByExampleSelective", parms);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table t_audit_type
     *
     * @ibatorgenerated Tue Oct 20 11:57:32 CST 2009
     */
    public int updateByExample(TAuditType record, TAuditTypeExample example) {
        UpdateByExampleParms parms = new UpdateByExampleParms(record, example);
        int rows = getSqlMapClientTemplate().update("t_audit_type.ibatorgenerated_updateByExample", parms);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table t_audit_type
     *
     * @ibatorgenerated Tue Oct 20 11:57:32 CST 2009
     */
    public int updateByPrimaryKeySelective(TAuditType record) {
        int rows = getSqlMapClientTemplate().update("t_audit_type.ibatorgenerated_updateByPrimaryKeySelective", record);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table t_audit_type
     *
     * @ibatorgenerated Tue Oct 20 11:57:32 CST 2009
     */
    public int updateByPrimaryKey(TAuditType record) {
        int rows = getSqlMapClientTemplate().update("t_audit_type.ibatorgenerated_updateByPrimaryKey", record);
        return rows;
    }

    /**
     * This class was generated by Apache iBATIS ibator.
     * This class corresponds to the database table t_audit_type
     *
     * @ibatorgenerated Tue Oct 20 11:57:32 CST 2009
     */
    private static class UpdateByExampleParms extends TAuditTypeExample {
        private Object record;

        public UpdateByExampleParms(Object record, TAuditTypeExample example) {
            super(example);
            this.record = record;
        }

        public Object getRecord() {
            return record;
        }
    }
}