package com.tl.resource.dao;

import com.tl.resource.dao.pojo.TBillsCodeDef;
import com.tl.resource.dao.pojo.TBillsCodeDefExample;
import java.util.List;
import org.springframework.orm.ibatis.support.SqlMapClientDaoSupport;

public class TBillsCodeDefDAOImpl extends SqlMapClientDaoSupport implements TBillsCodeDefDAO {

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table t_bills_code_def
     *
     * @ibatorgenerated Sun Nov 22 16:19:50 CST 2009
     */
    public TBillsCodeDefDAOImpl() {
        super();
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table t_bills_code_def
     *
     * @ibatorgenerated Sun Nov 22 16:19:50 CST 2009
     */
    public int countByExample(TBillsCodeDefExample example) {
        Integer count = (Integer)  getSqlMapClientTemplate().queryForObject("t_bills_code_def.ibatorgenerated_countByExample", example);
        return count.intValue();
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table t_bills_code_def
     *
     * @ibatorgenerated Sun Nov 22 16:19:50 CST 2009
     */
    public int deleteByExample(TBillsCodeDefExample example) {
        int rows = getSqlMapClientTemplate().delete("t_bills_code_def.ibatorgenerated_deleteByExample", example);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table t_bills_code_def
     *
     * @ibatorgenerated Sun Nov 22 16:19:50 CST 2009
     */
    public int deleteByPrimaryKey(String id) {
        TBillsCodeDef key = new TBillsCodeDef();
        key.setId(id);
        int rows = getSqlMapClientTemplate().delete("t_bills_code_def.ibatorgenerated_deleteByPrimaryKey", key);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table t_bills_code_def
     *
     * @ibatorgenerated Sun Nov 22 16:19:50 CST 2009
     */
    public void insert(TBillsCodeDef record) {
        getSqlMapClientTemplate().insert("t_bills_code_def.ibatorgenerated_insert", record);
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table t_bills_code_def
     *
     * @ibatorgenerated Sun Nov 22 16:19:50 CST 2009
     */
    public void insertSelective(TBillsCodeDef record) {
        getSqlMapClientTemplate().insert("t_bills_code_def.ibatorgenerated_insertSelective", record);
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table t_bills_code_def
     *
     * @ibatorgenerated Sun Nov 22 16:19:50 CST 2009
     */
    public List selectByExample(TBillsCodeDefExample example) {
        List list = getSqlMapClientTemplate().queryForList("t_bills_code_def.ibatorgenerated_selectByExample", example);
        return list;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table t_bills_code_def
     *
     * @ibatorgenerated Sun Nov 22 16:19:50 CST 2009
     */
    public TBillsCodeDef selectByPrimaryKey(String id) {
        TBillsCodeDef key = new TBillsCodeDef();
        key.setId(id);
        TBillsCodeDef record = (TBillsCodeDef) getSqlMapClientTemplate().queryForObject("t_bills_code_def.ibatorgenerated_selectByPrimaryKey", key);
        return record;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table t_bills_code_def
     *
     * @ibatorgenerated Sun Nov 22 16:19:50 CST 2009
     */
    public int updateByExampleSelective(TBillsCodeDef record, TBillsCodeDefExample example) {
        UpdateByExampleParms parms = new UpdateByExampleParms(record, example);
        int rows = getSqlMapClientTemplate().update("t_bills_code_def.ibatorgenerated_updateByExampleSelective", parms);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table t_bills_code_def
     *
     * @ibatorgenerated Sun Nov 22 16:19:50 CST 2009
     */
    public int updateByExample(TBillsCodeDef record, TBillsCodeDefExample example) {
        UpdateByExampleParms parms = new UpdateByExampleParms(record, example);
        int rows = getSqlMapClientTemplate().update("t_bills_code_def.ibatorgenerated_updateByExample", parms);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table t_bills_code_def
     *
     * @ibatorgenerated Sun Nov 22 16:19:50 CST 2009
     */
    public int updateByPrimaryKeySelective(TBillsCodeDef record) {
        int rows = getSqlMapClientTemplate().update("t_bills_code_def.ibatorgenerated_updateByPrimaryKeySelective", record);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table t_bills_code_def
     *
     * @ibatorgenerated Sun Nov 22 16:19:50 CST 2009
     */
    public int updateByPrimaryKey(TBillsCodeDef record) {
        int rows = getSqlMapClientTemplate().update("t_bills_code_def.ibatorgenerated_updateByPrimaryKey", record);
        return rows;
    }

    public void resetNum() {
    	getSqlMapClientTemplate().update("t_bills_code_def.ibatorgenerated_resetNum");
    }
    
    /**
     * This class was generated by Apache iBATIS ibator.
     * This class corresponds to the database table t_bills_code_def
     *
     * @ibatorgenerated Sun Nov 22 16:19:50 CST 2009
     */
    private static class UpdateByExampleParms extends TBillsCodeDefExample {
        private Object record;

        public UpdateByExampleParms(Object record, TBillsCodeDefExample example) {
            super(example);
            this.record = record;
        }

        public Object getRecord() {
            return record;
        }
    }
    
   
}