package com.tl.resource.dao;

import com.tl.resource.business.dto.CurSalesPriceHistoryDto;
import com.tl.resource.dao.pojo.TCusSalesPriceHistory;
import com.tl.resource.dao.pojo.TCusSalesPriceHistoryExample;
import java.util.List;
import java.util.Map;

import org.springframework.orm.ibatis.support.SqlMapClientDaoSupport;

public class TCusSalesPriceHistoryDAOImpl extends SqlMapClientDaoSupport implements TCusSalesPriceHistoryDAO {

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table t_cus_sales_price_history
     *
     * @ibatorgenerated Fri Oct 16 10:53:03 CST 2009
     */
    public TCusSalesPriceHistoryDAOImpl() {
        super();
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table t_cus_sales_price_history
     *
     * @ibatorgenerated Fri Oct 16 10:53:03 CST 2009
     */
    public int countByExample(TCusSalesPriceHistoryExample example) {
        Integer count = (Integer)  getSqlMapClientTemplate().queryForObject("t_cus_sales_price_history.ibatorgenerated_countByExample", example);
        return count.intValue();
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table t_cus_sales_price_history
     *
     * @ibatorgenerated Fri Oct 16 10:53:03 CST 2009
     */
    public int deleteByExample(TCusSalesPriceHistoryExample example) {
        int rows = getSqlMapClientTemplate().delete("t_cus_sales_price_history.ibatorgenerated_deleteByExample", example);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table t_cus_sales_price_history
     *
     * @ibatorgenerated Fri Oct 16 10:53:03 CST 2009
     */
    public int deleteByPrimaryKey(String id) {
    	
    	//System.out.println("$$$$$$$$$" + id);
        TCusSalesPriceHistory key = new TCusSalesPriceHistory();
        key.setId(id);
        int rows = getSqlMapClientTemplate().delete("t_cus_sales_price_history.ibatorgenerated_deleteByPrimaryKey", key);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table t_cus_sales_price_history
     *
     * @ibatorgenerated Fri Oct 16 10:53:03 CST 2009
     */
    public void insert(TCusSalesPriceHistory record) {
        getSqlMapClientTemplate().insert("t_cus_sales_price_history.ibatorgenerated_insert", record);
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table t_cus_sales_price_history
     *
     * @ibatorgenerated Fri Oct 16 10:53:03 CST 2009
     */
    public void insertSelective(TCusSalesPriceHistory record) {
        getSqlMapClientTemplate().insert("t_cus_sales_price_history.ibatorgenerated_insertSelective", record);
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table t_cus_sales_price_history
     *
     * @ibatorgenerated Fri Oct 16 10:53:03 CST 2009
     */
    public List selectByExample(TCusSalesPriceHistoryExample example) {
        List list = getSqlMapClientTemplate().queryForList("t_cus_sales_price_history.ibatorgenerated_selectByExample", example);
        return list;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table t_cus_sales_price_history
     *
     * @ibatorgenerated Fri Oct 16 10:53:03 CST 2009
     */
    public TCusSalesPriceHistory selectByPrimaryKey(String id) {
        TCusSalesPriceHistory key = new TCusSalesPriceHistory();
        key.setId(id);
        TCusSalesPriceHistory record = (TCusSalesPriceHistory) getSqlMapClientTemplate().queryForObject("t_cus_sales_price_history.ibatorgenerated_selectByPrimaryKey", key);
        return record;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table t_cus_sales_price_history
     *
     * @ibatorgenerated Fri Oct 16 10:53:03 CST 2009
     */
    public int updateByExampleSelective(TCusSalesPriceHistory record, TCusSalesPriceHistoryExample example) {
        UpdateByExampleParms parms = new UpdateByExampleParms(record, example);
        int rows = getSqlMapClientTemplate().update("t_cus_sales_price_history.ibatorgenerated_updateByExampleSelective", parms);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table t_cus_sales_price_history
     *
     * @ibatorgenerated Fri Oct 16 10:53:03 CST 2009
     */
    public int updateByExample(TCusSalesPriceHistory record, TCusSalesPriceHistoryExample example) {
        UpdateByExampleParms parms = new UpdateByExampleParms(record, example);
        int rows = getSqlMapClientTemplate().update("t_cus_sales_price_history.ibatorgenerated_updateByExample", parms);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table t_cus_sales_price_history
     *
     * @ibatorgenerated Fri Oct 16 10:53:03 CST 2009
     */
    public int updateByPrimaryKeySelective(TCusSalesPriceHistory record) {
        int rows = getSqlMapClientTemplate().update("t_cus_sales_price_history.ibatorgenerated_updateByPrimaryKeySelective", record);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table t_cus_sales_price_history
     *
     * @ibatorgenerated Fri Oct 16 10:53:03 CST 2009
     */
    public int updateByPrimaryKey(TCusSalesPriceHistory record) {
        int rows = getSqlMapClientTemplate().update("t_cus_sales_price_history.ibatorgenerated_updateByPrimaryKey", record);
        return rows;
    }

    /**
     * This class was generated by Apache iBATIS ibator.
     * This class corresponds to the database table t_cus_sales_price_history
     *
     * @ibatorgenerated Fri Oct 16 10:53:03 CST 2009
     */
    private static class UpdateByExampleParms extends TCusSalesPriceHistoryExample {
        private Object record;

        public UpdateByExampleParms(Object record, TCusSalesPriceHistoryExample example) {
            super(example);
            this.record = record;
        }

        public Object getRecord() {
            return record;
        }
    }

	@Override
	public List<CurSalesPriceHistoryDto> getCusSalesHistoryProductByPage(
			Map<String, Object> parmMap) {
		List<CurSalesPriceHistoryDto> list = getSqlMapClientTemplate().queryForList("culSalPriceHistory.getCusSalesHistoryProductByPage", parmMap);
        return list;
	}

	@Override
	public int getCusSalesHistoryProductTotal(Map<String, Object> parmMap) {
		 Integer count = (Integer)  getSqlMapClientTemplate().queryForObject("culSalPriceHistory.getCusSalesHistoryProductTotal",parmMap);
	     return count.intValue();
	}

	@Override
	public List<CurSalesPriceHistoryDto> getCusSalesHistoryProductByPageAndProductId(
			Map<String, Object> parmMap) {
		List<CurSalesPriceHistoryDto> list = getSqlMapClientTemplate().queryForList("culSalPriceHistory.getCusSalesHistoryProductByPageAndProductId", parmMap);
        return list;
	}

	@Override
	public int getCusSalesHistoryProductTotalByProductId(
			Map<String, Object> parmMap) {
		 Integer count = (Integer)  getSqlMapClientTemplate().queryForObject("culSalPriceHistory.getCusSalesHistoryProductTotalByProductId",parmMap);
	     return count.intValue();
	}
}