package com.tl.resource.dao;

import com.tl.resource.dao.pojo.TDepartmentsInfor;
import com.tl.resource.dao.pojo.TDepartmentsInforExample;
import java.util.List;
import org.springframework.orm.ibatis.support.SqlMapClientDaoSupport;

public class TDepartmentsInforDAOImpl extends SqlMapClientDaoSupport implements TDepartmentsInforDAO {

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table t_departments_infor
	 * @ibatorgenerated  Mon Oct 19 11:03:26 CST 2009
	 */
	public TDepartmentsInforDAOImpl() {
		super();
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table t_departments_infor
	 * @ibatorgenerated  Mon Oct 19 11:03:26 CST 2009
	 */
	public int countByExample(TDepartmentsInforExample example) {
		Integer count = (Integer) getSqlMapClientTemplate().queryForObject(
				"t_departments_infor.ibatorgenerated_countByExample", example);
		return count.intValue();
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table t_departments_infor
	 * @ibatorgenerated  Mon Oct 19 11:03:26 CST 2009
	 */
	public int deleteByExample(TDepartmentsInforExample example) {
		int rows = getSqlMapClientTemplate().delete(
				"t_departments_infor.ibatorgenerated_deleteByExample", example);
		return rows;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table t_departments_infor
	 * @ibatorgenerated  Mon Oct 19 11:03:26 CST 2009
	 */
	public int deleteByPrimaryKey(String id) {
		TDepartmentsInfor key = new TDepartmentsInfor();
		key.setId(id);
		int rows = getSqlMapClientTemplate().delete(
				"t_departments_infor.ibatorgenerated_deleteByPrimaryKey", key);
		return rows;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table t_departments_infor
	 * @ibatorgenerated  Mon Oct 19 11:03:26 CST 2009
	 */
	public void insert(TDepartmentsInfor record) {
		getSqlMapClientTemplate().insert(
				"t_departments_infor.ibatorgenerated_insert", record);
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table t_departments_infor
	 * @ibatorgenerated  Mon Oct 19 11:03:26 CST 2009
	 */
	public void insertSelective(TDepartmentsInfor record) {
		getSqlMapClientTemplate().insert(
				"t_departments_infor.ibatorgenerated_insertSelective", record);
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table t_departments_infor
	 * @ibatorgenerated  Mon Oct 19 11:03:26 CST 2009
	 */
	public List selectByExample(TDepartmentsInforExample example) {
		List list = getSqlMapClientTemplate().queryForList(
				"t_departments_infor.ibatorgenerated_selectByExample", example);
		return list;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table t_departments_infor
	 * @ibatorgenerated  Mon Oct 19 11:03:26 CST 2009
	 */
	public TDepartmentsInfor selectByPrimaryKey(String id) {
		TDepartmentsInfor key = new TDepartmentsInfor();
		key.setId(id);
		TDepartmentsInfor record = (TDepartmentsInfor) getSqlMapClientTemplate()
				.queryForObject(
						"t_departments_infor.ibatorgenerated_selectByPrimaryKey",
						key);
		return record;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table t_departments_infor
	 * @ibatorgenerated  Mon Oct 19 11:03:26 CST 2009
	 */
	public int updateByExampleSelective(TDepartmentsInfor record,
			TDepartmentsInforExample example) {
		UpdateByExampleParms parms = new UpdateByExampleParms(record, example);
		int rows = getSqlMapClientTemplate().update(
				"t_departments_infor.ibatorgenerated_updateByExampleSelective",
				parms);
		return rows;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table t_departments_infor
	 * @ibatorgenerated  Mon Oct 19 11:03:26 CST 2009
	 */
	public int updateByExample(TDepartmentsInfor record,
			TDepartmentsInforExample example) {
		UpdateByExampleParms parms = new UpdateByExampleParms(record, example);
		int rows = getSqlMapClientTemplate().update(
				"t_departments_infor.ibatorgenerated_updateByExample", parms);
		return rows;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table t_departments_infor
	 * @ibatorgenerated  Mon Oct 19 11:03:26 CST 2009
	 */
	public int updateByPrimaryKeySelective(TDepartmentsInfor record) {
		int rows = getSqlMapClientTemplate()
				.update(
						"t_departments_infor.ibatorgenerated_updateByPrimaryKeySelective",
						record);
		return rows;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table t_departments_infor
	 * @ibatorgenerated  Mon Oct 19 11:03:26 CST 2009
	 */
	public int updateByPrimaryKey(TDepartmentsInfor record) {
		int rows = getSqlMapClientTemplate().update(
				"t_departments_infor.ibatorgenerated_updateByPrimaryKey",
				record);
		return rows;
	}

	/**
	 * This class was generated by Apache iBATIS ibator. This class corresponds to the database table t_departments_infor
	 * @ibatorgenerated  Mon Oct 19 11:03:26 CST 2009
	 */
	private static class UpdateByExampleParms extends TDepartmentsInforExample {
		private Object record;

		public UpdateByExampleParms(Object record,
				TDepartmentsInforExample example) {
			super(example);
			this.record = record;
		}

		public Object getRecord() {
			return record;
		}
	}

	@Override
	public String findNewId(String parentId) {
		// TODO Auto-generated method stub
		return (String) getSqlMapClientTemplate().queryForObject("t_departments_infor.getNewDepartId", parentId);
	}
}