package com.tl.resource.dao;

import java.util.HashMap;
import java.util.List;
import java.util.Map;

import org.springframework.orm.ibatis.support.SqlMapClientDaoSupport;

import com.tl.resource.dao.pojo.TModulesDef;
import com.tl.resource.dao.pojo.TModulesDefExample;

public class TModulesDefDAOImpl extends SqlMapClientDaoSupport implements TModulesDefDAO {

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table t_modules_def
	 * @ibatorgenerated  Wed Oct 14 14:13:27 CST 2009
	 */
	public TModulesDefDAOImpl() {
		super();
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table t_modules_def
	 * @ibatorgenerated  Wed Oct 14 14:13:27 CST 2009
	 */
	public int countByExample(TModulesDefExample example) {
		Integer count = (Integer) getSqlMapClientTemplate().queryForObject(
				"t_modules_def.ibatorgenerated_countByExample", example);
		return count.intValue();
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table t_modules_def
	 * @ibatorgenerated  Wed Oct 14 14:13:27 CST 2009
	 */
	public int deleteByExample(TModulesDefExample example) {
		int rows = getSqlMapClientTemplate().delete(
				"t_modules_def.ibatorgenerated_deleteByExample", example);
		return rows;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table t_modules_def
	 * @ibatorgenerated  Wed Oct 14 14:13:27 CST 2009
	 */
	public int deleteByPrimaryKey(String id) {
		TModulesDef key = new TModulesDef();
		key.setId(id);
		int rows = getSqlMapClientTemplate().delete(
				"t_modules_def.ibatorgenerated_deleteByPrimaryKey", key);
		return rows;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table t_modules_def
	 * @ibatorgenerated  Wed Oct 14 14:13:27 CST 2009
	 */
	public void insert(TModulesDef record) {
		getSqlMapClientTemplate().insert(
				"t_modules_def.ibatorgenerated_insert", record);
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table t_modules_def
	 * @ibatorgenerated  Wed Oct 14 14:13:27 CST 2009
	 */
	public void insertSelective(TModulesDef record) {
		getSqlMapClientTemplate().insert(
				"t_modules_def.ibatorgenerated_insertSelective", record);
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table t_modules_def
	 * @ibatorgenerated  Wed Oct 14 14:13:27 CST 2009
	 */
	public List selectByExample(TModulesDefExample example) {
		List list = getSqlMapClientTemplate().queryForList(
				"t_modules_def.ibatorgenerated_selectByExample", example);
		return list;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table t_modules_def
	 * @ibatorgenerated  Wed Oct 14 14:13:27 CST 2009
	 */
	public TModulesDef selectByPrimaryKey(String id) {
		TModulesDef key = new TModulesDef();
		key.setId(id);
		TModulesDef record = (TModulesDef) getSqlMapClientTemplate()
				.queryForObject(
						"t_modules_def.ibatorgenerated_selectByPrimaryKey", key);
		return record;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table t_modules_def
	 * @ibatorgenerated  Wed Oct 14 14:13:27 CST 2009
	 */
	public int updateByExampleSelective(TModulesDef record,
			TModulesDefExample example) {
		UpdateByExampleParms parms = new UpdateByExampleParms(record, example);
		int rows = getSqlMapClientTemplate()
				.update(
						"t_modules_def.ibatorgenerated_updateByExampleSelective",
						parms);
		return rows;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table t_modules_def
	 * @ibatorgenerated  Wed Oct 14 14:13:27 CST 2009
	 */
	public int updateByExample(TModulesDef record, TModulesDefExample example) {
		UpdateByExampleParms parms = new UpdateByExampleParms(record, example);
		int rows = getSqlMapClientTemplate().update(
				"t_modules_def.ibatorgenerated_updateByExample", parms);
		return rows;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table t_modules_def
	 * @ibatorgenerated  Wed Oct 14 14:13:27 CST 2009
	 */
	public int updateByPrimaryKeySelective(TModulesDef record) {
		int rows = getSqlMapClientTemplate().update(
				"t_modules_def.ibatorgenerated_updateByPrimaryKeySelective",
				record);
		return rows;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table t_modules_def
	 * @ibatorgenerated  Wed Oct 14 14:13:27 CST 2009
	 */
	public int updateByPrimaryKey(TModulesDef record) {
		int rows = getSqlMapClientTemplate().update(
				"t_modules_def.ibatorgenerated_updateByPrimaryKey", record);
		return rows;
	}

	/**
	 * This class was generated by Apache iBATIS ibator. This class corresponds to the database table t_modules_def
	 * @ibatorgenerated  Wed Oct 14 14:13:27 CST 2009
	 */
	private static class UpdateByExampleParms extends TModulesDefExample {
		private Object record;

		public UpdateByExampleParms(Object record, TModulesDefExample example) {
			super(example);
			this.record = record;
		}

		public Object getRecord() {
			return record;
		}
	}

	@Override
	public String findNewId(String pid) {
		// TODO Auto-generated method stub
		
		return (String) getSqlMapClientTemplate().queryForObject("t_modules_def.getNewModuleId",pid);
	}

	@Override
	public List<TModulesDef> getUsersModules(String userId, String parentId) {
		// TODO Auto-generated method stub
		Map<String,String> params = new HashMap<String,String>();
		params.put("userId", userId);
		params.put("parentId", parentId);
		//System.out.println("----------------------------");
		return getSqlMapClientTemplate().queryForList("t_modules_def.getTheUserModules",params);
	}
}