package com.tl.resource.dao;

import com.tl.resource.business.dto.DegreeRebateDto;
import com.tl.resource.dao.pojo.TRebate;
import com.tl.resource.dao.pojo.TRebateExample;
import java.util.List;
import java.util.Map;

import org.springframework.orm.ibatis.support.SqlMapClientDaoSupport;

public class TRebateDAOImpl extends SqlMapClientDaoSupport implements TRebateDAO {

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table t_rebate
	 * @ibatorgenerated  Wed Oct 14 14:13:27 CST 2009
	 */
	public TRebateDAOImpl() {
		super();
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table t_rebate
	 * @ibatorgenerated  Wed Oct 14 14:13:27 CST 2009
	 */
	public int countByExample(TRebateExample example) {
		Integer count = (Integer) getSqlMapClientTemplate().queryForObject(
				"t_rebate.ibatorgenerated_countByExample", example);
		return count.intValue();
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table t_rebate
	 * @ibatorgenerated  Wed Oct 14 14:13:27 CST 2009
	 */
	public int deleteByExample(TRebateExample example) {
		int rows = getSqlMapClientTemplate().delete(
				"t_rebate.ibatorgenerated_deleteByExample", example);
		return rows;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table t_rebate
	 * @ibatorgenerated  Wed Oct 14 14:13:27 CST 2009
	 */
	public int deleteByPrimaryKey(String id) {
		TRebate key = new TRebate();
		key.setId(id);
		int rows = getSqlMapClientTemplate().delete(
				"t_rebate.ibatorgenerated_deleteByPrimaryKey", key);
		return rows;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table t_rebate
	 * @ibatorgenerated  Wed Oct 14 14:13:27 CST 2009
	 */
	public void insert(TRebate record) {
		getSqlMapClientTemplate().insert("t_rebate.ibatorgenerated_insert",
				record);
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table t_rebate
	 * @ibatorgenerated  Wed Oct 14 14:13:27 CST 2009
	 */
	public void insertSelective(TRebate record) {
		getSqlMapClientTemplate().insert(
				"t_rebate.ibatorgenerated_insertSelective", record);
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table t_rebate
	 * @ibatorgenerated  Wed Oct 14 14:13:27 CST 2009
	 */
	public List selectByExample(TRebateExample example) {
		List list = getSqlMapClientTemplate().queryForList(
				"t_rebate.ibatorgenerated_selectByExample", example);
		return list;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table t_rebate
	 * @ibatorgenerated  Wed Oct 14 14:13:27 CST 2009
	 */
	public TRebate selectByPrimaryKey(String id) {
		TRebate key = new TRebate();
		key.setId(id);
		TRebate record = (TRebate) getSqlMapClientTemplate().queryForObject(
				"t_rebate.ibatorgenerated_selectByPrimaryKey", key);
		return record;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table t_rebate
	 * @ibatorgenerated  Wed Oct 14 14:13:27 CST 2009
	 */
	public int updateByExampleSelective(TRebate record, TRebateExample example) {
		UpdateByExampleParms parms = new UpdateByExampleParms(record, example);
		int rows = getSqlMapClientTemplate().update(
				"t_rebate.ibatorgenerated_updateByExampleSelective", parms);
		return rows;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table t_rebate
	 * @ibatorgenerated  Wed Oct 14 14:13:27 CST 2009
	 */
	public int updateByExample(TRebate record, TRebateExample example) {
		UpdateByExampleParms parms = new UpdateByExampleParms(record, example);
		int rows = getSqlMapClientTemplate().update(
				"t_rebate.ibatorgenerated_updateByExample", parms);
		return rows;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table t_rebate
	 * @ibatorgenerated  Wed Oct 14 14:13:27 CST 2009
	 */
	public int updateByPrimaryKeySelective(TRebate record) {
		int rows = getSqlMapClientTemplate().update(
				"t_rebate.ibatorgenerated_updateByPrimaryKeySelective", record);
		return rows;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table t_rebate
	 * @ibatorgenerated  Wed Oct 14 14:13:27 CST 2009
	 */
	public int updateByPrimaryKey(TRebate record) {
		int rows = getSqlMapClientTemplate().update(
				"t_rebate.ibatorgenerated_updateByPrimaryKey", record);
		return rows;
	}

	/**
	 * This class was generated by Apache iBATIS ibator. This class corresponds to the database table t_rebate
	 * @ibatorgenerated  Wed Oct 14 14:13:27 CST 2009
	 */
	private static class UpdateByExampleParms extends TRebateExample {
		private Object record;

		public UpdateByExampleParms(Object record, TRebateExample example) {
			super(example);
			this.record = record;
		}

		public Object getRecord() {
			return record;
		}
	}

	@Override
	public List<DegreeRebateDto> getDegreeRebateByPageAndDegreeId(
			Map<String, Object> parmMap) {
		List list = getSqlMapClientTemplate().queryForList(
				"tDegreeRebate.getDegreeRebateByPageAndDegreeId", parmMap);
		return list;
	}

	@Override
	public int getDegreeRebateTotalByDegreeId(Map<String, Object> parmMap) {
		Integer count = (Integer) getSqlMapClientTemplate().queryForObject(
				"tDegreeRebate.getDegreeRebateTotalByDegreeId", parmMap);
		return count.intValue();
	}
}