package com.tl.resource.dao;

import com.tl.resource.business.dto.SuppliersBrandDto;
import com.tl.resource.dao.pojo.TSuppliersBrand;
import com.tl.resource.dao.pojo.TSuppliersBrandExample;
import java.util.List;
import java.util.Map;

public interface TSuppliersBrandDAO {
    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table t_suppliers_brand
     *
     * @ibatorgenerated Thu Nov 05 15:39:31 CST 2009
     */
    int countByExample(TSuppliersBrandExample example);

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table t_suppliers_brand
     *
     * @ibatorgenerated Thu Nov 05 15:39:31 CST 2009
     */
    int deleteByExample(TSuppliersBrandExample example);

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table t_suppliers_brand
     *
     * @ibatorgenerated Thu Nov 05 15:39:31 CST 2009
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table t_suppliers_brand
     *
     * @ibatorgenerated Thu Nov 05 15:39:31 CST 2009
     */
    void insert(TSuppliersBrand record);

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table t_suppliers_brand
     *
     * @ibatorgenerated Thu Nov 05 15:39:31 CST 2009
     */
    void insertSelective(TSuppliersBrand record);

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table t_suppliers_brand
     *
     * @ibatorgenerated Thu Nov 05 15:39:31 CST 2009
     */
    List selectByExample(TSuppliersBrandExample example);

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table t_suppliers_brand
     *
     * @ibatorgenerated Thu Nov 05 15:39:31 CST 2009
     */
    TSuppliersBrand selectByPrimaryKey(String id);

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table t_suppliers_brand
     *
     * @ibatorgenerated Thu Nov 05 15:39:31 CST 2009
     */
    int updateByExampleSelective(TSuppliersBrand record, TSuppliersBrandExample example);

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table t_suppliers_brand
     *
     * @ibatorgenerated Thu Nov 05 15:39:31 CST 2009
     */
    int updateByExample(TSuppliersBrand record, TSuppliersBrandExample example);

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table t_suppliers_brand
     *
     * @ibatorgenerated Thu Nov 05 15:39:31 CST 2009
     */
    int updateByPrimaryKeySelective(TSuppliersBrand record);

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table t_suppliers_brand
     *
     * @ibatorgenerated Thu Nov 05 15:39:31 CST 2009
     */
    int updateByPrimaryKey(TSuppliersBrand record);

	List<SuppliersBrandDto> getSuppliersBrandByPageAndSupplierId(
			Map<String, Object> parmMap);

	int getSuppliersBrandTotalBySupplierId(Map<String, Object> parmMap);

	void deleteSupplierBrandBySupplierId(String supplierIdPar);
}