package com.tl.resource.dao;

import com.tl.common.util.PaginationSupport;
import com.tl.resource.business.dto.RolesDto;
import com.tl.resource.dao.pojo.TUserInfor;
import com.tl.resource.dao.pojo.TUserInforExample;
import java.util.List;
import java.util.Map;

public interface TUserInforDAO {

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table t_user_infor
	 * @ibatorgenerated  Wed Oct 14 14:13:27 CST 2009
	 */
	int countByExample(TUserInforExample example);

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table t_user_infor
	 * @ibatorgenerated  Wed Oct 14 14:13:27 CST 2009
	 */
	int deleteByExample(TUserInforExample example);

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table t_user_infor
	 * @ibatorgenerated  Wed Oct 14 14:13:27 CST 2009
	 */
	int deleteByPrimaryKey(String id);

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table t_user_infor
	 * @ibatorgenerated  Wed Oct 14 14:13:27 CST 2009
	 */
	void insert(TUserInfor record);

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table t_user_infor
	 * @ibatorgenerated  Wed Oct 14 14:13:27 CST 2009
	 */
	void insertSelective(TUserInfor record);

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table t_user_infor
	 * @ibatorgenerated  Wed Oct 14 14:13:27 CST 2009
	 */
	List selectByExample(TUserInforExample example);

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table t_user_infor
	 * @ibatorgenerated  Wed Oct 14 14:13:27 CST 2009
	 */
	TUserInfor selectByPrimaryKey(String id);

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table t_user_infor
	 * @ibatorgenerated  Wed Oct 14 14:13:27 CST 2009
	 */
	int updateByExampleSelective(TUserInfor record, TUserInforExample example);

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table t_user_infor
	 * @ibatorgenerated  Wed Oct 14 14:13:27 CST 2009
	 */
	int updateByExample(TUserInfor record, TUserInforExample example);

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table t_user_infor
	 * @ibatorgenerated  Wed Oct 14 14:13:27 CST 2009
	 */
	int updateByPrimaryKeySelective(TUserInfor record);

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table t_user_infor
	 * @ibatorgenerated  Wed Oct 14 14:13:27 CST 2009
	 */
	int updateByPrimaryKey(TUserInfor record);

	List<RolesDto> getUserRoles(String userId);
	
	public PaginationSupport getWillSelectUser(Map<String,Object> params, int startIndex, int pageSize);
    
    public List<TUserInfor> getSelectedUser(Map<String,Object> params);
}