package com.tl.resource.dao;

import com.tl.resource.dao.pojo.TUsersRolesExample;
import com.tl.resource.dao.pojo.TUsersRolesKey;
import java.util.List;
import org.springframework.orm.ibatis.support.SqlMapClientDaoSupport;

public class TUsersRolesDAOImpl extends SqlMapClientDaoSupport implements TUsersRolesDAO {

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table t_users_roles
	 * @ibatorgenerated  Wed Oct 14 14:13:27 CST 2009
	 */
	public TUsersRolesDAOImpl() {
		super();
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table t_users_roles
	 * @ibatorgenerated  Wed Oct 14 14:13:27 CST 2009
	 */
	public int countByExample(TUsersRolesExample example) {
		Integer count = (Integer) getSqlMapClientTemplate().queryForObject(
				"t_users_roles.ibatorgenerated_countByExample", example);
		return count.intValue();
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table t_users_roles
	 * @ibatorgenerated  Wed Oct 14 14:13:27 CST 2009
	 */
	public int deleteByExample(TUsersRolesExample example) {
		int rows = getSqlMapClientTemplate().delete(
				"t_users_roles.ibatorgenerated_deleteByExample", example);
		return rows;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table t_users_roles
	 * @ibatorgenerated  Wed Oct 14 14:13:27 CST 2009
	 */
	public int deleteByPrimaryKey(TUsersRolesKey key) {
		int rows = getSqlMapClientTemplate().delete(
				"t_users_roles.ibatorgenerated_deleteByPrimaryKey", key);
		return rows;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table t_users_roles
	 * @ibatorgenerated  Wed Oct 14 14:13:27 CST 2009
	 */
	public void insert(TUsersRolesKey record) {
		getSqlMapClientTemplate().insert(
				"t_users_roles.ibatorgenerated_insert", record);
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table t_users_roles
	 * @ibatorgenerated  Wed Oct 14 14:13:27 CST 2009
	 */
	public void insertSelective(TUsersRolesKey record) {
		getSqlMapClientTemplate().insert(
				"t_users_roles.ibatorgenerated_insertSelective", record);
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table t_users_roles
	 * @ibatorgenerated  Wed Oct 14 14:13:27 CST 2009
	 */
	public List selectByExample(TUsersRolesExample example) {
		List list = getSqlMapClientTemplate().queryForList(
				"t_users_roles.ibatorgenerated_selectByExample", example);
		return list;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table t_users_roles
	 * @ibatorgenerated  Wed Oct 14 14:13:27 CST 2009
	 */
	public int updateByExampleSelective(TUsersRolesKey record,
			TUsersRolesExample example) {
		UpdateByExampleParms parms = new UpdateByExampleParms(record, example);
		int rows = getSqlMapClientTemplate()
				.update(
						"t_users_roles.ibatorgenerated_updateByExampleSelective",
						parms);
		return rows;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table t_users_roles
	 * @ibatorgenerated  Wed Oct 14 14:13:27 CST 2009
	 */
	public int updateByExample(TUsersRolesKey record, TUsersRolesExample example) {
		UpdateByExampleParms parms = new UpdateByExampleParms(record, example);
		int rows = getSqlMapClientTemplate().update(
				"t_users_roles.ibatorgenerated_updateByExample", parms);
		return rows;
	}

	/**
	 * This class was generated by Apache iBATIS ibator. This class corresponds to the database table t_users_roles
	 * @ibatorgenerated  Wed Oct 14 14:13:27 CST 2009
	 */
	private static class UpdateByExampleParms extends TUsersRolesExample {
		private Object record;

		public UpdateByExampleParms(Object record, TUsersRolesExample example) {
			super(example);
			this.record = record;
		}

		public Object getRecord() {
			return record;
		}
	}
}