package com.tl.resource.dao;

import java.util.List;
import java.util.Map;

import org.springframework.orm.ibatis.support.SqlMapClientDaoSupport;

import com.tl.common.util.PaginationSupport;
import com.tl.resource.dao.pojo.TWorkTrustRecord;
import com.tl.resource.dao.pojo.TWorkTrustRecordExample;

public class TWorkTrustRecordDAOImpl extends SqlMapClientDaoSupport implements TWorkTrustRecordDAO {

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table t_work_trust_record
	 * @ibatorgenerated  Wed Mar 10 19:02:58 CST 2010
	 */
	public TWorkTrustRecordDAOImpl() {
		super();
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table t_work_trust_record
	 * @ibatorgenerated  Wed Mar 10 19:02:58 CST 2010
	 */
	public int countByExample(TWorkTrustRecordExample example) {
		Integer count = (Integer) getSqlMapClientTemplate().queryForObject(
				"t_work_trust_record.ibatorgenerated_countByExample", example);
		return count.intValue();
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table t_work_trust_record
	 * @ibatorgenerated  Wed Mar 10 19:02:58 CST 2010
	 */
	public int deleteByExample(TWorkTrustRecordExample example) {
		int rows = getSqlMapClientTemplate().delete(
				"t_work_trust_record.ibatorgenerated_deleteByExample", example);
		return rows;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table t_work_trust_record
	 * @ibatorgenerated  Wed Mar 10 19:02:58 CST 2010
	 */
	public int deleteByPrimaryKey(String id) {
		TWorkTrustRecord key = new TWorkTrustRecord();
		key.setId(id);
		int rows = getSqlMapClientTemplate().delete(
				"t_work_trust_record.ibatorgenerated_deleteByPrimaryKey", key);
		return rows;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table t_work_trust_record
	 * @ibatorgenerated  Wed Mar 10 19:02:58 CST 2010
	 */
	public void insert(TWorkTrustRecord record) {
		getSqlMapClientTemplate().insert(
				"t_work_trust_record.ibatorgenerated_insert", record);
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table t_work_trust_record
	 * @ibatorgenerated  Wed Mar 10 19:02:58 CST 2010
	 */
	public void insertSelective(TWorkTrustRecord record) {
		getSqlMapClientTemplate().insert(
				"t_work_trust_record.ibatorgenerated_insertSelective", record);
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table t_work_trust_record
	 * @ibatorgenerated  Wed Mar 10 19:02:58 CST 2010
	 */
	public List selectByExample(TWorkTrustRecordExample example) {
		List list = getSqlMapClientTemplate().queryForList(
				"t_work_trust_record.ibatorgenerated_selectByExample", example);
		return list;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table t_work_trust_record
	 * @ibatorgenerated  Wed Mar 10 19:02:58 CST 2010
	 */
	public TWorkTrustRecord selectByPrimaryKey(String id) {
		TWorkTrustRecord key = new TWorkTrustRecord();
		key.setId(id);
		TWorkTrustRecord record = (TWorkTrustRecord) getSqlMapClientTemplate()
				.queryForObject(
						"t_work_trust_record.ibatorgenerated_selectByPrimaryKey",
						key);
		return record;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table t_work_trust_record
	 * @ibatorgenerated  Wed Mar 10 19:02:58 CST 2010
	 */
	public int updateByExampleSelective(TWorkTrustRecord record,
			TWorkTrustRecordExample example) {
		UpdateByExampleParms parms = new UpdateByExampleParms(record, example);
		int rows = getSqlMapClientTemplate().update(
				"t_work_trust_record.ibatorgenerated_updateByExampleSelective",
				parms);
		return rows;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table t_work_trust_record
	 * @ibatorgenerated  Wed Mar 10 19:02:58 CST 2010
	 */
	public int updateByExample(TWorkTrustRecord record,
			TWorkTrustRecordExample example) {
		UpdateByExampleParms parms = new UpdateByExampleParms(record, example);
		int rows = getSqlMapClientTemplate().update(
				"t_work_trust_record.ibatorgenerated_updateByExample", parms);
		return rows;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table t_work_trust_record
	 * @ibatorgenerated  Wed Mar 10 19:02:58 CST 2010
	 */
	public int updateByPrimaryKeySelective(TWorkTrustRecord record) {
		int rows = getSqlMapClientTemplate()
				.update(
						"t_work_trust_record.ibatorgenerated_updateByPrimaryKeySelective",
						record);
		return rows;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table t_work_trust_record
	 * @ibatorgenerated  Wed Mar 10 19:02:58 CST 2010
	 */
	public int updateByPrimaryKey(TWorkTrustRecord record) {
		int rows = getSqlMapClientTemplate().update(
				"t_work_trust_record.ibatorgenerated_updateByPrimaryKey",
				record);
		return rows;
	}

	/**
	 * This class was generated by Apache iBATIS ibator. This class corresponds to the database table t_work_trust_record
	 * @ibatorgenerated  Wed Mar 10 19:02:58 CST 2010
	 */
	private static class UpdateByExampleParms extends TWorkTrustRecordExample {
		private Object record;

		public UpdateByExampleParms(Object record,
				TWorkTrustRecordExample example) {
			super(example);
			this.record = record;
		}

		public Object getRecord() {
			return record;
		}
	}

	@Override
	public PaginationSupport getUserListWorkTrust(
			Map params, int startIndex,int pageSize) {
		params.put("startIndex", startIndex);
		params.put("pageSize", pageSize);
		List list = getSqlMapClientTemplate().queryForList(
				"t_work_trust_record.getUserListWorkTrust", params);
		Integer count = (Integer)getSqlMapClientTemplate().queryForObject(
				"t_work_trust_record.getUserListWorkTrustCount", params);
		PaginationSupport ps = new PaginationSupport(list, count, pageSize, startIndex);
		return ps;
	}
}